"""erdos993: exact independence polynomials of forests and unimodality checks.

Everything is computed with Python integers (and :class:`fractions.Fraction`
where a ratio is reported), so no verdict depends on floating point.

Main entry points
-----------------
* :func:`independence_polynomial_forest`, :func:`independence_polynomial_parent_array`,
  :func:`independence_polynomial_nx` -- coefficient lists ``[p_0, ..., p_alpha]``;
  :func:`product` for disjoint unions; :func:`path`, :func:`star`, :func:`broom`,
  :func:`double_broom`, :func:`spider`, :func:`caterpillar`, :func:`attach_leaf`.
* :mod:`erdos993.checks` -- :func:`is_unimodal`, :func:`is_log_concave`,
  :func:`L_cutoff`, :func:`wr_violations`, :func:`iso_values`, :func:`iso_violations`,
  :func:`descent_conditional_iso_violations`, :func:`tail_check`, :func:`first_descent`,
  :func:`mode`, :func:`full_report` and the descent-propagation framework.
* :mod:`erdos993.lemma` -- sympy verification of the descent-propagation lemma.
* :mod:`erdos993.enumerate` -- trees via ``nauty-gentreeg`` (or networkx) and
  forests via multisets of trees, with OEIS count verification.
* ``python3 -m erdos993 scan-trees N`` / ``python3 -m erdos993 poly EDGELIST``.
"""

from .checks import (
    DescentPropagationReport,
    DescentStep,
    FrameworkInconsistency,
    FrameworkResult,
    L_cutoff,
    UnimodalityResult,
    descent_conditional_iso_violations,
    descent_propagation_check,
    first_descent,
    first_weak_descent,
    full_report,
    is_log_concave,
    is_unimodal,
    iso_failures,
    iso_holds,
    iso_normalized_slack,
    iso_value,
    iso_values,
    iso_violations,
    log_concavity_breaks,
    mode,
    mode_range,
    tail_check,
    tail_cutoff,
    tail_failures,
    unimodality,
    unimodality_via_framework,
    wr_failures,
    wr_holds,
    wr_violations,
)
from .enumerate import (
    A000055,
    A005195,
    components_to_forest,
    count_forests,
    count_forests_formula,
    count_trees,
    independence_polynomial_components,
    iter_forests,
    iter_trees,
    verify_forest_counts,
    verify_tree_counts,
)
from .indpoly import (
    attach_leaf,
    attach_leaves,
    broom,
    caterpillar,
    double_broom,
    forest_to_nx,
    independence_number,
    independence_polynomial,
    independence_polynomial_bruteforce,
    independence_polynomial_forest,
    independence_polynomial_nx,
    independence_polynomial_parent_array,
    parent_array_to_edges,
    parent_array_to_nx,
    path,
    poly_add,
    poly_mul,
    poly_prod,
    poly_to_string,
    product,
    spider,
    star,
)
from .lemma import lemma_checks, verify_lemma

__version__ = "0.1.0"

__all__ = [
    "A000055",
    "A005195",
    "DescentPropagationReport",
    "DescentStep",
    "FrameworkInconsistency",
    "FrameworkResult",
    "L_cutoff",
    "UnimodalityResult",
    "attach_leaf",
    "attach_leaves",
    "broom",
    "caterpillar",
    "components_to_forest",
    "count_forests",
    "count_forests_formula",
    "count_trees",
    "descent_conditional_iso_violations",
    "descent_propagation_check",
    "double_broom",
    "first_descent",
    "first_weak_descent",
    "forest_to_nx",
    "full_report",
    "independence_number",
    "independence_polynomial",
    "independence_polynomial_bruteforce",
    "independence_polynomial_components",
    "independence_polynomial_forest",
    "independence_polynomial_nx",
    "independence_polynomial_parent_array",
    "is_log_concave",
    "is_unimodal",
    "iso_failures",
    "iso_holds",
    "iso_normalized_slack",
    "iso_value",
    "iso_values",
    "iso_violations",
    "iter_forests",
    "iter_trees",
    "lemma_checks",
    "log_concavity_breaks",
    "mode",
    "mode_range",
    "parent_array_to_edges",
    "parent_array_to_nx",
    "path",
    "poly_add",
    "poly_mul",
    "poly_prod",
    "poly_to_string",
    "product",
    "spider",
    "star",
    "tail_check",
    "tail_cutoff",
    "tail_failures",
    "unimodality",
    "unimodality_via_framework",
    "verify_forest_counts",
    "verify_lemma",
    "verify_tree_counts",
    "wr_failures",
    "wr_holds",
    "wr_violations",
]
