#!/usr/bin/env bash
# Fail-closed replay of every exact producer / independent audit in this
# directory, followed by a SHA-256 manifest of all sources and reports.
#
#   ./replay_all.sh          fast replays only (minutes)
#   ./replay_all.sh --full   also re-run the heavy censuses / searches
#
# Exit status is nonzero if any replay exits nonzero or prints a FAIL marker.
set -u
cd "$(dirname "$0")"
FULL=0
[ "${1:-}" = "--full" ] && FULL=1

status=0
run() {
  echo "=== $*"
  local out
  if ! out="$("$@" 2>&1)"; then
    echo "$out" | tail -n 40
    echo "!!! nonzero exit: $*"
    status=1
    return
  fi
  echo "$out" | grep -E "PASS|FAIL|SELFTEST" || echo "$out" | tail -n 5
  if echo "$out" | grep -q "FAIL"; then
    echo "!!! FAIL marker printed by: $*"
    status=1
  fi
}

run python3 forest_indep.py
[ -f audit_forest_indep_independent.py ]           && run python3 audit_forest_indep_independent.py
[ -f replay_wr_iso_tail_logic.py ]                 && run python3 replay_wr_iso_tail_logic.py
[ -f iso2_all_forests_proof.py ]                   && run python3 iso2_all_forests_proof.py
[ -f iso3_subgraph_expansion.py ]                  && run python3 iso3_subgraph_expansion.py
[ -f iso4_subgraph_expansion.py ]                  && run python3 iso4_subgraph_expansion.py
[ -f audit_iso234_independent.py ]                 && run python3 audit_iso234_independent.py
[ -f scope_lemma_adjacent_k00_producer.py ]        && run python3 scope_lemma_adjacent_k00_producer.py
[ -f scope_lemma_adjacent_k00_audit_independent.py ] && run python3 scope_lemma_adjacent_k00_audit_independent.py
[ -f descent_gated_target.py ]                     && run python3 descent_gated_target.py

if [ "$FULL" = 1 ]; then
  [ -f run_census_trees.sh ]      && run bash run_census_trees.sh
  [ -f census_forests.py ]        && run python3 census_forests.py --nmax 21
  [ -f families_stress.py ]       && run python3 families_stress.py
  [ -f iso5_subgraph_expansion.py ] && run python3 iso5_subgraph_expansion.py
  [ -f adversarial_iso_search.py ] && run python3 adversarial_iso_search.py
fi

mkdir -p results
{
  echo "# SHA-256 manifest generated by replay_all.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  sha256sum *.py *.sh *.c *.md 2>/dev/null
  sha256sum results/*.json 2>/dev/null
} > results/MANIFEST_SHA256.txt
echo "=== manifest written to results/MANIFEST_SHA256.txt ($(grep -c '^[0-9a-f]' results/MANIFEST_SHA256.txt) entries)"

if [ "$status" = 0 ]; then
  echo "REPLAY_ALL_PASS"
else
  echo "REPLAY_ALL_FAIL"
fi
exit "$status"
