import type { DifficultyDef, DifficultyId } from './types';

export const DIFFICULTIES: Record<DifficultyId, DifficultyDef> = {
  recruit: {
    id: 'recruit',
    name: 'RECRUIT',
    tagline: 'Forgiving enemies, generous armor. Learn the annex.',
    enemyCount: 9,
    enemyHealth: 80,
    enemyDamageMult: 0.65,
    enemyAccuracy: 0.5,
    enemyReactionTime: 0.9,
    visionRange: 21,
    hearingMult: 0.8,
    missionTime: 15 * 60,
    playerArmor: 75,
  },
  operator: {
    id: 'operator',
    name: 'OPERATOR',
    tagline: 'The intended experience. Deliberate and dangerous.',
    enemyCount: 12,
    enemyHealth: 100,
    enemyDamageMult: 1.0,
    enemyAccuracy: 0.68,
    enemyReactionTime: 0.62,
    visionRange: 26,
    hearingMult: 1.0,
    missionTime: 12 * 60,
    playerArmor: 50,
  },
  veteran: {
    id: 'veteran',
    name: 'VETERAN',
    tagline: 'Fast reactions, sharp eyes, no second chances.',
    enemyCount: 14,
    enemyHealth: 115,
    enemyDamageMult: 1.35,
    enemyAccuracy: 0.8,
    enemyReactionTime: 0.42,
    visionRange: 30,
    hearingMult: 1.3,
    missionTime: 10 * 60,
    playerArmor: 25,
  },
};
