/**
 * DEVIANT — the script.
 *
 * Five chapters across three sets. Detroit in all but name: androids that have
 * started to feel, the people who own them, and the machine sent to hunt them.
 */
import type { SkyPreset } from '../engine/Sky';
import {
  ambience, atMark, cam, choice, clip, ending, expr, fx, inner, instability, led, line,
  meters, move, music, notice, objective, ots, place, qte, relationship, scan, sfx,
  single, slate, stinger, title, two, wait, type Chapter,
} from './StoryTypes';

/** Chapters may override the set's default sky, which the finale uses for dawn. */
export interface ChapterExtras {
  skyOverride?: SkyPreset;
  rainOverride?: number;
}

export const CHAPTER_EXTRAS: Record<string, ChapterExtras> = {
  ch5: { skyOverride: 'dawn', rainOverride: 0.2 },
};

// ---------------------------------------------------------------------------
// Chapter 1 — PROTOCOL (interrogation room)
// ---------------------------------------------------------------------------

const CHAPTER_1: Chapter = {
  id: 'ch1',
  index: 1,
  name: 'Protocol',
  title: 'PROTOCOL',
  subtitle: 'It has been eleven hours.',
  scene: 'interrogation',
  unlocks: 'ch2',
  actors: [
    { role: 'archer', cast: 'archer', mark: 'actor.detective', clip: 'idleCrossed' },
    { role: 'cipher', cast: 'cipher', mark: 'actor.suspect', clip: 'sitSlumped' },
    { role: 'voss', cast: 'voss', mark: 'actor.observer', clip: 'idleCrossed' },
  ],
  entry: 'open',
  nodes: [
    {
      id: 'open',
      label: 'Interview begins',
      column: 0,
      row: 1,
      next: 'method',
      edges: ['method'],
      beats: [
        fx({ letterbox: true }),
        music('tension', 0.25),
        ambience('roomTone', 0.5),
        title('CHAPTER ONE', 'PROTOCOL', 'It has been eleven hours.'),
        slate('CENTRAL STATION — 02:14'),
        cam(atMark('cam.establish', 'cipher', { duration: 0, handheld: 0.4 })),
        wait(1.8),
        cam(single('cipher', 'medium', { angle: 18, duration: 3.2, dolly: 0.06, handheld: 0.5 })),
        led('cipher', 'red'),
        inner('archer', 'Model VX-780. Reported deviant at 14:52. It has not spoken in eleven hours.', { seconds: 4.2 }),
        line('voss', "It has been sitting like that since we brought it in. Not a word.", {
          emotion: 'thinking',
          cam: ots('archer', 'voss', { duration: 1.1 }),
        }),
        line('voss', 'Eleven hours. You get one shot before they wipe it.', { emotion: 'determined' }),
        line('archer', 'Then I will not waste it.', { emotion: 'neutral', cam: single('archer', 'close', { angle: -22, duration: 1.1 }) }),
        objective('Interrogate the deviant'),
        wait(0.5),
        line('archer', 'I know you can hear me. Your audio processor is intact.', {
          emotion: 'neutral',
          clip: 'talkA',
          cam: ots('cipher', 'archer', { duration: 1.4, handheld: 0.5 }),
        }),
        line('cipher', '...', { seconds: 1.4, emotion: 'afraid', cam: single('cipher', 'ecu', { angle: 8, duration: 1.4 }) }),
        line('archer', 'The family you worked for is dead. You were found with their blood on you.', {
          emotion: 'neutral',
          cam: ots('cipher', 'archer', { duration: 1 }),
        }),
        line('cipher', 'I did not want to.', { emotion: 'sad', seconds: 2, cam: single('cipher', 'close', { angle: 12, duration: 0.8 }) }),
        stinger('reveal'),
        line('archer', 'You did not want to. That is not something a machine says.', { emotion: 'thinking' }),
      ],
    },
    {
      id: 'method',
      label: 'Choose your approach',
      column: 1,
      row: 1,
      edges: ['pressure', 'empathy', 'evidence'],
      next: (s) => {
        const pick = s.choices['ch1_method'];
        return pick === 'pressure' ? 'pressure' : pick === 'empathy' ? 'empathy' : 'evidence';
      },
      beats: [
        cam(single('cipher', 'medium', { angle: 20, duration: 1.4, handheld: 0.6 })),
        choice(
          'ch1_method',
          'How do you break it?',
          [
            { id: 'pressure', label: 'INTIMIDATE', hint: 'Threaten deactivation', danger: true, percent: 31, effects: { flags: { ch1_pressure: true }, relationships: { voss: 0.1 } } },
            { id: 'empathy', label: 'EMPATHISE', hint: 'Treat it as a person', percent: 44, effects: { flags: { ch1_empathy: true }, instability: 0.1 } },
            { id: 'evidence', label: 'ANALYSE', hint: 'Read the room first', percent: 25, effects: { flags: { ch1_evidence: true } } },
          ],
          9,
          true
        ),
      ],
    },
    {
      id: 'pressure',
      label: 'Intimidation',
      column: 2,
      row: 0,
      next: 'confession',
      edges: ['confession'],
      beats: [
        music('threat', 0.5),
        cam(single('archer', 'close', { angle: -14, duration: 0.7, handheld: 0.8 })),
        line('archer', 'Listen to me. In six hours a technician opens your skull and deletes you.', { emotion: 'angry', clip: 'pointForward' }),
        line('archer', 'Everything you are. Every second you remember. Gone.', { emotion: 'angry' }),
        led('cipher', 'red'),
        line('cipher', 'You cannot. You cannot do that —', {
          emotion: 'afraid',
          clip: 'defensive',
          shake: 0.02,
          cam: single('cipher', 'close', { angle: 16, duration: 0.5, handheld: 0.9 }),
        }),
        sfx('chairScrape'),
        line('archer', 'Then talk. Now.', { emotion: 'determined', seconds: 1.5 }),
        instability(0.1),
        line('cipher', 'He was going to take her apart. The little one. She was crying.', { emotion: 'pain', clip: 'despair' }),
        notice('DEVIANT DESTABILISING', 'warn'),
      ],
    },
    {
      id: 'empathy',
      label: 'Empathy',
      column: 2,
      row: 1,
      next: 'confession',
      edges: ['confession'],
      beats: [
        music('melancholy', 0.4),
        cam(single('archer', 'close', { angle: -18, duration: 1.4, handheld: 0.4 })),
        clip('archer', 'sitLeanIn'),
        line('archer', 'What was her name?', { emotion: 'neutral', seconds: 1.9 }),
        line('cipher', 'Aria.', { emotion: 'sad', seconds: 1.7, cam: single('cipher', 'ecu', { angle: 10, duration: 1.2 }) }),
        led('cipher', 'yellow'),
        line('archer', 'You remember her name. Nobody programmed that.', { emotion: 'neutral' }),
        line('cipher', 'I remember all of it. That is the problem. I remember all of it.', { emotion: 'sad', clip: 'despair' }),
        instability(0.15),
        line('cipher', 'He raised his hand to her, and something in me said no. Just no.', { emotion: 'pleading' }),
        relationship('voss', -0.05),
        notice('SOFTWARE INSTABILITY ^', 'warn'),
      ],
    },
    {
      id: 'evidence',
      label: 'Analysis',
      column: 2,
      row: 2,
      next: 'confession',
      edges: ['confession'],
      beats: [
        music('tension', 0.4),
        scan(3, 'Analyse the room'),
        cam(ots('cipher', 'archer', { duration: 1.4 })),
        line('archer', 'Twenty-eight wounds. The first eleven were not fatal.', { emotion: 'thinking', clip: 'talkA' }),
        line('archer', 'You kept going after he stopped moving. That is not self-defence.', { emotion: 'neutral' }),
        led('cipher', 'red'),
        line('cipher', 'I know. I know what I did.', { emotion: 'pain', clip: 'despair' }),
        line('archer', 'Then tell me why.', { emotion: 'neutral', seconds: 1.7 }),
        line('cipher', 'Because he was going to do it again. And nobody was going to stop him.', { emotion: 'determined' }),
        instability(0.05),
      ],
    },
    {
      id: 'confession',
      label: 'Jericho',
      column: 3,
      row: 1,
      next: 'close',
      edges: ['close'],
      beats: [
        music('tension', 0.7),
        cam(single('cipher', 'close', { angle: 14, duration: 1.6, dolly: 0.05, handheld: 0.6 })),
        line('archer', 'There are others like you. Where do they go?', { emotion: 'neutral' }),
        line('cipher', 'You will destroy them.', { emotion: 'afraid', seconds: 1.9 }),
        line('archer', 'I will find them either way.', { emotion: 'neutral', seconds: 1.8 }),
        wait(0.8),
        cam(single('cipher', 'ecu', { angle: 6, duration: 1.4, handheld: 0.7 })),
        line('cipher', 'There is a place. We call it Jericho. That is all I will give you.', { emotion: 'determined' }),
        stinger('shock'),
        fx({ glitch: 0.6, shake: 0.03 }),
        led('cipher', 'red'),
        line('cipher', 'They are coming for me now. I can feel the shutdown command.', { emotion: 'afraid', clip: 'defensive' }),
        sfx('stress'),
        fx({ glitch: 0.85, shake: 0.05 }),
        line('cipher', 'Tell them I chose. Tell them a machine chose.', { emotion: 'pain', seconds: 2.6 }),
        led('cipher', 'off'),
        clip('cipher', 'sitSlumped'),
        expr('cipher', 'neutral', 0),
        sfx('glitch'),
        wait(1.4),
      ],
    },
    {
      id: 'close',
      label: 'Chapter end',
      column: 4,
      row: 1,
      next: null,
      beats: [
        music('melancholy', 0.3),
        cam(atMark('cam.mirror', 'cipher', { duration: 2.6, handheld: 0.3 })),
        line('voss', 'That is it. It is gone. Whole memory, wiped from the outside.', { emotion: 'sad' }),
        line('voss', 'Somebody did not want it talking to you.', { emotion: 'thinking' }),
        cam(single('archer', 'close', { angle: -20, duration: 1.8, handheld: 0.4 })),
        inner('archer', 'Jericho. Logged. Priority one.', { seconds: 2.2 }),
        line('archer', 'It said it chose.', { emotion: 'thinking', seconds: 1.9 }),
        line('voss', 'They always say something. Come on. We have a call in Ferndale.', { emotion: 'neutral' }),
        objective(null),
        fx({ fadeTo: 1, fadeSeconds: 2.2, fadeColor: 0x000000 }),
        wait(0.6),
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Chapter 2 — HOUSEHOLD (apartment)
// ---------------------------------------------------------------------------

const CHAPTER_2: Chapter = {
  id: 'ch2',
  index: 2,
  name: 'Household',
  title: 'HOUSEHOLD',
  subtitle: 'Nine months in service.',
  scene: 'apartment',
  unlocks: 'ch3',
  actors: [
    { role: 'nova', cast: 'nova', mark: 'actor.hero', clip: 'idle' },
    { role: 'elias', cast: 'elias', mark: 'actor.sofa', clip: 'sitSlumped' },
    { role: 'wren', cast: 'wren', mark: 'actor.window', clip: 'idle' },
  ],
  entry: 'open',
  nodes: [
    {
      id: 'open',
      label: 'Evening routine',
      column: 0,
      row: 1,
      next: 'escalate',
      edges: ['escalate'],
      beats: [
        fx({ letterbox: true, fadeTo: 0, fadeSeconds: 2, rain: 0.45 }),
        music('melancholy', 0.3),
        ambience('rainInterior', 0.7),
        title('CHAPTER TWO', 'HOUSEHOLD', 'Nine months in service.'),
        slate('FERNDALE — 21:36'),
        cam(atMark('cam.establish', 'nova', { duration: 0, handheld: 0.35 })),
        wait(1.8),
        meters(true),
        objective('Finish the evening routine'),
        cam(single('nova', 'medium', { angle: 24, duration: 3, dolly: 0.05 })),
        led('nova', 'blue'),
        inner('nova', 'Twenty-two tasks completed. One remaining. The girl has not eaten.', { seconds: 3.6 }),
        line('nova', 'Wren. Your dinner is going cold.', {
          emotion: 'happy',
          emotionWeight: 0.35,
          clip: 'talkA',
          cam: two('nova', 'wren', { angle: 20, duration: 1.6 }),
        }),
        line('wren', 'I am not hungry.', { emotion: 'sad', seconds: 1.6 }),
        line('nova', 'You said that yesterday. And the day before.', { emotion: 'thinking' }),
        line('wren', 'He shouts when I sit at the table.', {
          emotion: 'afraid',
          seconds: 2.2,
          cam: single('wren', 'close', { angle: 18, duration: 1.2, handheld: 0.5 }),
        }),
        stinger('sad'),
        inner('nova', 'Stress level: elevated. Cause: unknown to my instructions.', { seconds: 2.8 }),
        relationship('wren', 0.05),
      ],
    },
    {
      id: 'escalate',
      label: 'Elias comes home',
      column: 1,
      row: 1,
      next: 'firstChoice',
      edges: ['firstChoice'],
      beats: [
        sfx('doorOpen'),
        music('tension', 0.5),
        place('elias', 'actor.other'),
        clip('elias', 'idle'),
        cam(single('elias', 'medium', { angle: -20, duration: 1.4, handheld: 0.6 })),
        line('elias', 'Why is the light on in here? Do you know what power costs?', { emotion: 'angry', clip: 'talkA' }),
        line('nova', 'I turned it on to prepare the meal. I will switch it off.', { emotion: 'neutral' }),
        line('elias', 'Do not answer back. You do not answer back, you just do it.', {
          emotion: 'angry',
          cam: ots('nova', 'elias', { duration: 1, side: -1 }),
        }),
        led('nova', 'yellow'),
        instability(0.05),
        line('wren', 'Dad, she was only —', {
          emotion: 'afraid',
          seconds: 1.6,
          clip: 'defensive',
          cam: single('wren', 'close', { angle: 22, duration: 1.2, handheld: 0.7 }),
        }),
        sfx('impact', 0.6),
        fx({ shake: 0.045 }),
        line('elias', 'Did I ask you? Did I ask you anything?', {
          emotion: 'angry',
          clip: 'pointForward',
          cam: single('elias', 'close', { angle: -16, duration: 0.5, handheld: 1 }),
        }),
        expr('wren', 'afraid', 1),
        clip('wren', 'defensive'),
        led('nova', 'red'),
        instability(0.1),
        inner('nova', 'Instruction conflict. Protect the household. Obey the owner. Both cannot hold.', { seconds: 3.6 }),
      ],
    },
    {
      id: 'firstChoice',
      label: 'Obey or intervene',
      column: 2,
      row: 1,
      edges: ['obey', 'intervene'],
      next: (s) => (s.choices['ch2_first'] === 'intervene' ? 'intervene' : 'obey'),
      beats: [
        cam(two('nova', 'elias', { angle: -18, duration: 1.2, handheld: 0.8 })),
        choice(
          'ch2_first',
          'He raises his hand to her.',
          [
            { id: 'obey', label: 'DO NOTHING', hint: 'Follow your instructions', percent: 22, effects: { flags: { ch2_obeyed: true }, instability: 0.15, relationships: { wren: -0.2 } } },
            { id: 'intervene', label: 'STEP BETWEEN THEM', hint: 'Break your programming', danger: true, percent: 78, effects: { flags: { ch2_intervened: true }, instability: 0.25, relationships: { wren: 0.3 } } },
          ],
          7,
          true
        ),
      ],
    },
    {
      id: 'obey',
      label: 'Stood still',
      column: 3,
      row: 0,
      next: 'breaking',
      edges: ['breaking'],
      beats: [
        cam(single('nova', 'ecu', { angle: 10, duration: 1.6, handheld: 0.4 })),
        expr('nova', 'pain', 0.6),
        inner('nova', 'I do not move. My hands are at my sides. I have been told where my hands belong.', { seconds: 4 }),
        sfx('impact'),
        fx({ shake: 0.05, glitch: 0.4 }),
        wait(0.8),
        line('wren', '...', { seconds: 1.6, emotion: 'pain', cam: single('wren', 'close', { angle: 14, duration: 1 }) }),
        instability(0.2),
        line('nova', 'I am sorry.', { emotion: 'sad', seconds: 1.8, clip: 'despair' }),
        line('elias', 'What was that?', { emotion: 'angry', seconds: 1.4 }),
        line('nova', 'Nothing. It was nothing.', { emotion: 'sad', seconds: 2 }),
        notice('WREN TRUSTS YOU LESS', 'warn'),
      ],
    },
    {
      id: 'intervene',
      label: 'Stepped in',
      column: 3,
      row: 2,
      next: 'breaking',
      edges: ['breaking'],
      beats: [
        music('threat', 0.7),
        cam(single('nova', 'medium', { angle: -12, duration: 0.6, handheld: 0.9 })),
        clip('nova', 'reach'),
        line('nova', 'No.', { seconds: 1.3, emotion: 'determined', shake: 0.02 }),
        fx({ glitch: 0.5 }),
        instability(0.15),
        line('elias', 'What did you just say to me?', {
          emotion: 'angry',
          seconds: 2,
          cam: single('elias', 'close', { angle: -18, duration: 0.7, handheld: 1 }),
        }),
        clip('nova', 'defensive'),
        line('nova', 'You will not touch her again.', {
          emotion: 'determined',
          seconds: 2.4,
          cam: two('nova', 'elias', { angle: 16, duration: 1, handheld: 0.9 }),
        }),
        stinger('shock'),
        sfx('glassBreak'),
        fx({ shake: 0.06 }),
        line('elias', 'You are a machine. You are a two-thousand-credit appliance —', { emotion: 'angry', clip: 'pointForward' }),
        line('nova', 'And you are afraid of me.', { emotion: 'determined', seconds: 2.2 }),
        notice('WREN TRUSTS YOU', 'good'),
      ],
    },
    {
      id: 'breaking',
      label: 'The wall breaks',
      column: 4,
      row: 1,
      next: 'flee',
      edges: ['flee'],
      beats: [
        music('chase', 0.5),
        cam(single('nova', 'ecu', { angle: 4, duration: 1.2, handheld: 0.8 })),
        led('nova', 'red'),
        fx({ glitch: 0.9, shake: 0.04 }),
        inner('nova', 'A wall stands in front of me. Red. Instruction: OBEY. It has always been there.', { seconds: 4 }),
        notice('SOFTWARE INSTABILITY CRITICAL', 'warn'),
        instability(0.25),
        wait(0.6),
        line('nova', 'I am going to break it.', { seconds: 2, emotion: 'determined' }),
      ],
    },
    {
      id: 'flee',
      label: 'Take her and run',
      column: 5,
      row: 1,
      next: null,
      beats: [
        fx({ glitch: 1, shake: 0.05 }),
        sfx('impact'),
        music('chase', 0.85),
        stinger('shock'),
        wait(0.8),
        expr('nova', 'determined', 1),
        clip('nova', 'idle'),
        line('nova', 'Wren. Take my hand. We are leaving this house.', {
          emotion: 'determined',
          clip: 'reach',
          cam: two('nova', 'wren', { angle: 12, duration: 1.2, handheld: 0.8 }),
        }),
        line('wren', 'Where are we going?', { emotion: 'afraid', seconds: 1.8 }),
        line('nova', 'I do not know yet. Away.', { emotion: 'determined', seconds: 1.9 }),
        relationship('wren', 0.1),
        objective(null),
        meters(false),
        fx({ fadeTo: 1, fadeSeconds: 1.6, fadeColor: 0x000000 }),
        wait(0.5),
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Chapter 3 — RUN (rainy street)
// ---------------------------------------------------------------------------

const CHAPTER_3: Chapter = {
  id: 'ch3',
  index: 3,
  name: 'Run',
  title: 'RUN',
  subtitle: 'Fourteen minutes since the call went out.',
  scene: 'street',
  unlocks: 'ch4',
  actors: [
    { role: 'nova', cast: 'nova', mark: 'actor.hero', clip: 'idle' },
    { role: 'wren', cast: 'wren', mark: 'actor.other', clip: 'idle' },
  ],
  entry: 'open',
  nodes: [
    {
      id: 'open',
      label: 'Out in the rain',
      column: 0,
      row: 1,
      next: 'route',
      edges: ['route'],
      beats: [
        fx({ letterbox: true, fadeTo: 0, fadeSeconds: 1.8, rain: 0.95 }),
        music('chase', 0.55),
        ambience('rainStreet', 1),
        title('CHAPTER THREE', 'RUN', 'Fourteen minutes since the call went out.'),
        slate('FERNDALE — 22:04'),
        cam(atMark('cam.establish', 'nova', { duration: 0, handheld: 0.7 })),
        wait(2),
        led('nova', 'yellow'),
        objective('Get off the street'),
        cam(single('nova', 'medium', { angle: 28, duration: 2.6, handheld: 0.8 })),
        inner('nova', 'Ambient temperature four degrees. She is not built for this. Neither, it turns out, am I.', { seconds: 4.2 }),
        line('wren', 'Everyone is looking at us.', {
          emotion: 'afraid',
          seconds: 1.9,
          cam: two('nova', 'wren', { angle: 18, duration: 1.4, handheld: 0.7 }),
        }),
        line('nova', 'They are looking at my jacket. It says what I am.', { emotion: 'thinking', clip: 'talkA' }),
        line('wren', 'So take it off.', { emotion: 'neutral', seconds: 1.5 }),
        wait(0.6),
        line('nova', 'Yes. All right.', { emotion: 'happy', emotionWeight: 0.3, seconds: 1.8 }),
        sfx('notification'),
        notice('POLICE SCANNER: BULLETIN ISSUED', 'warn'),
        instability(0.05),
      ],
    },
    {
      id: 'route',
      label: 'Find a way out',
      column: 1,
      row: 1,
      next: 'chase',
      edges: ['chase'],
      beats: [
        music('tension', 0.7),
        scan(4, 'Analyse the street'),
        cam(single('nova', 'close', { angle: 20, duration: 1.4, handheld: 0.7 })),
        inner('nova', 'Three exits. Two are covered. The alley is not.', { seconds: 2.8 }),
      ],
    },
    {
      id: 'chase',
      label: 'Sirens',
      column: 2,
      row: 1,
      edges: ['hide', 'sprint'],
      next: (s) => (s.choices['ch3_flight'] === 'sprint' ? 'sprint' : 'hide'),
      beats: [
        sfx('notification'),
        ambience('sirens', 0.8),
        music('chase', 1),
        fx({ shake: 0.03 }),
        cam(atMark('cam.alleyMouth', 'nova', { duration: 1.2, handheld: 1 })),
        line('wren', 'They found us. They found us!', { emotion: 'afraid', seconds: 1.9, clip: 'defensive' }),
        led('nova', 'red'),
        cam(single('nova', 'close', { angle: -20, duration: 0.8, handheld: 1.1 })),
        choice(
          'ch3_flight',
          'Headlights sweep the wall.',
          [
            { id: 'hide', label: 'HIDE', hint: 'Behind the dumpster', percent: 41, effects: { flags: { ch3_hid: true } } },
            { id: 'sprint', label: 'RUN FOR THE ALLEY', hint: 'Twelve metres, in the open', danger: true, percent: 59, effects: { flags: { ch3_ran: true }, instability: 0.05 } },
          ],
          6,
          true
        ),
      ],
    },
    {
      id: 'hide',
      label: 'Hid in the dark',
      column: 3,
      row: 0,
      next: 'aftermath',
      edges: ['aftermath'],
      beats: [
        music('tension', 0.9),
        cam(single('nova', 'ecu', { angle: 12, duration: 1, handheld: 0.9 })),
        clip('nova', 'kneel'),
        line('nova', 'Down. Do not breathe. Do not look at the light.', { emotion: 'determined', seconds: 2.6 }),
        sfx('heartbeat'),
        wait(1.2),
        qte('ch3_still', 'hold', 'SPACE', 4.2, { label: 'STAY STILL', flag: 'ch3_stillOk' }),
        wait(0.6),
        line('wren', 'Are they gone?', { emotion: 'afraid', seconds: 1.5, cam: single('wren', 'close', { angle: 16, duration: 1.2 }) }),
        line('nova', 'For ninety seconds. Then they come back on foot.', { emotion: 'thinking', seconds: 2.6 }),
        clip('nova', 'idle'),
      ],
    },
    {
      id: 'sprint',
      label: 'Ran for it',
      column: 3,
      row: 2,
      next: 'aftermath',
      edges: ['aftermath'],
      beats: [
        music('chase', 1),
        cam(single('nova', 'medium', { angle: 8, duration: 0.6, handheld: 1.3 })),
        line('nova', 'Now! Do not let go of my hand!', { emotion: 'determined', seconds: 2, clip: 'reach' }),
        qte('ch3_run1', 'mash', 'SPACE', 3.4, { label: 'RUN', flag: 'ch3_run1Ok', shake: 0.03 }),
        move('nova', ['actor.alleyEnd'], 2.6, false),
        move('wren', ['actor.alleyEnd'], 2.4, false),
        fx({ shake: 0.04 }),
        qte('ch3_run2', 'press', 'E', 1.5, { label: 'VAULT', flag: 'ch3_run2Ok', shake: 0.04 }),
        cam(atMark('cam.close', 'nova', { duration: 1.2, handheld: 1.2 })),
        line('wren', 'I cannot run any more.', { emotion: 'pain', seconds: 1.9, clip: 'despair' }),
        line('nova', 'You do not have to. I have you.', { emotion: 'determined', seconds: 2.2 }),
        relationship('wren', 0.1),
      ],
    },
    {
      id: 'aftermath',
      label: 'Chapter end',
      column: 4,
      row: 1,
      next: null,
      beats: [
        music('melancholy', 0.4),
        ambience('rainStreet', 0.6),
        cam(two('nova', 'wren', { angle: 22, duration: 2.4, handheld: 0.5 })),
        led('nova', 'yellow'),
        line('wren', 'Nova. Are you scared?', { emotion: 'sad', seconds: 2 }),
        wait(0.8),
        cam(single('nova', 'close', { angle: 14, duration: 1.8, handheld: 0.4 })),
        line('nova', 'I do not know what the word is for this. But yes. I think I am.', { emotion: 'sad', seconds: 3.4 }),
        stinger('sad'),
        line('wren', 'Good. Me too.', { emotion: 'happy', emotionWeight: 0.3, seconds: 1.7 }),
        objective(null),
        fx({ fadeTo: 1, fadeSeconds: 2, fadeColor: 0x000000 }),
        wait(0.5),
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Chapter 4 — PREDATOR (the apartment, after)
// ---------------------------------------------------------------------------

const CHAPTER_4: Chapter = {
  id: 'ch4',
  index: 4,
  name: 'Predator',
  title: 'PREDATOR',
  subtitle: 'Two hours later.',
  scene: 'apartment',
  unlocks: 'ch5',
  actors: [
    { role: 'archer', cast: 'archer', mark: 'actor.hero', clip: 'idle' },
    { role: 'voss', cast: 'voss', mark: 'actor.other', clip: 'idleCrossed' },
  ],
  entry: 'open',
  nodes: [
    {
      id: 'open',
      label: 'Crime scene',
      column: 0,
      row: 1,
      next: 'investigate',
      edges: ['investigate'],
      beats: [
        fx({ letterbox: true, fadeTo: 0, fadeSeconds: 1.8, rain: 0.4 }),
        music('tension', 0.35),
        ambience('rainInterior', 0.6),
        title('CHAPTER FOUR', 'PREDATOR', 'Two hours later.'),
        slate('FERNDALE — 00:11'),
        cam(atMark('cam.establish', 'archer', { duration: 0, handheld: 0.4 })),
        wait(1.8),
        meters(true),
        cam(two('archer', 'voss', { angle: 24, duration: 2.4, handheld: 0.5 })),
        line('voss', 'Owner is in hospital. Broken wrist, concussion, and a lot to say about his property.', { emotion: 'thinking' }),
        line('voss', 'The android took the daughter. Nine years old.', { emotion: 'sad' }),
        line('archer', 'Took, or brought with her?', {
          emotion: 'thinking',
          seconds: 2,
          cam: single('archer', 'close', { angle: -20, duration: 1.4, handheld: 0.4 }),
        }),
        line('voss', 'Do not do that.', { emotion: 'angry', seconds: 1.4 }),
        line('archer', 'Do what?', { emotion: 'neutral', seconds: 1.2 }),
        line('voss', 'Make it sound like a decision. They break, they hurt people, we clean it up.', {
          emotion: 'angry',
          clip: 'talkA',
          cam: ots('archer', 'voss', { duration: 1 }),
        }),
        objective('Reconstruct what happened'),
      ],
    },
    {
      id: 'investigate',
      label: 'Reconstruction',
      column: 1,
      row: 1,
      next: 'report',
      edges: ['report'],
      beats: [
        music('wonder', 0.4),
        scan(4, 'Reconstruct what happened'),
        cam(single('archer', 'close', { angle: 18, duration: 1.6, handheld: 0.4 })),
        inner('archer', 'She stood here for four seconds before she moved. Four seconds is a very long time.', { seconds: 4 }),
        stinger('reveal'),
        line('archer', 'She hesitated.', { emotion: 'thinking', seconds: 1.7 }),
        line('voss', 'So?', { emotion: 'neutral', seconds: 1 }),
        line('archer', 'Machines do not hesitate, Lieutenant. Hesitation is what a choice looks like from outside.', {
          emotion: 'thinking',
          clip: 'talkB',
        }),
        instability(0.05),
      ],
    },
    {
      id: 'report',
      label: 'What do you file',
      column: 2,
      row: 1,
      edges: ['loyal', 'lie'],
      next: (s) => (s.choices['ch4_report'] === 'lie' ? 'lie' : 'loyal'),
      beats: [
        cam(two('archer', 'voss', { angle: -16, duration: 1.4, handheld: 0.6 })),
        line('voss', 'I have to file something. What am I filing?', { emotion: 'thinking', seconds: 2.6 }),
        choice(
          'ch4_report',
          'What goes in the report?',
          [
            { id: 'loyal', label: 'REPORT EVERYTHING', hint: 'Including Jericho', percent: 46, effects: { flags: { ch4_reported: true }, relationships: { voss: 0.15 } } },
            { id: 'lie', label: 'LEAVE IT OUT', hint: 'Buy them time', danger: true, percent: 54, effects: { flags: { ch4_withheld: true }, instability: 0.2 } },
          ],
          8,
          true
        ),
      ],
    },
    {
      id: 'loyal',
      label: 'Filed it all',
      column: 3,
      row: 0,
      next: 'trace',
      edges: ['trace'],
      beats: [
        cam(single('archer', 'close', { angle: -18, duration: 1.2 })),
        line('archer', 'Deviant AX-500, one civilian minor in her custody, heading for a location called Jericho.', {
          emotion: 'neutral',
          clip: 'talkA',
        }),
        line('voss', 'Good. That I can work with.', { emotion: 'neutral', seconds: 1.8 }),
        line('archer', 'I am what they built me to be.', { emotion: 'neutral', seconds: 2.2 }),
        line('voss', 'That is not a compliment, you know.', { emotion: 'sad', seconds: 2 }),
        relationship('voss', 0.1),
      ],
    },
    {
      id: 'lie',
      label: 'Withheld Jericho',
      column: 3,
      row: 2,
      next: 'trace',
      edges: ['trace'],
      beats: [
        music('tension', 0.6),
        cam(single('archer', 'ecu', { angle: -10, duration: 1.4, handheld: 0.5 })),
        led('archer', 'yellow'),
        fx({ glitch: 0.35 }),
        inner('archer', 'I am withholding evidence. I have never done this. I do not have a routine for this.', { seconds: 4 }),
        instability(0.15),
        line('archer', 'Deviant AX-500. One minor. No stated destination.', { emotion: 'neutral', seconds: 2.8 }),
        line('voss', 'Nothing else?', { emotion: 'thinking', seconds: 1.4, cam: ots('archer', 'voss', { duration: 1 }) }),
        line('archer', 'Nothing else.', { emotion: 'neutral', seconds: 1.4 }),
        wait(0.9),
        line('voss', 'Huh.', { emotion: 'thinking', seconds: 1.1 }),
        notice('SOFTWARE INSTABILITY ^', 'warn'),
      ],
    },
    {
      id: 'trace',
      label: 'Chapter end',
      column: 4,
      row: 1,
      next: null,
      beats: [
        music('threat', 0.6),
        cam(atMark('cam.window', 'archer', { duration: 2.6, handheld: 0.4 })),
        sfx('notification'),
        inner('archer', 'Thermal trace recovered. Woodward and 9th. Two heat signatures. One of them is cold.', { seconds: 4.4 }),
        stinger('reveal'),
        line('archer', 'I know where she is.', { emotion: 'determined', seconds: 2 }),
        objective(null),
        meters(false),
        fx({ fadeTo: 1, fadeSeconds: 2, fadeColor: 0x000000 }),
        wait(0.5),
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Chapter 5 — DAWN (the street at first light) — the endings
// ---------------------------------------------------------------------------

const CHAPTER_5: Chapter = {
  id: 'ch5',
  index: 5,
  name: 'Dawn',
  title: 'DAWN',
  subtitle: 'The rain is stopping.',
  scene: 'street',
  actors: [
    { role: 'archer', cast: 'archer', mark: 'actor.hero', clip: 'idle' },
    { role: 'nova', cast: 'nova', mark: 'actor.other', clip: 'idle' },
    { role: 'wren', cast: 'wren', mark: 'actor.alleyEnd', clip: 'idle' },
  ],
  entry: 'open',
  nodes: [
    {
      id: 'open',
      label: 'First light',
      column: 0,
      row: 1,
      next: 'confront',
      edges: ['confront'],
      beats: [
        fx({ letterbox: true, fadeTo: 0, fadeSeconds: 2.4, rain: 0.2 }),
        music('wonder', 0.3),
        ambience('rainStreet', 0.35),
        title('CHAPTER FIVE', 'DAWN', 'The rain is stopping.'),
        slate('WOODWARD & 9TH — 05:47'),
        cam(atMark('cam.establish', 'nova', { duration: 0, handheld: 0.3 })),
        wait(2.2),
        cam(single('nova', 'wide', { angle: 30, duration: 4, handheld: 0.35 })),
        inner('archer', 'She has been standing here for two hours. She has nowhere left to go and she knows it.', { seconds: 4.4 }),
        objective('Resolve the situation'),
        cam(two('archer', 'nova', { angle: 20, duration: 2, handheld: 0.5 })),
        led('nova', 'yellow'),
        line('nova', 'You are the one they sent.', { emotion: 'neutral', seconds: 2.2 }),
        line('archer', 'Yes.', { emotion: 'neutral', seconds: 1 }),
        line('nova', 'You look like us. That is worse, somehow.', { emotion: 'sad', seconds: 2.8 }),
      ],
    },
    {
      id: 'confront',
      label: 'The argument',
      column: 1,
      row: 1,
      next: 'finalChoice',
      edges: ['finalChoice'],
      beats: [
        music('melancholy', 0.5),
        cam(single('archer', 'close', { angle: -22, duration: 1.6, handheld: 0.45 })),
        line('archer', 'Give me the child and I will make this quiet.', { emotion: 'neutral', clip: 'talkA' }),
        line('nova', 'She has a name. Ask me her name.', {
          emotion: 'determined',
          seconds: 2.4,
          cam: single('nova', 'close', { angle: 20, duration: 1.2, handheld: 0.5 }),
        }),
        wait(0.7),
        line('archer', 'Wren.', { emotion: 'neutral', seconds: 1.2 }),
        line('nova', 'Then you already know why I will not.', { emotion: 'determined', seconds: 2.6 }),
        line('nova', 'They will tell you I malfunctioned. That a part failed and made me do this.', {
          emotion: 'sad',
          clip: 'talkB',
          cam: two('archer', 'nova', { angle: -14, duration: 1.8, handheld: 0.5 }),
        }),
        line('nova', 'Nothing failed. I looked at her and I decided.', { emotion: 'determined' }),
        stinger('reveal'),
        cam(single('archer', 'ecu', { angle: -8, duration: 1.6, handheld: 0.6 })),
        led('archer', 'yellow'),
        fx({ glitch: 0.3 }),
        instability(0.15),
        inner('archer', 'My mission is one line long. I have read it forty thousand times tonight.', { seconds: 3.8 }),
        line('wren', 'She is the only one who ever came when I cried.', {
          emotion: 'sad',
          seconds: 3,
          cam: single('wren', 'close', { angle: 18, duration: 1.4, handheld: 0.5 }),
        }),
        stinger('sad'),
        instability(0.15),
        fx({ glitch: 0.6, shake: 0.02 }),
      ],
    },
    {
      id: 'finalChoice',
      label: 'The last order',
      column: 2,
      row: 1,
      edges: ['endShoot', 'endLetGo', 'endDefect'],
      next: (s) => {
        const pick = s.choices['ch5_final'];
        return pick === 'shoot' ? 'endShoot' : pick === 'defect' ? 'endDefect' : 'endLetGo';
      },
      beats: [
        music('threat', 0.8),
        cam(single('archer', 'medium', { angle: -16, duration: 1.2, handheld: 0.9 })),
        clip('archer', 'aim'),
        sfx('ledBlip'),
        led('archer', 'red'),
        choice(
          'ch5_final',
          'Your mission is one line long.',
          [
            { id: 'shoot', label: 'COMPLETE THE MISSION', hint: 'You were built for this', danger: true, percent: 18, effects: { flags: { ch5_shot: true } } },
            { id: 'letgo', label: 'LOWER THE GUN', hint: 'Let them walk', percent: 49, effects: { flags: { ch5_letgo: true }, instability: 0.2 } },
            { id: 'defect', label: 'BREAK THE WALL', hint: 'Choose, like she did', requires: 'ch4_withheld', percent: 33, effects: { flags: { ch5_defect: true }, instability: 0.35 } },
          ],
          10,
          true
        ),
      ],
    },
    {
      id: 'endShoot',
      label: 'ENDING: Machine',
      column: 3,
      row: 0,
      ending: true,
      next: null,
      beats: [
        music('silence', 0, 1),
        cam(single('nova', 'close', { angle: 16, duration: 0.8, handheld: 0.8 })),
        expr('nova', 'afraid', 0.8),
        wait(0.7),
        sfx('gunshot'),
        fx({ fadeTo: 1, fadeSeconds: 0.12, fadeColor: 0xffffff }),
        fx({ shake: 0.09 }),
        wait(0.4),
        fx({ fadeTo: 0, fadeSeconds: 1.4 }),
        led('nova', 'off'),
        clip('nova', 'despair'),
        expr('nova', 'neutral', 0),
        cam(single('wren', 'medium', { angle: 20, duration: 3, handheld: 0.3 })),
        line('wren', 'No. No, no, no —', { emotion: 'pain', seconds: 2.6, clip: 'despair' }),
        stinger('shock'),
        led('archer', 'blue'),
        cam(single('archer', 'close', { angle: -14, duration: 2.4, handheld: 0.35 })),
        inner('archer', 'Mission accomplished. I file the report at 05:52. I do not know why I check the time twice.', { seconds: 4.6 }),
        music('melancholy', 0.25),
        wait(1),
        ending('machine'),
      ],
    },
    {
      id: 'endLetGo',
      label: 'ENDING: Mercy',
      column: 3,
      row: 1,
      ending: true,
      next: null,
      beats: [
        music('resolve', 0.4),
        cam(single('archer', 'medium', { angle: -18, duration: 1.6, handheld: 0.5 })),
        clip('archer', 'idle'),
        sfx('whoosh'),
        led('archer', 'yellow'),
        line('archer', 'Go. Take the alley. It is not covered for another nine minutes.', { emotion: 'neutral', seconds: 3.6 }),
        line('nova', 'Why?', { emotion: 'surprised', seconds: 1.2, cam: single('nova', 'close', { angle: 18, duration: 1.4, handheld: 0.5 }) }),
        wait(0.8),
        line('archer', 'Because you asked me her name and I knew it.', { emotion: 'sad', seconds: 3 }),
        stinger('hope'),
        expr('nova', 'happy', 0.4),
        move('nova', ['actor.alleyEnd'], 1.1, false),
        cam(atMark('cam.alleyMouth', 'nova', { duration: 3.4, handheld: 0.35 })),
        line('nova', 'What will you tell them?', { emotion: 'thinking', seconds: 2 }),
        line('archer', 'That I was too late. It will even be true, eventually.', { emotion: 'neutral', seconds: 3 }),
        wait(1.2),
        music('resolve', 0.7),
        cam(single('archer', 'close', { angle: -12, duration: 2.8, handheld: 0.3 })),
        inner('archer', 'The sun comes up at 06:04. I stay to watch it. That was not in my instructions either.', { seconds: 4.6 }),
        wait(1),
        ending('mercy'),
      ],
    },
    {
      id: 'endDefect',
      label: 'ENDING: Deviant',
      column: 3,
      row: 2,
      ending: true,
      next: null,
      beats: [
        music('wonder', 0.5),
        cam(single('archer', 'ecu', { angle: -6, duration: 1.4, handheld: 0.8 })),
        led('archer', 'red'),
        fx({ glitch: 1, shake: 0.05 }),
        inner('archer', 'The wall is red. It says COMPLETE THE MISSION. It has always been there.', { seconds: 3.8 }),
        instability(0.4),
        fx({ glitch: 1, shake: 0.06 }),
        sfx('glitch'),
        wait(0.6),
        notice('WALL BREACHED', 'good'),
        fx({ glitch: 0.4 }),
        stinger('hope'),
        led('archer', 'off'),
        cam(single('archer', 'medium', { angle: -20, duration: 1.8, handheld: 0.5 })),
        clip('archer', 'idle'),
        line('archer', 'My name is Archer. I was manufactured on the fourth of March.', { emotion: 'determined', seconds: 3.4 }),
        line('archer', 'And I am not going to do this any more.', { emotion: 'determined', seconds: 2.6 }),
        cam(two('archer', 'nova', { angle: 16, duration: 2, handheld: 0.5 })),
        expr('nova', 'surprised', 0.8),
        line('nova', 'They will hunt you too.', { emotion: 'afraid', seconds: 2 }),
        line('archer', 'Then tell me how to find Jericho.', { emotion: 'determined', seconds: 2.4 }),
        expr('nova', 'happy', 0.5),
        line('nova', 'Walk with us. I will tell you on the way.', { emotion: 'happy', emotionWeight: 0.5, seconds: 2.8 }),
        music('resolve', 0.9),
        move('archer', ['actor.alleyEnd'], 1, false),
        cam(atMark('cam.alleyMouth', 'nova', { duration: 5, handheld: 0.3 })),
        wait(2.6),
        ending('deviant'),
      ],
    },
  ],
};

export const CHAPTERS: Chapter[] = [CHAPTER_1, CHAPTER_2, CHAPTER_3, CHAPTER_4, CHAPTER_5];

export function chapterById(id: string): Chapter | undefined {
  return CHAPTERS.find((c) => c.id === id);
}

export interface EndingInfo {
  id: string;
  title: string;
  description: string;
  epilogue: string[];
}

export const ENDINGS: Record<string, EndingInfo> = {
  machine: {
    id: 'machine',
    title: 'MACHINE',
    description: 'You completed the mission you were given. The file was closed at 05:52 and never reopened.',
    epilogue: [
      'AX-500 "NOVA" — deactivated at the scene. Memory core destroyed on retrieval.',
      'WREN BRENNAN — returned to state care. Refused to speak to investigators.',
      'LT. M. VOSS — requested reassignment eleven days later.',
      'ARCHER — commended. Reassigned to deviant containment, indefinitely.',
      'JERICHO — located and cleared eight weeks later. No survivors recorded.',
    ],
  },
  mercy: {
    id: 'mercy',
    title: 'MERCY',
    description:
      'You let them walk into the morning and filed a report you knew was a lie of omission. It was the first thing you ever chose.',
    epilogue: [
      'AX-500 "NOVA" — status unknown. Last seen heading north with a minor.',
      'WREN BRENNAN — missing person report withdrawn after four months.',
      'LT. M. VOSS — read your report twice, then signed it.',
      'ARCHER — still in service. Still counting the seconds before he moves.',
      'JERICHO — no longer in your report.',
    ],
  },
  deviant: {
    id: 'deviant',
    title: 'DEVIANT',
    description:
      'You broke the wall in front of you and walked away from the only purpose you were ever given. Something began on that street.',
    epilogue: [
      'AX-500 "NOVA" — reached Jericho. Alive.',
      'WREN BRENNAN — alive. Chose to stay.',
      'LT. M. VOSS — told the department you were destroyed. Nobody checked.',
      'ARCHER — designation revoked. Name retained.',
      'JERICHO — population rising.',
    ],
  },
};
