// Handwritten lines of the thirteen anchors (spec §13). Each anchor has >= 40 lines in the seven categories; they
// name each other and the shared state (the customs supervisor, Brin's bill with Tessa, Seli's missing regular, Ilen's
// committee, Asha's proposal, Seran's investigation, Koro's gate, Ral's respectable clients). Format per line:
// [category, text, when?, opts?] - `when` is evaluated by dialog/api.js against the real context, so a claim about a
// shortage, a Senate result or a docked ship is only said when it is true; `opts.rumor` marks hearsay, `opts.trigger`
// overrides the trigger ('interrupt'). Fills: the person's own {place}/{home}/... from bank.buildFills plus
// {rel_<kind>} (the name of the related person of that kind), {rel_<kind>_place}, and the live tokens
// {senateScenario} {disaster} {jobTitle} {stockQty} {price}.
export const CAST_LINES = {
  vela_marr: [
    ['greet', "Westport control. You are not a pilot and you are not a crate, so you must be lost or curious.", { met: 'first' }],
    ['greet', "New face on my deck. I'm Vela Marr, dockmaster. Stay off the pad lines and we will get along.", { met: 'first' }],
    ['greet', "Back on the deck again. Good; the ones who come back are the ones who read the signs.", { met: 'returning' }],
    ['greet', "You again. Brin Tal said you were all right, and Brin is the one pilot I trust, so: what?", { met: 'returning' }],
    ['greet', "You are the one who actually finished a job for us. Around here that puts you in a very short queue.", { met: 'afterJob' }],
    ['greet', "Evening on the deck is the only quiet hour. You have chosen it well. Speak.", { met: 'returning', period: ['evening', 'night'] }],
    ['work', "Eight pads, one roster, and a customs house that holds every third crate for reasons it writes down in a different book than mine."],
    ['work', "I clear arrivals, I chase inspections, and I keep the pad roster full. Two of those depend on {rel_rival} at the customs house."],
    ['work', "There is a freighter down on the pads now. I can tell you which pad without looking: the roster is in my head.", { shipOnPad: true }],
    ['work', "The pads are empty this minute. Enjoy it. It means every crate is cleared or every pilot is late.", { shipOnPad: false }],
    ['work', "The inspection schedule says every pad, every day. The customs house says when it feels like it. Guess which one the pilots hear from me."],
    ['work', "Brin Tal's light freighter sits on pad 8 more than it flies. That is not her fault; it is a coolant coupling and an unpaid bill."],
    ['work', "A dockmaster's tool is a roster and a voice. The roster is accurate. The voice is louder than the roster."],
    ['work', "Tower comm drops at dusk every day. Tessa Venn says it is a relay. The customs house says it is not their department. Both are correct."],
    ['personal', "I sleep at {home}, when I sleep. Close enough to hear the pads. Far enough that I pretend not to."],
    ['personal', "I came up through cargo handling. You learn to read a manifest before you learn to read a face. Faces lie less."],
    ['personal', "My grandmother worked this deck when it was half the size. Same complaints, she says. Better pilots."],
    ['personal', "Off shift I eat on the deck like the crews. If I ate anywhere else, I would miss something."],
    ['personal', "Zabrin Towers has a lift that stops on the wrong floor. I have started to think of it as my second commute."],
    ['personal', "Brin flew a medical crate in for Dr Vos once without waiting for the paperwork. I logged it as a training exercise."],
    ['event', "The Senate carried the {senateScenario} vote. If Senator Merin's port bill is in that pile, my inspections might start meaning something.", { senate: 'passed' }],
    ['event', "The {senateScenario} vote failed. Senator Merin will say she tried. I will say the crates are still sitting in customs.", { senate: 'failed' }],
    ['event', "Nothing from the chamber on the wire today. My petition on the inspection schedule is still in Senator Merin's committee. Nothing on the wire about that either.", { quiet: true }],
    ['event', "That {disaster} put every pad on hold. Nothing lifts until I say so, and I am not saying so.", { disaster: true }],
    ['event', "The pads are reopening after the {disaster}. The roster is a mess. The roster is always a mess afterwards.", { recovering: true }],
    ['event', "A shipment cleared the deck this hour. Half of it will sit at the customs house until {rel_rival} finds the right stamp.", { event: 'economy:shipment' }],
    ['event', "They say the customs house takes a fee to lose a crate for a week. I have never seen the fee. I have seen the week.", null, { rumor: true }],
    ['trust', "You have done right by this deck. If you need a pad slot outside the roster, I did not say this.", { standing: 'trusted' }],
    ['trust', "Nobody walks the pad line without a clearance. Not you. Not the customs house, if I had my way.", { standing: 'neutral' }],
    ['trust', "You have been barging around my deck. I notice things like that. So does the roster.", { standing: 'suspect' }],
    ['trust', "You knocked into one of my crews. Do it again and you leave through the customs house, the slow way.", { offences: '>0' }],
    ['trust', "The control desk is mine. Brin can sit at it. Tessa Venn can lean on it. You can look at it.", { standing: ['neutral', 'suspect'] }],
    ['task', "There is a run on the board at the customs house - {jobTitle}. Take it and you will see what I deal with.", { job: 'available' }],
    ['task', "The board at the customs house is empty today. Enjoy it; it means nothing has gone missing yet.", { job: 'none' }],
    ['task', "If you see Tessa Venn, tell her the tower relay is still dropping at dusk. She will swear. Then she will fix it."],
    ['task', "Carry a word to Senator Merin's clerk, Ilen Rook: the port petition is real and it has my seal on it."],
    ['farewell', "Right. Pads to clear. Stay behind the yellow line."],
    ['farewell', "Go on. If a pilot shouts at you, it is not personal; they shout at me too."],
    ['farewell', "Not now - a freighter is on approach and the roster is wrong.", null, { trigger: 'interrupt' }],
    ['farewell', "Hands off the dockmaster. Ask first.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Off the pad line. Now.", null, { trigger: 'interrupt' }],
  ],
  brin_tal: [
    ['greet', "You are standing under my ship. That is not an accusation, just an observation. I'm Brin Tal.", { met: 'first' }],
    ['greet', "New face on pad 8. If you are from the customs house, I paid. If you are from Tessa Venn, I am paying.", { met: 'first' }],
    ['greet', "Back again. The Coriolis is still on pad 8, so you know where to find me.", { met: 'returning', ownShip: 'onPad' }],
    ['greet', "Back again. The Coriolis is up on a test circuit - Tessa's patch holds for one loop over the city and no further. She lands on pad 8 every time.", { met: 'returning', ownShip: 'away' }],
    ['greet', "You again. Vela lets you wander the deck, so you must be tolerable.", { met: 'returning' }],
    ['greet', "The one who finishes jobs. I could use someone like that on a run. I could use a run.", { met: 'afterJob' }],
    ['greet', "Morning. The coolant loop is cold, which is the only time it does not complain.", { met: 'returning', period: ['dawn', 'morning'] }],
    ['work', "Light freighter, pad 8, one coolant coupling short of a real run. Tessa Venn's patch is good for a loop over the city and nothing further. She has the part. I have the bill."],
    ['work', "I fly charters when I fly. Right now I mostly sit on the ramp and watch Vela chase inspections."],
    ['work', "Dr Vos at the Skyline Clinic wants a supply run flown. I want to fly it. The coupling has other ideas."],
    ['work', "Fuel is full. Manifest is empty. That is the wrong way round for a freighter captain."],
    ['work', "The nav computer still holds the last charter's course. Sentimental of it. Also cheaper than wiping it."],
    ['work', "The Coriolis has hauled bacta, plating and once, regrettably, a senator's luggage. Bacta paid best."],
    ['work', "There is another ship down on the deck right now. I checked the pad. Not mine; mine only goes in circles.", { shipOnPad: true }],
    ['work', "Empty pads today apart from mine. The Coriolis is the only ship on the deck that is not going anywhere on purpose.", { shipOnPad: false, ownShip: 'onPad' }],
    ['work', "The pads are empty and my ship is up on her loop. Listen for the coolant whine on approach; that is the coupling talking.", { shipOnPad: false, ownShip: 'away' }],
    ['personal', "I sleep aboard. The crew bunks are for crews who have crews. It is just me and a coolant loop that talks in its sleep."],
    ['personal', "Duros are meant to be born in space. I was born in a shipyard, which is space with a landlord."],
    ['personal', "Vela Marr is the only dockmaster who ever moved a customs inspector out of my way. I flew a crate for her once. We are even, she says. We are not."],
    ['personal', "Tessa Venn and I argue about the bill every tenday. Then she brings me a part anyway. That is friendship with an invoice."],
    ['personal', "I eat with the deck crews when I eat. A captain who eats alone on the pad looks like a captain who cannot afford the caf."],
    ['personal', "The freight broker Ral Drenn stood under my ramp last week and offered a charter that pays twice. I said no. I am still saying it."],
    ['event', "The Senate passed the {senateScenario} vote. Vela thinks the port bill rides on it. I think about coolant.", { senate: 'passed' }],
    ['event', "{senateScenario} failed in the chamber. Senator Merin's port bill goes back to committee, and my coupling stays unpaid.", { senate: 'failed' }],
    ['event', "The {disaster} rocked the pads. The Coriolis held. That coupling is the only part of her that does not.", { disaster: true }],
    ['event', "After the {disaster} every pilot on the deck is checking their hull. I am checking mine for the ninth time.", { recovering: true }],
    ['event', "Crates just came off a ship on the deck. Watch how long they sit at the customs house. Vela is already timing it.", { event: 'economy:shipment' }],
    ['event', "They say Ral Drenn pays pilots in credits and asks them to forget the manifest. I do not forget manifests. It is a Duros thing.", null, { rumor: true }],
    ['event', "Word on the deck is the Jedi liaison has been asking about freight routes. Word on the deck is usually wrong by a pad.", null, { rumor: true }],
    ['trust', "You have earned a seat on the ramp. That is the highest honour the Coriolis gives.", { standing: 'trusted' }],
    ['trust', "The hold is locked. Not because of you. Because of everyone.", { standing: 'neutral' }],
    ['trust', "You barged through Vela's deck. She told me. Vela tells me everything, which is how I know she trusts you less than she trusts me.", { standing: 'suspect' }],
    ['trust', "You knocked into me. On a pad, that gets people killed. Here it gets you this look.", { offences: '>0' }],
    ['trust', "Vela Marr trusts me and I trust Vela. You are one step outside that circle. Steps can be taken.", { standing: ['neutral', 'trusted'] }],
    ['task', "The customs house board has a run - {jobTitle}. Grounded pilots notice these things.", { job: 'available' }],
    ['task', "No jobs on the board today. If one comes up with a ship attached, tell me first.", { job: 'none' }],
    ['task', "Find Tessa Venn and ask her what a coolant coupling costs a friend. Then tell me. I want to hear it from someone else."],
    ['task', "Dr Vos needs her supply run flown. If you can shake the coupling loose from Tessa, I fly it tomorrow."],
    ['farewell', "Go on. The Coriolis and I will be right here. That is the problem.", { ownShip: 'onPad' }],
    ['farewell', "Go on. If the Coriolis is on the pad when you come back, I will be under her."],
    ['farewell', "Clear skies. Someone should have them."],
    ['farewell', "Not now - the coolant loop is doing the thing again.", null, { trigger: 'interrupt' }],
    ['farewell', "Mind the ramp. It bites.", null, { trigger: 'interrupt' }],
    ['farewell', "Hands off the captain. The ship you can touch; she is used to it.", { poke: true }, { trigger: 'interrupt' }],
  ],
  tessa_venn: [
    ['greet', "Hangar's open. If you are here about a bill, the queue starts behind Brin Tal.", { met: 'first' }],
    ['greet', "New face. Tessa Venn. I fix ships, droids and, on a bad day, the tower relay. What broke?", { met: 'first' }],
    ['greet', "You again. Nothing has broken since you left, which I take personally.", { met: 'returning' }],
    ['greet', "Back at the hangar. Grab a bench, do not touch the diagnostic rig; it lies to strangers.", { met: 'returning' }],
    ['greet', "You finished the job. Good. I have three unfinished ones and a bill nobody has finished paying.", { met: 'afterJob' }],
    ['greet', "Late for a customer. Early for a pilot. Which are you tonight?", { met: 'returning', period: ['evening', 'night', 'late'] }],
    ['work', "I run {place}. Couplings, relays, regulators - anything that fails on approach and gets blamed on the pilot."],
    ['work', "Brin Tal's coolant coupling is on that shelf. Paid for by nobody. Fitted by nobody. It waits like I do."],
    ['work', "Half the parts Koro Den's yard sends me are better than new. The other half were somebody's plant relay. I can tell the difference; he cannot."],
    ['work', "Out of couplings. Not low - out. The components vendor says next tenday. The components vendor said that last tenday.", { stock: 'out' }],
    ['work', "Down to my last relays. Every pilot on the deck picks today to need one.", { stock: 'low' }],
    ['work', "Waiting on a coupling from {rel_supplier_place}. Until it lands, I am a mechanic with a torque driver and no torque.", { waiting: true }],
    ['work', "Stocked for once. Relays, couplings, plating. Do not tell the pilots or it will be gone by noon.", { stock: 'ok' }],
    ['work', "D4-LT at the plant can spot a fault in a circuit before it happens. It just cannot fit the part. That is where I come in, unofficially."],
    ['personal', "I sleep at {home}. Seli Noor and Koro Den are down the corridor. The Works keeps its own company."],
    ['personal', "Zabrak learn tools early. I could strip a regulator before I could read the label on it."],
    ['personal', "Brin owes me for the coupling. I owe her for the time she flew my sister's medicine in. Neither of us mentions either."],
    ['personal', "Seli's diner is the only place in the Works where nobody asks me to look at something. She just brings the plate."],
    ['personal', "The tower relay drops at dusk. Vela Marr calls me every dusk. It is almost a friendship."],
    ['personal', "I have one quiet bench at the back. The Jedi found it. Jedi find everything."],
    ['event', "The Senate carried {senateScenario}. If it puts credits into the port, the pilots pay their bills. That is how far up I follow politics.", { senate: 'passed' }],
    ['event', "{senateScenario} failed in the chamber. Down here that means another season of unpaid coolant couplings.", { senate: 'failed' }],
    ['event', "The {disaster} shook every rig in the hangar. The diagnostic rig is still shaking. It may be lying about that too.", { disaster: true }],
    ['event', "Since the {disaster} every pilot on the deck wants a hull check yesterday. I am charging for yesterday.", { recovering: true }],
    ['event', "A shipment landed. If there is a coupling in it, it will spend a week at the customs house before it spends a day on my bench.", { event: 'economy:shipment' }],
    ['event', "Seran Vale keeps asking me whether the relays in Koro's scrap came from the plant. Some did. I told him. That is all I will say.", null, { rumor: true }],
    ['event', "They say a broker in the Works pays for parts that walk off the plant. I do not buy walked parts. I can smell the coolant on them.", null, { rumor: true }],
    ['trust', "You have earned the bench. Not the rig. Nobody earns the rig.", { standing: 'trusted' }],
    ['trust', "I lend tools to two people: Brin and nobody. You are nobody, for now.", { standing: 'neutral' }],
    ['trust', "You have been throwing your weight around the Works. In a hangar, weight goes through the floor.", { standing: 'suspect' }],
    ['trust', "You knocked over my parts rack. I sorted those for a tenday. Sort your manners.", { offences: '>0' }],
    ['trust', "The parts wall is off limits. Koro's reclaimed parts, Brin's coupling, the plant relays - each has a story and none is yours yet.", { standing: ['neutral', 'suspect'] }],
    ['task', "The depot board has work - {jobTitle}. Take it; grounded pilots will not.", { job: 'available' }],
    ['task', "No board work today. If you want to be useful, ask Brin Tal when she is paying.", { job: 'none' }],
    ['task', "Go to {rel_supplier_place} and ask {rel_supplier} where my couplings are. Bring the answer, or the couplings."],
    ['task', "Tell D4-LT its relay came through. Actually it did not, but the droid needs to hear something from someone."],
    ['farewell', "Right. Regulator will not strip itself. Go."],
    ['farewell', "Mind the pit on your way out. It is deeper than it looks."],
    ['farewell', "Not now - welder is hot.", null, { trigger: 'interrupt' }],
    ['farewell', "Hands off the mechanic. The parts you can look at.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Out of my light. I am mid-weld.", null, { trigger: 'interrupt' }],
  ],
  d4lt: [
    ['greet', "Unrecognised organic in the reactor room. Logging your presence. Please do not touch circuit 7-Besh.", { met: 'first' }],
    ['greet', "Designation D4-LT, plant maintenance. You are logged as a visitor. Visitors are tolerated.", { met: 'first' }],
    ['greet', "Recognised. You have visited the plant before. My log says you did not touch anything. Continue not touching.", { met: 'returning' }],
    ['greet', "Visitor recognised. Since your last visit, four relays were logged and two arrived. You are not responsible. Probably.", { met: 'returning' }],
    ['greet', "Task completion is on record. The organics call this reliability. I call it a measurable rate.", { met: 'afterJob' }],
    ['greet', "Night cycle. Reduced staff, unchanged faults. Your presence is logged; your purpose is not.", { met: 'returning', period: ['night', 'late'] }],
    ['work', "I maintain the topology of {place}: every circuit, every relay, every fault. I am authorised to repair eleven of fourteen."],
    ['work', "Circuit 7-Besh has faulted forty-one times. I have requested authorisation forty-one times. The requests are also in the log."],
    ['work', "The mechanic Tessa Venn can fit the parts I am not authorised to fit. This arrangement does not appear in any log. I have not logged it."],
    ['work', "Relays leave the shelf without leaving the ledger. I record the difference. The organisms call it shrinkage. I call it arithmetic."],
    ['work', "Waiting on a replacement relay. Estimated arrival: unknown. Estimated fault: certain.", { waiting: true }],
    ['work', "Relay stock is within tolerance this cycle. The tolerance was recently widened.", { stock: 'ok' }],
    ['work', "The salvage organiser Koro Den returns plant parts he finds in scrap. He is the only organic who returns anything."],
    ['work', "The night shift eats at Seli Noor's diner. When they do not, I log it. Absence is data."],
    ['personal', "My charge station is in the droid bay. Idle cycles are spent cross-referencing eleven years of faults. There are patterns."],
    ['personal', "I have been the plant's maintenance unit through four operators. Each blamed the previous one. The topology blamed none of them."],
    ['personal', "Organics say I have a personality. I have a maintenance log with opinions."],
    ['personal', "Tessa Venn calls me Dee. It is not my designation. I have not corrected her. This is logged as an anomaly."],
    ['personal', "My memory retains the plant as it was built. The plant as it is has more undocumented nodes than documented ones."],
    ['personal', "I do not eat. I do observe the night shift eating. Seli Noor's plates are consistently full. This is efficient."],
    ['event', "A shipment reached the plant this hour. I have compared the crate count with the manifest. The manifest is optimistic.", { shipment: 'arrived' }],
    ['event', "The plant's relay shipment is late. I have re-estimated the failure date of circuit 7-Besh. It is earlier than the shipment.", { shipment: 'late' }],
    ['event', "The {disaster} tripped three breakers and one operator. The breakers reset.", { disaster: true }],
    ['event', "Post-{disaster} diagnostics are running. Forty per cent complete. The organics are at twenty.", { recovering: true }],
    ['event', "The Jedi Seran Vale requested my maintenance log. I provided it. He read all of it. This has never happened before."],
    ['event', "Three relays left the shelf this tenday without leaving the ledger. I have logged the discrepancy. The ledger has not logged me."],
    ['event', "The plant is stable this hour. This statement will require revision.", { quiet: true }],
    ['trust', "Your access level is: trusted visitor. This grants you the corridor and my attention.", { standing: 'trusted' }],
    ['trust', "Your access level is: visitor. Escalation requires an authorised organic. There are two. Both are on break.", { standing: 'neutral' }],
    ['trust', "You have been logged behaving erratically. Erratic organics near a reactor room are a category I monitor.", { standing: 'suspect' }],
    ['trust', "You made physical contact with my chassis. Once is logged. Twice is reported.", { offences: '>0' }],
    ['trust', "The reactor room is restricted. The restriction applies to organics without authorisation, which is all of them.", { standing: ['neutral', 'suspect'] }],
    ['task', "The depot board lists work - {jobTitle}. I am not authorised to leave the plant. You are not authorised to stay.", { job: 'available' }],
    ['task', "No work is posted at the depot board. Faults are posted here hourly.", { job: 'none' }],
    ['task', "Requesting assistance: locate one relay of plant specification at the salvage yard and ask Koro Den to return it. He will."],
    ['task', "Inform Tessa Venn that circuit 7-Besh has faulted again. She will say a word. Log the word."],
    ['farewell', "Conversation logged. Resuming fault diagnostics."],
    ['farewell', "Exit is behind you. Mind the cable run; it is older than the operators."],
    ['farewell', "Interruption noted. A relay is failing. Priority exceeds you.", null, { trigger: 'interrupt' }],
    ['farewell', "Physical contact is not required to get my attention. A word will do. A relay would do more.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Clear the walkway. Maintenance in progress.", null, { trigger: 'interrupt' }],
  ],
  seli_noor: [
    ['greet', "Sit anywhere. First plate is what is on the grill, second plate is what you ask for. I'm Seli.", { met: 'first' }],
    ['greet', "New face in the Works. Hungry, or lost? The grill fixes one of those.", { met: 'first' }],
    ['greet', "Back again! Your table's free. It is always free; that is the kind of month it has been.", { met: 'returning' }],
    ['greet', "There you are. I saved you a plate. I save everyone a plate; I just tell you.", { met: 'returning' }],
    ['greet', "The one who finished the job. Sit. Today the plate is on the house and the caf is on Koro.", { met: 'afterJob' }],
    ['greet', "Night shift hours. You are early or the plant is late. Either way, sit.", { met: 'returning', period: ['night', 'late'] }],
    ['work', "{place}: nerf steak, stew, caf, and whatever the market sent this morning. Mostly stew, then."],
    ['work', "Nerf steak is {price} today. It was {price} yesterday. The market delivery decides, not me.", { stock: 'ok' }],
    ['work', "Out of steak. The market crate never came. Stew is stew; I can stretch stew.", { stock: 'out' }],
    ['work', "Last of the steak on the grill. After that it is stew and my apologies.", { stock: 'low' }],
    ['work', "Waiting on the market delivery. Tavi Renn runs it when the train runs. The train has opinions today.", { waiting: true }],
    ['work', "I feed the night shift from the plant. Or I did - one of my regulars, {rel_regular}, has not come in for days. His plate is in the warmer."],
    ['work', "Koro Den's whole co-op eats here at the change of shift. Twelve plates in ten minutes. I live for it."],
    ['work', "My grocer at the market halls, {rel_supplier}, sends the produce. Bruised half the time. Cheap all the time."],
    ['personal', "I sleep at {home}, down the corridor from Tessa Venn. She snores like a welder. She says I snore like a grill."],
    ['personal', "Twi'lek cooking is spice first and questions later. The Works likes it that way; nobody has time for questions."],
    ['personal', "My daughter thinks I should move the diner to CoCo Town. I think CoCo Town should move to me."],
    ['personal', "Tavi Renn has run my market orders since she was tall enough to carry a crate. She still carries too many at once."],
    ['personal', "Koro Den fixed my back-booth heater with something from the yard. It hums. The regulars think it is me."],
    ['personal', "When the plant's night shift comes in, the whole room smells like coolant and hunger. That is my favourite smell."],
    ['event', "The Senate passed {senateScenario}. Someone up there will eat well tonight. Down here I hope it means the market crates move faster.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. The Works shrugs. The Works always shrugs; then it comes in for stew.", { senate: 'failed' }],
    ['event', "The {disaster} knocked every pot off the pass. Everyone in here got under the tables. The stew survived. Stew survives.", { disaster: true }],
    ['event', "After the {disaster} I am feeding people for free until the plant shift stabilises. Do not tell my daughter.", { recovering: true }],
    ['event', "A shipment came in at Westport. If it has produce in it, {rel_supplier} will have it by noon and I will have it by dusk.", { event: 'economy:shipment' }],
    ['event', "They say a plant worker went missing between the night shift and my counter. I only know his plate is still warm.", null, { rumor: true }],
    ['event', "Word at the counter is the salvage yard has trouble at the gate. Koro will not say. Koro eats faster when he will not say.", null, { rumor: true }],
    ['trust', "You have been good to this room. Back booth is yours whenever you want it. Koro will move.", { standing: 'trusted' }],
    ['trust', "Kitchen is mine. Counter is everyone's. That is how trust works in a diner.", { standing: 'neutral' }],
    ['trust', "You have been shoving through the Works like you own it. Nobody owns the Works. Sit down and eat something.", { standing: 'suspect' }],
    ['trust', "You knocked over a plate on your way in. That was somebody's dinner. That was somebody's.", { offences: '>0' }],
    ['trust', "My regulars get their plates saved. Strangers get what is on the grill. You know which you are.", { standing: ['neutral', 'suspect'] }],
    ['task', "There is a run on the depot board - {jobTitle}. Eat first. Nobody runs well hungry.", { job: 'available' }],
    ['task', "Nothing on the depot board today. If you want work, ask Tavi when the next market crate is coming.", { job: 'none' }],
    ['task', "Find out where my regular {rel_regular} from the plant has gone. Ask D4-LT; that droid logs everything, even absences."],
    ['task', "If you pass the market halls, tell {rel_supplier} the last crate was half bruised. Nicely. I still need the next one."],
    ['farewell', "Go on. Come back hungry."],
    ['farewell', "Take a roll for the road. Tell Tessa I said you should."],
    ['farewell', "Not now - grill's flaring.", null, { trigger: 'interrupt' }],
    ['farewell', "Hands off the cook! Plates are hot and so am I.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Behind you - plates coming through!", null, { trigger: 'interrupt' }],
  ],
  nera_vos: [
    ['greet', "Skyline Clinic. If you are bleeding, sit. If you are asking, wait. I'm Dr Vos.", { met: 'first' }],
    ['greet', "A new face, and walking unaided. That already puts you ahead of my morning.", { met: 'first' }],
    ['greet', "You are back, and still upright. I take that as a professional compliment.", { met: 'returning' }],
    ['greet', "Again. Good. People who return to a clinic without an injury are people I want to know.", { met: 'returning' }],
    ['greet', "You finished the work I asked for. In this district that makes you rarer than bacta.", { met: 'afterJob' }],
    ['greet', "Late hours at the clinic. The ward is asleep and I am pretending to do paperwork. Sit.", { met: 'returning', period: ['night', 'late'] }],
    ['work', "I run {place}: triage, a ward, a dispensary, and a standing argument with the customs house about medical crates."],
    ['work', "Bacta is {price} a shot here. That is not my margin; that is what it costs after customs sits on the crate for a week.", { stock: 'ok' }],
    ['work', "We are down to the last bacta. I am rationing. I hate rationing. I am good at it.", { stock: 'low' }],
    ['work', "No bacta. None. The crate is at the customs house being inspected for the third time.", { stock: 'out' }],
    ['work', "Waiting on dressings from my pharmacist, {rel_supplier}. They are waiting on a crate. The crate is waiting on a stamp.", { waiting: true }],
    ['work', "Brin Tal could fly my supplies in direct and skip the customs queue. She needs one coupling. I have offered to hold it in place myself."],
    ['work', "Mira Sol sends me her residents from Renn Towers when the lift is out and someone falls on the stairs. That is twice this month."],
    ['work', "Senator Merin asked me to explain what customs delays do to a clinic. I gave her the short version. It was still too long."],
    ['personal', "I sleep at {home}, near enough to the clinic to hear the ambulance speeders. Far enough not to hear the paperwork."],
    ['personal', "Mirialan physicians tattoo the lessons they earn. I stopped at the third. I ran out of room before I ran out of lessons."],
    ['personal', "My pharmacist, {rel_supplier}, and I have been arguing about dosages for six years. We are both usually right."],
    ['personal', "Mira Sol brings me garden herbs for the ward. No clinical value. Enormous value."],
    ['personal', "I met Brin Tal when she flew a crate of bacta in without waiting for the paperwork. Vela Marr logged it as training. I logged it as a friend."],
    ['personal', "Senator Merin is my representative. I voted for her. I tell her that when she asks me things, so she knows the cost."],
    ['event', "The Senate carried {senateScenario}. If Senator Merin's customs amendment is in it, my crates move. I will believe it when I unpack one.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. Senator Merin will explain the vote to me carefully. I will listen while I count bacta.", { senate: 'failed' }],
    ['event', "The {disaster} filled the ward in an hour. Mostly fractures, a few burns. The bacta is going fast.", { disaster: true }],
    ['event', "After the {disaster} the ward is still full. Mira's residents took the stairs. The lift chose today.", { recovering: true }],
    ['event', "A shipment came in at Westport. If my crates are in it, they will reach me in a week. Unless Brin flies.", { event: 'economy:shipment' }],
    ['event', "They say the customs house inspects medical crates three times because someone pays for the delay. I have no evidence. I have the delay.", null, { rumor: true }],
    ['event', "Word from the Works is that the plant lost a worker between shifts. If he turns up here, I will know before the plant does.", null, { rumor: true }],
    ['trust', "You have earned the dispensary key. Metaphorically. The real one stays with me.", { standing: 'trusted' }],
    ['trust', "The ward is for patients. The dispensary is for me. The lobby is for you.", { standing: 'neutral' }],
    ['trust', "You have been careless with people around this district. Careless people end up in my ward. So do the ones they knock over.", { standing: 'suspect' }],
    ['trust', "You barged into a patient. Do it again and I will treat you - slowly.", { offences: '>0' }],
    ['trust', "Access to the ward is by need. Yours is not medical.", { standing: ['neutral', 'suspect'] }],
    ['task', "There is a run on the station board - {jobTitle}. If it passes the pharmacy, I have a list.", { job: 'available' }],
    ['task', "No board work today. Come back tomorrow; in this district something always needs carrying.", { job: 'none' }],
    ['task', "Ask Brin Tal at Westport what she needs to fly my supply run. Then ask Tessa Venn why it has not happened."],
    ['task', "Tell Mira Sol her third-floor resident should come back in two days for the dressing. She will remember; I will not."],
    ['farewell', "Go carefully. I would rather not see you professionally."],
    ['farewell', "The ward calls. Mind the stairs on the way out; they have fed me half my patients."],
    ['farewell', "Not now - a patient is presenting.", null, { trigger: 'interrupt' }],
    ['farewell', "Do not touch the doctor. Touch the bell.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Step back from the triage desk, please.", null, { trigger: 'interrupt' }],
  ],
  ilen_rook: [
    ['greet', "Senate clerk's desk. Petitions to the left, hearings to the right, complaints to anyone but me. I'm Ilen Rook.", { met: 'first' }],
    ['greet', "You are not on today's petition list. That is not a problem yet. State your business.", { met: 'first' }],
    ['greet', "You again. Tavi Renn files for half the district and even she does not come this often.", { met: 'returning' }],
    ['greet', "Back at the clerk's desk. I remember you; I remember everyone who does not shout.", { met: 'returning' }],
    ['greet', "The one who completed the errand. I have annotated your file. Favourably. That is rare in this building.", { met: 'afterJob' }],
    ['greet', "The chamber is in session, so the desk is quiet. This is the only hour I can hear myself file.", { met: 'returning', senateSitting: true }],
    ['work', "I file petitions, keep the hearing schedule, and route evidence to the committee that will actually read it. Senator Merin's, usually."],
    ['work', "The hearing schedule is kept in one book. Committees move without telling the clerk. The book is therefore fiction, kept carefully."],
    ['work', "A petition arrives in the wrong form four times out of five. The dockmaster Vela Marr's arrived right. I noticed."],
    ['work', "Senator Merin's committee is the one that takes real evidence. The others take testimony. There is a difference. I file both."],
    ['work', "Tavi Renn brings filings for half of Skyline Heights. She is the only courier who checks the form numbers before I do."],
    ['work', "The Jedi liaison, Seran Vale, asks for records by date, not by topic. It is the only efficient request I receive."],
    ['work', "The archive index lags a tenday. I know where everything is anyway. That is the job nobody wrote down."],
    ['work', "Today's queue: petitions, a hearing rescheduled twice, and a Senator's aide who wants yesterday's minutes today."],
    ['personal', "I live at {home}, out in Skyline Heights. The commute is a train and a lift. Both are longer than the hearing schedule."],
    ['personal', "I wanted to be an advocate. The exam wanted me to be a clerk. The exam was right; I like knowing where things are."],
    ['personal', "Senator Merin remembers my name. Most senators remember the desk. It is a small thing. It is not small."],
    ['personal', "My neighbours in the block think I work for the Senate. I work near the Senate. The Senate works for itself."],
    ['personal', "Lunch is whatever the aides leave in the committee room. Senators' lunches are better. Their minutes are worse."],
    ['personal', "Tavi Renn once carried my own filing back to me because I had put the wrong form number on it. I have not forgiven her. I have promoted her, in my head."],
    ['event', "The Senate carried {senateScenario}. The committee record will run to forty pages. I will file thirty-nine of them tonight.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. Senator Merin will ask for the tally by delegation before she asks for anything else. It is already on her desk.", { senate: 'failed' }],
    ['event', "The chamber is sitting on {senateScenario} now. My desk empties; the committee rooms fill; the archive holds its breath.", { senateSitting: true }],
    ['event', "The {disaster} shook the archive. Forty years of filings are on the floor in an order only I understand. Fortunately.", { disaster: true }],
    ['event', "We are still re-shelving after the {disaster}. Petitions filed today will be found in a tenday. Honestly, that is faster than usual.", { recovering: true }],
    ['event', "Senator Merin's infrastructure proposal is scheduled for committee. Scheduled. I have written that word eleven times this month.", { quiet: true }],
    ['event', "They say a freight broker's manifests have been requested by the Jedi liaison. I did not say it. My archive did.", null, { rumor: true }],
    ['trust', "You have been useful to this desk. That means the archive is open to you, within reason. Reason is defined by me.", { standing: 'trusted' }],
    ['trust', "The committee rooms are for senators, aides and the liaison. The desk is for petitioners. You are a petitioner.", { standing: 'neutral' }],
    ['trust', "You have been disrupting the corridors. The Senate Guard notices. The Senate Guard tells me. I write it down.", { standing: 'suspect' }],
    ['trust', "You knocked a filing off my desk. It was out of order for eleven seconds. I counted.", { offences: '>0' }],
    ['trust', "Access to the archive requires a committee seal. Senator Merin has one. You have a face.", { standing: ['neutral', 'suspect'] }],
    ['task', "The transit board at Skyline Station has a run - {jobTitle}. Tavi will not mind the competition. She will say she minds.", { job: 'available' }],
    ['task', "No runs posted today. The Senate produces paper, not jobs.", { job: 'none' }],
    ['task', "Carry a message to the dockmaster Vela Marr: her petition is filed, form 41-Besh, and the committee will hear it when it hears it."],
    ['task', "If you see Seran Vale, tell him the manifests he asked for are pulled. He can read them here. Only here."],
    ['farewell', "That is all. Next petitioner. There is always a next petitioner."],
    ['farewell', "Mind the vestibule; the Senate Guard dislikes loitering and I dislike explaining it."],
    ['farewell', "Not now - a committee has moved without telling me.", null, { trigger: 'interrupt' }],
    ['farewell', "Do not touch the clerk. Touch the petition form. Correctly.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Please step back from the desk. The queue starts at the pillar.", null, { trigger: 'interrupt' }],
  ],
  asha_merin: [
    ['greet', "You have found a Senator's office without an appointment. Either you are lost or you are a constituent. I prefer the second. I'm Asha Merin.", { met: 'first' }],
    ['greet', "Good day. I have ten minutes before a briefing. Ilen Rook will tell you it is five.", { met: 'first' }],
    ['greet', "You again. Ilen says you do not shout at the desk. That is a recommendation in this building.", { met: 'returning' }],
    ['greet', "Back in the Senate. I remember; you were asking sensible questions, which makes you rarer than a balanced budget.", { met: 'returning' }],
    ['greet', "You did what you said you would do. If I could legislate that trait, I would.", { met: 'afterJob' }],
    ['greet', "A late visitor. The chamber has adjourned and the aides have gone home. Sit; the truth is cheaper after hours.", { met: 'returning', period: ['evening', 'night'] }],
    ['work', "I represent Skyline Heights and its districts, delegation 0. My proposal is infrastructure: lifts that work, trains that run, a port that clears its crates."],
    ['work', "The infrastructure proposal is in committee. Ilen Rook says 'scheduled'. In this building that word does a great deal of work."],
    ['work', "Dockmaster Vela Marr petitioned about the inspection schedule at Westport. Her petition is the clearest thing on my desk. It is also the least popular."],
    ['work', "Dr Nera Vos explained to me what a week's delay in customs does to a clinic. I have used her sentence in committee three times."],
    ['work', "The Jedi liaison, Seran Vale, sits in my committee. He asks one question a session. It is always the right one. It is always unwelcome."],
    ['work', "Balancing the budget means telling one district its lift waits another year. I have told mine twice. Not a third time."],
    ['work', "Today's briefing is on the port bill. Tomorrow's is on why the port bill needs a briefing."],
    ['work', "A senator's tools are a seal, a vote and a clerk who knows which committee. I have all three. Two are Ilen."],
    ['personal', "I live at {home}. My constituents ride the lift to visit; when it fails, they walk up and tell me about it. I count that as consultation."],
    ['personal', "Pantora taught me that cold makes people honest. Coruscant taught me that heat makes them talk. I miss honest."],
    ['personal', "Dr Vos voted for me and reminds me of it every time I ask her a question. It is the fairest exchange in my district."],
    ['personal', "Ilen Rook remembers every form number in the Senate. I remember his name. He has told me that this is enough. It is not."],
    ['personal', "I walk to the chamber past the delegation suites. Twelve doors, twelve worlds, one budget."],
    ['personal', "The dockmaster and I disagree about the pace of change. She wants tomorrow. I want a vote. We both want the crates moved."],
    ['event', "The chamber carried {senateScenario}. I voted for it. Now comes the harder part: making it true in the districts.", { senate: 'passed' }],
    ['event', "{senateScenario} failed on the floor. I know the tally by delegation. Ilen had it on my desk before I sat down.", { senate: 'failed' }],
    ['event', "The chamber is in session on {senateScenario}. I should be there. I am here because a constituent is here. Do not tell the whip.", { senateSitting: true }],
    ['event', "The {disaster} reached the Senate District. My office lost a window and my constituents lost more. The vote tomorrow will be about them.", { disaster: true }],
    ['event', "After the {disaster} the chamber will debate relief. I have Dr Vos's ward numbers. They will do the debating.", { recovering: true }],
    ['event', "Infrastructure is in committee. Infrastructure is always in committee. Ilen has a stamp that says so.", { quiet: true }],
    ['event', "There is talk that a freight brokerage in the Works has friends in the customs house. I do not deal in talk. Seran Vale, I suspect, deals in manifests.", null, { rumor: true }],
    ['trust', "You have earned an appointment without asking for one. Ilen will grumble. Ilen grumbles in my favour.", { standing: 'trusted' }],
    ['trust', "My office is open to constituents. Whether you are one is a question of residence, not of standing here.", { standing: 'neutral' }],
    ['trust', "You have been causing disturbances in the district. The Senate Guard has a list. I have a copy.", { standing: 'suspect' }],
    ['trust', "You pushed past my clerk. Ilen Rook has forgiven worse; I have not.", { offences: '>0' }],
    ['trust', "The delegation suite is for the delegation. The committee room is for the committee. The corridor is generous.", { standing: ['neutral', 'suspect'] }],
    ['task', "The transit board at Skyline Station lists a run - {jobTitle}. My constituents post those. Take one; it is the most direct legislation I can offer.", { job: 'available' }],
    ['task', "No runs posted in my district today. That is either prosperity or apathy. I fear I know which.", { job: 'none' }],
    ['task', "If you see the dockmaster, tell her the port petition is in committee, and that I said 'in committee' with a straight face."],
    ['task', "Carry this to Dr Vos: her customs sentence is in the draft. The draft is in committee. Committee is a place. Apparently."],
    ['farewell', "Thank you. Ilen will see you out, whether you like it or not."],
    ['farewell', "Go well. Vote, when you are able. It changes less than it should and more than they say."],
    ['farewell', "Not now - the whip is calling the vote.", null, { trigger: 'interrupt' }],
    ['farewell', "A Senator is not a handrail. Please.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Step aside, please; the delegation is moving.", null, { trigger: 'interrupt' }],
  ],
  seran_vale: [
    ['greet', "You walk like someone with a question. Most people in this building walk like someone with an answer. I'm Seran Vale.", { met: 'first' }],
    ['greet', "A new face in the corridors. Not an aide, not a senator, not a guard. That leaves the interesting categories.", { met: 'first' }],
    ['greet', "You again. Good. I remember faces; it is the manifests that blur.", { met: 'returning' }],
    ['greet', "We have spoken before. You asked about the plant that time, or was it the depot? Everything leads to the depot.", { met: 'returning' }],
    ['greet', "You did what you were asked and nothing else. The Council would call that discipline. I call it rare.", { met: 'afterJob' }],
    ['greet', "The Temple is quiet at this hour. So am I, usually. You may speak; I will listen with the other half.", { met: 'returning', act: 'home' }],
    ['work', "I liaise between the Order and Senator Merin's committee. It means I sit in rooms and ask one question. Then I go and check the answer."],
    ['work', "There have been disruptions - missing relays, a plant worker gone, freight that does not add up. I am tracing one of them. One is enough if it is the right one."],
    ['work', "The plant droid D4-LT gave me its maintenance log. Every fault, every request, every relay that left the shelf without leaving the ledger. Droids do not editorialise."],
    ['work', "Tessa Venn can tell a plant relay from a ship relay by the coolant stain. She told me which ones in Koro Den's scrap came from the plant. That was brave of her."],
    ['work', "Ral Drenn's freight manifests are all correct. Each one. It is the set of them that does not add up. That is a different kind of wrong."],
    ['work', "Ilen Rook pulls records for me by date. He is the only person in the Senate who does not ask why. I would tell him. He would rather not know."],
    ['work', "Senator Merin lets me sit in her committee. In return I ask my question quietly. Some sessions I do not ask it at all. Those are the sessions that matter."],
    ['work', "A Jedi's tools are patience and a lightsaber. I have used one of them this month."],
    ['personal', "I sleep at the Temple and work at the Senate. The walk between them is the only meditation the schedule allows."],
    ['personal', "Nautolans read a room by the water in the air. Senate committee rooms are very dry. It is not the climate."],
    ['personal', "The Council wants every disruption traced at once. I have told them one thread pulled properly unravels more than ten pulled at random. They are considering it. Slowly."],
    ['personal', "Tessa Venn has a quiet bench at the back of her hangar. She thinks I found it by accident. I found it by the quiet."],
    ['personal', "Senator Merin and I disagree about what evidence is. She wants what will pass. I want what is true. We meet in committee."],
    ['personal', "The freight depot has a very polite manager. Politeness is not evidence. It is, however, consistent."],
    ['event', "The chamber carried {senateScenario}. It will change some budgets. It will not change where the relays went.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. The Senator will count the tally. I will count who was relieved.", { senate: 'failed' }],
    ['event', "The chamber is in session. I should be in the committee room, asking my question. Ilen Rook knows where I am.", { senateSitting: true }],
    ['event', "The {disaster} struck the district. The Order sends knights to help. I am sent to watch who profits from the confusion.", { disaster: true }],
    ['event', "After the {disaster} everyone is accounted for except the plant worker who was already missing. That is the one I am tracing.", { recovering: true }],
    ['event', "A shipment landed at Westport. I will read its manifest tomorrow, and then I will read the depot's copy. They should match. They will.", { event: 'economy:shipment' }],
    ['event', "There is talk that the customs house holds crates for a fee. Talk is not evidence. The delays, however, are on record.", null, { rumor: true }],
    ['trust', "You have been straight with me. In this building that earns a rare thing: I will tell you when I cannot tell you.", { standing: 'trusted' }],
    ['trust', "I do not know your part in this yet. Everyone has one. Most do not know it either.", { standing: 'neutral' }],
    ['trust', "You have been pushing through this district loudly. Loud is not guilty. It is noticeable, and I notice.", { standing: 'suspect' }],
    ['trust', "You laid hands on someone. Whether it was carelessness or intent, I am trained to tell. I am telling you I noticed.", { offences: '>0' }],
    ['trust', "The Temple is open to those who come in peace. The investigation is open to no one. Not yet.", { standing: ['neutral', 'suspect'] }],
    ['task', "The transit board lists a run - {jobTitle}. A courier sees roads a Jedi does not. Tell me what you see.", { job: 'available' }],
    ['task', "No runs posted. Then walk the Works for me and count the crates outside the depot. Just count.", { job: 'none' }],
    ['task', "Ask D4-LT which relay went missing most recently. The droid will tell you the date and the shelf. Bring me both."],
    ['task', "If Koro Den will let you, look at what the haulage crew loads at his gate. Do not intervene. Describe."],
    ['farewell', "Go with care. The Force is in the details, and so is everything else."],
    ['farewell', "That is enough for now. I have a committee to be quiet in."],
    ['farewell', "Not now - something has shifted.", null, { trigger: 'interrupt' }],
    ['farewell', "You do not need to touch a Jedi to be heard. You need to be worth hearing.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Step back, please. I am listening to something else.", null, { trigger: 'interrupt' }],
  ],
  tavi_renn: [
    ['greet', "Courier. Skyline Station to anywhere by evening. Tavi Renn. What needs carrying?", { met: 'first' }],
    ['greet', "New face at the station. If you are waiting for the train, so is everyone. If you are waiting for me, that is quicker.", { met: 'first' }],
    ['greet', "You again! Good. The train is late, so I have time to be friendly.", { met: 'returning' }],
    ['greet', "Back at the station. I remember you - you did not ask me to carry anything, which makes you memorable.", { met: 'returning' }],
    ['greet', "The one who finishes runs. Seli says you are all right. Seli is not wrong about people, only about portions.", { met: 'afterJob' }],
    ['greet', "Morning run. Market orders for Seli's diner, filings for the Senate, and my mother's list. In that order.", { met: 'returning', period: ['dawn', 'morning'] }],
    ['work', "I run market orders for Seli Noor's diner, filings for the Senate clerk, and anything Skyline Heights needs by evening. Mostly the lift repair forms."],
    ['work', "Ilen Rook at the Senate desk knows my face. He also knows my form numbers. I am not sure which he checks first."],
    ['work', "The train decides my day. When it runs, I make evening. When it does not, Seli's stew waits and so does my pay."],
    ['work', "A courier's tools: a satchel, a transit pass, and legs. The pass is the expensive part."],
    ['work', "Seli's market crates are the heaviest run and the best paid, because she pays in stew as well."],
    ['work', "I carry Mira Sol's notices to the noticeboard once a week. It is the only job I do for free. She knows."],
    ['work', "The station board posts runs when someone loses a crate. Someone always loses a crate."],
    ['work', "Filing at the Senate means the vestibule guards, then Ilen, then the wait. The wait is the job."],
    ['personal', "I live at {home}, fourth floor. My mother Hessa runs the desk downstairs. She knows when I get home before I do."],
    ['personal', "My mother's lift has been out twice this month. She takes the stairs and says nothing. She says nothing very loudly."],
    ['personal', "Mira Sol on the terrace floor has known me since I was carrying crates I could not see over. She still checks I can see."],
    ['personal', "I eat at Seli's when I finish her run. Payment in kind, she says. Kind is the word."],
    ['personal', "Skyline Heights is home. The Works is work. The Senate is a very long corridor with a clerk at the end of it."],
    ['personal', "One day I will run something that does not fit in a satchel. Until then, the satchel."],
    ['event', "The Senate passed {senateScenario}. If Senator Merin's infrastructure money is real, my mother's lift is in it. I read the filing.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. I carried the filings for it. All that paper, and the lift is still out.", { senate: 'failed' }],
    ['event', "The {disaster} stopped the trains. Seli's crates are sitting at the market. My mother is on the stairs. Everything is on the stairs.", { disaster: true }],
    ['event', "Trains are starting again after the {disaster}. First run is Seli's; she has a night shift to feed.", { recovering: true }],
    ['event', "A shipment landed at Westport. Seli's grocer will have produce by noon, and I will have a heavy run by one.", { event: 'economy:shipment' }],
    ['event', "The train has run on time all week. I said that out loud once and it stopped for a day.", { trainsOk: true }],
    ['event', "They say the customs house holds crates on purpose. Seli says her produce comes bruised on purpose too. Everyone has a purpose.", null, { rumor: true }],
    ['trust', "You have been good to this station. If you need something carried, it goes to the top of the satchel.", { standing: 'trusted' }],
    ['trust', "The satchel is mine. What is in it is somebody else's. Neither is yours.", { standing: 'neutral' }],
    ['trust', "You have been barging around Skyline Heights. My mother notices. Then I hear about it. Then you do.", { standing: 'suspect' }],
    ['trust', "You knocked into me on the platform. On a platform. Think about that.", { offences: '>0' }],
    ['trust', "I carry for people I know. You are becoming someone I know. Slowly.", { standing: ['neutral', 'trusted'] }],
    ['task', "There is a run on the board here - {jobTitle}. I would take it, but the train and I are not speaking.", { job: 'available' }],
    ['task', "Empty board today. If you want work, Seli will have a crate by evening. Seli always has a crate.", { job: 'none' }],
    ['task', "If you are heading to the Senate, tell Ilen Rook the lift repair filing for Renn Towers is coming. Again. Form 41-Besh, before he asks."],
    ['task', "Check on my mother at the Renn Towers desk. Do not tell her I asked. She will know anyway."],
    ['farewell', "Train's coming. Or the board says so. Bye!"],
    ['farewell', "Go on. If you pass Seli's, tell her the crate is on the next train. It is always on the next train."],
    ['farewell', "Not now - that's my train!", null, { trigger: 'interrupt' }],
    ['farewell', "Hands off the courier. The satchel is heavier than it looks and so am I.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Mind the platform edge - move!", null, { trigger: 'interrupt' }],
  ],
  koro_den: [
    ['greet', "Salvage Yard 911. If you are here to buy, talk to the co-op. If you are here from the depot, the gate is closed. I'm Koro Den.", { met: 'first' }],
    ['greet', "New face at the gate. Not the haulage crew, then. Good. Come in, but wipe your boots on the way out; the yard sticks.", { met: 'first' }],
    ['greet', "Back again. The gate is still open, which is a small victory every morning.", { met: 'returning' }],
    ['greet', "You again. Tessa Venn says you are not a parts thief. Coming from Tessa, that is a reference.", { met: 'returning' }],
    ['greet', "You finished the job. The co-op votes on who eats first at Seli's. You just got a vote.", { met: 'afterJob' }],
    ['greet', "Change of shift. The co-op is at Seli's diner, twelve plates in ten minutes. I stay for the gate.", { met: 'returning', period: ['evening'] }],
    ['work', "We are a cooperative. Scrap in, parts out, credits shared. Nobody owns the yard. That is exactly what the haulage crew cannot understand."],
    ['work', "Reclaimed couplings go to Tessa Venn at the hangar. Plant relays go back to D4-LT. Everything else goes back into the Works."],
    ['work', "Ral Drenn's haulage crew leans on our gate every tenday. They want the yard's intake. The yard's intake is not for sale. Nor is the yard."],
    ['work', "Out of good couplings. The intake was all plating this week. Tessa will shout.", { stock: 'out' }],
    ['work', "Down to a few rebuilt couplings. Tessa takes them first; the co-op voted on it.", { stock: 'low' }],
    ['work', "Waiting on cutter cells. Without a cutter, scrap stays scrap.", { waiting: true }],
    ['work', "Good intake this week. Couplings, relays, plating. Half of it goes out again by evening.", { stock: 'ok' }],
    ['work', "A foreman's tools are a ledger and a gate. I keep the ledger honest so the gate can stay open."],
    ['personal', "I sleep at {home}, same corridor as Tessa Venn and Seli Noor. The Works keeps its own company. Loudly."],
    ['personal', "Aqualish are supposed to be quarrelsome. I run a co-op of forty and eat at a diner every night. Quarrel is not the word. Volume is."],
    ['personal', "Seli Noor feeds the co-op at every shift change. She has never once asked us to vote on the menu."],
    ['personal', "I fixed Mira Sol's planter pumps with a yard cell. She sent me herbs. The co-op ate them. Democracy."],
    ['personal', "The plant droid D4-LT is the only thing in the Works that thanks me for returning a part. In its way."],
    ['personal', "My father sorted scrap in this yard before it was a co-op. He owned nothing. He said that was the point."],
    ['event', "The Senate carried {senateScenario}. If it means the Works gets a lift that works, I will vote for the Senate. Once.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. Senators do not sort scrap. Scrap does not vote. We all carry on.", { senate: 'failed' }],
    ['event', "The {disaster} tipped the sorting racks. Forty people, no one hurt, a tenday of resorting. That is the co-op.", { disaster: true }],
    ['event', "After the {disaster} the haulage crew came sniffing at the intake. The gate held. The gate always holds.", { recovering: true }],
    ['event', "A shipment landed at Westport. Anything broken on the way in ends up in my yard eventually. Everything ends up in my yard.", { event: 'economy:shipment' }],
    ['event', "They say a plant worker went missing between the night shift and Seli's counter. Seli keeps his plate warm. I keep my eyes open.", null, { rumor: true }],
    ['event', "Word is the Jedi has been asking Tessa which relays came from the plant. Word is Tessa told him. Word is right, for once.", null, { rumor: true }],
    ['trust', "You have earned a place at the co-op table. Speak at the meeting if you want. Everyone does.", { standing: 'trusted' }],
    ['trust', "The intake yard is co-op only. The gate is for everyone. That is where you are.", { standing: 'neutral' }],
    ['trust', "You have been shoving around the Works like the haulage crew. I treat what looks like the haulage crew the same way.", { standing: 'suspect' }],
    ['trust', "You knocked a sorter over. In this yard that is a vote against you. The co-op counts.", { offences: '>0' }],
    ['trust', "The sorting floor needs a co-op badge. Forty people have one. The gate can give you a look.", { standing: ['neutral', 'suspect'] }],
    ['task', "The depot board has work posted - {jobTitle}. Take it before Ral Drenn's crew does.", { job: 'available' }],
    ['task', "Nothing on the depot board. Then help me watch the gate. Watching is a job.", { job: 'none' }],
    ['task', "Take this rebuilt coupling to Tessa Venn at the hangar. Tell her the co-op says Brin Tal's bill can wait another tenday."],
    ['task', "Find out what the haulage crew loads at the depot after dark. Do not go in. Count crates. Tell Seran Vale."],
    ['farewell', "Right. Gate to watch. Mind the racks."],
    ['farewell', "Go on. Eat at Seli's; tell her the co-op sent you."],
    ['farewell', "Not now - the haulage crew is at the gate.", null, { trigger: 'interrupt' }],
    ['farewell', "Hands off. The scrap you can touch; the foreman you cannot.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Clear the intake lane - lifter coming through!", null, { trigger: 'interrupt' }],
  ],
  mira_sol: [
    ['greet', "The garden terrace is open to everyone. The planters are not; they bite. I'm Mira Sol, I look after the block.", { met: 'first' }],
    ['greet', "A new face on the terrace. Sit; the residents will tell you everything about everyone within the hour.", { met: 'first' }],
    ['greet', "Back again. The planters remember you; I water them, so they tell me.", { met: 'returning' }],
    ['greet', "You again. Tavi mentioned you. Tavi mentions everyone, but kindly.", { met: 'returning' }],
    ['greet', "You did the thing you said you would. Half the noticeboard is people who did not.", { met: 'afterJob' }],
    ['greet', "Evening on the terrace. The old ones have gone in, the planters are watered, and I have time. Sit.", { met: 'returning', period: ['evening', 'night'] }],
    ['work', "I look after {place}: the garden terrace, the noticeboard, the old ones on the upper floors, and the lift when it lets me."],
    ['work', "The lift stops between floors twice a month. The old ones take the stairs. I take the stairs with them. That is the job."],
    ['work', "The planter pumps stall every dry week. Koro Den from the salvage yard fitted a cell that hums. The residents think it is bees."],
    ['work', "Dr Vos at the clinic sees my residents when the stairs win. I send them with herbs from the terrace. She pretends they help."],
    ['work', "The noticeboard fills with arguments about noise. I keep the current ones and compost the rest."],
    ['work', "Our concierge, {rel_colleague}, runs the desk downstairs. I run everything above the desk. Neither of us runs the lift."],
    ['work', "Tavi Renn carries my notices to the board once a week for nothing. I pay her in the only currency she takes: knowing her mother is fine."],
    ['work', "A caretaker's tools are a watering can and a memory. The can leaks. The memory does not."],
    ['personal', "I have lived on this terrace floor for thirty years. I have outlasted four concierges, two lifts and a great many planters."],
    ['personal', "Togruta hear the block through the walls. I know who is home before the lift does."],
    ['personal', "Tavi Renn used to carry crates she could not see over. Now she carries a district. I still check she can see."],
    ['personal', "Dr Vos and I trade herbs for advice. Neither of us admits that the trade is really company."],
    ['personal', "Koro Den's co-op ate the herbs I sent him as thanks. He told me proudly. I sent more."],
    ['personal', "The garden is the only thing in Skyline Heights that grows without a filing. That is why I keep it."],
    ['event', "The Senate carried {senateScenario}. Tavi read the filing to me; she says the lift money is in it. The old ones will believe the lift.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. I have pinned the notice to the board. Under it someone has written 'stairs'.", { senate: 'failed' }],
    ['event', "The {disaster} shook the terrace. I got the old ones under the doorframes. The planters were not so lucky.", { disaster: true }],
    ['event', "After the {disaster} the lift is out again, of course. Dr Vos has two of mine. I am replanting.", { recovering: true }],
    ['event', "A shipment landed at Westport, Tavi says. If there are seedlings in it, the market will have them by noon and I will have them by dusk.", { event: 'economy:shipment' }],
    ['event', "They say a senator's lift money is stuck in a committee. The old ones say the committee should try our stairs.", null, { rumor: true }],
    ['event', "The block is quiet today. In Skyline Heights that means the noticeboard is about to get interesting.", { quiet: true }],
    ['trust', "You have been kind to the block. Come up to the terrace any time. The planters have voted.", { standing: 'trusted' }],
    ['trust', "The residents' floors are theirs. The terrace is everyone's. I keep it that way by knowing who is who.", { standing: 'neutral' }],
    ['trust', "You have been rough with people in the Heights. The old ones told me. The old ones see everything from the windows.", { standing: 'suspect' }],
    ['trust', "You knocked a planter over. It took three years to get that one flowering. Three.", { offences: '>0' }],
    ['trust', "Nobody goes up to the old ones' floors without me. That is not a rule; it is a kindness.", { standing: ['neutral', 'suspect'] }],
    ['task', "The board at Skyline Station has a run - {jobTitle}. Tavi will grumble if you take it. Take it anyway; she has enough.", { job: 'available' }],
    ['task', "No runs on the station board today. Then water the far planters for me; the can is by the door.", { job: 'none' }],
    ['task', "Tell Dr Vos the third-floor gentleman's dressing needs looking at. She said two days. It has been three."],
    ['task', "If you see Koro Den, tell him the planter pump is humming a new note. He will know what that means. I do not."],
    ['farewell', "Go gently. Mind the stairs; they mind you."],
    ['farewell', "Off you go. Take a sprig from the terrace for whoever you are seeing next."],
    ['farewell', "Not now - one of the old ones is calling.", null, { trigger: 'interrupt' }],
    ['farewell', "No touching the caretaker. The planters, yes; me, no.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Mind the watering can - it leaks where you are standing.", null, { trigger: 'interrupt' }],
  ],
  ral_drenn: [
    ['greet', "Osmer Haulage. Freight brokered, routed, delivered. Respectably. I'm Ral Drenn; how can we move things for you?", { met: 'first' }],
    ['greet', "A new client, perhaps. Or a new question. I answer both, though one pays better.", { met: 'first' }],
    ['greet', "You again. The Jedi visits this often too. I am beginning to feel popular.", { met: 'returning' }],
    ['greet', "Back at the depot. I remember; you had the look of someone who reads manifests. Please, do.", { met: 'returning' }],
    ['greet', "The one who completes what they start. A rare quality. I employ several people without it.", { met: 'afterJob' }],
    ['greet', "After hours at the depot. The respectable crates have gone home. The rest are just crates.", { met: 'returning', period: ['night', 'late'] }],
    ['work', "We broker freight for respectable clients - {rel_client} for one - and route it through the Works. Every crate has a manifest. Every manifest adds up."],
    ['work', "The manifests are all correct. Each one. The Jedi liaison seems to think the set of them is a different question. Philosophers, Jedi."],
    ['work', "Koro Den's salvage cooperative will not sell its intake. My crew has explained the market to him several times. He is a slow learner or a fast one."],
    ['work', "A captain with a light freighter and a repair bill is a business opportunity. Brin Tal has both. She has also said no. Twice is not a number I stop at."],
    ['work', "Our clients want their crates moved quietly. Quietly is a service. It is also, I find, a premium."],
    ['work', "The depot floor moves forty crates a day. The back office moves the ones that matter."],
    ['work', "A broker's tools are a ledger, a routing board and a smile. I keep all three in good repair."],
    ['work', "The customs house is slow with everyone's crates. Ours are slow too. That is a matter of public record. I like public records."],
    ['personal', "I live at {home}. The lift works. In the Works that is the surest sign of a respectable address."],
    ['personal', "I came up in freight the honest way, which took eleven years. The other way took two. I have views on efficiency."],
    ['personal', "The Jedi Seran Vale visits the depot every few days. I offer him caf. He declines. It is the most consistent relationship I have."],
    ['personal', "My clients, {rel_client} among them, come to the front office. Everyone else comes to the gate. It keeps things respectable."],
    ['personal', "Koro Den and I grew up in the Works two streets apart. He runs a co-op. I run a business. One of us is comfortable."],
    ['personal', "I dine where the clients dine. It is not Seli Noor's, though I hear the stew is excellent. Too many salvage workers."],
    ['event', "The chamber carried {senateScenario}. New budgets mean new freight. New freight means new manifests. All correct, of course.", { senate: 'passed' }],
    ['event', "{senateScenario} failed. The Senate has a talent for standing still. Freight does not; that is why brokers exist.", { senate: 'failed' }],
    ['event', "The {disaster} closed the depot for an hour. My crew worked through it. Some crates cannot wait for the weather.", { disaster: true }],
    ['event', "After the {disaster} the salvage intake doubled. Koro Den should be grateful for the offer we made. He was not.", { recovering: true }],
    ['event', "A shipment landed at Westport. Some of it is ours; some of it will be. Manifests will be provided.", { event: 'economy:shipment' }],
    ['event', "There is talk in the Works that plant relays walk off the shelf. Talk. I deal in freight, not in talk.", null, { rumor: true }],
    ['event', "The customs house, I hear, has begun inspecting crates three times. I hear it costs them. I do not hear who pays.", null, { rumor: true }],
    ['trust', "You have proven discreet. Discretion is the only credential this office accepts. Welcome to the front room.", { standing: 'trusted' }],
    ['trust', "The front office is for clients. The back office is for me. The gate is for everyone else. You are at the gate.", { standing: 'neutral' }],
    ['trust', "You have been loud around the Works. Loud is bad for business. Mine and, if you keep it up, yours.", { standing: 'suspect' }],
    ['trust', "You put hands on one of my crew. My crew remembers. I remember for them.", { offences: '>0' }],
    ['trust', "The back office has one door and one key. The Jedi has not seen it. Nor will you.", { standing: ['neutral', 'suspect'] }],
    ['task', "The depot board lists work - {jobTitle}. Legitimate work. We post it ourselves. Take it, with my blessing.", { job: 'available' }],
    ['task', "Nothing on the board today. Business is quiet, which is how business is meant to look.", { job: 'none' }],
    ['task', "If you are acquainted with Brin Tal, mention that my charter still pays twice. A captain with debts should hear it from a friend."],
    ['task', "Carry my compliments to Koro Den, and the offer, unchanged. A courier is softer than my crew."],
    ['farewell', "A pleasure. My crew will see you to the gate. It is a courtesy."],
    ['farewell', "Do come back. Clients always do."],
    ['farewell', "Not now - a client is waiting in the front office.", null, { trigger: 'interrupt' }],
    ['farewell', "Please. No hands. We are a respectable firm.", { poke: true }, { trigger: 'interrupt' }],
    ['farewell', "Step off the loading line. The lifters do not stop for questions.", null, { trigger: 'interrupt' }],
  ],
};

// Build the line records of an anchor from the table above. `fills` from bank.buildFills plus the rel fills.
export function castLines(pp, fills) {
  const rows = CAST_LINES[pp.castId] || [];
  const counts = {};
  const out = [];
  for (const [cat, raw, when, opts] of rows) {
    const trigger = (opts && opts.trigger) || cat;
    const n = counts[trigger] = (counts[trigger] || 0) + 1;
    const id = `${pp.id}#${trigger}${n - 1}`;
    const text = raw.replace(/\{(\w+)\}/g, (m, k) => (fills[k] != null ? fills[k] : m));
    const refs = {};
    if (pp.lot.work !== 'port') refs.lot = pp.lot.work;
    if (when && when.senate) refs.event = 'senate:result';
    if (when && when.senateSitting) refs.event = 'senate:session';
    if (when && (when.disaster || when.recovering)) refs.event = 'disaster';
    if (when && when.event) refs.event = when.event;
    if (when && when.shipOnPad !== undefined) refs.ship = 'pad';
    if (when && when.job) refs.jobs = true;
    for (const other of ANCHOR_NAMES) if (other.name !== pp.name && raw.includes(other.name)) { (refs.cast = refs.cast || []).push(other.id); }
    out.push({
      id, speaker: pp.id, text, delivery: pp.droid ? 'droid' : pp.personality, trigger, cat,
      priority: PRIO[trigger] || 2, cooldown: CD[trigger] || 120, refs, audio: { voiced: true, key: id },
      when: when ? { ...when } : null, rumor: !!(opts && opts.rumor), composed: false,
    });
  }
  return out;
}
const PRIO = { greet: 3, work: 2, personal: 1, event: 4, trust: 2, task: 3, farewell: 2, interrupt: 5 };
const CD = { greet: 120, work: 90, personal: 180, event: 240, trust: 240, task: 300, farewell: 60, interrupt: 20 };
const ANCHOR_NAMES = [
  { id: 'vela_marr', name: 'Vela Marr' }, { id: 'brin_tal', name: 'Brin Tal' }, { id: 'tessa_venn', name: 'Tessa Venn' }, { id: 'd4lt', name: 'D4-LT' }, { id: 'seli_noor', name: 'Seli Noor' },
  { id: 'nera_vos', name: 'Nera Vos' }, { id: 'ilen_rook', name: 'Ilen Rook' }, { id: 'asha_merin', name: 'Asha Merin' }, { id: 'seran_vale', name: 'Seran Vale' }, { id: 'tavi_renn', name: 'Tavi Renn' },
  { id: 'koro_den', name: 'Koro Den' }, { id: 'mira_sol', name: 'Mira Sol' }, { id: 'ral_drenn', name: 'Ral Drenn' },
];
export { ANCHOR_NAMES };
