// Line banks for the Coruscant crowd (rubric 07 row 8). Every archetype has >= 20 lines about its own work and what
// it sees; shared banks cover time of day, district gossip, disasters, reactions to the player, directions and
// vendor prices. Star Wars flavour, no film quotes, every line <= 90 characters. Templates: {name} {building}
// {district} {landmark} {dir} {blocks} {item} {price} {job} {hour}.

export const JOB_LINES = {
  'office worker': [
    'Third shift on the Kuat contract and the forms still will not reconcile.', 'The datapad froze again. Forty pages of tariff schedules, gone.',
    'If the Trade Federation audit lands on my desk one more time I am moving to Alderaan.', 'Quarterly numbers go to the director at six. It is five forty.',
    'Half this floor runs on caf and unpaid overtime.', 'Filed the manifest in triplicate. The clan wants it in quadruplicate.',
    'The lift takes four minutes from the lobby. I time it every morning.', 'Someone reprogrammed the copier droid to speak only Huttese.',
    'Hyperlane freight rates are up nine percent. Nobody upstairs noticed.', 'Another merger memo. They renamed the department, not the desks.',
    'I push credits from one column to another all day. Somebody has to.', 'My console has a view of the boulevard. On a clear day, of a wall.',
    'We lost a contract to a firm on Corellia. Their bribes were better.', 'The director wants the report shorter and longer at the same time.',
    'Twenty years of ledgers and I still cannot spell Banking Clan without a shiver.', 'Lunch is a ration bar at the desk. The cafeteria queue is longer than my patience.',
    'The holoprojector crashed mid-pitch. We sold them nothing, very convincingly.', 'If the Senate passes the new levy we redo every ledger in the tower.',
    'The stairwell is faster than the lift after four. Everyone knows, nobody uses it.', 'Payroll runs at midnight. Pray to whatever the accountants pray to.',
    'They installed a droid supervisor. It counts our keystrokes.', 'One more form and I qualify for a pension on a moon nobody visits.',
  ],
  resident: [
    'The rent went up again. The view of the ventilation shaft did not.', 'Our neighbour keeps a nerf on the balcony. In a tower. On the ninetieth floor.',
    'The lift in our block has been humming for a week. Humming is not a good sign.', 'I have lived here forty years and never seen the ground. Nobody has.',
    'The laundry droid ate another tunic. That is three this month.', 'The kids race speeder bikes on the skybridge. I raced too, once.',
    'Sky always looks the same up here. Traffic, then more traffic.', 'The market has real fruit on tenth day. Real, as in grown in dirt.',
    'Power flickered last night. Half the tower thought it was an attack.', 'My mother came from Naboo. She never stopped missing grass.',
    'If the plumbing droid does not come today, I am learning plumbing.', 'The neighbours across the alley wave every morning. We have never met.',
    'Rooftop garden lottery is tomorrow. Two hundred names for six planters.', 'The concierge knows everyone. That is either comforting or terrifying.',
    'You can hear the Senate bells from our floor when the wind is right.', 'We moved up eleven floors last year. Same apartment, better air.',
    'The window cleaner droid waved at my daughter today. She waved back.', 'Grocery prices in this district would make a Hutt blush.',
    'Someone on floor sixty is learning the kloo horn. Badly. At dawn.', 'The air scrubbers were serviced. I can smell the caf shop from here again.',
    'Every window in this city is lit at night and still nobody is home.', 'Back home was three floors. Here three floors is a broom cupboard.',
  ],
  senator: [
    'The committee sits at ten. The vote will be delayed, as always.', 'My constituents want lower tariffs and better roads. On a planet with no roads.',
    'Do not quote me, but the Chancellor has never read the budget.', 'A senator is judged by the size of the delegation waiting outside.',
    'The rotunda is a marvel. Also a very expensive echo chamber.', 'I have three speeches drafted for one motion. Politics is preparation.',
    'The Banking Clan lobbyists arrive with pastries. It never helps them.', 'My pod jammed mid-session. Two hundred systems watched me hover.',
    'A delegation from the Outer Rim wants aid. The Core wants a study first.', 'Twelve amendments before lunch. None of them mine.',
    'My aide drafts the words. I supply the gravitas.', 'Sessions run late when the Rodian delegation feels poetic.',
    'They call it debate. I call it a very slow shouting match with robes.', 'The vote is close. Close means somebody is buying dinner tonight.',
    'The Senate cafeteria serves the same soup as the undercity. Plated better.', 'Diplomacy is repeating yourself until the room gets tired.',
    'I keep my old speeches in the archive. Nobody has ever requested one.', 'My robes cost more than my first office. My tailor is a senator of his own.',
    'A motion to adjourn is the only motion that always passes.', 'The Chancellor smiled at me today. I should check my committee seat.',
    'Every system sends its best talkers. Some of them can even listen.', 'I was elected to represent a planet I have visited twice.',
  ],
  'senate aide': [
    'The senator needs the trade brief in ten minutes. I have nine.', 'I carry the datapads, the caf and the blame.',
    'Do you know how many footnotes a tariff bill has? Four hundred. I wrote them.', 'If the senator asks, I was here at six. I was here at six.',
    'The Chancellor\'s office called twice. Nobody knows what they wanted.', 'Protocol says bow to a Wookiee delegation. Protocol says nothing about the smell.',
    'Every aide in this building is writing the same speech for a different boss.', 'The lifts to the pods are reserved. We aides take the stairs. Ninety floors.',
    'I proofread the Republic budget once. I found eleven errors. They kept nine.', 'Sessions are streamed to a thousand worlds. My shoulder appears in most of them.',
    'The Senate cafeteria runs on aides. Senators eat at the Grand.', 'Someone leaked the amendment. Everyone suspects the aides. Fair.',
    'I have memorised the seating chart of the rotunda. Nobody has ever asked.', 'My senator votes the way the poll says at breakfast.',
    'The committee wants a summary. Of the summary.', 'One day I will be the one with the robes. Today I fetch them from the cleaner.',
    'Our office got a window this year. It faces the other office.', 'A courier ran the wrong brief to the wrong chamber. It passed anyway.',
    'The Outer Rim delegates bring the best snacks to the hearings.', 'If you see a senator running, follow them. Something has happened.',
    'Motion, amendment, recess, repeat. That is the whole job, in four words.', 'The archives have every vote ever cast. The aides have every excuse.',
  ],
  'senate guard': [
    'Halt. State your business in the Senate District.', 'This post has been held for a thousand years. Move along.',
    'The blue is ceremonial. The pike is not.', 'Delegations enter by the east ramp. Visitors by the plaza gates.',
    'Twelve hours at attention. My knees have opinions.', 'Nobody passes this door without a pass. Not even the Chancellor\'s cousin.',
    'I have seen every species in the galaxy walk up these steps. Some twice.', 'The helmet keeps out the sun. It does not keep out the speeches.',
    'Guarding the Senate mostly means guarding it from tourists.', 'Someone tried to bring a nerf into the rotunda last week. A nerf.',
    'We rotate posts every four hours. The rotunda post is the quiet one.', 'A guard does not comment on politics. A guard has thoughts, though.',
    'Stand back from the pods. They move faster than they look.', 'My unit trained on Alsakan. It is colder there and calmer.',
    'The Chancellor\'s detail wears red. We wear blue. Nobody envies the red.', 'No holorecording inside the chamber. Yes, that includes your droid.',
    'The plaza fountain is not for bathing. I say this daily.', 'A quiet shift is a good shift. Keep it quiet.',
    'They pipe the session audio to the guard posts. It helps nobody sleep.', 'The pikes are heavier than they look. So are the robes.',
    'Ceremonial guard duty is the only job where standing still is a promotion.', 'Keep your hands where I can see them and your opinions where I cannot.',
  ],
  'security officer': [
    'Coruscant Security. Keep moving, citizen.', 'Third robbery on this level this week. Undercity gangs are getting bold.',
    'Speeder traffic is backed up to the Works. Walk if you can.', 'I patrol four blocks and two levels. My feet patrol the rest.',
    'The precinct scanner flagged a bounty hunter. It also flagged a sandwich.', 'We closed a cantina for serving spice. It reopened as a caf. Same spice.',
    'Nobody steals on the upper levels. They call it business up there.', 'Curfew in the undercity is a suggestion, apparently.',
    'Lost tourists are half my calls. The other half are found tourists.', 'I have a datapad full of parking violations for speeders that can fly.',
    'A protocol droid reported a crime in six languages. All wrong.', 'Precinct caf is illegal in some systems. We drink it anyway.',
    'The turbolifts here jam twice a week. I have the incident numbers memorised.', 'No blasters on the boulevard. Yes, that includes the decorative ones.',
    'The Senate has its guards. We get everything the guards do not want.', 'Traffic lane four is closed. Lane four has been closed since I joined.',
    'My partner is a droid. It never eats, never sleeps, never stops filing.', 'Every skybridge has a camera. Every camera has a blind spot. I know them all.',
    'Pickpockets work the market. Report yours and we will look sympathetic.', 'The undercity smells like ozone and fried nerf. I sort of miss it on leave.',
    'If a speeder falls off the deck, it is a traffic matter. Above me, thankfully.', 'Move along. Nothing to see here except me telling you to move along.',
  ],
  pilot: [
    'Customs held my freighter for six hours over a crate of Jogan fruit.', 'The hyperlane approach was stacked twelve deep this morning.',
    'She lists to port after a hard burn. Mechanics say character. I say leak.', 'Flew in from the Rim with a hold full of ore and a headache to match.',
    'Landing pad four has a crosswind nobody warns you about.', 'My navicomputer speaks Bocce when it is annoyed. It is often annoyed.',
    'A good pilot lands. A great pilot lands with the cargo still inside.', 'Refuelling costs more than the cargo pays. Welcome to the Core.',
    'I fly the Corellian run twice a week. Twice a week I swear never again.', 'The spaceport tower put me in a hold for an hour to let a yacht through.',
    'Coruscant traffic control is a thousand voices all saying no.', 'My copilot is an astromech. It has never once agreed with my landings.',
    'Deck crews here are the best in the galaxy. Also the slowest.', 'Lost a stabiliser fin to a bird on Naboo. Here the birds are speeders.',
    'The Kessel run pays well if you do not mind the company.', 'Grounded till the inspectors clear my hyperdrive. Could be a week.',
    'Rain on the pad, oil on the deck, and a customs droid with a grudge.', 'Every pilot has a story about the Maw. Half of them are true.',
    'The freighter was my father\'s. The debt was his too.', 'Cargo manifest says machine parts. Cargo smells like fish.',
    'They repainted pad seven again. Still cannot see the numbers at night.', 'Next hop is Bespin. Bring a coat, they said. On a gas giant.',
  ],
  mechanic: [
    'The hyperdrive motivator is fried. Third one this week off the Kuat line.', 'Hand me the power coupling. No, the other one. The one that is not on fire.',
    'She needs a new compressor and a prayer. I only stock compressors.', 'The pilot says it makes a noise. They all make a noise. This one screams.',
    'Welded the landing strut back on. Told him to land softer. He laughed.', 'Every freighter that lands here leaks something. I am the something department.',
    'Bought the parts from a Jawa. Half work. Guess which half.', 'Repulsorlifts are simple until they are not. Then they are a crater.',
    'The manual is in Huttese. The ship is Corellian. I am tired.', 'Coolant line burst at dawn. Blue everywhere. Very festive.',
    'That yacht costs more than my whole district. Its owner cannot find the fuel port.', 'Torch is running low on gas. So am I.',
    'Never trust a droid brain that came out of a scrap barge. Or a scrap barge.', 'I fix ships that were built to be replaced, not fixed. Job security.',
    'Sparks are normal. Smoke is normal. Silence is the one that worries me.', 'The astromech keeps rewiring the console to play music. Good taste, bad timing.',
    'Rebuilt a sublight engine from three dead ones. It runs. It hums the wrong note.', 'Somebody put sand in this intake. Someone flew through a desert with the vents open.',
    'Six bolts hold the whole cowling on. Five of them are mine.', 'Kuat parts fit Kuat ships. Everything else fits with a hammer.',
    'A customer asked for a rush job. Everything here is a rush job with a wait.', 'When the deck officer says the pad is clear, count your fingers first.',
  ],
  'dock worker': [
    'Two hundred crates by noon and the loader droid is on strike.', 'Sign the manifest or get off my dock.',
    'Freight from Kessel smells like it. Every crate.', 'The repulsor sled lifts a ton. My back lifts the rest.',
    'Customs pulled a whole container for one unlabelled fruit.', 'The cargo lift jammed with a Hutt\'s luggage inside. Nobody rushed.',
    'Night shift pays double. Night shift is also when things fall off decks.', 'Bay three is for freighters. Bay three has a yacht in it. Again.',
    'Twenty years hauling and I have never dropped a crate. Two droids, yes.', 'The foreman counts crates. I count hours.',
    'We unloaded a shipment of live nerfs once. Once was plenty.', 'The depot roof leaks on the durasteel and rusts nothing but my mood.',
    'Somebody labelled a crate fragile in Aurebesh and dropped it in Basic.', 'The Works sends ore up, we send parts down. Same lift, both ways.',
    'A loader droid asked me for a break today. I gave it two. It earned them.', 'Every crate has a story. Most of them are boring. Some of them tick.',
    'Freight rates went up, my wages did not. Somebody is loading the difference.', 'The best part of the dock is the view of ships leaving without me.',
    'Straps, clamps, mag-locks, and a lot of shouting. That is logistics.', 'The pallet said machine parts. It clucked.',
    'Foreman wants the bay clear by six. The bay has never been clear.', 'A fell crate is a fall crate. Old dock saying. Mind your feet.',
  ],
  vendor: [
    'Fresh Jogan fruit, two credits. Ripe today, jam tomorrow.', 'Best prices on the level. Second best on the planet.',
    'I do not haggle. I do, actually. Come closer.', 'The stall next door sells the same thing for more. They call it premium.',
    'Everything here fell off a ship. Legally. Mostly.', 'Business is slow when the Senate is in session. Nobody buys during speeches.',
    'Twenty years at this stall. My father had it. His was cleaner.', 'The security officer takes an apple every morning. He calls it inspection.',
    'A Hutt bought my whole stock once. Then complained about the bag.', 'Credits, not Republic dataries. I have been burned before.',
    'The market droid sweeps under my stall every hour. Very thorough. Very loud.', 'Rain never reaches this level. Dust always does.',
    'You want it cheaper, come back at closing. You want it good, buy it now.', 'My cousin sells droid parts three stalls down. Do not tell him I sent you.',
    'Tourists pay full price and thank me. Locals pay half and complain.', 'A shipment from Naboo is due. Real flowers. Bring a mask, the smell is strong.',
    'The awning is older than the district council. Holds up better too.', 'This stall has a permit. Somewhere. Probably.',
    'Fresh from the hydroponics deck this morning. Well, a morning.', 'Not on the counter? I have it in the back. Not in the back? I know a guy.',
    'Step right up. The queue is the price of quality.', 'Two for one on ration bars. Nobody has ever taken the offer.',
  ],
  cook: [
    'Nerf steak special. It is special because we have nerf.', 'The grill runs hot, the tips run cold.',
    'A hundred covers by noon and one working stove.', 'Order up. Two sliders, one bantha stew, no comments.',
    'If the kitchen droid burns the bread again it is going back to the Works.', 'Bantha stew takes six hours. Customers give me six minutes.',
    'The Senate cafeteria poached my sous-chef. Twice the pay, half the flavour.', 'Real Jogan fruit for the dessert. Do not tell the accountant.',
    'My knife is older than the district. Sharper too.', 'Somebody ordered a salad in this district. I had to look it up.',
    'Half the spices come from the Rim. The other half come from the label.', 'The extractor fan died. You can smell the special two levels up.',
    'A Rodian critic gave us three stars and a complaint about the lighting.', 'Grease fire on the second stove. Small one. Character building.',
    'I cook for senators and dock workers. The dock workers say thank you.', 'The recipe is my grandmother\'s. The pan is my landlord\'s.',
    'Diner rule: if the coffee is fresh the food is old. We keep both fresh. Mostly.', 'Twenty sliders a minute at lunch. The grill sings.',
    'Fresh out of Alderaanian flour. The bread will be Coruscanti today.', 'Every cook on this level knows every other cook. We trade insults and salt.',
    'A protocol droid tried to order for a Hutt. Took twenty minutes. Ordered water.', 'Wash your hands. Wash them again. This is a kitchen, not a hangar.',
  ],
  bartender: [
    'What will it be? Caf, or something that regrets you in the morning?', 'No blasters, no droids, no credit. House rules, older than the house.',
    'The band plays at nine. The fights start at ten. Tips peak at eleven.', 'Juri juice is out. Try the blue milk, it is less blue than it sounds.',
    'A bounty hunter drank here last night. Tipped well, said nothing.', 'The Outlander Club down the strip waters its drinks. We water our plants.',
    'Every spacer who lands on Coruscant ends up at my bar. Some never leave.', 'I pour, I listen, I forget. That is the whole profession.',
    'The caf machine is older than the cantina. It still outworks me.', 'Last call is when the lights come on and the truth comes out.',
    'Somebody left a datapad full of Senate secrets on the bar. I sold it back to him.', 'Fresh Corellian ale off the freighter. Fresh being a relative word.',
    'The musicians play for tips. The customers pay for silence. Nobody wins.', 'A Wookiee ordered the whole top shelf once. Paid in bolts. Good bolts.',
    'Do not lean on the bar. It leans back.', 'Two credits for a caf, five for a story. The story is better.',
    'We stopped serving Jawa juice after the incident. Do not ask about the incident.', 'The night shift crowd is dock workers. The day crowd is aides hiding.',
    'Bar was here before the boulevard. It will be here after.', 'The bouncer is new. Be polite, he is still learning who to throw out.',
    'My regulars have regulars. It is a whole ecosystem.', 'A drink a day keeps the Senate away. Old Uscru saying.',
  ],
  medic: [
    'Take a number. The med droid will see you before I do.', 'Bacta is rationed. Synth-flesh is not. Guess which one you get.',
    'Three speeder collisions before breakfast. Nobody wears a harness up here.', 'The ward is full. The ward is always full.',
    'I have set bones from forty species. Wookiee arms are the worst.', 'Fever, cough, and a sudden urge to complain about the Senate. Very common.',
    'The medcenter lifts jam with the gurneys in them. We carry a ladder.', 'Wash the wound, dress the wound, bill the wound. Republic medicine.',
    'A patient asked for a second opinion. The droid gave him a third.', 'Half my shift is telling dock workers to lift with their knees.',
    'The clinic caf is medicinal. That is the only defence for the taste.', 'Twenty hours on shift. My hands are steady. My humour is not.',
    'Spice cases are up in the undercity. Nobody funds the undercity clinics.', 'Somebody brought a nerf into triage. The nerf was fine. The nurse was not.',
    'A Senator came in with a paper cut. Ran a full scan. Politics.', 'The scanner says you are fine. The scanner also says I am a Rodian.',
    'The bacta tank leaks. We patched it with the same stuff we patch people with.', 'Breathing filters, everyone. The lower levels are thick today.',
    'Medical school on Rhinnal. Residency in the Uscru undercity. Culture shock.', 'Healing is easy. Paperwork is where they lose you.',
    'I stitched a mechanic and a droid in one afternoon. Same technique, honestly.', 'The night ward is quiet. The night ward is where I do my thinking.',
  ],
  patient: [
    'Waited four hours to be told to wait four more.', 'The med droid says rest. My landlord says rent.',
    'I fell off a cargo sled. The sled is fine. I am the paperwork.', 'They gave me a gown and took my dignity. Standard procedure.',
    'A bacta patch costs a week\'s wages. I healed the old-fashioned way. Slowly.', 'The ward has a view of the boulevard. I count speeders to pass the time.',
    'Broke my arm on the skybridge railing. The railing did not apologise.', 'The nurse droid has cold hands. It has no hands. Still cold.',
    'Everyone in this ward has a speeder story. Mine has a wall in it.', 'I told the medic it hurts when I do this. She said stop doing this.',
    'My insurance covers half. Half of a body is a strange thing to insure.', 'The soup here is medicine. Not good medicine.',
    'They scanned me three times. Third time they found the datapad I sat on.', 'Nothing wrong with me except the waiting room.',
    'A protocol droid explained my diagnosis in six languages. Still unclear.', 'The clinic is quieter than my apartment. I might stay.',
    'Sprained ankle. Two floors of stairs to the clinic. Irony is free here.', 'The medic smiled at me. That is either good news or very bad.',
    'I came in coughing. I am leaving coughing and poorer.', 'The Grand Republic Medical Facility has a gift shop. A gift shop.',
    'Someone in the next bed snores in Huttese.', 'Discharged tomorrow, they say. They said that yesterday.',
  ],
  tourist: [
    'Is that the Senate? It looks smaller on the holos.', 'We came from Chandrila for the opera. The queue is longer than the opera.',
    'Everything here is up. Where is down?', 'My guidebook says the undercity is dangerous. My guidebook was written by a coward.',
    'Two hundred credits for a room with a view of another room.', 'The holo-tour skipped the market. The market is the best bit.',
    'Take my picture with the guard. He does not blink. Perfect.', 'The food is amazing. I have no idea what it is.',
    'We got lost on a skybridge for an hour. Best hour of the trip.', 'The speeder lanes never stop. Does anyone here sleep?',
    'Back home the tallest building is a silo. This is many silos.', 'The Jedi Temple is closed to visitors. We looked at it from a great distance.',
    'A droid sold me a map. The map is of a different level.', 'My partner wants to see the opera. I want to see a bed.',
    'The fountain in the plaza is real water. We checked. Twice.', 'They say five hundred Republica has a thousand floors. We saw the lobby.',
    'I bought a Senate souvenir pike. It is a broom.', 'The tour droid speaks nine languages. None of them slowly.',
    'Coruscant at night is a thousand suns. Bring sunglasses for the dark.', 'Our shuttle leaves in three hours from a spaceport I cannot find.',
    'The locals walk so fast. Are they late, or is that just how legs work here?', 'One more holo and then we find lunch. Then one more holo.',
  ],
  courier: [
    'Priority packet for the ministry. Out of my way, please.', 'Forty deliveries before noon. My legs invoice separately.',
    'The lifts are for people who are not late. I am always late.', 'A senator\'s lunch, a lawyer\'s brief and a droid part. Same bag. Same hour.',
    'Skybridge to the Federal District is faster if the guard is asleep.', 'Sign here. And here. And here. The Republic loves a signature.',
    'Datapad says floor 88. Building has 86 floors. Classic.', 'If it fits in the satchel it ships. If it does not, it ships slower.',
    'I know every alley on three levels and two of the ministers by scent.', 'The courier guild is a myth. The couriers are very real and very tired.',
    'Someone shipped a live gizka. It arrived. The satchel did not.', 'Rain? No. Traffic? Always. Deliveries? On time. Ask anyone.',
    'The hotel porter tips in pastry. The bank tips in silence.', 'Ran a brief from the archives to the Senate in nine minutes. Record stands.',
    'Half of what I carry is caf. The other half is complaints about the caf.', 'The undercity route is quicker and only slightly more stabby.',
    'A courier never reads the packet. A courier always guesses.', 'Turbolift is out on Tower Nine. Eighty floors of stairs. Priority packet.',
    'My satchel has been to more ministries than most senators.', 'Deliveries to the Jedi Temple go to the gate. Nobody goes past the gate.',
    'Traffic droid gave me a ticket for running. Running.', 'Next stop the HoloNet tower. They order lunch like it is breaking news.',
  ],
  'protocol droid': [
    'Good day. I am fluent in six million forms of communication and all of them are polite.', 'This unit is assigned to the ministry lobby. May I direct you?',
    'The senator is in session. Might I offer you a seat and a very long wait?', 'Etiquette note: one does not touch a Wookiee delegate\'s shoulder.',
    'I have translated three treaties this morning. Two of them contradict each other.', 'Protocol dictates a bow of fourteen degrees for a Neimoidian envoy.',
    'My memory holds the seating plans of every Senate banquet since my activation.', 'A Hutt asked for directions. I complied. I also computed a bath schedule.',
    'Visitors must register. Droids must register twice. I find this unfair.', 'The lift is to your left. The stairs are for those with a lower opinion of lifts.',
    'I served a Bothan trade mission once. Everyone left with everyone\'s secrets.', 'My joints require oil every ninety days. The Republic requires forms every nine.',
    'Please refrain from running in the atrium. I cannot keep up and it is undignified.', 'The Chancellor\'s office schedules in seven-minute increments. I schedule the increments.',
    'I have been reprogrammed twice. The second time they left the manners.', 'A guest asked me to lie for him. I explained that I am programmed for diplomacy instead.',
    'Aurebesh, Basic, Huttese, Bocce, and whatever the accountants speak.', 'Kindly do not lean on the counter. It is antique. So am I.',
    'The reception log shows four hundred visitors today. Three were pleasant.', 'This unit does not carry luggage. This unit carries the burden of protocol.',
    'I am not permitted opinions. I am permitted observations. Observe: the queue.', 'A pleasure to serve. A greater pleasure to serve someone who is on time.',
  ],
  astromech: [
    'Bweep-bwoo. Translation: the hyperdrive is fine, the pilot is not.', 'Whirr-click. The mechanic keeps calling me a toolbox with an attitude. Accurate.',
    'Dweet! Rerouted the fuel line. Nobody asked. Nobody complained yet.', 'Bloop-beep. I have the landing codes for four spaceports and a cantina.',
    'Whoop-wee. Someone spilled caf in my dome. Everything tastes like caf now.', 'Bwoo-bwoo-beep. My last pilot flew into a comet. I flew out.',
    'Tweedle-dee. The repair bay droid gossips in binary. I hear everything.', 'Beep-beep. Charging port on pad four is loose. I did not do that. Probably.',
    'Bwip. The astromech union has two rules: no stairs, no questions.', 'Dweeoo. I patched the nav computer. It plays music now. You are welcome.',
    'Chirp-whirr. Stairs are the enemy. Lifts are the friend. Ramps are family.', 'Woop-woop. A tourist tried to sit on me. I am not a stool. I am a stool with a laser.',
    'Bloop. My pilot lost a wing. I found it. It was on another ship.', 'Beedle-boop. The Works foundry has the best scrap. I have a collection.',
    'Dweet-dweet. Systems nominal. Pilot not nominal. Pilot asleep on pad.', 'Whirr. Six hundred repair logs on file. Five hundred say pilot error.',
    'Bwoo-weep. Cargo droids are slow. I have said this to their faces. They have no faces.', 'Beep-blat. Customs scanned me. Customs found a spanner. My spanner.',
    'Bwee-whistle. I once rerouted power from a yacht to a caf machine. Priorities.', 'Tweet-click. The hangar door sensor is mine now. Nobody leaves without a beep.',
    'Woo-dweet. If it has a socket, I can talk to it. Most things regret this.', 'Bwip-bwip. I am rolling. Mind the wheels. Mind the dignity.',
  ],
  'sweeper droid': [
    'Bzzt. Sweeping sector four. Please lift your feet.', 'Debris detected: one ration wrapper, one dream of a cleaner city.',
    'Whirr. I have swept this boulevard eleven thousand times. It stays dirty. I stay sweeping.', 'Klik-klik. The market stalls produce forty kilos of husk per day. I count them.',
    'Brrr. Tourists drop more than dock workers. Dock workers drop heavier things.', 'Zzt. My brushes were replaced last cycle. They already miss the old grime.',
    'Whirr-hum. Rain never falls this deep. Dust always does. Job security.', 'Bip. The plaza fountain sprays leaves. Leaves are my nemesis.',
    'Bzzt-bzzt. Somebody parked a speeder on my route. I swept around it. Twice.', 'Klak. Sector clean. Sector will not stay clean. Sector never does.',
    'Hmmm. The night shift is quieter. The night shift has more spilled drinks.', 'Whirr. A child rode on me for three blocks. Efficiency down, morale up.',
    'Brrr-tik. I am not a toy. I am a municipal asset with brushes.', 'Zzzt. Vent grates collect the most. Vent grates also collect me if I am careless.',
    'Bip-bip. Sweeping under the senator\'s door. The senator\'s door does not tip.', 'Klik. Ozone, grease, fried nerf. My sensors know this district by smell.',
    'Whirr-whirr. Someone painted a face on my chassis. I have kept it.', 'Bzzt. A courier ran over my brush. I swept his footprints out of spite.',
    'Hum. Battery at forty percent. Determination at one hundred.', 'Tik-tik. The undercity floor has been durasteel for a thousand years. Still dusty.',
    'Brrr. Confetti from the opera gala. Three days of sweeping. Worth it, apparently.', 'Zzt. Move along, citizen. This dirt is spoken for.',
  ],
  jedi: [
    'The Temple spires catch the first light. Most of the city misses it.', 'Patience is easy in a garden. Coruscant is not a garden.',
    'I walk the boulevards to remember whom the Order serves.', 'A thousand lit windows and each one a life the Force runs through.',
    'The Senate asks for peacekeepers. Peace is not kept, it is grown.', 'My padawan wants to see the undercity. My master forbade it. I went anyway, once.',
    'The crowd moves like a river. Rivers know where they are going.', 'Meditation on the Temple roof is loud. The speeders help, in a way.',
    'A youngling asked me why the city never sleeps. I am still composing the answer.', 'The Council sits today. The Council always sits. The city keeps standing.',
    'Fear is a small room. This city is full of small rooms.', 'A senator asked me to settle a dispute. It was about a parking pad.',
    'The archives hold ten thousand years of records and very little wisdom.', 'The market vendors know more about the Republic than the committees do.',
    'My robes mark me. So I walk slowly and listen well.', 'The undercity has its own Force. Darker, warmer, closer.',
    'A guard saluted me. I bowed. Neither of us knows the other\'s protocol.', 'The Force does not hurry. Coruscant does. We meet in the middle, usually late.',
    'I trained on this plateau before the boulevards were rebuilt. The wind is the same.', 'Even a Jedi waits for a lift. The lift does not care what I sense.',
    'The city\'s hum is a kind of meditation, if you let it be.', 'Trust the path, mind the railing.',
  ],
  'bounty hunter': [
    'Not looking for you. Yet.', 'The Guild posts in the undercity. The Senate posts everywhere else. Same faces.',
    'Coruscant pays well and asks little. Ideal.', 'My armour is Mandalorian. My patience is not.',
    'The cantina keeps my tab. I keep the cantina safe. Fair trade.', 'A bail-jumper hid in the Works for a month. The Works does not hide anyone.',
    'Security scans for blasters. I carry other things.', 'Twelve levels down there are people who owe. Twelve levels up, people who pay.',
    'I do not do politics. I do people who did politics badly.', 'A Hutt pays late. A senator pays never. A bank pays on time and asks for receipts.',
    'The Guild has rules. Coruscant has more rules. I read neither.', 'Tracked a smuggler through the market by the smell of his cargo. Fish.',
    'This helmet has seen forty systems. It prefers the ones with fewer lifts.', 'The undercity strip is the best place to lose someone. Or find them.',
    'A bounty is a promise. I keep promises.', 'Do not stand behind me. Do not stand in front of me either.',
    'Security officers give me space. Smart officers.', 'Every job ends in a cantina. Some start there too.',
    'I flew in on a shuttle full of tourists. I was the quiet one.', 'They call it work. I call it a very long errand with a reward at the end.',
    'The Senate has a bounty board. It is called a committee.', 'Say less. Walk away. Good.',
  ],
  journalist: [
    'HoloNet News, live from the Senate plaza. Do you have a minute? No? Perfect quote.', 'The committee vote is in three hours. The story is in two.',
    'Somebody leaked the budget. Everybody leaked the budget. Great day for journalism.', 'My editor wants a scandal by six. The Senate usually delivers by five.',
    'I interviewed a protocol droid once. Best sources never sleep.', 'The undercity beat pays less and tells more.',
    'Channel Twelve got the senator. We got the senator\'s speeder pilot. Better story.', 'Every window in this city is a potential source. Most of them close.',
    'Live in five. Keep it down, the recorder picks up everything, including your opinion.', 'The Chancellor\'s office released a statement. It said nothing beautifully.',
    'Rumour has it the Banking Clan is buying a district. Rumour is usually right.', 'Interviewed a Jedi for four minutes. Got two sentences and a headache.',
    'The HoloNet tower is a hundred and seventy blocks tall. The stories still leak sideways.', 'I cover the Senate. My colleague covers the undercity. We compare notes on corruption.',
    'A senator promised me an exclusive. Six senators have promised me that exclusive.', 'The best quotes come from the caf queue, not the podium.',
    'Deadline, recorder, holo-cam, and a very fast pair of boots.', 'Nobody reads the transport report. I write it anyway. Somebody needs to.',
    'A tourist asked if I was famous. Only on twelve worlds, and only for a week.', 'Editorial wants pictures of the plaza fountain. The fountain is very photogenic today.',
    'Breaking news is mostly waiting for news to break.', 'Off the record? Nothing in this city is off the record.',
  ],
};

// Time-of-day banks (any archetype). Keys match `periodOf(hour)`.
export const TIME_LINES = {
  dawn: ['First light on the spires. Best part of the day, and the shortest.', 'Dawn shift. The city looks almost quiet from here. Almost.', 'The caf shops open before the sun clears the towers. Good.', 'Early. Too early. The speeders have not even started shouting yet.', 'Morning haze in the undercity. It clears by noon, mostly.'],
  morning: ['Rush hour on the boulevards. Mind the couriers.', 'The lifts are full every morning. Every single morning.', 'A whole city late for work at the same time. It is a wonder anything opens.', 'Morning. The skybridges are busy and the caf is strong.', 'Half the Federal District is crossing the plaza. The other half is already at a desk.'],
  noon: ['Lunch rush. Every diner on the level has a queue.', 'Midday sun on the deck. It cooks the durasteel and the tempers.', 'The plaza fills at noon. Aides, clerks, tourists, pigeons if we had them.', 'Noon. The Senate breaks, the cafs fill, the couriers sprint.', 'Everybody eats at the same hour in this city. It is a design flaw.'],
  afternoon: ['Long afternoon. The towers throw their shadows across the plaza.', 'Afternoon session, afternoon shift, afternoon slump. The city yawns.', 'Traffic thickens after three. It never actually thins.', 'The light turns gold on the spires around now. Worth a look up.', 'Afternoon. Two more hours and this level turns into a cantina.'],
  evening: ['Evening shift comes on. The day shift heads for the cantinas.', 'The towers light up one window at a time. Then all at once.', 'Sunset over the Works. Orange smoke, orange sky, same colour.', 'Evening in Uscru. The music starts before the sun is gone.', 'The boulevards glow at dusk. That is the best trick this city has.'],
  night: ['Night shift. The city never sleeps, it just changes clothes.', 'A million lit windows and the traffic still does not stop.', 'Night in the undercity is louder than day. Different people, same noise.', 'Late. The lifts are empty and the corridors hum.', 'The entertainment district owns the night. The rest of us borrow it.'],
};

// District gossip (keyed by layout district)
export const GOSSIP = {
  senate: ['Word is the trade committee vote was bought with pastries.', 'The Chancellor\'s office is renovating. Again. With Republic credits.', 'A senator\'s pod broke loose mid-session and floated for an hour.', 'The Senate Guard caught a HoloNet drone in the rotunda. Nobody claimed it.', 'They say the Jedi Temple and the Senate have a private turbolift. They do not. Probably.'],
  financial: ['The Banking Clan is buying half the Federal District. The other half is leasing.', 'A firm on floor ninety collapsed overnight. Their windows are still lit.', 'The new office tower has a lobby the size of a hangar and one receptionist.', 'Rumour says a supertall is going up where the caf is. The caf disagrees.', 'Someone embezzled a whole department here and nobody noticed for a year.'],
  residential: ['The tower association voted on the roof garden. Nobody can find the minutes.', 'A family on floor sixty keeps a nerf. In a two-room. On purpose.', 'The lifts in Skyline Heights sing when they are overloaded. They sing a lot.', 'The school got a new droid teacher. The kids reprogrammed it by lunch.', 'They are opening a second clinic on this level. About time.'],
  industrial: ['The Works blew a reactor seal last night. Just steam, they say. Just steam.', 'The foundry is hiring. It is always hiring. Think about why.', 'A freighter clipped the depot crane. The crane won.', 'Somebody stole a whole pallet of motivators from Bay Nine. Inside job.', 'The Works smoke turns the sunset orange. Tourists love it. Lungs do not.'],
  entertainment: ['The Opera House sold out for a Bith quartet. A quartet. Sold out.', 'A bounty hunter drank at the Outlander last night. Nobody looked up.', 'The undercity strip stays open till dawn now. The precinct pretends not to know.', 'They say the arcade has a dejarik table that cheats. It does.', 'A cantina fight last week involved three Rodians and a kloo horn.'],
  market: ['CoCo Town prices doubled since the tariff. Vendors blame the Senate. Fair.', 'A Jawa crew set up a stall for a day and sold everyone their own tools back.', 'The market droid swept a whole stall into the recycler. Owner was inside.', 'Real Naboo fruit hit the stalls this morning. Gone by ten.', 'Pickpockets are working the north stalls. Watch your credits, friend.'],
  spaceport: ['Customs impounded a yacht for a week over one unlabelled fruit crate.', 'Pad seven has a crosswind that has flipped two shuttles this season.', 'A Corellian freighter landed with a live nerf in the cockpit. The nerf was the pilot\'s.', 'The control tower lost a shuttle for ten minutes. It was parked.', 'Fuel prices went up again. The pilots say the tower is skimming.'],
};

// Disaster shouts (same kinds the frontier town uses). `sky` = something strange overhead.
export const DISASTER_LINES = {
  flood: ['Water on the deck! Get to the upper levels!', 'The undercity is flooding! Up the stairs, now!', 'Grab the railing! The deck is awash!', 'Everybody up! The lower levels are going under!'],
  tornado: ['Wind shear on the boulevard! Inside, everyone!', 'That funnel is coming down the boulevard! Take cover!', 'Get off the skybridge! The wind will take you!', 'Inside the lobby! Now!'],
  beam: ['What is that light? Get away from it!', 'The sky is burning over the plaza! Run!', 'Orbital fire! Clear the deck!', 'Do not look at it! Get inside!'],
  sky: ['What is that above the towers?', 'Is that a ship? That is not a ship.', 'Look up. No, really, look up.', 'Somebody call the precinct. Look at the sky.', 'That was not in the traffic forecast.'],
  panic: ['Move! Move!', 'Clear the way!', 'Get to the towers!', 'Somebody help!'],
};

// Reactions to the player
export const PLAYER_LINES = {
  vandal: ['Hey! That is Republic property!', 'You cannot just break that. This is the Senate District.', 'Security! Somebody is tearing up the plaza!', 'Put that back. This district has cameras. Many cameras.', 'That took a crew a week to lay and you a second to break.'],
  flying: ['Is that citizen flying? Without a speeder?', 'No repulsor pack, no wings. How is he doing that?', 'Someone is flying over the boulevard. Traffic control will not like it.', 'Look at that! Flying like a Jedi on holiday!', 'Get down from there before the precinct sees you!'],
  bump: ['Watch it!', 'Hey, mind where you walk!', 'Excuse you.', 'Careful, friend. The deck is crowded enough.', 'Oof. Slow down, this is not a hyperlane.'],
  poke: ['Hands off!', 'Do that again and I call security.', 'What is wrong with you?', 'Easy there. I bruise like a Jogan fruit.', 'Do not touch the uniform.', 'Back off, citizen.'],
  greet: ['Yes? Make it quick.', 'Can I help you, citizen?', 'You look lost. Everybody does, on this level.', 'Afternoon, citizen. New to the district?', 'What do you need?', 'Something I can do for you?'],
  running: ['Somebody is in a hurry.', 'Slow down, the lifts will still be there.', 'Running on the deck. Bold.'],
};

// Directions: {landmark} {dir} {blocks}
export const DIRECTION_LINES = [
  'The {landmark}? That way, about {blocks} {dir}.', '{landmark} is {blocks} {dir}. Follow the boulevard and you cannot miss it.',
  'Head {dir} for {blocks} and you will hit the {landmark}.', 'You want the {landmark}. It is {dir} of here, {blocks} or so.',
  '{blocks} {dir}, take the skybridge if you can. That is the {landmark}.', 'Straight {dir}. When the towers open up, that is the {landmark}.',
  'Nearest place worth seeing is the {landmark}, {blocks} to the {dir}.', 'Keep {dir} for {blocks}. The {landmark} has the big doors.',
];
export const NO_LANDMARK_LINES = ['Nothing worth seeing near here. Try the plaza.', 'You are between districts. Pick a boulevard and follow it.'];

// Vendor price quotes: {item} {price}
export const PRICE_LINES = [
  '{item} is {price} credits. Fair price, as prices go.', 'For you, {item} at {price} credits. Do not tell the next customer.',
  '{price} credits buys you {item}. Best deal on the level.', 'Fresh {item}, {price} credits each. Cheaper by the crate.',
  '{item}? {price} credits and worth every one.', 'Today only: {item} for {price} credits. Also every other day.',
];
export const NOT_VENDOR_LINES = ['I am not selling anything. Try the market level.', 'Trade? Wrong person. The vendors are at the stalls.', 'Do I look like a stall? The shops are down the boulevard.'];

// Replies to "what do you do here" that wrap a job line: {job} {building}
export const WORK_INTRO = ['I work at {building}. {job}, if you must know.', '{building}. I am the {job}.', 'This is {building}. I keep it running as the {job}.', 'The {job} at {building}. Not glamorous, but it pays.'];
export const STREET_INTRO = ['I keep to the streets of the {district}. {job}.', '{job}. The whole {district} is my office.', 'Me? {job}, working the {district}.'];
export const RESIDENT_INTRO = ['I live at {building}. Just heading out.', 'Home is {building}. Work is wherever they pay.'];

// Vendor call-outs (ambient, market stalls)
export const CALLOUTS = ['Fresh Jogan fruit! Two credits!', 'Ration bars, power cells, holo-chips! Best prices!', 'Droid parts! Certified! Mostly!', 'Caf! Hot caf! Strong enough to wake a Hutt!', 'Nerf jerky, dried on the Works vents! Authentic!', 'Blue milk! Cold today!', 'Real cloth from Alderaan! Feel it!', 'Speeder parts, no questions!', 'Step up, step up! Everything must go before the tariff!'];

export const ALL_BANKS = { JOB_LINES, TIME_LINES, GOSSIP, DISASTER_LINES, PLAYER_LINES, DIRECTION_LINES, NO_LANDMARK_LINES, PRICE_LINES, NOT_VENDOR_LINES, WORK_INTRO, STREET_INTRO, RESIDENT_INTRO, CALLOUTS };
