import { NOISE_GLSL } from '../../procgen/shaders/noise.glsl';

/**
 * Every FX sprite, flipbook frame and decal is generated by this one fragment
 * program. A single program keeps shader-link time to one compile for the whole
 * effects library — twenty separate bake shaders cost twenty links, and on a
 * software rasteriser that is seconds of boot time.
 *
 * `uMode` selects how the destination texture is subdivided:
 *   0  one image filling the target, generator `uKind`
 *   1  a `uGrid` atlas of consecutive generators starting at `uKind`
 *   2  a `uGrid` flipbook of generator `uKind`, cell index driving `t`
 *   3  a `uGrid` atlas of variants of generator `uKind`, cell index driving `t`
 */
export const TEX_KIND = {
  RADIAL: 0,
  SMOKE_PUFF: 1,
  SMOKE_FLIP: 2,
  FIRE_FLIP: 3,
  SPARK_STREAK: 4,
  FIREBALL_FLIP: 5,
  // chip atlas, 3x3, consecutive
  CHIP: 10,
  LEAF: 11,
  GLASS_SHARD: 12,
  DROPLET: 13,
  SPLINTER_A: 14,
  SPLINTER_B: 15,
  CHIP_B: 16,
  CHIP_C: 17,
  GRIT: 18,
  // glow atlas, 4x4, consecutive
  GLOW_SOFT: 20,
  FLASH_STAR_A: 21,
  FLASH_STAR_B: 22,
  FLASH_STAR_C: 23,
  FLASH_STAR_D: 24,
  FLASH_STAR_E: 25,
  GAS_CONE: 26,
  HOT_CORE: 27,
  SHOCK_RING: 28,
  LENS_STREAK: 29,
  EMBER: 30,
  SPLASH_COLUMN: 31,
  HAZE: 32,
  RIPPLE_RING: 33,
  SMOKE_RING: 34,
  BURST_STAR: 35,
  // decal atlas, 4x4, consecutive
  HOLE_CONCRETE_A: 40,
  HOLE_CONCRETE_B: 41,
  HOLE_BRICK: 42,
  HOLE_PLASTER: 43,
  HOLE_METAL_A: 44,
  HOLE_METAL_B: 45,
  HOLE_WOOD_A: 46,
  HOLE_WOOD_B: 47,
  HOLE_GLASS_A: 48,
  HOLE_GLASS_B: 49,
  DIVOT_DIRT: 50,
  DIVOT_GRAVEL: 51,
  BLOOD_SPLAT_A: 52,
  BLOOD_SPLAT_B: 53,
  BLOOD_POOL: 54,
  CRATER: 55,
  // blood particle atlas, 2x2, consecutive
  BLOOD_DROP: 60,
  BLOOD_MIST: 61,
  BLOOD_STRAND: 62,
  BLOOD_GOUT: 63,
} as const;

const HELPERS = /* glsl */ `
const float PI2 = 6.28318530718;

float sat(float v) { return clamp(v, 0.0, 1.0); }
vec3 sat3(vec3 v) { return clamp(v, 0.0, 1.0); }

/** Smooth radial falloff, 1 at the centre and 0 at radius 1. */
float falloff(float r, float power) {
  return pow(sat(1.0 - r), power);
}

/** Angle in [0,1) around the cell centre. */
float angle01(vec2 p) {
  return atan(p.y, p.x) / PI2 + 0.5;
}

/** Random-length radial spokes: cracks, splinters, spatter legs. */
float spokes(vec2 p, float count, float seed, float sharp) {
  float a = angle01(p) * count;
  float i = floor(a);
  float f = fract(a) - 0.5;
  float len = 0.35 + 0.65 * hash12(vec2(i, seed));
  float width = mix(0.06, 0.3, hash12(vec2(i, seed + 3.7)));
  float r = length(p);
  float along = sat(1.0 - r / max(len, 0.02));
  float across = pow(sat(1.0 - abs(f) / width), sharp);
  return along * across;
}

/** Irregular blob radius: the silhouette every organic sprite starts from. */
float blobRadius(vec2 p, float lobes, float amount, float seed) {
  float a = angle01(p);
  float n = fbmValue2(vec2(a * lobes, seed), vec2(lobes, 64.0), 3);
  return 1.0 - amount + n * amount * 2.0;
}

/** Soft-edged blob mask in [0,1]. */
float blob(vec2 p, float radius, float lobes, float amount, float soft, float seed) {
  float r = length(p) / max(radius, 1e-3);
  float edge = blobRadius(p, lobes, amount, seed);
  return smoothstep(edge + soft, edge - soft, r);
}

float ring(float r, float centre, float width) {
  return sat(1.0 - abs(r - centre) / max(width, 1e-4));
}
`;

const GENERATORS = /* glsl */ `
struct Sprite {
  vec3 color;
  float alpha;
};

/** Soft radial falloff — the workhorse glow. */
void genRadial(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  s.color = vec3(1.0);
  s.alpha = falloff(r, 2.2) * 0.85 + falloff(r, 8.0) * 0.5;
}

/**
 * Puffy smoke sprite. Billowed turbulence eroded by a radial ramp so the
 * silhouette is lumpy rather than circular, with the density biased away from
 * the rim so overlapping copies never draw a visible disc edge.
 *
 * The dense parts have to *saturate*. Everything that reaches the screen is a
 * product — sprite coverage times the emitter's peak opacity times the fade-out
 * envelope — and four factors that each look reasonable on their own multiply
 * out to nothing: a generator peaking at half coverage, a peak opacity of a
 * third and a fade-out that is already down to 0.4 by mid-life leave a puff
 * about six per cent opaque, which is invisible however many of them are alive.
 * So the noise is thresholded hard and then scaled past 1: the clumps clip to
 * fully opaque and the thin regions between them keep the lumpy silhouette.
 */
void genSmokePuff(vec2 uv, float variant, inout Sprite s) {
  float r = length(uv) * 2.0;
  vec2 q = uv * 3.4 + variant * 17.0;
  float billow = turbulence2(q, vec2(1024.0), 5);
  float lumps = fbmValue2(uv * 5.0 + variant * 31.0, vec2(1024.0), 4);
  float density = mix(billow, lumps, 0.45);

  // The boundary is a lobed radius, not a circle. This is the single most
  // important line in the generator: a radial ramp plus a saturating interior
  // bakes a disc with a two-texel edge, and a wall covered in discs is the most
  // conspicuous way a particle system gives itself away. A ragged outline lets
  // overlapping copies read as one irregular volume instead.
  float edge = blobRadius(uv, 5.0, 0.24, variant * 7.0 + 2.0) * 0.94;
  float body = sat(1.0 - r / max(edge, 0.05));
  float a = sat(pow(body, 0.8) * mix(0.4, 1.35, density) * 1.35 - 0.16);
  // Feather the outer fifth so the rim is a gradient however dense the middle is.
  a *= smoothstep(0.0, 0.22, body);
  // A touch of internal density variation reads as depth once lit.
  s.color = vec3(0.72 + density * 0.34);
  s.alpha = sat(a);
}

/** 4x4 flipbook of an evolving, rising, expanding smoke puff. */
void genSmokeFlip(vec2 uv, float t, inout Sprite s) {
  // Modest growth inside the flipbook: the emitters already interpolate a
  // particle from its birth size to its death size, and a generator that also
  // starts at half a cell multiplies the two and leaves early frames tiny.
  float grow = 0.68 + t * 0.4;
  vec2 p = uv / grow;
  // Rise and shear as it ages.
  p.y -= t * 0.12;
  p.x += (fbmValue2(vec2(t * 3.0, 5.5), vec2(64.0), 2) - 0.5) * t * 0.25;
  float r = length(p) * 2.0;

  vec2 q = p * mix(3.0, 1.9, t) + vec2(0.0, -t * 2.1) + 11.0;
  float billow = turbulence2(q, vec2(1024.0), 5);
  float detail = fbmValue2(p * mix(9.0, 4.5, t) + t * 7.0, vec2(1024.0), 3);
  float density = mix(billow, detail, 0.38);

  // Lobed boundary rather than a radial ramp: a smoke puff is a cauliflower, and
  // the outline is most of what says so. The lobes tighten as the frame advances
  // so the silhouette boils.
  float edge = blobRadius(p, mix(3.5, 6.0, t), mix(0.26, 0.42, t), 13.0) * 0.92;
  float body = sat(1.0 - r / max(edge, 0.05));
  // Dissipation: the threshold climbs so the puff tears apart rather than
  // fading uniformly, which is what actually reads as smoke thinning out. Early
  // frames saturate — fresh explosion smoke is genuinely opaque, and it is the
  // only thing in the library that can hide the skyline behind it.
  float threshold = mix(0.34, 0.72, t);
  float a = sat(density * 2.5 - threshold) * pow(body, mix(0.7, 1.3, t));
  a += pow(body, 2.2) * mix(0.42, 0.06, t);
  a *= smoothstep(0.0, 0.2, body);
  s.color = vec3(0.66 + density * 0.4);
  s.alpha = sat(a * mix(1.45, 0.95, t));
}

/**
 * 4x4 flipbook of a flame licking upward.
 *
 * The flame is deliberately drawn nearly edge to edge of its cell. Every emitter
 * sizes a sprite by the flame it wants to see, so a generator that leaves a
 * third of the cell empty silently makes every fire in the game a third smaller
 * than the code asked for — and the fix then gets applied at the emitters, where
 * it also inflates the spacing between sprites.
 */
void genFireFlip(vec2 uv, float t, inout Sprite s) {
  vec2 p = uv;
  // Flames are taller than wide and taper at the top.
  p.y -= 0.02;
  float h = sat(p.y + 0.5);
  float taper = mix(1.0, 0.4, pow(h, 1.3));
  vec2 q = vec2(p.x / max(taper, 0.05), p.y);

  float flow = t * 2.6;
  float wobble = (fbmValue2(vec2(h * 3.0 - flow, 3.1), vec2(256.0), 3) - 0.5) * 0.34 * h;
  q.x -= wobble;

  float core = sat(1.0 - length(vec2(q.x * 1.95, (q.y - 0.02) * 1.18)) * 2.0);
  float lick = turbulence2(vec2(q.x * 5.0, q.y * 3.0 - flow * 1.6) + 21.0, vec2(512.0), 4);
  float body = sat(core * 1.3 + lick * 0.6 - 0.26);
  // Tear the tip into separate tongues.
  body *= mix(1.0, sat(1.4 - h * 1.45 + lick * 0.7), 0.8);
  body *= smoothstep(0.0, 0.12, h);

  float heat = sat(body * 1.5 + core * 0.9);
  // White-hot base through yellow and orange to a smoky red tip.
  vec3 c = mix(vec3(0.55, 0.09, 0.02), vec3(1.0, 0.42, 0.06), sat(heat * 1.5));
  c = mix(c, vec3(1.0, 0.83, 0.42), sat(heat * heat * 1.7 - 0.45));
  c = mix(c, vec3(1.0), sat(heat * 2.4 - 1.6));
  s.color = c;
  s.alpha = sat(body * 1.35);
}

/**
 * 4x4 flipbook of a fireball: a convecting, cauliflower-lobed mass of burning
 * fuel that tears itself apart and sooties over as it cools.
 *
 * A fireball is not a flame, and reusing the flame book for one is the mistake
 * this generator exists to fix. A flame is a tall tapering tongue anchored at
 * its base, which is right for something burning in place; a cluster of tongues
 * scattered through a blast volume reads as leaves blowing past the camera. A
 * fireball needs a roughly round, deeply lobed silhouette with hot creases
 * between the lobes, so that a dozen overlapping copies sum to one billowing
 * mass rather than to a bouquet.
 *
 * The other half of the job is the soot. The outside of a fireball has already
 * turned to smoke while the inside is still burning, and that dark, opaque limb
 * is what gives the ball mass — a purely luminous fireball is a light bulb. The
 * darkness of each texel drives the coverage it writes in the particle shader,
 * so the burning parts add light and the cooled parts block it.
 */
void genFireball(vec2 uv, float t, inout Sprite s) {
  vec2 p = uv;
  // Convection: the mass climbs a little inside its own cell as it burns.
  p.y -= t * 0.05;
  float r = length(p) * 2.0;
  float a = angle01(p);

  // The coarse lobes drift slowly so successive frames read as one ball
  // evolving rather than as unrelated shapes; the fine lobes advance faster so
  // the edge boils. Both matter: a dozen sprites of one blast sit within a
  // tenth of a second of each other and therefore on nearly the same frame, so
  // a silhouette that never changes is a dozen copies of the same outline.
  float coarse = fbmValue2(vec2(a * 4.0, 3.0 + t * 1.6), vec2(4.0, 64.0), 3) - 0.5;
  float fine = fbmValue2(vec2(a * 12.0, 8.0 + t * 3.0), vec2(12.0, 64.0), 3) - 0.5;
  float edge = 0.9 + coarse * 0.5 + fine * mix(0.16, 0.44, t);

  // Interior: bubbles of burning gas divided by cooler creases.
  vec2 q = p * mix(4.0, 2.6, t) + vec2(0.0, -t * 1.4) + 31.0;
  float bubbles = turbulence2(q, vec2(1024.0), 5);
  float detail = fbmValue2(p * mix(8.0, 4.5, t) + t * 4.0 + 5.0, vec2(1024.0), 4);
  float structure = mix(bubbles, detail, 0.4);

  float body = sat(1.0 - r / max(edge, 0.05));
  // Coverage is mostly the convection field, gated by the silhouette, and only
  // weakly radial. This is the difference between a fireball and popcorn: a
  // coverage built primarily on distance from the centre bakes every cell as a
  // smooth sphere, and a dozen smooth spheres never sum to one mass however
  // much they overlap, because each one still has its own visible outline. Led
  // by the noise instead, the dense regions are irregular and off-centre, so
  // overlapping copies interlock.
  float mass = sat(structure * 2.3 - mix(0.62, 1.0, t)) + pow(body, 2.0) * mix(0.6, 0.1, t);
  mass = sat(mass) * smoothstep(0.0, 0.12, body);

  // Heat lives in the burning cells, not at the geometric centre, for the same
  // reason. What is left of the radial term is the mild bias that keeps the
  // middle of the ball hotter than its limb.
  float heat = sat(structure * mix(1.5, 0.72, t) + body * mix(0.42, 0.12, t) - t * 0.26);

  vec3 c = mix(vec3(0.62, 0.11, 0.015), vec3(1.0, 0.44, 0.06), sat(heat * 1.8));
  c = mix(c, vec3(1.0, 0.84, 0.44), sat(heat * heat * 2.1 - 0.42));
  c = mix(c, vec3(1.0, 0.99, 0.95), sat(heat * 3.0 - 1.9));
  // Soot: the limb has already turned to smoke while the middle still burns, and
  // that dark opaque edge is what gives the ball mass.
  float soot = sat((1.0 - heat) * mix(0.75, 1.45, t) - 0.05);
  c = mix(c, vec3(0.075, 0.062, 0.056), sat(soot * 0.95));

  s.color = c;
  s.alpha = sat(mass * mix(1.35, 1.0, t));
}

/** Horizontal streak with a hot core; the quad is stretched along velocity. */
void genSparkStreak(vec2 uv, inout Sprite s) {
  float along = sat(1.0 - abs(uv.x) * 2.0);
  float across = abs(uv.y) * 2.0;
  // Comet profile: bright head at +x, tail thinning toward -x.
  float head = sat(uv.x + 0.5);
  float width = mix(0.22, 1.0, pow(head, 0.7));
  float core = pow(sat(1.0 - across / max(width, 0.02)), 2.6);
  float glow = pow(sat(1.0 - across), 5.0) * 0.35;
  float body = pow(along, 0.55) * core + glow * along;
  s.color = mix(vec3(1.0, 0.52, 0.12), vec3(1.0, 0.97, 0.86), pow(head, 2.0));
  s.alpha = sat(body * 1.4);
}

/**
 * Angular chip of stone, brick or splintered wood.
 *
 * The silhouette has to have straight edges and sharp corners. A chip built as a
 * radius per angular wedge is still a circle with dents in it, and a scatter of
 * near-circles does not read as fragmented stone — it reads as gravel at best
 * and as out-of-focus dots at worst. Intersecting a handful of half-planes gives
 * a convex polygon instead: flat fracture faces, corners, and a different
 * outline for every variant.
 *
 * The face tone is deliberately uniform. Shading a chip from the inside makes it
 * look spherical, and the light on a tumbling fragment belongs to the whole
 * fragment at once; the particle shader supplies that.
 */
void genChip(vec2 uv, float variant, inout Sprite s) {
  float d = -1.0;
  for (int k = 0; k < 5; k++) {
    float fk = float(k);
    // One plane per 72-degree sector keeps the intersection bounded.
    float ang = (fk + hash12(vec2(fk, variant * 3.7))) * 1.2566371;
    vec2 nrm = vec2(cos(ang), sin(ang));
    float dist = 0.17 + 0.21 * hash12(vec2(fk * 2.3, variant * 7.1));
    d = max(d, dot(uv, nrm) - dist);
  }
  float mask = smoothstep(0.012, -0.008, d);
  float face = 0.7 + 0.42 * hash12(vec2(variant * 11.3, 4.1));
  // A bright line just inside the outline: the fresh fracture edge.
  float bevel = smoothstep(0.0, 0.05, -d) * (1.0 - smoothstep(0.02, 0.1, -d));
  s.color = vec3(face + bevel * 0.5);
  s.alpha = mask;
}

/** Leaf blade: a pointed lens with a midrib, curled so one half catches light. */
void genLeaf(vec2 uv, inout Sprite s) {
  vec2 p = uv * 2.0;
  // Two arcs meeting at points. Reads as a leaf even at ten pixels, which an
  // ellipse never does — the points are the whole identity of the shape.
  float span = 1.0 - p.x * p.x;
  float halfWidth = 0.44 * pow(max(span, 0.0), 0.6);
  float across = abs(p.y) / max(halfWidth, 1e-3);
  float mask = smoothstep(1.02, 0.84, across) * step(abs(p.x), 1.0);
  float curl = smoothstep(-0.6, 0.8, p.y);
  float midrib = sat(1.0 - abs(p.y) * 20.0) * mask;
  float veins = sat(1.0 - abs(fract(p.x * 4.5 + p.y * 1.5) - 0.5) * 8.0) * mask * 0.4;
  vec3 c = mix(vec3(0.17, 0.26, 0.08), vec3(0.44, 0.57, 0.21), curl);
  s.color = mix(c, vec3(0.56, 0.63, 0.31), sat(midrib + veins));
  s.alpha = mask;
}

/**
 * Wood splinter: a long sliver with a torn end.
 *
 * Wood does not chip, it splits along the grain, so the fragment it throws is a
 * needle several times longer than it is wide with a ragged break at one end and
 * a point at the other. Reusing the stone chip for it is the difference between
 * splinters and confetti — at the size these fly, the aspect ratio of the
 * silhouette is the only cue the eye gets about what the wall is made of.
 */
void genSplinter(vec2 uv, float variant, inout Sprite s) {
  vec2 p = uv * 2.0;
  // Sheared, so the sliver is not a symmetrical spindle lying on the axis.
  p.y += p.x * (hash12(vec2(variant, 3.1)) - 0.5) * 0.55;
  float h = sat(p.x * 0.5 + 0.5);
  // Widest a third of the way from the torn end, tapering to nothing at the tip.
  float taper = pow(1.0 - h, 0.42) * pow(h, 0.22);
  // Fibres run the length of the sliver, so the edge frays along it rather than
  // wobbling like a coastline.
  float fray = 0.78 + 0.4 * hash12(vec2(floor(p.x * 9.0), variant * 5.3));
  float halfWidth = 0.19 * taper * fray;
  float across = abs(p.y) / max(halfWidth, 1e-4);
  float mask = smoothstep(1.05, 0.7, across) * step(abs(p.x), 1.0);
  // Long grain lines, and a bright torn end where the fibres pulled apart.
  float grain = sat(1.0 - abs(fract(p.y * 26.0 + variant) - 0.5) * 5.0) * 0.22;
  float tear = smoothstep(-1.0, -0.72, p.x) * 0.4;
  s.color = vec3(0.62 + grain + tear);
  s.alpha = mask;
}

/** Grain of sand or grit: barely more than a lit speck with a flat side. */
void genGrit(vec2 uv, inout Sprite s) {
  float d = -1.0;
  for (int k = 0; k < 4; k++) {
    float fk = float(k);
    float ang = (fk + hash12(vec2(fk, 2.9))) * 1.5707963;
    d = max(d, dot(uv, vec2(cos(ang), sin(ang))) - (0.2 + 0.16 * hash12(vec2(fk * 3.1, 6.2))));
  }
  s.color = vec3(0.82);
  s.alpha = smoothstep(0.02, -0.01, d);
}

void genGlassShard(vec2 uv, inout Sprite s) {
  // A long thin sliver rather than a filled triangle: glass breaks into needles,
  // and what is actually visible of one in flight is the lit edge, not the pane
  // between the edges.
  vec2 p = uv * 2.0;
  float d = max(
    max(-p.y * 0.9 - 0.74, p.y * 0.45 + p.x * 1.3 - 0.48),
    p.y * 0.4 - p.x * 1.4 - 0.4);
  float mask = smoothstep(0.03, -0.02, d);
  float edge = smoothstep(0.13, 0.0, abs(d)) * mask;
  s.color = mix(vec3(0.6, 0.72, 0.8), vec3(1.0), edge);
  s.alpha = sat(mask * 0.32 + edge * 0.85);
}

void genDroplet(vec2 uv, inout Sprite s) {
  // Teardrop with the point trailing: the shape a droplet holds while it is
  // still moving. The width profile peaks near the head and leaves the tip on a
  // fractional power, so the tail thickens straight away — drawn as a needle the
  // shape reads as a lollipop rather than as liquid.
  vec2 p = uv * 2.0;
  float h = sat(p.x * 0.5 + 0.5);
  float halfWidth = 1.45 * pow(h, 1.286) * sqrt(1.0 - h);
  float across = abs(p.y) / max(halfWidth, 1e-4);
  float mask = smoothstep(1.04, 0.78, across);
  float spec = pow(sat(1.0 - length(p - vec2(0.3, 0.22)) * 1.9), 4.0);
  s.color = vec3(0.62) + spec * 0.85;
  s.alpha = sat(mask * 0.85 + spec * 0.3);
}

void genGlowSoft(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  s.color = vec3(1.0);
  s.alpha = falloff(r, 3.0) * 0.7 + falloff(r, 1.4) * 0.3;
}

/**
 * Multi-lobed muzzle-flash star.
 *
 * The petals have to dominate the core, not sit inside it. A star whose core
 * glow is wide enough to swallow the lobes bakes down to a soft disc, and a soft
 * disc at the end of a barrel is the single most common way a muzzle flash goes
 * wrong: it reads as a light bulb rather than as burning gas escaping under
 * pressure. So the core here is deliberately tiny and the lobes reach the edge
 * of the cell.
 */
void genFlashStar(vec2 uv, float variant, inout Sprite s) {
  float r = length(uv) * 2.0;
  float petals = 3.0 + floor(hash12(vec2(variant, 1.7)) * 3.0);
  float a = angle01(uv) * petals;
  float i = floor(a);
  float f = fract(a) - 0.5;
  float len = mix(0.78, 1.0, hash12(vec2(i, variant * 5.3)));
  // Wide enough to carry real brightness at the twenty or thirty pixels a flash
  // actually occupies, narrow enough that the lobes stay separate. Hairline
  // petals bake down to nothing once the mip chain gets hold of them.
  float width = mix(0.19, 0.33, hash12(vec2(i, variant * 2.9 + 8.0)));
  float petal = pow(sat(1.0 - abs(f) / width), 1.2) * pow(sat(1.0 - r / len), 0.7);
  // Secondary short petals offset by half a period fill the gaps.
  float a2 = a + 0.5;
  float i2 = floor(a2);
  float f2 = fract(a2) - 0.5;
  float len2 = mix(0.34, 0.66, hash12(vec2(i2, variant * 7.1 + 3.0)));
  float petal2 = pow(sat(1.0 - abs(f2) / 0.2), 1.5) * pow(sat(1.0 - r / len2), 0.8);

  float core = pow(sat(1.0 - r * 2.6), 2.0);
  float body = sat(petal + petal2 * 0.75);
  // Ragged edges: real flashes are torn, not smooth.
  body *= mix(0.55, 1.0, fbmValue2(uv * 11.0 + variant * 13.0, vec2(512.0), 3));
  body = sat(body + core);
  s.color = mix(vec3(1.0, 0.5, 0.1), vec3(1.0, 0.97, 0.86), sat(body * 1.5 + core));
  s.alpha = sat(body * 1.35);
}

void genGasCone(vec2 uv, inout Sprite s) {
  // Cone opening toward +x, used for the expanding muzzle gas.
  float x = uv.x + 0.5;
  float halfWidth = mix(0.02, 0.46, pow(x, 0.75));
  float across = abs(uv.y) / max(halfWidth, 1e-3);
  float body = pow(sat(1.0 - across), 1.6) * sat(1.0 - pow(x, 2.6));
  float turb = fbmValue2(vec2(x * 6.0, uv.y * 8.0) + 4.0, vec2(512.0), 4);
  body *= mix(0.55, 1.15, turb);
  s.color = mix(vec3(1.0, 0.72, 0.34), vec3(0.9, 0.88, 0.84), sat(x * 1.4));
  s.alpha = sat(body * 1.2);
}

void genHotCore(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float core = pow(sat(1.0 - r), 5.0);
  float bloom = falloff(r, 1.3) * 0.45;
  s.color = mix(vec3(1.0, 0.72, 0.3), vec3(1.0), sat(core * 2.0));
  s.alpha = sat(core * 1.6 + bloom);
}

/** Thin bright expanding shock ring with a compressed leading edge. */
void genShockRing(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float outer = ring(r, 0.86, 0.16);
  float inner = ring(r, 0.7, 0.34) * 0.35;
  float wobble = 1.0 + (fbmValue2(vec2(angle01(uv) * 14.0, 2.0), vec2(14.0, 64.0), 3) - 0.5) * 0.22;
  float body = pow(outer * wobble, 2.0) + inner;
  body *= smoothstep(1.02, 0.9, r);
  s.color = mix(vec3(0.86, 0.9, 1.0), vec3(1.0), pow(outer, 3.0));
  s.alpha = sat(body * 1.3);
}

void genLensStreak(vec2 uv, inout Sprite s) {
  float across = abs(uv.y) * 2.0;
  float along = abs(uv.x) * 2.0;
  float body = pow(sat(1.0 - across), 7.0) * pow(sat(1.0 - along), 1.4);
  body += pow(sat(1.0 - length(uv) * 4.0), 3.0) * 0.6;
  s.color = vec3(1.0, 0.94, 0.86);
  s.alpha = sat(body);
}

void genEmber(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float core = pow(sat(1.0 - r * 2.2), 2.0);
  s.color = mix(vec3(1.0, 0.35, 0.05), vec3(1.0, 0.86, 0.5), core);
  s.alpha = sat(core * 1.6 + falloff(r, 4.0) * 0.3);
}

/** Vertical water column, wide base narrowing to a spray crown. */
void genSplashColumn(vec2 uv, inout Sprite s) {
  float h = sat(uv.y + 0.5);
  float halfWidth = mix(0.42, 0.1, pow(h, 0.55)) * (1.0 + h * 0.6);
  float across = abs(uv.x) / max(halfWidth, 1e-3);
  float body = pow(sat(1.0 - across), 1.3);
  float fingers = fbmValue2(vec2(uv.x * 14.0, h * 3.0), vec2(512.0), 3);
  body *= mix(0.4, 1.2, fingers);
  body *= smoothstep(1.0, 0.55, h) + pow(h, 3.0) * fingers * 0.7;
  body *= smoothstep(0.0, 0.12, h);
  s.color = mix(vec3(0.62, 0.72, 0.76), vec3(1.0), pow(sat(body), 2.0));
  s.alpha = sat(body * 0.9);
}

/**
 * Refraction-ish shimmer used for heat haze.
 *
 * With no refraction buffer to sample, hot air can only be faked by lifting the
 * background where it is thinnest, so this keeps the positive lobes of a
 * difference-of-noise field and throws the rest away. Signing the colour instead
 * just bakes half the sprite to black, which under additive blending is a hole.
 */
void genHaze(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float n = fbmValue2(uv * 7.0, vec2(512.0), 4);
  float n2 = fbmValue2(uv * 15.0 + 3.0, vec2(512.0), 3);
  s.color = vec3(1.0);
  s.alpha = sat((n - n2) * 2.2) * 0.55 * falloff(r, 2.0);
}

void genRippleRing(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float a = ring(r, 0.82, 0.1) * 0.9 + ring(r, 0.6, 0.07) * 0.45 + ring(r, 0.42, 0.05) * 0.22;
  a *= smoothstep(1.0, 0.9, r);
  s.color = vec3(0.82, 0.9, 0.94);
  s.alpha = sat(a);
}

/** Dark expanding smoke ring, the ground dust wave of an explosion. */
void genSmokeRing(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float band = ring(r, 0.78, 0.3);
  float lumps = turbulence2(vec2(angle01(uv) * 9.0, r * 4.0), vec2(9.0, 512.0), 4);
  float a = sat(band * mix(0.4, 1.5, lumps) - 0.1);
  a *= smoothstep(1.05, 0.88, r);
  s.color = vec3(0.7 + lumps * 0.3);
  s.alpha = sat(a);
}

void genBurstStar(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float sp = spokes(uv, 16.0, 4.4, 2.4);
  float core = pow(sat(1.0 - r * 1.8), 2.5);
  s.color = mix(vec3(1.0, 0.6, 0.2), vec3(1.0), sat(core * 2.0));
  s.alpha = sat(sp * 0.9 + core * 1.3);
}

// ---------------------------------------------------------------------------
// Decals. Alpha is coverage; colour is a multiplier over the authored tint, so
// a hole is dark in the middle and dusty pale at the rim.
// ---------------------------------------------------------------------------

/**
 * Concrete/brick crater: dark pit, spalled lip, radial hairline cracks and a
 * faint film of dust thrown onto the wall around it.
 *
 * Coverage discipline matters more here than anywhere else in the library. A
 * bullet hole is a few centimetres of hole and a hand's width of barely-there
 * dust; if the halo carries real opacity all the way to the edge of the cell,
 * every hit stamps an opaque disc on the wall.
 */
void genCrateredHole(vec2 uv, float variant, float crackCount, float dustAmount, inout Sprite s) {
  float r = length(uv) * 2.0;
  // The pit is small. What carries the hit at any distance is the pale spall
  // around it, the cracks running out of it and the film of dust thrown onto the
  // wall — a pit sized to most of the cell stamps a plain dark circle, which is
  // exactly what a bullet hole looks like when it has been authored from the
  // outside in rather than from what concrete does when it is struck.
  float pit = blob(uv, 0.062, 5.0, 0.34, 0.028, variant);
  // The spall is a patchy ring of flakes, not a filled disc. Concrete comes off
  // a strike in scales, so the coverage between them has to reach zero: a solid
  // annulus at any real opacity is a pale sticker with a dot in the middle, and
  // that is worse than no decal at all.
  float flakes = fbmValue2(uv * 9.0 + variant * 5.0, vec2(512.0), 4);
  float spall = sat(ring(r, 0.2, 0.18) * sat(flakes * 2.2 - 0.6) * 2.4);
  float cracks = spokes(uv, crackCount, variant * 3.1, 3.0);
  cracks *= mix(0.08, 1.0, fbmValue2(uv * 14.0 + variant, vec2(512.0), 3));
  float film = pow(sat(1.0 - r / 0.98), 2.4);
  film *= mix(0.04, 1.0, fbmValue2(uv * 4.5 + variant * 2.0, vec2(512.0), 4));

  float a = sat(pit * 0.98 + spall * 0.6 + cracks * 0.44 + film * dustAmount * 0.2);
  a *= smoothstep(1.0, 0.78, r);
  s.alpha = a;
  // Everything outside the pit is pulverised material, and pulverised material is
  // paler than the weathered face it came off. The *floor* under the mask is what
  // matters: the faint outer film carries little coverage but it covers a wide
  // disc, and with the mask near zero out there it blends toward the authored
  // hole colour, which is nearly black — so a magazine emptied into one wall
  // accumulates those halos into a black smear. A floor sends them toward the
  // surface's own dust instead, where they belong.
  float pale = max(0.8, sat(spall * 1.6 + film * 1.7));
  s.color = vec3(sat(pale - pit * 3.0 - cracks * 0.6));
}

/** Metal punch: torn bright lip, dark hole, small radial dents. */
void genMetalPunch(vec2 uv, float variant, inout Sprite s) {
  float r = length(uv) * 2.0;
  float hole = blob(uv, 0.055, 5.0, 0.24, 0.025, variant);
  // Sheet metal deforms into a raised crater around the hole and the paint
  // flakes off it, so the torn ring is the loud part — but it is torn, and the
  // gaps in it are what stop the mark reading as a washer glued to the wall.
  float grain = fbmValue2(uv * 15.0 + variant * 5.0, vec2(512.0), 3);
  float lip = sat(ring(r, 0.16, 0.13) * sat(grain * 2.1 - 0.5) * 2.6);
  float tear = spokes(uv, 9.0, variant * 4.7, 2.4) * 0.55;
  float smudge = pow(sat(1.0 - r / 0.85), 2.6) * 0.16;

  float a = sat(hole * 0.98 + lip * 0.72 + tear * 0.45 + smudge);
  a *= smoothstep(1.0, 0.8, r);
  // Bare metal torn open reflects far brighter than the painted surface, and
  // everything that is not the hole itself is either bare metal or fine swarf.
  s.color = vec3(sat(max(0.85, lip * 2.2 + tear * 1.7) - hole * 3.0));
  s.alpha = a;
}

/** Wood: fibrous hole with long splinters running with the grain. */
void genWoodHole(vec2 uv, float variant, inout Sprite s) {
  float r = length(uv) * 2.0;
  float hole = blob(uv, 0.062, 6.0, 0.34, 0.03, variant);
  // Splinters biased to the horizontal, i.e. along the grain, and long: raw
  // torn fibre reaching well out of the hole is what identifies wood.
  vec2 g = uv * vec2(1.0, 2.6);
  float splinter = spokes(g, 13.0, variant * 6.3, 1.6);
  splinter *= mix(0.12, 1.0, fbmValue2(uv * vec2(24.0, 6.0) + variant, vec2(512.0), 3));
  float bruise = pow(sat(1.0 - r / 0.85), 2.4) * 0.2;

  float a = sat(hole * 0.98 + splinter * 0.7 + bruise);
  a *= smoothstep(1.0, 0.8, r);
  // Torn end grain is raw and pale against the finished face; the bruise around
  // it is crushed fibre, halfway between the two.
  s.color = vec3(sat(max(0.55, splinter * 1.9) - hole * 3.0));
  s.alpha = a;
}

/** Glass: bright spiderweb of radial cracks plus concentric fractures. */
void genGlassWeb(vec2 uv, float variant, inout Sprite s) {
  float r = length(uv) * 2.0;
  float radial = spokes(uv, 11.0 + floor(hash12(vec2(variant, 3.0)) * 6.0), variant * 8.1, 5.0);
  // Concentric fracture rings, jittered per angle so they are not perfect circles.
  float a01 = angle01(uv);
  float jitter = (fbmValue2(vec2(a01 * 8.0, variant), vec2(8.0, 64.0), 3) - 0.5) * 0.16;
  float rings = 0.0;
  rings += ring(r + jitter, 0.3, 0.022);
  rings += ring(r + jitter, 0.52, 0.02) * 0.8;
  rings += ring(r + jitter, 0.74, 0.016) * 0.55;
  rings *= sat(0.35 + radial * 2.0);

  float hole = blob(uv, 0.055, 4.0, 0.3, 0.03, variant) * 1.2;
  float frost = blob(uv, 0.13, 6.0, 0.3, 0.12, variant + 5.0) * 0.4;

  float a = sat(radial * 0.9 + rings * 0.95 + hole + frost);
  a *= smoothstep(1.0, 0.82, r);
  // Fractured glass scatters light, so the cracks are the bright part and the
  // pane between them is left alone entirely.
  s.color = vec3(sat(max(0.8, radial * 1.4 + rings * 1.5 + frost * 0.8) - hole * 1.6));
  s.alpha = a;
}

/** Soft divot in loose ground: a shallow dark pit with a thrown-out apron. */
void genDivot(vec2 uv, float variant, float apron, inout Sprite s) {
  float r = length(uv) * 2.0;
  // A round hole punched in dirt is a hole for about a second and a scuff after
  // that, so the pit stays shallow and most of the mark is the grit thrown out
  // of it — which is *paler* than the ground, being dry and freshly turned over.
  //
  // The pit has to be a decent fraction of the mark rather than a dot at the
  // centre of it. A small dark centre inside a pale apron is an annulus, and a
  // bullet leaves no annulus in sand; a dozen of them down a firing lane read as
  // spilled coffee rings, which is worse than having no decal at all.
  float pit = blob(uv, 0.26, 4.0, 0.32, 0.16, variant);
  float grit = fbmValue2(uv * 7.0 + variant * 3.0, vec2(512.0), 4);
  // Thresholded hard so the apron breaks into speckle. A smooth radial falloff
  // is what draws the clean ring; scattered grains are what the ground actually
  // gets, and they also hide the circular footprint of the quad.
  float throwOut = pow(sat(1.0 - r / 0.95), 1.1) * sat(grit * 2.2 - 0.9);
  float a = sat(pit * 0.8 + throwOut * apron * 1.6);
  a *= smoothstep(1.0, 0.5, r);
  // Damp subsoil in the pit, dry thrown-out grit around it.
  s.color = vec3(sat(0.88 - pit * 0.42 + throwOut * 0.22));
  s.alpha = a;
}

/** Blood spatter: central smear with thrown legs ending in droplets. */
void genBloodSplat(vec2 uv, float variant, inout Sprite s) {
  float r = length(uv) * 2.0;
  float core = blob(uv, 0.26, 5.0, 0.34, 0.06, variant);
  float legs = spokes(uv, 14.0, variant * 2.3, 1.4);
  legs = pow(legs, 1.4);
  // Detached droplets around the rim.
  vec3 w = worley2(uv * 7.0 + variant * 11.0, vec2(512.0), 1.0);
  float drops = smoothstep(0.26, 0.1, w.x) * smoothstep(0.95, 0.45, r) * 0.9;
  float a = sat(core * 1.15 + legs * 0.8 + drops);
  a *= smoothstep(1.0, 0.8, r);
  // A thick pool of blood is nearly black; it is the thin films at the edges of
  // the spatter that show any red at all.
  s.color = vec3(sat(1.0 - core * 1.5) * 0.85 + drops * 0.3);
  s.alpha = a;
}

void genBloodPool(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float body = blob(uv, 0.62, 4.0, 0.22, 0.13, 3.0);
  float sheen = pow(sat(1.0 - length(uv * vec2(1.4, 1.0) - vec2(-0.1, 0.12)) * 2.2), 3.0);
  float grain = fbmValue2(uv * 5.0, vec2(512.0), 4);
  float a = sat(body * mix(0.82, 1.0, grain));
  a *= smoothstep(1.0, 0.86, r);
  // Only the specular sheen lifts off the near-black body.
  s.color = vec3(sat(sheen * 1.3 + (1.0 - body) * 0.5) * mix(0.85, 1.05, grain));
  s.alpha = a;
}

/**
 * Explosion crater: charred pit, sooty burn, radial ejecta streaks, pale
 * pulverised apron.
 *
 * Two things have to be true or this stamps a black sticker on the floor, which
 * is the single most conspicuous way a decal system gives itself away. Coverage
 * has to reach zero smoothly and well inside the cell, so the crater ends in a
 * ragged fade rather than a circle. And the paleness mask has to sit up in the
 * middle of its range across most of the burn: it is what blends the authored
 * char colour toward the surface's own pulverised dust, and a mask near zero
 * means the whole disc resolves to the char colour, which by design is nearly
 * black.
 */
void genCrater(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  // Lumpy silhouette. A blast edge is never a circle.
  float edge = blobRadius(uv, 5.0, 0.17, 7.0);
  float soot = fbmValue2(uv * 2.6 + 9.0, vec2(512.0), 4);
  float grain = fbmValue2(uv * 7.0 + 2.0, vec2(512.0), 5);

  float body = sat(1.0 - r / max(edge, 0.05));
  // Soot lies unevenly. Coverage that reaches a flat 1.0 over any real area
  // stamps a uniform dark ellipse, and a uniform dark ellipse reads as a sticker
  // however good its silhouette is — the ground has to show through in patches.
  float burn = pow(body, 1.3) * sat(soot * 2.0 - 0.34);
  float streaks = spokes(uv, 22.0, 5.9, 1.2) * 0.55;
  float pit = blob(uv, 0.17, 5.0, 0.3, 0.15, 2.0);

  float a = sat(burn * 1.5 + streaks * body * 0.7 + pit * 0.7);
  a *= smoothstep(0.99, 0.34, r);
  s.alpha = sat(a * 0.88);

  // Char in the pit, soot through the middle, pulverised surface at the rim.
  float rim = ring(r, 0.55, 0.36);
  s.color = vec3(sat(0.3 + rim * 0.55 + streaks * 0.8 + grain * 0.3 - pit * 1.2 - body * 0.18));
}

void genBloodDrop(vec2 uv, inout Sprite s) {
  vec2 p = uv * vec2(2.3, 1.9);
  float r = length(p);
  float mask = smoothstep(0.95, 0.62, r);
  float spec = pow(sat(1.0 - length(p - vec2(-0.2, 0.24)) * 2.1), 5.0);
  s.color = mix(vec3(0.85), vec3(1.4), spec);
  s.alpha = sat(mask);
}

void genBloodMist(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float n = turbulence2(uv * 5.0 + 9.0, vec2(512.0), 4);
  float a = sat(n * 1.5 - 0.45) * pow(sat(1.25 - r * 1.25), 1.5);
  a += falloff(r, 3.0) * 0.1;
  s.color = vec3(1.0);
  s.alpha = sat(a * 0.85);
}

void genBloodStrand(vec2 uv, inout Sprite s) {
  float across = abs(uv.y + sin(uv.x * 7.0) * 0.06) * 2.0;
  float along = abs(uv.x) * 2.0;
  float w = mix(0.12, 0.5, sat(uv.x + 0.5));
  float body = pow(sat(1.0 - across / w), 1.5) * pow(sat(1.0 - along), 0.8);
  vec3 wo = worley2(vec2(uv.x * 9.0, 0.5), vec2(512.0), 1.0);
  body *= mix(0.55, 1.15, wo.x);
  s.color = vec3(1.0);
  s.alpha = sat(body);
}

void genBloodGout(vec2 uv, inout Sprite s) {
  float r = length(uv) * 2.0;
  float body = blob(uv, 0.7, 4.0, 0.3, 0.16, 11.0);
  float legs = spokes(uv, 8.0, 2.7, 1.2) * 0.6;
  s.color = vec3(1.0);
  s.alpha = sat((body + legs) * smoothstep(1.02, 0.8, r));
}
`;

/**
 * `uv` is centred on the cell and spans [-0.5, 0.5]; `t` is the flipbook phase.
 */
const DISPATCH = /* glsl */ `
Sprite generate(int kind, vec2 uv, float t) {
  Sprite s;
  s.color = vec3(1.0);
  s.alpha = 0.0;

  if (kind == 0) genRadial(uv, s);
  else if (kind == 1) genSmokePuff(uv, t, s);
  else if (kind == 2) genSmokeFlip(uv, t, s);
  else if (kind == 3) genFireFlip(uv, t, s);
  else if (kind == 4) genSparkStreak(uv, s);
  else if (kind == 5) genFireball(uv, t, s);
  else if (kind == 10) genChip(uv, t, s);
  else if (kind == 11) genLeaf(uv, s);
  else if (kind == 12) genGlassShard(uv, s);
  else if (kind == 13) genDroplet(uv, s);
  else if (kind == 14) genSplinter(uv, t, s);
  else if (kind == 15) genSplinter(uv, t, s);
  else if (kind == 16) genChip(uv, t, s);
  else if (kind == 17) genChip(uv, t, s);
  else if (kind == 18) genGrit(uv, s);
  else if (kind == 20) genGlowSoft(uv, s);
  else if (kind == 21) genFlashStar(uv, 1.0, s);
  else if (kind == 22) genFlashStar(uv, 2.0, s);
  else if (kind == 23) genFlashStar(uv, 3.0, s);
  else if (kind == 24) genFlashStar(uv, 4.0, s);
  else if (kind == 25) genFlashStar(uv, 5.0, s);
  else if (kind == 26) genGasCone(uv, s);
  else if (kind == 27) genHotCore(uv, s);
  else if (kind == 28) genShockRing(uv, s);
  else if (kind == 29) genLensStreak(uv, s);
  else if (kind == 30) genEmber(uv, s);
  else if (kind == 31) genSplashColumn(uv, s);
  else if (kind == 32) genHaze(uv, s);
  else if (kind == 33) genRippleRing(uv, s);
  else if (kind == 34) genSmokeRing(uv, s);
  else if (kind == 35) genBurstStar(uv, s);
  else if (kind == 40) genCrateredHole(uv, 1.0, 7.0, 0.9, s);
  else if (kind == 41) genCrateredHole(uv, 2.0, 5.0, 1.0, s);
  else if (kind == 42) genCrateredHole(uv, 3.0, 6.0, 0.7, s);
  else if (kind == 43) genCrateredHole(uv, 4.0, 4.0, 1.25, s);
  else if (kind == 44) genMetalPunch(uv, 1.0, s);
  else if (kind == 45) genMetalPunch(uv, 2.0, s);
  else if (kind == 46) genWoodHole(uv, 1.0, s);
  else if (kind == 47) genWoodHole(uv, 2.0, s);
  else if (kind == 48) genGlassWeb(uv, 1.0, s);
  else if (kind == 49) genGlassWeb(uv, 2.0, s);
  else if (kind == 50) genDivot(uv, 1.0, 0.85, s);
  else if (kind == 51) genDivot(uv, 2.0, 0.6, s);
  else if (kind == 52) genBloodSplat(uv, 1.0, s);
  else if (kind == 53) genBloodSplat(uv, 2.0, s);
  else if (kind == 54) genBloodPool(uv, s);
  else if (kind == 55) genCrater(uv, s);
  else if (kind == 60) genBloodDrop(uv, s);
  else if (kind == 61) genBloodMist(uv, s);
  else if (kind == 62) genBloodStrand(uv, s);
  else if (kind == 63) genBloodGout(uv, s);
  return s;
}
`;

export const FX_TEXTURE_FRAGMENT = /* glsl */ `
precision highp float;

in vec2 vUv;
layout(location = 0) out vec4 outColor;

uniform int uKind;
uniform int uMode;
uniform vec2 uGrid;
uniform float uEdgeFade;

${NOISE_GLSL}
${HELPERS}
${GENERATORS}
${DISPATCH}

void main() {
  vec2 cellUv = vUv;
  int kind = uKind;
  float t = 0.0;

  if (uMode != 0) {
    vec2 g = vUv * uGrid;
    vec2 cell = floor(g);
    cellUv = fract(g);
    float index = cell.y * uGrid.x + cell.x;
    float total = max(uGrid.x * uGrid.y, 1.0);
    if (uMode == 1) {
      kind = uKind + int(index + 0.5);
      t = index;
    } else if (uMode == 3) {
      t = index;
    } else {
      // Frame order matches the linear cell index the particle shader computes,
      // so cell 0 is bottom-left and frames advance along +u then +v.
      t = total > 1.0 ? index / (total - 1.0) : 0.0;
    }
  }

  Sprite s = generate(kind, cellUv - 0.5, t);

  // Every cell must reach zero coverage at its border or bilinear filtering
  // and the mip chain will bleed neighbours into each other.
  vec2 d = min(cellUv, 1.0 - cellUv);
  float border = smoothstep(0.0, max(uEdgeFade, 1e-4), min(d.x, d.y));
  outColor = vec4(s.color, sat(s.alpha) * border);
}
`;
