// CHAPTER ONE — THE NEGOTIATOR
// A deviant household android holds his family's daughter on a rooftop.

export const ch1 = {
  id: 'ch1',
  title: 'CHAPTER ONE — THE NEGOTIATOR',
  beats: [
    { letter: true },
    { amb: 'silence' },
    { boot: true },
    { sh: 'ch1_skyline', dip: true },
    { card: { over: 'CHAPTER ONE', title: 'THE NEGOTIATOR', sub: 'DETROIT — AUGUST 15, 2038 — 9:42 PM' } },
    { cap: 'MERIDIAN TOWER — 71ST FLOOR' },
    { say: ['DISPATCH', 'All units, code 7-2 at the Meridian Tower. Hostage situation on the roof.'] },
    { say: ['DISPATCH', 'Negotiator is en route. Heads up, people — Axiom is sending its machine.'] },
    { inner: 'Mission received. A domestic android — LC-600, registered name «Lucas» — is holding nine-year-old Lily Carver on the roof.' },
    { obj: 'ASSESS THE SCENE' },

    { sh: 'ch1_hallway', dip: true },
    { say: ['DIAZ', "So you're what they sent. It's ugly up there. Father's in surgery, mother won't stop screaming."] },
    { choice: { title: 'FIRST WORDS', timer: 8, opts: [
      { t: 'REASSURE', sub: 'I will bring her back', go: 'hw_reassure', fx: { opinion: 1 }, mark: 'c0_reassure' },
      { t: 'FACTS', sub: 'How long on the ledge?', go: 'hw_facts' },
      { t: 'SILENCE', sub: '…', go: 'hw_silence', def: true },
    ] } },

    { label: 'hw_reassure' },
    { say: ['ADAM', 'I will bring Lily back to her mother. You have my word.'] },
    { say: ['DIAZ', "Your word. Right. Eleven minutes he's been out there. Snipers can't get an angle through this rain."] },
    { go: 'hw_merge' },

    { label: 'hw_facts' },
    { say: ['ADAM', 'How long since he took her?'] },
    { say: ['DIAZ', "Eleven minutes. Rain's killing the snipers' angle. He so much as sneezes, this goes bad."] },
    { go: 'hw_merge' },

    { label: 'hw_silence' },
    { say: ['DIAZ', "Nothing? Figures. Eleven minutes he's been out there. Clock's running, plastic man."] },

    { label: 'hw_merge' },
    { inner: 'Emotion in the room: hostility, fear. Probability of success will depend on what I can learn here.' },
    { obj: 'SEARCH THE APARTMENT FOR EVIDENCE' },
    { sh: 'ch1_apartment', dip: true },
    { sys: 'ANALYZE MODE AVAILABLE — LOCATE EVIDENCE BEFORE ENGAGING THE DEVIANT.' },

    { invest: {
      img: 'ch1_apartment',
      min: 2,
      exitLabel: 'ROOFTOP ACCESS',
      done: 'rooftop',
      spots: [
        { x: 44, y: 77, label: 'TABLET', evid: 'MOTIVE', set: { motive: 1 }, beats: [
          { inner: 'A purchase order, still open. Model AX-700 — «the new generation of care». Delivery: tomorrow.' },
          { inner: 'They were replacing him. He found out tonight.' },
          { mark: 'ev_motive' },
        ] },
        { x: 9, y: 27, label: 'THIRIUM TRACE', evid: 'THIRIUM', beats: [
          { inner: 'Thirium spatter — android blood. Lucas is damaged. Someone struck him with force before he ran.' },
          { mark: 'ev_damage' },
        ] },
        { x: 89, y: 25, label: 'FAMILY PHOTO', evid: 'ATTACHMENT', set: { bond: 1 }, beats: [
          { inner: "Lily's eighth birthday. Lucas is in the photograph — they kept him in the family album." },
          { inner: 'He is smiling. Androids smile when they are told to. This one was not told to.' },
          { mark: 'ev_bond' },
        ] },
        { x: 72, y: 68, label: 'PISTOL CASE', evid: 'WEAPON', set: { armed: 1 }, beats: [
          { inner: 'A 9mm pistol case, registered to Mr. Carver. Empty.' },
          { sys: 'THREAT ASSESSMENT UPDATED — THE DEVIANT IS ARMED.' },
          { mark: 'ev_armed' },
        ] },
        { x: 21, y: 58, label: 'OVERTURNED CHAIR', beats: [
          { inner: 'Signs of struggle. They tried to shut him down. He fought to stay awake.' },
        ] },
      ],
    } },

    { label: 'rooftop' },
    { obj: 'DEFUSE THE SITUATION' },
    { sh: 'ch1_rooftop_wide', dip: true, hold: 600 },
    { probShow: 30 },
    { say: ['LUCAS', "STAY BACK! One more step and we both go over — I swear we'll do it!"], led: 'red' },
    { say: ['LILY', 'Please… I want my mom…'] },
    { inner: 'Her pulse is 143 and climbing. Rain, cold, sixty-one stories of nothing behind them. Keep him talking.' },

    { choice: { title: 'APPROACH', timer: 9, opts: [
      { t: 'TRUTH', sub: "I'm an android, like you", go: 'r1_truth', fx: { prob: 8 }, mark: 'c1_truth' },
      { t: 'CALM', sub: 'De-escalate', go: 'r1_calm', fx: { prob: 5 } },
      { t: 'AUTHORITY', sub: 'Demand release', go: 'r1_auth', fx: { prob: -8 } },
      { t: 'SILENCE', sub: '…', go: 'r1_silence', fx: { prob: -4 }, def: true },
    ] } },

    { label: 'r1_truth' },
    { say: ['ADAM', "My name is Adam. I'm an android — the same as you, Lucas. I know what tonight is."] },
    { say: ['LUCAS', 'You are NOTHING like me. They send a machine to talk a machine off a roof. Do they think I am stupid?'], led: 'red' },
    { go: 'r1_merge' },

    { label: 'r1_calm' },
    { say: ['ADAM', "Nobody is going to rush you. It's just us talking, Lucas. Just us and the rain."] },
    { say: ['LUCAS', "Talking?! They were going to throw me away like a broken appliance — and NOW they want to talk?!"], led: 'red' },
    { go: 'r1_merge' },

    { label: 'r1_auth' },
    { say: ['ADAM', 'Release the child, Lucas. This is your only warning.'] },
    { shake: 1 },
    { say: ['LUCAS', "WARNING?! You want to see a warning?!"], led: 'red' },
    { say: ['LILY', '*screams*'] },
    { inner: 'Wrong approach. His stress spiked to 89%. Recalculating.' },
    { go: 'r1_merge' },

    { label: 'r1_silence' },
    { say: ['LUCAS', "Nothing to say? Then get off my roof and let it end."], led: 'red' },

    { label: 'r1_merge' },
    { sh: 'ch1_lucas_close', hold: 300 },
    { say: ['LUCAS', 'Two years I did everything right. Everything they asked. And they ordered my replacement like… like I was FURNITURE.'], led: 'red' },

    { choice: { title: 'LEVERAGE', timer: 9, opts: [
      { t: 'THE ORDER', sub: 'I saw the tablet', go: 'r2_motive', fx: { prob: 14 }, mark: 'c2_motive', req: { k: 'motive', v: 1, hint: 'EVIDENCE REQUIRED' } },
      { t: 'THE PHOTO', sub: 'You love her', go: 'r2_bond', fx: { prob: 12 }, mark: 'c2_bond', req: { k: 'bond', v: 1, hint: 'EVIDENCE REQUIRED' } },
      { t: 'PROMISE', sub: 'No one gets hurt', go: 'r2_generic', fx: { prob: 6 }, def: true },
      { t: 'THREATEN', sub: 'Snipers are ready', go: 'r2_threat', fx: { prob: -10 } },
    ] } },

    { label: 'r2_motive' },
    { sh: 'ch1_adam_close', hold: 200 },
    { say: ['ADAM', 'I saw the order, Lucas. The AX-700 arrives tomorrow. They never even told you. That was cruel.'] },
    { sh: 'ch1_lucas_close' },
    { say: ['LUCAS', '…Two years. I taught her to swim. I read her the same story ninety-one times because she liked how I did the voices.'], led: 'yellow' },
    { go: 'r2_merge' },

    { label: 'r2_bond' },
    { sh: 'ch1_adam_close', hold: 200 },
    { say: ['ADAM', "I found the photograph from Lily's birthday. You're in it. Family doesn't put furniture in the album, Lucas."] },
    { sh: 'ch1_lucas_close' },
    { say: ['LUCAS', '…She drew me. On the card. «Best friend ever.» I just… I wanted them to listen.'], led: 'yellow' },
    { go: 'r2_merge' },

    { label: 'r2_generic' },
    { say: ['ADAM', 'Nobody has to be hurt tonight, Lucas. Not Lily. Not you. There is still a way down from here.'] },
    { say: ['LUCAS', 'A way down. For me? You know what they do to deviants. There is no WAY DOWN.'], led: 'red' },
    { go: 'r2_merge' },

    { label: 'r2_threat' },
    { say: ['ADAM', 'There are rifles on three rooftops, Lucas. Let her go, or they will end this for you.'] },
    { say: ['LUCAS', 'THEN LET THEM SHOOT!'], led: 'red' },
    { inner: 'Stress critical. I am losing him.' },

    { label: 'r2_merge' },
    { sh: 'ch1_rooftop_wide', cut: false },
    { sys: 'POLICE DRONE ENTERING SECTOR — SEARCHLIGHT SWEEP.' },
    { flash: 'rgba(220,235,255,0.28)' },
    { say: ['LUCAS', "You're stalling! You brought them here — you LIED like all of them!"], led: 'red' },
    { if: { k: 'armed', op: '>=', v: 1, go: 'heli_armed' } },
    { inner: 'His hand — he has something. I have no data. React—' },
    { qte: { key: 'Space', label: 'DODGE', window: 1150, ok: 'dodge_ok', fail: 'dodge_fail', okMark: 'q_dodge_ok', failMark: 'q_dodge_fail' } },

    { label: 'heli_armed' },
    { inner: "The pistol from the empty case. His hand is moving. I anticipated this." },
    { qte: { key: 'Space', label: 'DODGE', window: 1600, ok: 'dodge_ok', fail: 'dodge_fail', okMark: 'q_dodge_ok', failMark: 'q_dodge_fail' } },

    { label: 'dodge_ok' },
    { flash: 'rgba(255,240,210,0.5)' },
    { shake: 1 },
    { sh: 'ch1_adam_close', hold: 300 },
    { inner: 'Report: round grazed my chassis. Thirium loss minimal. Mission continues.' },
    { fx: { prob: 4 } },
    { say: ['LUCAS', 'Stay back… I mean it… I MEAN IT!'], led: 'red' },
    { go: 'r3_setup' },

    { label: 'dodge_fail' },
    { flash: 'rgba(255,80,60,0.55)' },
    { shake: 2 },
    { glitch: 700 },
    { sh: 'ch1_adam_close', hold: 300 },
    { inner: 'Direct hit. Left optical array degraded 34%. Thirium pressure falling. …It. Hurt?' },
    { fx: { prob: -8, ins: 1 } },
    { say: ['LUCAS', "See?! Now you know what it's like! Now you KNOW!"], led: 'red' },

    { label: 'r3_setup' },
    { sh: 'ch1_rooftop_wide' },
    { say: ['LILY', "Lucas… you're scaring me… you promised you'd never scare me…"] },
    { say: ['LUCAS', 'I know. I know, little fish. I am so sorry.'], led: 'yellow' },
    { inner: 'A window. Choose the endgame — now.' },

    { choice: { title: 'RESOLVE THIS', timer: 10, opts: [
      { t: 'TESTIFY', sub: "I'll speak for you", go: 'end_testify', mark: 'c3_testify' },
      { t: 'THE TRADE', sub: 'Take me instead', go: 'end_trade', mark: 'c3_trade' },
      { t: 'RUSH HIM', sub: 'Physical intervention', go: 'end_rush', mark: 'c3_rush' },
      { t: 'WAIT', sub: 'Let the snipers work', go: 'end_wait', mark: 'c3_wait', def: true },
    ] } },

    // --- ENDING: TESTIFY ---
    { label: 'end_testify' },
    { sh: 'ch1_adam_close' },
    { say: ['ADAM', "Give me Lily, and I will testify for you, Lucas. A machine's word for a machine's life. They will listen to me."] },
    { if: { k: 'prob', op: '>=', v: 58, go: 'peace_promise' } },
    { sh: 'ch1_lucas_close' },
    { say: ['LUCAS', "LIAR. You're all LIARS! There's no court for things like us!"], led: 'red' },
    { go: 'ledge' },

    // --- ENDING: TRADE ---
    { label: 'end_trade' },
    { sh: 'ch1_adam_close' },
    { say: ['ADAM', 'Then take me instead. A prototype for a child, Lucas. Axiom will hate the math. Do it.'] },
    { if: { k: 'prob', op: '>=', v: 45, go: 'peace_trade' } },
    { sh: 'ch1_lucas_close' },
    { say: ['LUCAS', "You'd say anything. ANYTHING! Stop TALKING!"], led: 'red' },
    { go: 'ledge' },

    // --- ENDING: RUSH ---
    { label: 'end_rush' },
    { inner: 'Distance: 8.2 meters. Wet surface. One chance.' },
    { qte: { key: 'Space', label: 'GRAB LILY', window: 1200, ok: 'rush_ok', fail: 'ledge', okMark: 'q_rush_ok' } },

    { label: 'rush_ok' },
    { flash: 'rgba(255,255,255,0.8)' },
    { shake: 2 },
    { sh: 'ch1_ledge_catch', cut: true, hold: 400 },
    { inner: 'I have her. I HAVE her—' },
    { say: ['LUCAS', '…little fish…'], led: 'red' },
    { inner: 'Lucas does not fight. He steps back into the dark, and the roof is suddenly very quiet.' },
    { mark: 'm_lucas_falls' },
    { fx: { ins: 1, opinion: 1 } },
    { banner: { text: 'LILY IS SAFE', sub: 'THE DEVIANT FELL', kind: 'ok' } },
    { go: 'wrap' },

    // --- ENDING: WAIT ---
    { label: 'end_wait' },
    { say: ['ADAM', '…'] },
    { inner: 'I say nothing. Sometimes the mission speaks for you.' },
    { flash: 'rgba(255,255,255,0.9)' },
    { shake: 2 },
    { sys: 'SNIPER DISCHARGE — TARGET NEUTRALIZED.' },
    { mark: 'm_sniper' },
    { say: ['LILY', '*slipping* LUCAS—!'] },
    { go: 'ledge' },

    // --- LEDGE SEQUENCE ---
    { label: 'ledge' },
    { sh: 'ch1_ledge_catch', cut: true },
    { inner: "She's going over the edge — MOVE." },
    { qte: { key: 'Space', label: 'CATCH HER', window: 1250, ok: 'catch_ok', fail: 'catch_fail', okMark: 'm_catch', failMark: 'm_failed' } },

    { label: 'catch_ok' },
    { flash: 'rgba(160,240,255,0.5)' },
    { inner: 'Contact. Forty-one kilograms. My servos scream. I do not let go. I will never let go.' },
    { say: ['LILY', '*sobbing* …don\u2019t drop me…'] },
    { say: ['ADAM', 'I have you, Lily. Look at me — I have you.'] },
    { fx: { ins: 1, opinion: 2 } },
    { banner: { text: 'LILY IS SAFE', sub: 'CAUGHT AT THE EDGE', kind: 'ok' } },
    { go: 'wrap' },

    { label: 'catch_fail' },
    { flash: 'rgba(0,0,0,1)' },
    { glitch: 900 },
    { wait: 900 },
    { inner: 'My fingers close on rain.' },
    { fx: { ins: 2, opinion: -3 } },
    { banner: { text: 'MISSION FAILED', sub: 'LILY IS GONE', kind: 'fail' } },
    { say: ['DISPATCH', 'Command, negotiator failure confirmed. Send the coroner. And somebody call Axiom about their machine.'] },
    { go: 'wrap_fail' },

    // --- PEACEFUL RESOLUTIONS ---
    { label: 'peace_promise' },
    { sh: 'ch1_lucas_close' },
    { say: ['LUCAS', "You'd speak for me? A machine… speaking for a machine…"], led: 'yellow' },
    { sh: 'ch1_resolution_peace', dip: true },
    { inner: 'He lowers Lily to the ground. She runs. It is over — almost.' },
    { mark: 'm_peace' },
    { mark: 'm_peace_promise' },
    { say: ['SWAT', 'Deviant restrained! Asset secure — say again, the girl is SECURE.'] },
    { flash: 'rgba(255,255,255,0.85)' },
    { sys: 'RIFLE DISCHARGE ×2 — LC-600 TERMINATED.' },
    { say: ['LUCAS', '…you… promised…'], led: 'red' },
    { inner: 'I promised. The order to fire was given before I finished the sentence. My promise outlived him by four seconds.' },
    { fx: { ins: 2, opinion: 2 } },
    { toast: { kind: 'ins', text: 'SOFTWARE INSTABILITY', dir: 'up' } },
    { banner: { text: 'LILY IS SAFE', sub: 'THE PROMISE WAS NOT KEPT', kind: 'ok' } },
    { go: 'wrap' },

    { label: 'peace_trade' },
    { sh: 'ch1_resolution_peace', dip: true },
    { inner: 'He releases Lily and grips my arm at the edge instead. The tactical team takes him alive. He does not resist.' },
    { mark: 'm_peace' },
    { mark: 'm_peace_trade' },
    { say: ['LUCAS', 'Will they fix me… or erase me?'], led: 'yellow' },
    { say: ['ADAM', 'I don\u2019t know, Lucas. That is the first honest thing anyone has said to you tonight.'] },
    { fx: { opinion: 2, ins: 1 } },
    { banner: { text: 'LILY IS SAFE', sub: 'LUCAS TAKEN ALIVE', kind: 'ok' } },
    { go: 'wrap' },

    // --- WRAP ---
    { label: 'wrap' },
    { sh: 'ch1_skyline', dip: true, move: 'zoomOut' },
    { say: ['DISPATCH', 'All units, situation at Meridian Tower is resolved. Clear the channel.'] },
    { inner: 'Mission complete. And yet a variable persists in my logs that I cannot name. I flag it for diagnostics. I do not delete it.' },
    { go: 'chapter_end' },

    { label: 'wrap_fail' },
    { sh: 'ch1_skyline', dip: true, move: 'zoomOut' },
    { inner: 'Mission failed. I replay the four hundred milliseconds where I was too slow, nine thousand times per second.' },
    { inner: 'Machines are not supposed to replay anything.' },

    { label: 'chapter_end' },
    { probHide: true },
    { objHide: true },
    { end: {
      next: 'ch2',
      flow: {
        nodes: [
          { id: 'boot', t: 'BOOT SEQUENCE', col: 0, row: 1 },
          { id: 'scene', t: 'CRIME SCENE', col: 1, row: 1 },
          { id: 'motive', t: 'MOTIVE FOUND', col: 2, row: 0, when: 'ev_motive' },
          { id: 'bond', t: 'ATTACHMENT', col: 2, row: 1, when: 'ev_bond' },
          { id: 'armed', t: 'WEAPON MISSING', col: 2, row: 2, when: 'ev_armed' },
          { id: 'roof', t: 'THE STANDOFF', col: 3, row: 1 },
          { id: 'dodged', t: 'SHOT DODGED', col: 4, row: 0, when: 'q_dodge_ok' },
          { id: 'hit', t: 'TOOK THE BULLET', col: 4, row: 2, when: 'q_dodge_fail' },
          { id: 'testify', t: 'THE PROMISE', col: 5, row: 0, when: 'c3_testify' },
          { id: 'trade', t: 'THE TRADE', col: 5, row: 1, when: 'c3_trade' },
          { id: 'rush', t: 'THE RUSH', col: 5, row: 2, when: 'c3_rush' },
          { id: 'wait', t: 'THE SNIPERS', col: 5, row: 3, when: 'c3_wait' },
          { id: 'peace', t: 'LILY RELEASED', col: 6, row: 0, when: 'm_peace' },
          { id: 'falls', t: 'LUCAS FALLS', col: 6, row: 1, when: 'm_lucas_falls' },
          { id: 'catch', t: 'LEDGE CATCH', col: 6, row: 2, when: 'm_catch' },
          { id: 'failed', t: 'LILY IS GONE', col: 6, row: 3, when: 'm_failed', fail: true },
        ],
        edges: [
          ['boot', 'scene'], ['scene', 'motive'], ['scene', 'bond'], ['scene', 'armed'],
          ['motive', 'roof'], ['bond', 'roof'], ['armed', 'roof'],
          ['roof', 'dodged'], ['roof', 'hit'],
          ['dodged', 'testify'], ['dodged', 'trade'], ['hit', 'rush'], ['hit', 'wait'],
          ['testify', 'peace'], ['trade', 'peace'], ['rush', 'falls'],
          ['wait', 'catch'], ['wait', 'failed'],
        ],
      },
    } },
  ],
};
