"""Non-isomorphic free trees and forests -- audit enumeration.

Method (deliberately different from the WROM free-tree generator used by the
main library):

1. *All* rooted trees on ``n`` vertices are generated as canonical level
   sequences with the successor algorithm of Beyer and Hedetniemi,
   "Constant time generation of rooted trees", SIAM J. Comput. 9 (1980).
   The root has level 1, the first sequence is the path ``1, 2, ..., n`` and
   the last one is the star ``1, 2, 2, ..., 2``.  Rooted-tree counts are
   checked against OEIS A000081.
2. A rooted tree is kept only if its root is a centre of the underlying free
   tree (cheap one-pass eccentricity/diameter test on the parent array).
3. The surviving trees are de-duplicated with an AHU canonical form of the
   free tree rooted at its centre(s) (leaf stripping, computed independently
   of step 2, which must confirm the root is a centre).  Every free tree
   appears at least once in step 2 (each free tree has a centre, and the
   rooted tree "T rooted at a centre" is generated by step 1), and the
   canonical form identifies isomorphic copies, so the result is exactly one
   representative per isomorphism class.  Counts are checked against OEIS
   A000055.
4. Forests of order ``n`` are multisets of trees: for every integer partition
   of ``n`` and every part size ``s`` with multiplicity ``k`` choose a
   ``k``-multiset of the free trees of order ``s``.  Counts are checked
   against OEIS A005195.

Representatives are parent arrays with ``parent[0] == -1`` and
``parent[v] < v`` (preorder), rooted at a centre.  This module imports
nothing from ``erdos993lib``.
"""

from __future__ import annotations

from itertools import combinations_with_replacement, product
from typing import Dict, Iterator, List, Optional, Sequence, Tuple

# OEIS A000055 -- free trees with n unlabelled nodes, n = 0..18 (from the task statement).
A000055 = [1, 1, 1, 1, 2, 3, 6, 11, 23, 47, 106, 235, 551, 1301, 3159, 7741, 19320, 48629, 123867]

# OEIS A005195 -- forests with n unlabelled nodes, n = 0..17 (from the task statement).
A005195 = [1, 1, 2, 3, 6, 10, 20, 37, 76, 153, 329, 710, 1601, 3658, 8599, 20514, 49905, 122963]

# OEIS A000081 -- rooted trees with n unlabelled nodes, n = 0..19.
A000081 = [
    0, 1, 1, 2, 4, 9, 20, 48, 115, 286, 719, 1842, 4766, 12486, 32973, 87811,
    235381, 634847, 1721159, 4688676,
]

Parent = List[int]
Edge = Tuple[int, int]


# --------------------------------------------------------------------------- #
# 1. rooted trees: Beyer-Hedetniemi
# --------------------------------------------------------------------------- #
def beyer_hedetniemi_successor(seq: Sequence[int]) -> Optional[List[int]]:
    """Next canonical level sequence after ``seq`` (root level 1), or ``None``.

    Let ``p`` be the last position with level ``> 2`` and ``q`` the parent of
    ``p`` (last position before ``p`` with level ``seq[p] - 1``).  The
    successor keeps ``seq[:p]`` and fills the rest by repeating the block
    starting at ``q`` periodically: ``s[i] = s[i - (p - q)]`` for ``i >= p``.
    """
    n = len(seq)
    p = n - 1
    while p >= 0 and seq[p] <= 2:
        p -= 1
    if p <= 0:
        return None
    q = p - 1
    target = seq[p] - 1
    while seq[q] != target:
        q -= 1
    d = p - q
    nxt = list(seq[:p])
    for i in range(p, n):
        nxt.append(nxt[i - d])
    return nxt


def rooted_level_sequences(n: int) -> Iterator[List[int]]:
    """All rooted trees on ``n >= 1`` vertices as level sequences (root level 1).

    The yielded lists must not be mutated by the consumer.
    """
    if n < 1:
        return
    seq: Optional[List[int]] = list(range(1, n + 1))
    while seq is not None:
        yield seq
        seq = beyer_hedetniemi_successor(seq)


def level_sequence_to_parent(seq: Sequence[int]) -> Parent:
    """Parent array: the parent of ``i`` is the latest ``j < i`` on the level above."""
    n = len(seq)
    parent = [-1] * n
    latest_at_level = [0] * (n + 2)
    for i in range(1, n):
        lev = seq[i]
        parent[i] = latest_at_level[lev - 1]
        latest_at_level[lev] = i
    return parent


def count_rooted_trees(n: int) -> int:
    return sum(1 for _ in rooted_level_sequences(n))


# --------------------------------------------------------------------------- #
# 2. cheap centre test on the parent array
# --------------------------------------------------------------------------- #
def root_is_centre(parent: Sequence[int]) -> Tuple[bool, int]:
    """``(root is a centre, diameter)`` in one backwards pass.

    ``top1[v] >= top2[v]`` are the two largest values of ``1 + height(child)``
    over the children of ``v`` (0 if absent); the longest path with topmost
    vertex ``v`` has length ``top1[v] + top2[v]``, the root's eccentricity is
    ``top1[root]`` (the tree's height), and a vertex is a centre iff its
    eccentricity equals the radius ``ceil(diameter / 2)``.
    """
    n = len(parent)
    top1 = [0] * n
    top2 = [0] * n
    diameter = 0
    for i in range(n - 1, 0, -1):
        h = top1[i]
        if h + top2[i] > diameter:
            diameter = h + top2[i]
        p = parent[i]
        h += 1
        if h > top1[p]:
            top2[p] = top1[p]
            top1[p] = h
        elif h > top2[p]:
            top2[p] = h
    if top1[0] + top2[0] > diameter:
        diameter = top1[0] + top2[0]
    return top1[0] == (diameter + 1) // 2, diameter


# --------------------------------------------------------------------------- #
# 3. canonical forms
# --------------------------------------------------------------------------- #
def parent_to_adjacency(parent: Sequence[int]) -> List[List[int]]:
    n = len(parent)
    adj: List[List[int]] = [[] for _ in range(n)]
    for v in range(n):
        p = parent[v]
        if p >= 0:
            adj[v].append(p)
            adj[p].append(v)
    return adj


def edges_to_adjacency(n: int, edges: Sequence[Edge]) -> List[List[int]]:
    adj: List[List[int]] = [[] for _ in range(n)]
    for u, v in edges:
        adj[u].append(v)
        adj[v].append(u)
    return adj


def tree_centres(adj: Sequence[Sequence[int]]) -> List[int]:
    """Centre(s) of a tree by repeatedly stripping all current leaves."""
    n = len(adj)
    if n <= 2:
        return list(range(n))
    degree = [len(a) for a in adj]
    layer = [v for v in range(n) if degree[v] == 1]
    alive = n
    while alive > 2:
        # with more than two vertices alive no two current leaves are adjacent,
        # so each leaf has exactly one alive neighbour, which has degree >= 2
        alive -= len(layer)
        nxt: List[int] = []
        for v in layer:
            degree[v] = 0
            for w in adj[v]:
                if degree[w] > 1:
                    degree[w] -= 1
                    if degree[w] == 1:
                        nxt.append(w)
        layer = nxt
    return sorted(layer)


def rooted_canonical_form(adj: Sequence[Sequence[int]], root: int) -> str:
    """AHU code: ``'1' + concat(sorted(child codes)) + '0'`` (balanced bracket word).

    Two rooted trees are isomorphic iff their codes coincide: the code of a
    vertex is uniquely parsed into the multiset of child codes.
    """
    n = len(adj)
    par = [-2] * n
    par[root] = -1
    order: List[int] = []
    stack = [root]
    while stack:
        v = stack.pop()
        order.append(v)
        for w in adj[v]:
            if w != par[v]:
                par[w] = v
                stack.append(w)
    child_codes: List[List[str]] = [[] for _ in range(n)]
    code = [""] * n
    for v in reversed(order):
        kids = child_codes[v]
        kids.sort()
        c = "1" + "".join(kids) + "0"
        code[v] = c
        if par[v] >= 0:
            child_codes[par[v]].append(c)
    return code[root]


def free_canonical_form_adj(adj: Sequence[Sequence[int]]) -> Tuple[str, List[int]]:
    """Canonical code of a free tree = min over its centre(s) of the rooted code."""
    centres = tree_centres(adj)
    if not centres:
        return "", []
    return min(rooted_canonical_form(adj, c) for c in centres), centres


def free_canonical_form(parent: Sequence[int]) -> str:
    return free_canonical_form_adj(parent_to_adjacency(parent))[0]


def free_canonical_form_edges(n: int, edges: Sequence[Edge]) -> str:
    return free_canonical_form_adj(edges_to_adjacency(n, edges))[0]


# --------------------------------------------------------------------------- #
# free trees
# --------------------------------------------------------------------------- #
def free_trees(n: int) -> Iterator[Parent]:
    """One parent array per isomorphism class of free trees on ``n`` vertices.

    ``n == 0`` yields the empty tree once (OEIS convention A000055(0) = 1).
    """
    if n < 0:
        raise ValueError("order must be >= 0")
    if n == 0:
        yield []
        return
    seen: Dict[str, None] = {}
    for seq in rooted_level_sequences(n):
        parent = level_sequence_to_parent(seq)
        centre_root, _diam = root_is_centre(parent)
        if not centre_root:
            continue
        code, centres = free_canonical_form_adj(parent_to_adjacency(parent))
        if 0 not in centres:
            raise AssertionError("centre test disagrees with leaf stripping for %r" % (seq,))
        if code in seen:
            continue
        seen[code] = None
        yield parent


def free_tree_list(n: int) -> List[Parent]:
    return list(free_trees(n))


def count_free_trees(n: int) -> int:
    return sum(1 for _ in free_trees(n))


def parent_to_edges(parent: Sequence[int]) -> List[Edge]:
    return [(parent[v], v) for v in range(len(parent)) if parent[v] >= 0]


# --------------------------------------------------------------------------- #
# 4. forests as multisets of trees
# --------------------------------------------------------------------------- #
def partitions(n: int, largest: Optional[int] = None) -> Iterator[List[int]]:
    """Integer partitions of ``n`` as non-increasing lists (``[]`` for ``n == 0``)."""
    if largest is None or largest > n:
        largest = n
    if n == 0:
        yield []
        return
    for first in range(largest, 0, -1):
        for rest in partitions(n - first, first):
            yield [first] + rest


ForestSpec = Tuple[Tuple[int, ...], Tuple[int, ...]]


def forest_specs(n: int, tree_counts: Sequence[int]) -> Iterator[ForestSpec]:
    """``(component_orders, tree_indices)`` for every forest of order ``n``.

    ``tree_counts[s]`` is the number of free trees of order ``s``; indices refer
    to :func:`free_trees` order.  Component orders are non-increasing and,
    within one order, tree indices are non-decreasing, so every forest is
    produced exactly once.
    """
    for parts in partitions(n):
        multiplicity: Dict[int, int] = {}
        for s in parts:
            multiplicity[s] = multiplicity.get(s, 0) + 1
        sizes = sorted(multiplicity, reverse=True)
        pools = [
            list(combinations_with_replacement(range(tree_counts[s]), multiplicity[s]))
            for s in sizes
        ]
        for choice in product(*pools):
            orders: List[int] = []
            idxs: List[int] = []
            for s, combo in zip(sizes, choice):
                for t in combo:
                    orders.append(s)
                    idxs.append(t)
            yield tuple(orders), tuple(idxs)


def forest_graph(spec: ForestSpec, tree_cache: Dict[int, List[Parent]]) -> Tuple[int, List[Edge]]:
    """Labelled graph ``(order, edges)`` of a forest spec (components relabelled in blocks)."""
    orders, idxs = spec
    edges: List[Edge] = []
    offset = 0
    for s, t in zip(orders, idxs):
        parent = tree_cache[s][t]
        for v in range(s):
            if parent[v] >= 0:
                edges.append((offset + parent[v], offset + v))
        offset += s
    return offset, edges


def count_forests(n: int, tree_counts: Sequence[int]) -> int:
    """Number of forests by explicit enumeration of the multisets."""
    return sum(1 for _ in forest_specs(n, tree_counts))


def count_forests_formula(n: int, tree_counts: Sequence[int]) -> int:
    """Same number via ``prod_s C(t_s + k_s - 1, k_s)`` over the partitions."""
    from math import comb

    total = 0
    for parts in partitions(n):
        multiplicity: Dict[int, int] = {}
        for s in parts:
            multiplicity[s] = multiplicity.get(s, 0) + 1
        term = 1
        for s, k in multiplicity.items():
            term *= comb(tree_counts[s] + k - 1, k)
        total += term
    return total
