/**
 * Screenshot checkpoint manifest.
 *
 * Each entry pins a moment of the cinematic that the automated visual tour
 * stops at. `expectVisible` names objects that must be on screen (matched
 * against the scene graph and a frustum test), `expectCamera` is the shot the
 * director should have selected, and `assertions` are free-form checks that the
 * runtime evaluates in `runCheckpointAssertions`.
 */

export interface Checkpoint {
  id: string;
  /** Absolute timeline seconds. */
  time: number;
  chapter: string;
  camera: string;
  /** Objects (by `Object3D.name` or selectable id) expected to be visible. */
  expectVisible: string[];
  /** Human-readable expectations, also machine-checked where marked. */
  assertions: string[];
  file: string;
  note: string;
}

export const CHECKPOINTS: Checkpoint[] = [
  {
    id: 'prologue-open',
    time: 9,
    chapter: 'prologue',
    camera: 'prologue.crawl',
    expectVisible: ['Stars', 'TitleCrawl'],
    assertions: ['fade<0.05', 'crawlOpacity>0.4', 'no-nan'],
    file: '01-prologue-open.png',
    note: 'Golden prologue receding into a star field, first paragraph legible.',
  },
  {
    id: 'prologue-late',
    time: 34,
    chapter: 'prologue',
    camera: 'prologue.crawl',
    expectVisible: ['Stars', 'TitleCrawl'],
    assertions: ['crawlOpacity>0.4', 'no-nan'],
    file: '02-prologue-late.png',
    note: 'Later paragraphs; text should still be readable, never clipped hard.',
  },
  {
    id: 'tatooine-wide',
    time: 56,
    chapter: 'tatooine',
    camera: 'tatooine.wide',
    expectVisible: ['Tatooine_Surface', 'Stars'],
    assertions: ['planet-visible', 'planet-spherical', 'no-nan', 'camera-outside-planet'],
    file: '03-tatooine-wide.png',
    note: 'Planet reads as a lit sphere with an atmospheric limb, stars behind.',
  },
  {
    id: 'tatooine-limb',
    time: 76,
    chapter: 'tatooine',
    camera: 'tatooine.limb',
    expectVisible: ['Tatooine_Surface', 'Tatooine_Atmosphere'],
    assertions: ['planet-visible', 'no-nan', 'camera-outside-planet'],
    file: '04-tatooine-limb.png',
    note: 'Bright limb across the frame; the day side must not be crushed to black.',
  },
  {
    id: 'runner-entry',
    time: 92,
    chapter: 'pursuit',
    camera: 'pursuit.entry',
    expectVisible: ['runner', 'Tatooine_Surface'],
    assertions: ['runner-visible', 'runner-forward', 'no-nan'],
    file: '05-runner-entry.png',
    note: 'Blockade runner enters at speed with the planet below.',
  },
  {
    id: 'runner-track',
    time: 104,
    chapter: 'pursuit',
    camera: 'pursuit.track',
    expectVisible: ['runner'],
    assertions: ['runner-visible', 'runner-forward', 'engines-lit', 'no-nan'],
    file: '06-runner-track.png',
    note: 'Tracking three-quarter of the runner; engine glow and hull detail legible.',
  },
  {
    id: 'destroyer-reveal',
    time: 122,
    chapter: 'pursuit',
    camera: 'pursuit.reveal',
    expectVisible: ['destroyer', 'runner'],
    assertions: ['destroyer-visible', 'destroyer-dominates', 'no-nan'],
    file: '07-destroyer-reveal.png',
    note: 'The reveal: the wedge must dwarf the runner and fill most of the frame.',
  },
  {
    id: 'destroyer-belly',
    time: 137,
    chapter: 'pursuit',
    camera: 'pursuit.belly',
    expectVisible: ['destroyer'],
    assertions: ['destroyer-visible', 'destroyer-dominates', 'no-nan'],
    file: '08-destroyer-belly.png',
    note: 'Underside crossing the top of frame; ventral detail and hangar visible.',
  },
  {
    id: 'battle-profile',
    time: 150,
    chapter: 'pursuit',
    camera: 'pursuit.profile',
    expectVisible: ['destroyer', 'runner'],
    assertions: ['both-ships-visible', 'no-nan'],
    file: '09-battle-profile.png',
    note: 'Both ships legible in one frame with bolts crossing the gap.',
  },
  {
    id: 'runner-hits',
    time: 163,
    chapter: 'pursuit',
    camera: 'pursuit.hits',
    expectVisible: ['runner'],
    assertions: ['runner-visible', 'runner-damaged', 'no-nan'],
    file: '10-runner-hits.png',
    note: 'Close on impacts: scorching, venting smoke, shield flashes.',
  },
  {
    id: 'capture-wide',
    time: 186,
    chapter: 'capture',
    camera: 'capture.wide',
    expectVisible: ['destroyer', 'runner'],
    assertions: ['both-ships-visible', 'tractor-active', 'no-nan'],
    file: '11-capture-wide.png',
    note: 'Relative positions unmistakable; tractor beam connects the two hulls.',
  },
  {
    id: 'capture-close',
    time: 206,
    chapter: 'capture',
    camera: 'capture.airlock',
    expectVisible: ['runner'],
    assertions: ['runner-visible', 'no-nan'],
    file: '12-capture-close.png',
    note: 'Push toward the airlock immediately before the match cut inside.',
  },
  {
    id: 'corridor-establish',
    time: 218,
    chapter: 'corridor',
    camera: 'corridor.establish',
    expectVisible: ['Corridor_Walls', 'rebel'],
    assertions: ['interior', 'camera-in-corridor', 'characters-on-floor', 'no-nan'],
    file: '13-corridor-establish.png',
    note: 'Corridor geography readable end to end, defenders moving to posts.',
  },
  {
    id: 'door-breach',
    time: 233,
    chapter: 'corridor',
    camera: 'corridor.door',
    expectVisible: ['BlastDoor_Seam'],
    assertions: ['interior', 'door-glowing', 'camera-in-corridor', 'no-nan'],
    file: '14-door-breach.png',
    note: 'Molten seam around the door, leaves bulging inward.',
  },
  {
    id: 'boarders',
    time: 241,
    chapter: 'corridor',
    camera: 'corridor.entry',
    expectVisible: ['trooper'],
    assertions: ['interior', 'troopers-visible', 'characters-on-floor', 'no-nan'],
    file: '15-boarders.png',
    note: 'Stormtroopers advancing through smoke; silhouettes clearly identifiable.',
  },
  {
    id: 'firefight',
    time: 252,
    chapter: 'corridor',
    camera: 'corridor.firefight',
    expectVisible: ['trooper', 'rebel'],
    assertions: ['interior', 'bolts-in-flight', 'camera-in-corridor', 'no-nan'],
    file: '16-firefight.png',
    note: 'Exchange of fire with both colours of bolt and readable geography.',
  },
  {
    id: 'vader-entrance',
    time: 272,
    chapter: 'corridor',
    camera: 'corridor.vader',
    expectVisible: ['vader'],
    assertions: ['interior', 'vader-visible', 'characters-on-floor', 'no-nan'],
    file: '17-vader-entrance.png',
    note: 'Low-angle entrance through the breach; cold rim light, cape reading.',
  },
  {
    id: 'vader-walk',
    time: 283,
    chapter: 'corridor',
    camera: 'corridor.vaderWalk',
    expectVisible: ['vader'],
    assertions: ['interior', 'vader-visible', 'characters-on-floor', 'no-nan'],
    file: '18-vader-walk.png',
    note: 'Tracking ahead of him down the corridor.',
  },
  {
    id: 'hologram',
    time: 310,
    chapter: 'plans',
    camera: 'plans.hologram',
    expectVisible: ['DataProjection'],
    assertions: ['interior', 'hologram-visible', 'no-nan'],
    file: '19-hologram.png',
    note: 'Station schematic: wire sphere, equatorial trench, emitter well.',
  },
  {
    id: 'transfer',
    time: 316,
    chapter: 'plans',
    camera: 'plans.transfer',
    expectVisible: ['r2', 'leia'],
    assertions: ['interior', 'r2-visible', 'leia-visible', 'characters-on-floor', 'no-nan'],
    file: '20-transfer.png',
    note: 'The plans shrink into the astromech; both figures readable.',
  },
  {
    id: 'droids-run',
    time: 344,
    chapter: 'escape',
    camera: 'escape.branch',
    expectVisible: ['r2', 'threepio'],
    assertions: ['interior', 'r2-visible', 'threepio-visible', 'characters-on-floor', 'no-nan'],
    file: '21-droids-run.png',
    note: 'Both droids in the branch corridor with contrasting gaits.',
  },
  {
    id: 'pod-launch',
    time: 366,
    chapter: 'escape',
    camera: 'escape.launch',
    expectVisible: ['pod', 'runner'],
    assertions: ['pod-visible', 'pod-separated', 'no-nan'],
    file: '22-pod-launch.png',
    note: 'The pod visibly clear of the hull with the runner still clamped above.',
  },
  {
    id: 'pod-descend',
    time: 382,
    chapter: 'escape',
    camera: 'escape.descend',
    expectVisible: ['pod', 'Tatooine_Surface'],
    assertions: ['pod-visible', 'planet-visible', 'no-nan'],
    file: '23-pod-descend.png',
    note: 'Following the pod toward the planet with the fleet shrinking behind.',
  },
  {
    id: 'reentry',
    time: 398,
    chapter: 'epilogue',
    camera: 'epilogue.wide',
    expectVisible: ['pod', 'Tatooine_Surface', 'destroyer'],
    assertions: ['pod-visible', 'planet-visible', 'destroyer-visible', 'reentry-active', 'no-nan'],
    file: '24-reentry.png',
    note: 'Bright point entering the atmosphere with the two ships still overhead.',
  },
  {
    id: 'epilogue-card',
    time: 407,
    chapter: 'epilogue',
    camera: 'epilogue.wide',
    expectVisible: ['Tatooine_Surface'],
    assertions: ['card-visible', 'no-nan'],
    file: '25-epilogue-card.png',
    note: 'Closing original line over the wide.',
  },
];
