/**
 * Screenshot checkpoint manifest.
 *
 * Each entry names a moment the QA tour must be able to render, what should
 * be on screen, and the assertions the harness checks before saving the
 * image. `subjects` are keys understood by TestHooks.subjectVisible().
 */

export interface Checkpoint {
  id: string;
  /** Absolute timeline seconds. */
  time: number;
  chapter: string;
  camera: string;
  /** Objects that must be inside the frustum. */
  subjects: string[];
  /** Minimum fraction of viewport height the primary subject must cover. */
  minCoverage?: { subject: string; fraction: number };
  /** Mean luminance window for the frame, 0..1. */
  luminance?: [number, number];
  file: string;
  note: string;
}

export const CHECKPOINTS: Checkpoint[] = [
  {
    id: 'prologue-text',
    time: 13.5,
    chapter: 'Prologue',
    camera: 'prologue.void',
    subjects: [],
    luminance: [0.002, 0.3],
    file: '01-prologue-text.png',
    note: 'Gold prologue typography receding into darkness.',
  },
  {
    id: 'prologue-title',
    time: 38.5,
    chapter: 'Prologue',
    camera: 'prologue.void',
    subjects: [],
    luminance: [0.004, 0.35],
    file: '02-prologue-title.png',
    note: 'Title card before the cut to the starfield.',
  },
  {
    id: 'tatooine-wide',
    time: 50,
    chapter: 'The Desert World',
    camera: 'tatooine.establish',
    subjects: ['planet'],
    luminance: [0.02, 0.6],
    file: '03-tatooine-wide.png',
    note: 'Planet fills the lower frame with a lit limb and haze.',
  },
  {
    id: 'tatooine-limb',
    time: 70,
    chapter: 'The Desert World',
    camera: 'tatooine.limb',
    subjects: ['planet'],
    file: '04-tatooine-limb.png',
    note: 'Bright limb across frame, stars above.',
  },
  {
    id: 'corvette-enter',
    time: 83,
    chapter: 'The Pursuit',
    camera: 'pursuit.enter',
    subjects: ['runner'],
    minCoverage: { subject: 'runner', fraction: 0.03 },
    file: '05-corvette-enter.png',
    note: 'Corvette crossing frame at speed, engines lit.',
  },
  {
    id: 'destroyer-nose',
    time: 96,
    chapter: 'The Pursuit',
    camera: 'pursuit.reveal',
    subjects: ['runner', 'destroyer'],
    file: '06-destroyer-nose.png',
    note: 'Destroyer bow entering the top of frame above the camera.',
  },
  {
    id: 'destroyer-overhead',
    time: 104,
    chapter: 'The Pursuit',
    camera: 'pursuit.reveal',
    subjects: ['destroyer'],
    minCoverage: { subject: 'destroyer', fraction: 0.55 },
    file: '07-destroyer-overhead.png',
    note: 'The wedge fills most of the frame — the scale beat.',
  },
  {
    id: 'battle-profile',
    time: 122,
    chapter: 'The Pursuit',
    camera: 'pursuit.profile',
    subjects: ['runner', 'destroyer'],
    file: '08-battle-profile.png',
    note: 'Both ships in one frame with turbolaser fire in transit.',
  },
  {
    id: 'chase-nearmiss',
    time: 140,
    chapter: 'The Pursuit',
    camera: 'pursuit.chase',
    subjects: ['runner'],
    minCoverage: { subject: 'runner', fraction: 0.12 },
    file: '09-chase-nearmiss.png',
    note: 'Chase camera on the corvette flank, bolts passing.',
  },
  {
    id: 'shields-fail',
    time: 155,
    chapter: 'The Pursuit',
    camera: 'pursuit.impacts',
    subjects: ['runner'],
    file: '10-shields-fail.png',
    note: 'Impacts and venting after the drive is hit.',
  },
  {
    id: 'tractor',
    time: 184,
    chapter: 'Capture',
    camera: 'capture.tractor',
    subjects: ['runner', 'destroyer'],
    file: '11-tractor.png',
    note: 'Tractor beam reaching down to the disabled corvette.',
  },
  {
    id: 'underbelly',
    time: 198,
    chapter: 'Capture',
    camera: 'capture.underbelly',
    subjects: ['runner', 'destroyer'],
    file: '12-underbelly.png',
    note: 'Corvette held beneath the destroyer — relative positions clear.',
  },
  {
    id: 'corridor-wide',
    time: 214,
    chapter: 'The Forward Passage',
    camera: 'corridor.establish',
    subjects: ['corridor', 'rebels'],
    luminance: [0.05, 0.6],
    file: '13-corridor-wide.png',
    note: 'Corridor geography established before any close action.',
  },
  {
    id: 'door-glow',
    time: 231,
    chapter: 'The Forward Passage',
    camera: 'corridor.defender',
    subjects: ['corridor', 'rebels'],
    file: '14-door-glow.png',
    note: 'Cutting seam glowing, defenders aiming.',
  },
  {
    id: 'breach',
    time: 236.5,
    chapter: 'The Forward Passage',
    camera: 'corridor.breach',
    subjects: ['troopers'],
    file: '15-breach.png',
    note: 'Door blown inward, smoke and debris, boarders entering.',
  },
  {
    id: 'firefight',
    time: 246,
    chapter: 'The Forward Passage',
    camera: 'corridor.crossfire',
    subjects: ['rebels', 'troopers'],
    file: '16-firefight.png',
    note: 'Crossfire with bolts in flight in both directions.',
  },
  {
    id: 'vader-entrance',
    time: 275,
    chapter: 'The Forward Passage',
    camera: 'corridor.vader',
    subjects: ['vader'],
    minCoverage: { subject: 'vader', fraction: 0.3 },
    file: '17-vader-entrance.png',
    note: 'The dark lord in the ruined doorway, lighting shifted red.',
  },
  {
    id: 'vader-advance',
    time: 286,
    chapter: 'The Forward Passage',
    camera: 'corridor.vader.walk',
    subjects: ['vader'],
    file: '18-vader-advance.png',
    note: 'He walks the corridor; troopers hold position.',
  },
  {
    id: 'plans-projection',
    time: 308,
    chapter: 'The Plans',
    camera: 'plans.console',
    subjects: ['leia', 'plans'],
    file: '19-plans-projection.png',
    note: 'The stolen plans as a geometric projection above the console.',
  },
  {
    id: 'data-transfer',
    time: 317,
    chapter: 'The Plans',
    camera: 'plans.transfer',
    subjects: ['leia', 'r2'],
    file: '20-data-transfer.png',
    note: 'The file going into the astromech — readable in one frame.',
  },
  {
    id: 'droids-run',
    time: 338,
    chapter: 'Pod Six',
    camera: 'pod.run',
    subjects: ['r2', 'threepio'],
    file: '21-droids-run.png',
    note: 'Contrasting droid behaviour on the way to the bay.',
  },
  {
    id: 'pod-bay',
    time: 347,
    chapter: 'Pod Six',
    camera: 'pod.bay',
    subjects: ['interiorPod', 'r2'],
    file: '22-pod-bay.png',
    note: 'Both droids at the correct pod, clamps still engaged.',
  },
  {
    id: 'pod-launch',
    time: 355,
    chapter: 'Pod Six',
    camera: 'pod.launch',
    subjects: ['pod', 'runner'],
    file: '23-pod-launch.png',
    note: 'Pod visibly leaving the corvette hull.',
  },
  {
    id: 'pod-away',
    time: 369,
    chapter: 'Pod Six',
    camera: 'pod.away',
    subjects: ['pod', 'runner', 'destroyer'],
    file: '24-pod-away.png',
    note: 'Pod falling clear with both ships still overhead.',
  },
  {
    id: 'descent',
    time: 379,
    chapter: 'Pod Six',
    camera: 'pod.descent',
    subjects: ['pod', 'planet'],
    file: '25-descent.png',
    note: 'The pod as a bright point against the desert world.',
  },
  {
    id: 'epilogue',
    time: 390,
    chapter: 'Epilogue',
    camera: 'epilogue.wide',
    subjects: ['runner', 'destroyer'],
    file: '26-epilogue.png',
    note: 'The captured ships remain above the planet.',
  },
  {
    id: 'closing-card',
    time: 399,
    chapter: 'Epilogue',
    camera: 'epilogue.card',
    subjects: [],
    file: '27-closing-card.png',
    note: 'Closing line before explore mode is offered.',
  },
];
