import * as THREE from 'three';

/**
 * Per-part surface detail for the weapon materials.
 *
 * The procgen library paints the *material* — the phosphate, the mould stipple,
 * the walnut — and it does that well, but it paints it as one tile with no idea
 * what part it lands on. What was missing is everything that belongs to the
 * object rather than the substance: the receiver being rubbed bright along every
 * chamfer, one panel of a handguard finishing rougher than the next, grime in the
 * underside of a trigger guard, the fine longitudinal striation that makes a
 * barrel read as turned steel instead of a grey cylinder. Without those a weapon
 * is a correctly-textured collection of primitives, which is exactly how it was
 * described.
 *
 * All of it is one compile hook over three's standard material, driven by
 * uniforms so every role shares a single program:
 *
 *  - object-space value noise, for roughness and value break-up at part scale
 *  - `fwidth` of the interpolated normal as an edge detector, for rub-through
 *  - a downward bias, for grime that settles under a part rather than over it
 *  - anisotropic striation in UV space, for turned and brushed metal
 *
 * The edge term is worth explaining because the obvious implementation is a
 * baked curvature attribute. That would have to be generated by every geometry
 * helper in `Parts.ts` and by the handful of places that use a three primitive
 * directly, and a mesh that missed one would sample an unbound attribute. The
 * derivative of the shading normal needs nothing bound at all and is a true
 * measure of how fast the surface is turning under this pixel, which is what
 * "edge" means. It also scales with distance for free: an edge 25 cm from the eye
 * is picked out, the same edge across the room is not, and that is the correct
 * behaviour for a first-person weapon.
 */

const PARS = /* glsl */ `
varying vec3 vGunLocal;
uniform vec4 uGunWear;        // x: edge, y: breakup, z: grime, w: wear roughness
uniform vec4 uGunDetail;      // x: noise scale, y: value break-up, z: aniso depth, w: aniso freq
uniform vec3 uGunWearMetal;   // x: metalness exposed by wear, y: raise it at all, z: roughness bias
uniform vec3 uGunWearColor;

float obGunHash( vec3 p ) {
  p = fract( p * 0.3183099 + vec3( 0.71, 0.113, 0.419 ) );
  p *= 17.0;
  return fract( p.x * p.y * p.z * ( p.x + p.y + p.z ) );
}

/** Trilinear value noise; three of these is enough at the scale a part is seen. */
float obGunNoise( vec3 p ) {
  vec3 i = floor( p );
  vec3 f = fract( p );
  f = f * f * ( 3.0 - 2.0 * f );
  float n000 = obGunHash( i );
  float n100 = obGunHash( i + vec3( 1.0, 0.0, 0.0 ) );
  float n010 = obGunHash( i + vec3( 0.0, 1.0, 0.0 ) );
  float n110 = obGunHash( i + vec3( 1.0, 1.0, 0.0 ) );
  float n001 = obGunHash( i + vec3( 0.0, 0.0, 1.0 ) );
  float n101 = obGunHash( i + vec3( 1.0, 0.0, 1.0 ) );
  float n011 = obGunHash( i + vec3( 0.0, 1.0, 1.0 ) );
  float n111 = obGunHash( i + vec3( 1.0, 1.0, 1.0 ) );
  return mix(
    mix( mix( n000, n100, f.x ), mix( n010, n110, f.x ), f.y ),
    mix( mix( n001, n101, f.x ), mix( n011, n111, f.x ), f.y ),
    f.z
  );
}

/**
 * Rotated between octaves, and weighted much less towards the first.
 *
 * Value noise puts every one of its extrema on the integer lattice, so summed
 * on the axes it is sampled on it is not noise at all but a grid of blobs at the
 * sampling pitch — and the parts here are boxes and cylinders whose own axes are
 * those axes exactly. Measured on the handguard it came out as a 12 mm lattice
 * with 15 per cent contrast, matching the break-up frequency to the millimetre:
 * a moulded stipple is what it was meant to read as, a printed dot screen is what
 * it read as. Rotating each octave off the last leaves the lattice pointing
 * nowhere in particular on any part, and four octaves at a flatter falloff put
 * enough amplitude between its nodes to hide where they are.
 */
const mat3 OB_GUN_ROT = mat3( 0.00, 0.80, 0.60, -0.80, 0.36, -0.48, -0.60, -0.48, 0.64 );

float obGunFbm( vec3 p ) {
  vec3 q = OB_GUN_ROT * p;
  float f = obGunNoise( q ) * 0.5;
  q = OB_GUN_ROT * q * 2.17 + 4.3;
  f += obGunNoise( q ) * 0.27;
  q = OB_GUN_ROT * q * 2.11 - 2.7;
  f += obGunNoise( q ) * 0.15;
  q = OB_GUN_ROT * q * 2.03 + 1.9;
  return f + obGunNoise( q ) * 0.08;
}
`;

const FRAGMENT = /* glsl */ `
{
  float gunField = obGunFbm( vGunLocal * uGunDetail.x );

  // Rub-through. The derivative is measured per pixel rather than per metre, so a
  // chamfer reads the same whether the part is 6 mm across or 60, and an edge
  // across the room correctly stops being picked out at all.
  float gunEdge = 0.0;
  float gunGrime = 0.0;
#ifndef FLAT_SHADED
  vec3 gunN = normalize( vNormal );
  float gunTurn = length( fwidth( gunN ) );
  gunEdge = smoothstep( 0.10, 0.48, gunTurn );
  // Silhouettes are excluded, and they have to be explicitly: the normal turns
  // faster per pixel at the edge of a smooth cylinder than anywhere on a chamfer,
  // so a derivative-based edge term paints bare steel around the outline of every
  // curved part and the weapon comes back wearing a white pencil line. The
  // interpolated normal is in view space, so its z is the facing term for free.
  gunEdge *= smoothstep( 0.16, 0.52, abs( gunN.z ) );
  // Wear is not uniform along an edge; where the noise is low the coating holds.
  gunEdge *= smoothstep( 0.26, 0.70, gunField + 0.20 );
  // Grime under the part. Object space is authored bore-up on every weapon, so
  // -Y is genuinely "underneath" and needs no per-part direction.
  gunGrime = smoothstep( 0.55, -0.1, gunN.y ) * smoothstep( 0.34, 0.78, gunField );
#endif

  // Longitudinal striation. Fine across the profile and smooth along it, so the
  // highlight on a turned surface breaks into axial threads instead of sitting on
  // it as one smooth sweep. That is the anisotropy: the grooves have a direction,
  // so the specular lobe stretches along it.
  float gunStria = 0.5;
#ifdef USE_MAP
  gunStria = sin( vMapUv.x * uGunDetail.w ) * 0.5 + 0.5;
  gunStria *= 0.6 + 0.4 * obGunNoise( vec3( vMapUv.x * uGunDetail.w * 0.29, vMapUv.y * 2.7, 0.0 ) );
#endif

  float gunWear = gunEdge * uGunWear.x;
  // The bias is added, not multiplied, because the material's own roughness is a
  // multiplier over a map that averages 0.5 and three's own weathering pass
  // clamps that multiplier at 1 — so multiplying cannot reach the roughness a
  // machined and phosphated surface actually has, however large the factor.
  roughnessFactor = clamp( roughnessFactor + uGunWearMetal.z, 0.045, 1.0 );
  roughnessFactor = mix( roughnessFactor, uGunWear.w, gunWear );
  roughnessFactor *= 1.0 + ( gunField - 0.5 ) * 2.0 * uGunWear.y;
  roughnessFactor += ( gunStria - 0.5 ) * uGunDetail.z;
  roughnessFactor = clamp( roughnessFactor, 0.045, 1.0 );

  diffuseColor.rgb = mix( diffuseColor.rgb, uGunWearColor, gunWear );
  diffuseColor.rgb *= 1.0 + ( gunField - 0.5 ) * 2.0 * uGunDetail.y;
  diffuseColor.rgb *= 1.0 - gunGrime * uGunWear.z;
  // Steel rubs through to bare metal; polymer and fabric only ever scuff paler,
  // so the exposed metalness is per-role rather than assumed.
  metalnessFactor = mix(
    metalnessFactor,
    mix( metalnessFactor, max( metalnessFactor, uGunWearMetal.x ), uGunWearMetal.y ),
    gunWear
  );
}
`;

export interface GunSurfaceOptions {
  /** Rub-through on edges, 0..1. */
  edgeWear?: number;
  /** Roughness variation across the part, as a fraction of the mapped value. */
  breakup?: number;
  /** Grime darkening on downward faces, 0..1. */
  grime?: number;
  /** Roughness the exposed metal takes at full rub-through. */
  wearRoughness?: number;
  /** Linear albedo the rub-through exposes. Defaults to bare steel. */
  wearColor?: readonly [number, number, number];
  /** Cycles per metre of the object-space break-up field. */
  scale?: number;
  /** Value variation across the part, as a fraction of albedo. */
  valueBreakup?: number;
  /** Depth of the anisotropic striation in roughness; 0 disables it. */
  striation?: number;
  /** Striation frequency across the profile, in radians per UV unit. */
  striationFrequency?: number;
  /**
   * Metalness the rub-through exposes. `null` leaves metalness alone, which is
   * what polymer and fabric want — they scuff, they do not reveal steel.
   */
  wearMetalness?: number | null;
  /** Added to the mapped roughness before anything else; see the shader. */
  roughnessBias?: number;
}

/**
 * Bare steel exposed by rub-through, as linear albedo.
 *
 * Under the F0 of real polished steel, which is nearer 0.6, and deliberately. The
 * roles this sits over are coatings at 0.02 to 0.03 albedo, so at a physical value
 * the edge term is thirty times its surroundings and every chamfer on the weapon
 * comes back as a white line drawn in pencil — which is what the receiver and the
 * buffer tube were doing. Worn phosphate is a grey-silver sheen and not a
 * highlight, and fifteen times the coating is already more contrast than the frame
 * can show.
 */
const DEFAULT_WEAR_COLOR: readonly [number, number, number] = [0.4, 0.408, 0.42];

/**
 * Installs the detail layer on a material.
 *
 * Chains onto any hook already present rather than replacing it: the library
 * installs its own for tiled variants and for the world-space macro layer, and
 * silently dropping that would cost the material its UV scale.
 *
 * The options are kept on `userData` so `cloneGunSurface` can put the layer back
 * after a clone. That is not defensive tidiness: `Material.copy` does not copy
 * `onBeforeCompile`, so anything that clones one of these silently returns a
 * material with no wear, no break-up and no grime, and it does it without a
 * warning of any kind. The per-weapon weathering pass clones exactly the five
 * roles that cover most of a weapon's surface, which is how the receiver, the
 * handguard, the magazine and the stock all came to be shipping bare.
 */
export function applyGunSurface(
  material: THREE.MeshStandardMaterial,
  options: GunSurfaceOptions = {},
): THREE.MeshStandardMaterial {
  material.userData.gunSurface = options;
  const wearColor = options.wearColor ?? DEFAULT_WEAR_COLOR;
  const uniforms = {
    uGunWear: {
      value: new THREE.Vector4(
        options.edgeWear ?? 0.4,
        options.breakup ?? 0.22,
        options.grime ?? 0.3,
        options.wearRoughness ?? 0.3,
      ),
    },
    uGunDetail: {
      value: new THREE.Vector4(
        options.scale ?? 26,
        options.valueBreakup ?? 0.14,
        options.striation ?? 0,
        options.striationFrequency ?? 420,
      ),
    },
    uGunWearMetal: {
      value: new THREE.Vector3(
        options.wearMetalness ?? 0.86,
        options.wearMetalness === null ? 0 : 1,
        options.roughnessBias ?? 0,
      ),
    },
    uGunWearColor: {
      value: new THREE.Color().setRGB(
        wearColor[0],
        wearColor[1],
        wearColor[2],
        THREE.LinearSRGBColorSpace,
      ),
    },
  };

  const previous = material.onBeforeCompile;
  const chained = previous !== THREE.Material.prototype.onBeforeCompile ? previous : null;
  const previousKey = material.customProgramCacheKey;
  const chainedKey =
    previousKey !== THREE.Material.prototype.customProgramCacheKey ? previousKey : null;

  material.onBeforeCompile = (shader, renderer) => {
    chained?.call(material, shader, renderer);
    for (const [name, uniform] of Object.entries(uniforms)) shader.uniforms[name] = uniform;
    shader.vertexShader = `varying vec3 vGunLocal;\n${shader.vertexShader}`.replace(
      '#include <begin_vertex>',
      '#include <begin_vertex>\n  vGunLocal = position;',
    );
    shader.fragmentShader = `${PARS}\n${shader.fragmentShader}`.replace(
      '#include <metalnessmap_fragment>',
      `#include <metalnessmap_fragment>\n${FRAGMENT}`,
    );
  };
  material.customProgramCacheKey = function key(): string {
    return `vmsurface|${chainedKey ? chainedKey.call(material) : ''}`;
  };
  material.needsUpdate = true;
  return material;
}

/**
 * Clones a material and reinstalls its detail layer, optionally nudged.
 *
 * Anything deriving a variant from a palette material has to go through here.
 * `overrides` is what makes two rifles wear differently: the layer is driven by
 * uniforms, so a per-weapon shift in how rubbed-through or how filthy a surface
 * is costs a clone and no extra program.
 */
export function cloneGunSurface(
  material: THREE.MeshStandardMaterial,
  overrides: GunSurfaceOptions = {},
): THREE.MeshStandardMaterial {
  const clone = material.clone() as THREE.MeshStandardMaterial;
  const options = material.userData.gunSurface as GunSurfaceOptions | undefined;
  if (options) applyGunSurface(clone, { ...options, ...overrides });
  return clone;
}
