import type { WeaponId, WeaponSpec } from '../core/Contracts';

/**
 * The six-weapon loadout. Stats are tuned CoD-style: readable falloff windows,
 * distinct recoil/handling identities, and mag/reserve counts that feel right
 * for each class. All distances are metres, times are seconds, angles degrees.
 */

export const WEAPON_ORDER: WeaponId[] = [
  'ar_wolverine',
  'smg_viper',
  'sniper_longbow',
  'shotgun_breacher',
  'pistol_sidearm',
  'lmg_bulwark',
];

export const WEAPON_SPECS: Record<WeaponId, WeaponSpec> = {
  ar_wolverine: {
    id: 'ar_wolverine',
    displayName: 'WOLVERINE',
    className: 'ASSAULT RIFLE',
    fireMode: 'auto',
    rpm: 720,
    magSize: 30,
    reserveAmmo: 210,
    damage: 32,
    damageRangeStart: 30,
    damageRangeEnd: 62,
    damageFalloff: 0.55,
    headshotMultiplier: 1.5,
    muzzleVelocity: 860,
    pelletsPerShot: 1,
    spreadHip: 2.4,
    spreadAds: 0.16,
    spreadMoving: 1.3,
    recoilVertical: 0.5,
    recoilHorizontal: 0.18,
    recoilRecovery: 8,
    adsTime: 0.24,
    reloadTime: 2.0,
    reloadEmptyTime: 2.65,
    drawTime: 0.55,
    adsFovScale: 0.72,
    scoped: false,
    fireSound: 'weapon_assault_rifle',
    penetration: 0.45,
    caliber: 'rifle',
  },

  smg_viper: {
    id: 'smg_viper',
    displayName: 'VIPER',
    className: 'SMG',
    fireMode: 'auto',
    rpm: 900,
    magSize: 30,
    reserveAmmo: 270,
    damage: 24,
    damageRangeStart: 16,
    damageRangeEnd: 34,
    damageFalloff: 0.45,
    headshotMultiplier: 1.4,
    muzzleVelocity: 640,
    pelletsPerShot: 1,
    spreadHip: 2.6,
    spreadAds: 0.32,
    spreadMoving: 1.1,
    recoilVertical: 0.32,
    recoilHorizontal: 0.24,
    recoilRecovery: 10,
    adsTime: 0.17,
    reloadTime: 1.65,
    reloadEmptyTime: 2.25,
    drawTime: 0.45,
    adsFovScale: 0.82,
    scoped: false,
    fireSound: 'weapon_smg',
    penetration: 0.28,
    caliber: 'pistol',
  },

  sniper_longbow: {
    id: 'sniper_longbow',
    displayName: 'LONGBOW',
    className: 'SNIPER',
    fireMode: 'bolt',
    rpm: 55,
    magSize: 5,
    reserveAmmo: 40,
    damage: 150,
    damageRangeStart: 60,
    damageRangeEnd: 240,
    damageFalloff: 0.85,
    headshotMultiplier: 2.5,
    muzzleVelocity: 900,
    pelletsPerShot: 1,
    spreadHip: 4.5,
    spreadAds: 0.02,
    spreadMoving: 3.2,
    recoilVertical: 2.2,
    recoilHorizontal: 0.3,
    recoilRecovery: 4.5,
    adsTime: 0.45,
    reloadTime: 3.1,
    reloadEmptyTime: 3.6,
    drawTime: 0.9,
    adsFovScale: 0.32,
    scoped: true,
    scopeMagnification: 6,
    fireSound: 'weapon_sniper',
    penetration: 0.9,
    caliber: 'magnum',
  },

  shotgun_breacher: {
    id: 'shotgun_breacher',
    displayName: 'BREACHER',
    className: 'SHOTGUN',
    fireMode: 'pump',
    rpm: 75,
    magSize: 6,
    reserveAmmo: 42,
    damage: 15,
    damageRangeStart: 6,
    damageRangeEnd: 18,
    damageFalloff: 0.15,
    headshotMultiplier: 1.35,
    muzzleVelocity: 420,
    pelletsPerShot: 9,
    spreadHip: 5.2,
    spreadAds: 3.0,
    spreadMoving: 6.4,
    recoilVertical: 1.6,
    recoilHorizontal: 0.4,
    recoilRecovery: 6,
    adsTime: 0.3,
    reloadTime: 2.9,
    reloadEmptyTime: 3.3,
    drawTime: 0.7,
    adsFovScale: 0.9,
    scoped: false,
    fireSound: 'weapon_shotgun',
    penetration: 0.2,
    caliber: 'shell',
  },

  pistol_sidearm: {
    id: 'pistol_sidearm',
    displayName: 'SIDEARM',
    className: 'PISTOL',
    fireMode: 'semi',
    rpm: 450,
    magSize: 15,
    reserveAmmo: 90,
    damage: 28,
    damageRangeStart: 18,
    damageRangeEnd: 40,
    damageFalloff: 0.5,
    headshotMultiplier: 1.6,
    muzzleVelocity: 480,
    pelletsPerShot: 1,
    spreadHip: 2.0,
    spreadAds: 0.2,
    spreadMoving: 1.6,
    recoilVertical: 0.7,
    recoilHorizontal: 0.26,
    recoilRecovery: 12,
    adsTime: 0.16,
    reloadTime: 1.55,
    reloadEmptyTime: 2.1,
    drawTime: 0.4,
    adsFovScale: 0.85,
    scoped: false,
    fireSound: 'weapon_pistol',
    penetration: 0.25,
    caliber: 'pistol',
  },

  lmg_bulwark: {
    id: 'lmg_bulwark',
    displayName: 'BULWARK',
    className: 'LMG',
    fireMode: 'auto',
    rpm: 640,
    magSize: 100,
    reserveAmmo: 200,
    damage: 34,
    damageRangeStart: 40,
    damageRangeEnd: 85,
    damageFalloff: 0.6,
    headshotMultiplier: 1.4,
    muzzleVelocity: 870,
    pelletsPerShot: 1,
    spreadHip: 3.6,
    spreadAds: 0.3,
    spreadMoving: 2.4,
    recoilVertical: 0.55,
    recoilHorizontal: 0.3,
    recoilRecovery: 5.5,
    adsTime: 0.4,
    reloadTime: 5.0,
    reloadEmptyTime: 5.6,
    drawTime: 1.0,
    adsFovScale: 0.8,
    scoped: false,
    fireSound: 'weapon_lmg',
    penetration: 0.6,
    caliber: 'rifle',
  },
};

/** Tracer cadence per weapon (every Nth round leaves a visible tracer). */
export const TRACER_EVERY: Record<WeaponId, number> = {
  ar_wolverine: 3,
  smg_viper: 4,
  sniper_longbow: 1,
  shotgun_breacher: 0, // pellets don't tracer
  pistol_sidearm: 0,
  lmg_bulwark: 3,
};
