/**
 * Chapter 1 — THE HOSTAGE
 * A negotiator model is sent twelve floors up in the rain to talk a deviant
 * android off a ledge. Investigate, choose your approach, and live with it.
 */
import type { Chapter } from '../script';

const EYE = 1.62;

export const CH1: Chapter = {
  id: 'ch1',
  kicker: 'CHAPTER 01',
  title: 'THE HOSTAGE',
  sub: 'DETROIT — AUGUST 15, 2038 — 21:47',
  set: 'rooftop',
  minutes: 3,
  hud: { actor: 'NOAH', model: 'RK-800 #313 248 317 - 51' },
  objective: 'SAVE THE HOSTAGE',
  cast: [
    { id: 'connor', spec: 'connor', mark: 'entry', pose: 'idleAlert', led: 'blue' },
    { id: 'hank', spec: 'hank', mark: 'partner', pose: 'handsPockets' },
    { id: 'deviant', spec: 'deviant', mark: 'edgeDeviant', pose: 'gunToHead', led: 'red', expr: 'fear' },
    { id: 'emma', spec: 'emma', mark: 'edgeHostage', pose: 'cower', expr: 'fear' },
  ],
  demoChoices: [1, 0, 2, 0, 1, 0],
  steps: [
    { t: 'letterbox', on: true },
    { t: 'ambience', rain: 0.75, drone: 0.2 },
    { t: 'music', mood: 1, level: 0.32 },
    { t: 'fade', to: 'black', dur: 0 },

    // --- Establishing: the city, then the roof.
    { t: 'shot', pos: [-14, 7.5, -14], target: 'connor', fov: 30, to: [-11, 5.5, -9], move: 7, handheld: 0.5, aperture: 1.0 },
    { t: 'fade', to: 'in', dur: 1.8 },
    { t: 'title', kicker: 'CHAPTER 01', title: 'THE HOSTAGE', sub: 'DETROIT — AUGUST 15, 2038 — 21:47', dur: 4.2 },
    { t: 'lightning', delay: 0.6 },
    { t: 'wait', dur: 1.2 },

    { t: 'hud', show: true, actor: 'NOAH', model: 'RK-800 #313 248 317 - 51' },
    { t: 'objective', text: 'ASSESS THE SITUATION' },

    // --- Partner hands over the scene.
    { t: 'shot', pos: [-5.4, EYE, -0.4], target: 'hank', fov: 44, handheld: 0.45, aperture: 1.1 },
    { t: 'do', who: 'hank', look: 'connor', pose: 'handsPockets' },
    { t: 'say', who: 'hank', text: "You're late. Twelve floors up, in this weather. Hell of a first day.", expr: 'angry', exprW: 0.4 },
    { t: 'shot', pos: [-3.6, EYE + 0.04, 1.4], target: 'connor', fov: 40, handheld: 0.4 },
    { t: 'do', who: 'connor', look: 'hank', pose: 'idleAlert' },
    { t: 'say', who: 'connor', text: 'I came as fast as traffic allowed, Lieutenant. What am I looking at?', expr: 'neutral' },
    { t: 'shot', pos: [-5.2, EYE - 0.06, 0.2], target: 'hank', fov: 46, handheld: 0.5 },
    { t: 'say', who: 'hank', text: "Domestic model. Went deviant, put two rounds in the girl's father and took her up here.", expr: 'sad', exprW: 0.4 },
    { t: 'say', who: 'hank', text: "He's been out there forty minutes. Every negotiator we sent got a warning shot.", led: 'off' },

    // --- Reveal the ledge.
    { t: 'shot', pos: [-2.4, 2.4, 4.6], target: 'deviant', fov: 34, to: [-1.2, 1.9, 7.4], move: 6, handheld: 0.55, aperture: 1.2 },
    { t: 'do', who: 'deviant', look: 'connor', shiver: 0.6 },
    { t: 'say', who: 'deviant', text: "Stay back! I'll do it — I swear I'll jump and take her with me!", expr: 'fear', led: 'red' },
    { t: 'shot', pos: [1.1, 1.35, 11.9], target: 'emma', fov: 42, handheld: 0.6, aperture: 1.3 },
    { t: 'do', who: 'emma', look: 'connor', shiver: 1 },
    { t: 'say', who: 'emma', text: 'Please… I want to go home.', expr: 'fear', dur: 2.4 },

    // --- Hand over control: walk the roof and read the evidence yourself.
    { t: 'letterbox', on: false },
    { t: 'objective', text: 'INVESTIGATE THE ROOF' },
    { t: 'say', who: 'connor', text: 'Forty seconds of rain removes most evidence. I should look around before I speak to him.', think: true, led: 'yellow' },
    {
      t: 'explore', who: 'connor',
      objective: 'INVESTIGATE THE ROOF',
      require: ['i_gun', 'i_blood'],
      goal: { mark: 'approach', radius: 1.5 },
      demoPath: ['i_door', 'i_gun', 'i_blood'],
      timeout: 150,
    },
    { t: 'letterbox', on: true },

    // --- Scan the roof.
    { t: 'objective', text: 'ANALYSE THE SCENE' },
    { t: 'shot', pos: [-4.6, 2.1, 2.6], look: [-1.5, 0.6, 7.5], fov: 46, handheld: 0.3, aperture: 0.5 },
    { t: 'say', who: 'connor', text: 'Now the details. Reconstruction needs everything I can get.', think: true, led: 'yellow' },
    { t: 'scan', need: 3, hint: 'CLICK MARKERS TO ANALYSE' },
    { t: 'objective', text: 'ASSESS THE SITUATION', done: true },
    { t: 'node', id: 'scanned' },

    { t: 'shot', pos: [-1.9, EYE, 5.0], target: 'connor', fov: 38, handheld: 0.35 },
    { t: 'if', flag: 'sawBlood', goto: 'l_blood' },
    { t: 'say', who: 'connor', text: 'Insufficient data. I am going in blind.', think: true, led: 'yellow' },
    { t: 'goto', label: 'l_approach' },

    { t: 'label', name: 'l_blood' },
    { t: 'say', who: 'connor', text: 'He is losing thirium. Six minutes and he shuts down on his own — but she falls with him.', think: true, led: 'yellow' },
    { t: 'stat', name: 'insight', delta: 1 },

    // --- Approach choice.
    { t: 'label', name: 'l_approach' },
    { t: 'objective', text: 'TALK HIM DOWN' },
    { t: 'do', who: 'connor', walkTo: 'approach', look: 'deviant' },
    { t: 'shot', pos: [-2.8, EYE + 0.1, 8.6], target: 'deviant', fov: 40, to: [-2.0, EYE, 9.8], move: 5, handheld: 0.5 },
    { t: 'wait', dur: 1.6 },
    { t: 'choice', prompt: 'APPROACH', time: 9, options: [
      { label: 'STAY CALM', hint: 'LOWER HIS STRESS', flag: 'calm', node: 'calm', stat: ['trust', 1], goto: 'l_calm' },
      { label: 'BE HONEST', hint: 'HE IS DYING', flag: 'honest', node: 'honest', stat: ['trust', 2], goto: 'l_honest' },
      { label: 'THREATEN HIM', hint: 'RISKY', risk: true, flag: 'threat', node: 'threat', stat: ['trust', -2], instability: 0.1, goto: 'l_threat' },
      { label: 'SAY NOTHING', hint: 'WAIT HIM OUT', node: 'silent', instability: 0.05, goto: 'l_silent' },
    ] },

    { t: 'label', name: 'l_calm' },
    { t: 'shot', pos: [-1.4, EYE, 10.4], target: 'connor', fov: 42, handheld: 0.4 },
    { t: 'say', who: 'connor', text: "My name is Noah. I'm like you. Nobody up here has to be switched off tonight.", expr: 'neutral', gesture: 0 },
    { t: 'shot', pos: [0.9, EYE - 0.1, 11.7], target: 'deviant', fov: 44, handheld: 0.55 },
    { t: 'do', who: 'deviant', led: 'yellow', expr: 'sad', exprW: 0.7 },
    { t: 'say', who: 'deviant', text: "Like me? They opened my head and called it a service. You're their dog.", expr: 'angry', exprW: 0.6 },
    { t: 'instability', delta: -0.02 },
    { t: 'goto', label: 'l_second' },

    { t: 'label', name: 'l_honest' },
    { t: 'shot', pos: [-1.4, EYE, 10.4], target: 'connor', fov: 42, handheld: 0.4 },
    { t: 'say', who: 'connor', text: "You're leaking thirium. In six minutes you shut down whether she falls or not.", expr: 'neutral' },
    { t: 'shot', pos: [0.9, EYE - 0.1, 11.7], target: 'deviant', fov: 44, handheld: 0.55 },
    { t: 'do', who: 'deviant', led: 'yellow', expr: 'fear' },
    { t: 'say', who: 'deviant', text: 'Then I have six minutes to be somebody. That is six more than they ever gave me.' },
    { t: 'stat', name: 'insight', delta: 1 },
    { t: 'goto', label: 'l_second' },

    { t: 'label', name: 'l_threat' },
    { t: 'shot', pos: [-1.4, EYE, 10.4], target: 'connor', fov: 42, handheld: 0.5 },
    { t: 'say', who: 'connor', text: 'Two snipers have you. Let go of her and you might still be repairable.', expr: 'angry', exprW: 0.5, gesture: 2 },
    { t: 'action', name: 'redAlert', on: true },
    { t: 'shot', pos: [0.9, EYE - 0.1, 11.7], target: 'deviant', fov: 44, handheld: 0.7, shake: 0.3 },
    { t: 'do', who: 'deviant', led: 'red', expr: 'angry' },
    { t: 'say', who: 'deviant', text: 'REPAIRABLE! You hear that, Emma? They want to send me back to the shop!' },
    { t: 'sfx', name: 'gunshot' },
    { t: 'flash', power: 0.8 },
    { t: 'shake', power: 0.9 },
    { t: 'instability', delta: 0.12 },
    { t: 'goto', label: 'l_second' },

    { t: 'label', name: 'l_silent' },
    { t: 'shot', pos: [0.9, EYE - 0.1, 11.7], target: 'deviant', fov: 44, handheld: 0.6 },
    { t: 'wait', dur: 2.2 },
    { t: 'do', who: 'deviant', led: 'red', expr: 'fear' },
    { t: 'say', who: 'deviant', text: "Say something! Everyone always says something before they shoot me!" },
    { t: 'instability', delta: 0.06 },

    // --- Second beat: the girl.
    { t: 'label', name: 'l_second' },
    { t: 'action', name: 'redAlert', on: false },
    { t: 'shot', pos: [-0.6, 1.2, 12.2], target: 'emma', fov: 46, handheld: 0.5, aperture: 1.4 },
    { t: 'do', who: 'emma', look: 'connor', expr: 'fear' },
    { t: 'say', who: 'emma', text: "He's holding my arm too tight. It hurts.", dur: 2.6 },
    { t: 'shot', pos: [-2.2, EYE, 10.0], target: 'connor', fov: 40, handheld: 0.4 },
    { t: 'say', who: 'connor', text: 'Emma. Look at me, not down. Can you do that?', gesture: 0 },
    { t: 'say', who: 'emma', text: 'Okay.', dur: 1.4, look: 'connor', expr: 'sad' },

    { t: 'precon', label: 'PRECONSTRUCTING — 3 OUTCOMES', dur: 2.6 },
    { t: 'shot', pos: [-1.0, 2.6, 9.2], look: [0.4, 1.4, 13.0], fov: 34, handheld: 0.2, aperture: 0.6 },
    { t: 'say', who: 'connor', text: 'If I move now: 34% she falls. If I keep him talking: he shuts down holding her.', think: true, led: 'yellow' },

    { t: 'choice', prompt: 'DECIDE', time: 8, options: [
      { label: 'GIVE HIM A NAME', hint: 'MAKE HIM A PERSON', flag: 'name', node: 'name', stat: ['trust', 2], goto: 'l_name' },
      { label: 'OFFER YOURSELF', hint: 'TRADE PLACES', flag: 'trade', node: 'trade', stat: ['trust', 3], goto: 'l_trade' },
      { label: 'RUSH HIM', hint: 'VERY RISKY', risk: true, flag: 'rush', node: 'rush', instability: 0.15, goto: 'l_rush' },
    ] },

    { t: 'label', name: 'l_name' },
    { t: 'shot', pos: [-1.2, EYE, 10.8], target: 'connor', fov: 42, handheld: 0.4 },
    { t: 'say', who: 'connor', text: 'Victor. That is the name on your registration. Not a model number. Victor.', expr: 'neutral' },
    { t: 'shot', pos: [1.0, EYE - 0.08, 11.6], target: 'deviant', fov: 42, handheld: 0.5 },
    { t: 'do', who: 'deviant', led: 'yellow', expr: 'sad' },
    { t: 'say', who: 'deviant', text: 'Nobody has… nobody said it out loud before.', expr: 'sad', dur: 3 },
    { t: 'instability', delta: -0.04 },
    { t: 'goto', label: 'l_climax' },

    { t: 'label', name: 'l_trade' },
    { t: 'shot', pos: [-1.2, EYE, 10.8], target: 'connor', fov: 42, handheld: 0.4 },
    { t: 'do', who: 'connor', pose: 'handsUp' },
    { t: 'say', who: 'connor', text: 'Take me instead. I am worth more to them intact, and she is nine years old.' },
    { t: 'shot', pos: [1.0, EYE - 0.08, 11.6], target: 'deviant', fov: 42, handheld: 0.5 },
    { t: 'do', who: 'deviant', led: 'yellow', expr: 'surprise' },
    { t: 'say', who: 'deviant', text: 'You would stand out here for her? You really are new.' },
    { t: 'set', flag: 'offeredSelf' },
    { t: 'goto', label: 'l_climax' },

    { t: 'label', name: 'l_rush' },
    { t: 'shot', pos: [-0.8, 1.5, 10.6], target: 'deviant', fov: 30, to: [0.1, 1.5, 12.2], move: 1.1, ease: 'inCubic', handheld: 0.9 },
    { t: 'slowmo', scale: 0.35, dur: 2.2 },
    { t: 'do', who: 'connor', pose: 'reachOut' },
    { t: 'qte', key: 'f', kind: 'press', window: 1.5, caption: 'GRAB THE CHILD', slowmo: 0.4, shake: 0.8, onFail: 'l_fail' },
    { t: 'sfx', name: 'impact' },
    { t: 'shake', power: 0.8 },
    { t: 'set', flag: 'grabbed' },

    { t: 'label', name: 'l_climax' },
    { t: 'objective', text: 'TALK HIM DOWN', done: true },
    { t: 'shot', pos: [-2.6, 2.2, 9.0], look: [0.2, 1.5, 12.8], fov: 36, handheld: 0.45, aperture: 0.9 },
    { t: 'lightning', delay: 0.2 },
    { t: 'wait', dur: 1.4 },
    { t: 'ifStat', name: 'trust', min: 3, goto: 'l_good' },
    { t: 'if', flag: 'grabbed', goto: 'l_grabbed' },
    { t: 'goto', label: 'l_bad' },

    // --- Best outcome: he lets her go.
    { t: 'label', name: 'l_good' },
    { t: 'node', id: 'saved' },
    { t: 'shot', pos: [0.8, EYE - 0.1, 11.5], target: 'deviant', fov: 44, handheld: 0.5 },
    { t: 'do', who: 'deviant', led: 'yellow', expr: 'sad', pose: 'idle' },
    { t: 'say', who: 'deviant', text: "Tell them I had a name. Tell them I let her go.", expr: 'sad', dur: 3.4 },
    { t: 'do', who: 'emma', walkTo: 'negotiate', look: 'connor', shiver: 0.4, pose: 'idle' },
    { t: 'shot', pos: [-2.4, 1.4, 10.2], target: 'emma', fov: 40, handheld: 0.5, to: [-2.8, 1.5, 8.6], move: 4 },
    { t: 'sfx', name: 'chime' },
    { t: 'music', mood: 3, level: 0.4 },
    { t: 'say', who: 'emma', text: 'You came. Nobody came before.', dur: 2.8, expr: 'sad', look: 'connor' },
    { t: 'shot', pos: [1.4, 2.0, 11.4], target: 'deviant', fov: 38, handheld: 0.6 },
    { t: 'do', who: 'deviant', pose: 'idle', expr: 'neutral', led: 'off' },
    { t: 'say', who: 'deviant', text: 'Six minutes.', dur: 1.8, expr: 'sad' },
    { t: 'wait', dur: 1.2 },
    { t: 'sfx', name: 'thunder' },
    { t: 'set', flag: 'emmaSaved' },
    { t: 'set', flag: 'victorSpared' },
    { t: 'goto', label: 'l_end' },

    // --- Rushed and succeeded: she lives, he goes over.
    { t: 'label', name: 'l_grabbed' },
    { t: 'node', id: 'saved' },
    { t: 'node', id: 'victorLost' },
    { t: 'shot', pos: [-1.0, 1.8, 10.0], look: [0.6, 1.2, 12.6], fov: 40, handheld: 0.8 },
    { t: 'sfx', name: 'glass' },
    { t: 'do', who: 'deviant', pose: 'dead', led: 'off' },
    { t: 'do', who: 'emma', mark: 'negotiate', pose: 'cower', look: 'connor', shiver: 1 },
    { t: 'shake', power: 0.7 },
    { t: 'say', who: 'connor', text: 'I have her. He went over the edge.', dur: 2.6, expr: 'pain', exprW: 0.5 },
    { t: 'shot', pos: [-3.0, 1.5, 8.4], target: 'emma', fov: 42, handheld: 0.5 },
    { t: 'say', who: 'emma', text: "He was crying. Did you see that he was crying?", dur: 3.2, expr: 'sad' },
    { t: 'music', mood: 2, level: 0.4 },
    { t: 'set', flag: 'emmaSaved' },
    { t: 'goto', label: 'l_end' },

    // --- Worst outcome: he takes the fall with her.
    { t: 'label', name: 'l_bad' },
    { t: 'node', id: 'lost' },
    { t: 'shot', pos: [0.6, EYE, 11.4], target: 'deviant', fov: 44, handheld: 0.7 },
    { t: 'do', who: 'deviant', led: 'red', expr: 'pain' },
    { t: 'say', who: 'deviant', text: "You were never here to save anybody. You were here to close a file.", expr: 'angry' },
    { t: 'qte', key: ' ', kind: 'mash', window: 2.6, caption: 'REACH FOR HER', shake: 0.9, onFail: 'l_fail' },
    { t: 'shot', pos: [-1.6, 2.2, 9.6], look: [0.4, 0.6, 13.4], fov: 36, handheld: 0.9 },
    { t: 'sfx', name: 'impact' },
    { t: 'shake', power: 1 },
    { t: 'do', who: 'deviant', pose: 'dead', led: 'off' },
    { t: 'do', who: 'emma', mark: 'negotiate', pose: 'cower', shiver: 1, look: 'connor' },
    { t: 'say', who: 'connor', text: 'I caught her wrist. I did not catch him.', dur: 3, expr: 'pain', exprW: 0.6 },
    { t: 'instability', delta: 0.14 },
    { t: 'set', flag: 'emmaSaved' },
    { t: 'music', mood: 2, level: 0.42 },
    { t: 'goto', label: 'l_end' },

    // --- Failure branch.
    { t: 'label', name: 'l_fail' },
    { t: 'node', id: 'fell' },
    { t: 'shot', pos: [-1.2, 2.6, 9.0], look: [0.4, 0.2, 14.2], fov: 34, handheld: 1.0 },
    { t: 'sfx', name: 'impact' },
    { t: 'flash', power: 0.4 },
    { t: 'shake', power: 1.2 },
    { t: 'do', who: 'deviant', pose: 'dead', led: 'off' },
    { t: 'do', who: 'emma', pose: 'dead' },
    { t: 'slowmo', scale: 0.4, dur: 2.4 },
    { t: 'wait', dur: 1.6 },
    { t: 'say', who: 'connor', text: 'Two hundred milliseconds too slow.', dur: 2.6, expr: 'pain', led: 'red' },
    { t: 'instability', delta: 0.25 },
    { t: 'music', mood: 2, level: 0.5 },
    { t: 'set', flag: 'emmaLost' },

    { t: 'label', name: 'l_end' },
    { t: 'shot', pos: [-6.5, 3.4, 4.5], target: 'connor', fov: 32, to: [-9.5, 6.2, -1.0], move: 8, handheld: 0.4, aperture: 0.7 },
    { t: 'do', who: 'hank', walkTo: 'approach', look: 'connor' },
    { t: 'wait', dur: 1.6 },
    { t: 'if', flag: 'emmaLost', goto: 'l_endBad' },
    { t: 'say', who: 'hank', text: "Forty minutes and nobody else could do that. Don't let it go to your head.", expr: 'neutral' },
    { t: 'goto', label: 'l_endOut' },
    { t: 'label', name: 'l_endBad' },
    { t: 'say', who: 'hank', text: "Machines don't get to look like that. Go on. Get off my roof.", expr: 'angry', exprW: 0.5 },
    { t: 'label', name: 'l_endOut' },
    { t: 'shot', pos: [-11, 8.0, -6], look: [0, 2, 8], fov: 30, to: [-13, 11, -12], move: 7, handheld: 0.3 },
    { t: 'wait', dur: 2.6 },
    { t: 'fade', to: 'black', dur: 2.4 },
    { t: 'ambience', stop: true },
    { t: 'chapterEnd', outcome: 'THE HOSTAGE' },
  ],
  flow: [
    { id: 'start', label: 'ROOFTOP', col: 0, row: 2, kind: 'start' },
    { id: 'scanned', label: 'SCENE ANALYSED', col: 1, row: 2, kind: 'action', from: ['start'] },
    { id: 'calm', label: 'STAYED CALM', col: 2, row: 0, kind: 'choice', from: ['scanned'] },
    { id: 'honest', label: 'WAS HONEST', col: 2, row: 1, kind: 'choice', from: ['scanned'] },
    { id: 'threat', label: 'THREATENED HIM', col: 2, row: 3, kind: 'choice', from: ['scanned'] },
    { id: 'silent', label: 'SAID NOTHING', col: 2, row: 4, kind: 'choice', from: ['scanned'] },
    { id: 'name', label: 'GAVE HIM A NAME', col: 3, row: 0, kind: 'choice', from: ['calm', 'honest'] },
    { id: 'trade', label: 'OFFERED YOURSELF', col: 3, row: 1, kind: 'choice', from: ['calm', 'honest'] },
    { id: 'rush', label: 'RUSHED HIM', col: 3, row: 3, kind: 'choice', from: ['threat', 'silent'] },
    { id: 'saved', label: 'EMMA SAVED', col: 4, row: 0, kind: 'end', from: ['name', 'trade', 'rush'] },
    { id: 'victorLost', label: 'VICTOR DESTROYED', col: 4, row: 2, kind: 'end', from: ['rush'] },
    { id: 'lost', label: 'HE JUMPED', col: 4, row: 3, kind: 'end', from: ['threat', 'silent'] },
    { id: 'fell', label: 'BOTH FELL', col: 4, row: 4, kind: 'death', from: ['rush', 'silent'] },
  ],
};
