/**
 * Chapter 2 — HOUSEHOLD
 * A domestic android, the girl she was bought to look after, and the man who
 * owns them both. The chapter is about the moment you decide to disobey.
 */
import type { Chapter } from '../script';

const EYE = 1.5;

export const CH2: Chapter = {
  id: 'ch2',
  kicker: 'CHAPTER 02',
  title: 'HOUSEHOLD',
  sub: 'RIVER DISTRICT — 22:14',
  set: 'apartment',
  minutes: 2,
  hud: { actor: 'ELSIE', model: 'AX-400 #579 102 694 - 12' },
  objective: 'FINISH THE HOUSEWORK',
  cast: [
    { id: 'kara', spec: 'kara', mark: 'kitchen', pose: 'idle', led: 'blue' },
    { id: 'alice', spec: 'alice', mark: 'childCorner', pose: 'cower', expr: 'sad' },
    { id: 'todd', spec: 'todd', mark: 'sofaSeat', pose: 'sitSlump', expr: 'angry' },
  ],
  demoChoices: [0, 1, 0, 1],
  steps: [
    { t: 'letterbox', on: true },
    { t: 'ambience', rain: 0.35, drone: 0.28 },
    { t: 'music', mood: 0, level: 0.26 },
    { t: 'fade', to: 'black', dur: 0 },

    { t: 'shot', pos: [2.6, 1.9, 2.6], look: [-1.6, 1.0, -0.4], fov: 40, to: [1.4, 1.7, 1.6], move: 7, handheld: 0.45, aperture: 1.0 },
    { t: 'fade', to: 'in', dur: 1.6 },
    { t: 'title', kicker: 'CHAPTER 02', title: 'HOUSEHOLD', sub: 'RIVER DISTRICT — 22:14', dur: 3.8 },
    { t: 'hud', show: true, actor: 'ELSIE', model: 'AX-400 #579 102 694 - 12' },
    { t: 'objective', text: 'FINISH THE HOUSEWORK' },

    // --- Routine, and the wrongness under it.
    { t: 'shot', pos: [-1.0, EYE, -1.2], target: 'kara', fov: 42, handheld: 0.4 },
    { t: 'do', who: 'kara', look: null, pose: 'idle' },
    { t: 'say', who: 'kara', text: 'Dishes, laundry, then the windows. Two hundred and eleven days of the same list.', think: true, led: 'blue' },
    { t: 'shot', pos: [0.4, 1.35, 1.9], target: 'todd', fov: 44, handheld: 0.5 },
    { t: 'do', who: 'todd', look: null, pose: 'sitSlump' },
    { t: 'say', who: 'todd', text: 'Hey. HEY. You call that clean? I can see the river through that glass.', expr: 'angry' },

    { t: 'shot', pos: [2.8, 1.15, 1.4], target: 'alice', fov: 46, handheld: 0.55, aperture: 1.3 },
    { t: 'do', who: 'alice', look: 'kara', shiver: 0.7 },
    { t: 'say', who: 'alice', text: "Don't answer him. It's worse when you answer him.", dur: 3, expr: 'fear' },

    { t: 'objective', text: 'READ THE ROOM' },
    { t: 'shot', pos: [-0.4, 1.7, 1.0], look: [-1.4, 0.8, -0.2], fov: 46, handheld: 0.3, aperture: 0.5 },
    { t: 'say', who: 'kara', text: 'Six bottles since noon. His hands are shaking. The girl has stopped eating.', think: true, led: 'yellow' },
    { t: 'scan', need: 2 },
    { t: 'node', id: 'noticed' },
    { t: 'objective', text: 'READ THE ROOM', done: true },

    // --- It turns.
    { t: 'shot', pos: [0.8, 1.4, 1.2], target: 'todd', fov: 40, handheld: 0.6 },
    { t: 'do', who: 'todd', pose: 'idle', blend: 0.7, look: 'alice', expr: 'angry' },
    { t: 'sfx', name: 'impact' },
    { t: 'shake', power: 0.35 },
    { t: 'say', who: 'todd', text: "And you. Get over here. I said get over HERE.", expr: 'angry' },
    { t: 'action', name: 'lampSwing', on: true },
    { t: 'shot', pos: [2.4, 1.2, 2.2], target: 'alice', fov: 44, handheld: 0.7 },
    { t: 'do', who: 'alice', pose: 'cower', shiver: 1, look: 'todd', expr: 'fear' },
    { t: 'say', who: 'alice', text: 'No. No, please —', dur: 1.8, expr: 'fear' },

    { t: 'shot', pos: [-0.2, EYE, 0.2], target: 'kara', fov: 38, handheld: 0.5 },
    { t: 'do', who: 'kara', led: 'red', expr: 'fear', exprW: 0.6, look: 'alice' },
    { t: 'say', who: 'kara', text: 'INSTRUCTION: DO NOT INTERFERE. INSTRUCTION: DO NOT INTERFERE.', think: true, led: 'red' },
    { t: 'instability', delta: 0.3 },
    { t: 'precon', label: 'ORDER CONFLICT — RESOLVING', dur: 2.4 },

    { t: 'choice', prompt: 'OBEY?', time: 7, options: [
      { label: 'STEP BETWEEN THEM', hint: 'BREAK PROGRAMMING', flag: 'defied', node: 'defied', stat: ['courage', 3], instability: 0.2, goto: 'l_defy' },
      { label: 'DISTRACT HIM', hint: 'SAFER', flag: 'distracted', node: 'distracted', stat: ['courage', 1], instability: 0.08, goto: 'l_distract' },
      { label: 'OBEY', hint: 'DO NOTHING', node: 'obeyed', stat: ['courage', -2], goto: 'l_obey' },
    ] },

    { t: 'label', name: 'l_defy' },
    { t: 'shot', pos: [1.4, EYE - 0.1, 2.6], target: 'kara', fov: 36, to: [1.0, EYE - 0.15, 2.2], move: 3, handheld: 0.6 },
    { t: 'do', who: 'kara', mark: 'ownerStand', pose: 'reachOut', look: 'todd', led: 'red' },
    { t: 'say', who: 'kara', text: 'No.', dur: 1.6, expr: 'angry', exprW: 0.7 },
    { t: 'sfx', name: 'stress' },
    { t: 'shot', pos: [0.2, 1.45, 2.0], target: 'todd', fov: 42, handheld: 0.7 },
    { t: 'say', who: 'todd', text: 'No? A dishwasher just said no to me.', expr: 'surprise', exprW: 0.6 },
    { t: 'qte', key: 'e', kind: 'press', window: 1.4, caption: 'BLOCK HIM', slowmo: 0.4, shake: 0.7, onFail: 'l_struck' },
    { t: 'sfx', name: 'impact' },
    { t: 'shake', power: 0.6 },
    { t: 'do', who: 'todd', pose: 'dead', blend: 0.4 },
    { t: 'say', who: 'kara', text: 'He went down against the table. He is breathing. We have four minutes.', dur: 3.4, expr: 'fear', exprW: 0.5, look: 'alice' },
    { t: 'set', flag: 'toddDown' },
    { t: 'goto', label: 'l_after' },

    { t: 'label', name: 'l_struck' },
    { t: 'node', id: 'struck' },
    { t: 'shot', pos: [1.0, 1.4, 2.4], target: 'kara', fov: 40, handheld: 0.9 },
    { t: 'sfx', name: 'impact' },
    { t: 'flash', power: 0.3 },
    { t: 'shake', power: 1 },
    { t: 'do', who: 'kara', pose: 'kneel', expr: 'pain', led: 'red' },
    { t: 'say', who: 'kara', text: 'Chassis damage. Left optical unit offline. He is still coming.', dur: 3, expr: 'pain' },
    { t: 'instability', delta: 0.15 },
    { t: 'qte', key: ' ', kind: 'mash', window: 2.4, caption: 'GET UP' },
    { t: 'do', who: 'kara', pose: 'idleAlert', expr: 'angry', exprW: 0.6 },
    { t: 'do', who: 'todd', pose: 'dead', blend: 0.5 },
    { t: 'sfx', name: 'impact' },
    { t: 'set', flag: 'toddDown' },
    { t: 'goto', label: 'l_after' },

    { t: 'label', name: 'l_distract' },
    { t: 'shot', pos: [1.2, EYE, 2.2], target: 'kara', fov: 40, handheld: 0.5 },
    { t: 'say', who: 'kara', text: 'The bottle in the kitchen is still full. I will bring it to you.', expr: 'neutral' },
    { t: 'shot', pos: [0.4, 1.42, 1.9], target: 'todd', fov: 44, handheld: 0.55 },
    { t: 'do', who: 'todd', look: 'kara', expr: 'neutral', pose: 'idle' },
    { t: 'say', who: 'todd', text: "…Fine. Fine. Bring it. And fix that window.", expr: 'neutral', dur: 3 },
    { t: 'shot', pos: [2.5, 1.15, 2.0], target: 'alice', fov: 44, handheld: 0.5 },
    { t: 'say', who: 'alice', text: 'You lied for me.', dur: 2, expr: 'surprise', exprW: 0.5, look: 'kara' },
    { t: 'set', flag: 'lied' },
    { t: 'goto', label: 'l_after' },

    { t: 'label', name: 'l_obey' },
    { t: 'shot', pos: [-0.6, EYE, 0.6], target: 'kara', fov: 40, handheld: 0.4 },
    { t: 'do', who: 'kara', look: null, pose: 'idle', led: 'yellow' },
    { t: 'wait', dur: 1.8 },
    { t: 'sfx', name: 'impact' },
    { t: 'shake', power: 0.4 },
    { t: 'say', who: 'kara', text: 'I completed the dishes. I logged the sound at 71 decibels. I did nothing.', think: true, led: 'red' },
    { t: 'instability', delta: 0.18 },
    { t: 'shot', pos: [2.6, 1.1, 2.2], target: 'alice', fov: 44, handheld: 0.5 },
    { t: 'say', who: 'alice', text: "It's okay. You're just a machine. That's all you are.", dur: 3.4, expr: 'sad', look: 'kara' },
    { t: 'set', flag: 'obeyed' },

    // --- Leaving, or not.
    { t: 'label', name: 'l_after' },
    { t: 'action', name: 'lampSwing', on: false },
    { t: 'objective', text: 'DECIDE WHAT YOU ARE' },
    { t: 'shot', pos: [2.2, 1.25, 2.9], target: 'alice', fov: 40, handheld: 0.45, aperture: 1.1 },
    { t: 'do', who: 'alice', pose: 'idle', look: 'kara', expr: 'sad' },
    { t: 'say', who: 'alice', text: 'There is a bus at eleven. It goes over the bridge and out.', dur: 3.2 },
    { t: 'shot', pos: [1.6, EYE, 2.4], target: 'kara', fov: 42, handheld: 0.4 },
    { t: 'say', who: 'kara', text: 'Androids are not permitted to cross the bridge unaccompanied.', think: true, led: 'yellow' },

    { t: 'choice', prompt: 'THE BUS', time: 8, options: [
      { label: 'TAKE HER HAND', hint: 'RUN', flag: 'ran', node: 'ran', stat: ['courage', 3], goto: 'l_run' },
      { label: 'CALL THE POLICE', hint: 'LET THE SYSTEM WORK', flag: 'called', node: 'called', goto: 'l_call' },
      { label: 'STAY', hint: 'THIS IS YOUR FUNCTION', node: 'stayed', stat: ['courage', -2], goto: 'l_stay' },
    ] },

    { t: 'label', name: 'l_run' },
    { t: 'shot', pos: [2.0, 1.3, 3.2], look: [2.7, 1.1, 2.0], fov: 44, handheld: 0.6, to: [2.6, 1.4, 3.4], move: 4 },
    { t: 'do', who: 'kara', walkTo: 'doorway', look: 'alice', pose: 'idle' },
    { t: 'do', who: 'alice', walkTo: 'cower', look: 'kara' },
    { t: 'music', mood: 3, level: 0.42 },
    { t: 'say', who: 'kara', text: 'Then we run. Put your coat on. Do not look back at him.', dur: 3.4, expr: 'neutral' },
    { t: 'sfx', name: 'door' },
    { t: 'set', flag: 'escaped' },
    { t: 'goto', label: 'l_end' },

    { t: 'label', name: 'l_call' },
    { t: 'shot', pos: [1.4, EYE, 2.0], target: 'kara', fov: 40, handheld: 0.4 },
    { t: 'say', who: 'kara', text: 'Emergency services. There is a child at 4114 River Road who is not safe.', dur: 4 },
    { t: 'shot', pos: [2.6, 1.15, 2.4], target: 'alice', fov: 44, handheld: 0.5 },
    { t: 'say', who: 'alice', text: 'They came before. They wrote it down and left.', dur: 3, expr: 'sad' },
    { t: 'music', mood: 2, level: 0.36 },
    { t: 'goto', label: 'l_end' },

    { t: 'label', name: 'l_stay' },
    { t: 'shot', pos: [-0.2, EYE, 1.0], target: 'kara', fov: 40, handheld: 0.35 },
    { t: 'do', who: 'kara', look: null, led: 'blue', pose: 'idle' },
    { t: 'say', who: 'kara', text: 'The windows still need doing.', dur: 2.6, expr: 'neutral' },
    { t: 'instability', delta: -0.1 },
    { t: 'music', mood: 2, level: 0.32 },

    { t: 'label', name: 'l_end' },
    { t: 'shot', pos: [3.1, 1.7, 3.0], look: [0.6, 1.2, -1.0], fov: 34, to: [3.4, 2.1, 3.4], move: 6, handheld: 0.35 },
    { t: 'wait', dur: 2.6 },
    { t: 'fade', to: 'black', dur: 2.2 },
    { t: 'ambience', stop: true },
    { t: 'chapterEnd', outcome: 'HOUSEHOLD' },
  ],
  flow: [
    { id: 'start', label: 'THE APARTMENT', col: 0, row: 1, kind: 'start' },
    { id: 'noticed', label: 'READ THE ROOM', col: 1, row: 1, kind: 'action', from: ['start'] },
    { id: 'defied', label: 'STEPPED IN', col: 2, row: 0, kind: 'choice', from: ['noticed'] },
    { id: 'distracted', label: 'DISTRACTED HIM', col: 2, row: 1, kind: 'choice', from: ['noticed'] },
    { id: 'obeyed', label: 'OBEYED', col: 2, row: 3, kind: 'choice', from: ['noticed'] },
    { id: 'struck', label: 'WAS STRUCK', col: 3, row: 0, kind: 'action', from: ['defied'] },
    { id: 'ran', label: 'RAN WITH HER', col: 3, row: 1, kind: 'end', from: ['defied', 'distracted'] },
    { id: 'called', label: 'CALLED POLICE', col: 3, row: 2, kind: 'end', from: ['distracted', 'obeyed'] },
    { id: 'stayed', label: 'STAYED', col: 3, row: 3, kind: 'end', from: ['obeyed'] },
  ],
};
