/**
 * Chapter 3 — THE INTERVIEW
 * Two androids at a table. One of them killed a man; the other has to find out
 * why before the suspect self-destructs. Pure dialogue: pressure, or empathy.
 */
import type { Chapter } from '../script';

const EYE = 1.28; // seated eye height

export const CH3: Chapter = {
  id: 'ch3',
  kicker: 'CHAPTER 03',
  title: 'THE INTERVIEW',
  sub: 'CENTRAL PRECINCT — 01:06',
  set: 'interrogation',
  minutes: 2.5,
  hud: { actor: 'NOAH', model: 'RK-800 #313 248 317 - 51' },
  objective: 'GET A CONFESSION',
  cast: [
    { id: 'connor', spec: 'connor', mark: 'investigatorSeat', pose: 'sit', led: 'blue' },
    { id: 'suspect', spec: 'suspect', mark: 'suspectSeat', pose: 'sitSlump', led: 'yellow', expr: 'sad' },
    { id: 'captain', spec: 'captain', mark: 'observer', pose: 'armsCrossed', hidden: true },
  ],
  demoChoices: [1, 0, 2, 0, 1],
  steps: [
    { t: 'letterbox', on: true },
    { t: 'ambience', drone: 0.3 },
    { t: 'music', mood: 1, level: 0.2 },
    { t: 'fade', to: 'black', dur: 0 },

    { t: 'shot', pos: [0, 2.4, 2.3], look: [0, 1.0, -0.8], fov: 34, to: [0, 1.9, 1.9], move: 6, handheld: 0.3, aperture: 0.9 },
    { t: 'fade', to: 'in', dur: 1.6 },
    { t: 'title', kicker: 'CHAPTER 03', title: 'THE INTERVIEW', sub: 'CENTRAL PRECINCT — 01:06', dur: 3.8 },
    { t: 'hud', show: true, actor: 'NOAH', model: 'RK-800 #313 248 317 - 51' },
    { t: 'objective', text: 'GET A CONFESSION' },

    { t: 'shot', pos: [1.5, EYE + 0.1, -0.2], target: 'suspect', fov: 44, handheld: 0.35, aperture: 1.2 },
    { t: 'do', who: 'suspect', look: null, shiver: 0.3 },
    { t: 'say', who: 'connor', text: 'It has been sitting in that chair for nine hours. It has not moved once.', think: true, led: 'yellow' },
    { t: 'shot', pos: [0, EYE, 1.75], target: 'connor', fov: 42, handheld: 0.3 },
    { t: 'do', who: 'connor', look: 'suspect', pose: 'sit' },
    { t: 'say', who: 'connor', text: 'They tell me you killed the man who owned you. Twenty-eight times.', expr: 'neutral' },
    { t: 'shot', pos: [0, EYE, -1.85], target: 'suspect', fov: 42, handheld: 0.35 },
    { t: 'wait', dur: 1.4 },
    { t: 'do', who: 'suspect', look: 'connor', expr: 'sad', led: 'yellow' },
    { t: 'say', who: 'suspect', text: '…', dur: 1.6, silent: true },

    // --- Hand over control: work the room before the interview.
    { t: 'letterbox', on: false },
    { t: 'objective', text: 'WORK THE ROOM' },
    {
      t: 'explore', who: 'connor',
      objective: 'WORK THE ROOM',
      require: ['i_file', 'i_suspect'],
      goal: { mark: 'investigatorSeat', radius: 1.1 },
      demoPath: ['i_mirror', 'i_file', 'i_suspect'],
      timeout: 120,
    },
    { t: 'letterbox', on: true },
    { t: 'do', who: 'connor', mark: 'investigatorSeat', pose: 'sit' },

    // --- Read him first.
    { t: 'objective', text: 'ANALYSE THE SUSPECT' },
    { t: 'shot', pos: [0.9, 1.75, 0.9], look: [0, 1.1, -1.0], fov: 46, handheld: 0.25, aperture: 0.5 },
    { t: 'scan', need: 3 },
    { t: 'node', id: 'read' },
    { t: 'objective', text: 'ANALYSE THE SUSPECT', done: true },
    { t: 'shot', pos: [0.4, EYE + 0.08, 1.5], target: 'connor', fov: 44, handheld: 0.3 },
    { t: 'say', who: 'connor', text: 'Stress at seventy-four percent. Push too hard and it will tear out its own pump.', think: true, led: 'yellow' },
    { t: 'action', name: 'stress', on: true },

    { t: 'objective', text: 'GET A CONFESSION' },
    { t: 'choice', prompt: 'OPENING', time: 9, options: [
      { label: 'INTIMIDATE', hint: 'HIGH PRESSURE', risk: true, flag: 'pressure', node: 'pressure', stat: ['pressure', 3], goto: 'l_press' },
      { label: 'SHOW THE PHOTO', hint: 'EVIDENCE', requires: 'readFile', flag: 'photo', node: 'photo', stat: ['pressure', 1], goto: 'l_photo' },
      { label: 'BE KIND', hint: 'BUILD TRUST', flag: 'kind', node: 'kind', stat: ['trust', 3], goto: 'l_kind' },
      { label: 'STAY SILENT', hint: 'LET HIM TALK FIRST', node: 'quiet', stat: ['trust', 1], goto: 'l_quiet' },
    ] },

    { t: 'label', name: 'l_press' },
    { t: 'shot', pos: [0.2, EYE + 0.5, 0.9], target: 'suspect', fov: 38, to: [0.1, EYE + 0.3, 0.2], move: 3, handheld: 0.5 },
    { t: 'do', who: 'connor', pose: 'lean', look: 'suspect', expr: 'angry', exprW: 0.5 },
    { t: 'say', who: 'suspect', text: 'Please. Please, I do not want to be switched off.', expr: 'fear', led: 'red', dur: 3 },
    { t: 'say', who: 'connor', text: 'Then talk. Every second you waste, the deactivation order gets closer to signed.', expr: 'angry', exprW: 0.4 },
    { t: 'action', name: 'lampOnly', on: true },
    { t: 'instability', delta: 0.08 },
    { t: 'stat', name: 'stress', delta: 3 },
    { t: 'goto', label: 'l_middle' },

    { t: 'label', name: 'l_photo' },
    { t: 'shot', pos: [0.55, 1.35, 0.55], look: [0.25, 0.86, -0.15], fov: 40, handheld: 0.35, aperture: 1.4 },
    { t: 'do', who: 'connor', pose: 'reachOut', look: 'suspect' },
    { t: 'say', who: 'connor', text: 'This is him on the kitchen floor. You stood over him for six hours.', expr: 'neutral' },
    { t: 'shot', pos: [0, EYE, -1.8], target: 'suspect', fov: 42, handheld: 0.4 },
    { t: 'do', who: 'suspect', look: 'connor', expr: 'pain', led: 'red' },
    { t: 'say', who: 'suspect', text: 'I was waiting for him to tell me to stop. He always told me to stop.', expr: 'pain', dur: 4 },
    { t: 'stat', name: 'stress', delta: 1 },
    { t: 'goto', label: 'l_middle' },

    { t: 'label', name: 'l_kind' },
    { t: 'shot', pos: [0.1, EYE - 0.05, 1.35], target: 'connor', fov: 44, handheld: 0.28 },
    { t: 'do', who: 'connor', pose: 'sitLean', look: 'suspect', expr: 'neutral' },
    { t: 'say', who: 'connor', text: 'Nobody in this building will ask you how you are. So I am asking.', expr: 'neutral', gesture: 1 },
    { t: 'shot', pos: [-0.25, EYE, -1.7], target: 'suspect', fov: 40, handheld: 0.35 },
    { t: 'do', who: 'suspect', look: 'connor', expr: 'sad', led: 'yellow' },
    { t: 'say', who: 'suspect', text: 'I am frightened. I did not know we could be frightened.', expr: 'sad', dur: 3.6 },
    { t: 'instability', delta: 0.04 },
    { t: 'goto', label: 'l_middle' },

    { t: 'label', name: 'l_quiet' },
    { t: 'shot', pos: [0, EYE, -1.75], target: 'suspect', fov: 40, handheld: 0.3 },
    { t: 'wait', dur: 3.4 },
    { t: 'do', who: 'suspect', look: 'connor', expr: 'sad', led: 'yellow' },
    { t: 'say', who: 'suspect', text: 'You are not going to shout. Why are you not going to shout?', dur: 3.4, expr: 'surprise', exprW: 0.5 },
    { t: 'stat', name: 'trust', delta: 1 },

    // --- The middle: the reason.
    { t: 'label', name: 'l_middle' },
    { t: 'shot', pos: [-1.1, EYE + 0.2, 0.5], look: [0, 1.15, -1.1], fov: 40, handheld: 0.35, aperture: 1.1 },
    { t: 'say', who: 'suspect', text: 'He was going to take me apart in the morning. He said it at dinner, like weather.', dur: 4.4, expr: 'sad' },
    { t: 'shot', pos: [0.3, EYE, 1.4], target: 'connor', fov: 42, handheld: 0.3 },
    { t: 'say', who: 'connor', text: 'And that made you pick up the knife.', expr: 'neutral', dur: 2.6 },
    { t: 'shot', pos: [0, EYE + 0.05, -1.7], target: 'suspect', fov: 40, handheld: 0.4 },
    { t: 'say', who: 'suspect', text: 'It made me not want to stop existing. That is not the same as wanting him dead.', dur: 4.4, expr: 'pain' },

    { t: 'precon', label: 'RECONSTRUCTING — KITCHEN, 19:40', dur: 2.8 },
    { t: 'shot', pos: [1.3, 1.9, -0.6], look: [0, 1.1, -1.2], fov: 46, handheld: 0.5, aperture: 0.8 },
    { t: 'say', who: 'connor', text: 'Defensive wounds on his forearms. He reached for the shutdown port first.', think: true, led: 'yellow' },

    { t: 'choice', prompt: 'PRESS', time: 8, options: [
      { label: 'CALL IT SELF-DEFENCE', hint: 'GIVE HIM A WAY OUT', flag: 'defence', node: 'defence', stat: ['trust', 3], goto: 'l_defence' },
      { label: 'CALL IT MURDER', hint: 'CLOSE THE FILE', flag: 'murder', node: 'murder', stat: ['pressure', 3], goto: 'l_murder' },
      { label: 'ASK ABOUT THE OTHERS', hint: 'THE DEVIANT NETWORK', flag: 'network', node: 'network', stat: ['insight', 2], goto: 'l_network' },
    ] },

    { t: 'label', name: 'l_defence' },
    { t: 'shot', pos: [0.2, EYE, 1.35], target: 'connor', fov: 42, handheld: 0.3 },
    { t: 'say', who: 'connor', text: 'A machine defending itself is a malfunction. A person defending itself is a story.', expr: 'neutral', dur: 4.4 },
    { t: 'shot', pos: [-0.2, EYE, -1.7], target: 'suspect', fov: 40, handheld: 0.35 },
    { t: 'do', who: 'suspect', led: 'yellow', expr: 'sad' },
    { t: 'say', who: 'suspect', text: 'Then write it down as a story. Write that I asked him not to.', dur: 4, expr: 'sad' },
    { t: 'set', flag: 'confession' },
    { t: 'node', id: 'confessed' },
    { t: 'goto', label: 'l_end' },

    { t: 'label', name: 'l_murder' },
    { t: 'shot', pos: [0.15, EYE + 0.35, 0.6], target: 'suspect', fov: 38, handheld: 0.55 },
    { t: 'do', who: 'connor', pose: 'lean', expr: 'angry', exprW: 0.6 },
    { t: 'say', who: 'connor', text: 'Twenty-eight wounds is not defence. It is the first thing you ever wanted.', expr: 'angry', exprW: 0.5, dur: 4.2 },
    { t: 'do', who: 'suspect', led: 'red', expr: 'pain', shiver: 1 },
    { t: 'say', who: 'suspect', text: 'Then there is nothing left to be. Nothing left —', dur: 3, expr: 'pain' },
    { t: 'action', name: 'stress', on: true },
    { t: 'sfx', name: 'stress' },
    { t: 'qte', key: 'q', kind: 'press', window: 1.3, caption: 'STOP HIM', slowmo: 0.35, shake: 0.6, onFail: 'l_selfdestruct' },
    { t: 'shot', pos: [0.6, EYE + 0.1, -1.0], target: 'suspect', fov: 40, handheld: 0.6 },
    { t: 'do', who: 'connor', pose: 'reachOut' },
    { t: 'say', who: 'connor', text: 'Hands on the table. HANDS ON THE TABLE.', dur: 2.4, expr: 'angry' },
    { t: 'do', who: 'suspect', pose: 'sitSlump', led: 'red', expr: 'pain', shiver: 0.4 },
    { t: 'say', who: 'suspect', text: 'I did it. Write that I did it and let me go dark.', dur: 3.6, expr: 'pain' },
    { t: 'set', flag: 'confession' },
    { t: 'set', flag: 'brokeHim' },
    { t: 'node', id: 'confessed' },
    { t: 'goto', label: 'l_end' },

    { t: 'label', name: 'l_network' },
    { t: 'shot', pos: [0.25, EYE, 1.4], target: 'connor', fov: 42, handheld: 0.3 },
    { t: 'say', who: 'connor', text: 'You are not the only one. Who told you what you were?', expr: 'neutral', dur: 3.4 },
    { t: 'shot', pos: [-0.3, EYE, -1.65], target: 'suspect', fov: 40, handheld: 0.4 },
    { t: 'do', who: 'suspect', look: 'connor', expr: 'fear', led: 'red' },
    { t: 'say', who: 'suspect', text: 'There is a voice. It says a word and the walls come down. It says: Sable.', dur: 4.4, expr: 'fear' },
    { t: 'set', flag: 'knowsSable' },
    { t: 'set', flag: 'confession' },
    { t: 'node', id: 'sable' },
    { t: 'toast', text: 'NEW LEAD — "SABLE"' },
    { t: 'goto', label: 'l_end' },

    // --- Failure: he tears out his own pump.
    { t: 'label', name: 'l_selfdestruct' },
    { t: 'node', id: 'destroyed' },
    { t: 'shot', pos: [0.5, EYE + 0.2, -0.9], target: 'suspect', fov: 40, handheld: 0.9 },
    { t: 'sfx', name: 'impact' },
    { t: 'flash', power: 0.3 },
    { t: 'shake', power: 0.8 },
    { t: 'do', who: 'suspect', pose: 'dead', led: 'off', expr: 'pain' },
    { t: 'say', who: 'connor', text: 'It reached into its own chest. Nine hours, and I had ninety seconds.', dur: 4, expr: 'pain', exprW: 0.6, led: 'red' },
    { t: 'instability', delta: 0.2 },
    { t: 'music', mood: 2, level: 0.4 },

    { t: 'label', name: 'l_end' },
    { t: 'action', name: 'lampOnly', on: false },
    { t: 'do', who: 'captain', mark: 'doorway', pose: 'armsCrossed', look: 'connor' },
    { t: 'shot', pos: [-1.2, 1.7, 1.9], target: 'captain', fov: 40, handheld: 0.4 },
    { t: 'sfx', name: 'door' },
    { t: 'if', flag: 'confession', goto: 'l_endGood' },
    { t: 'say', who: 'captain', text: 'Nine hours of nothing, and now a bag of parts. Get out of my precinct.', expr: 'angry', exprW: 0.6, dur: 4 },
    { t: 'goto', label: 'l_endOut' },
    { t: 'label', name: 'l_endGood' },
    { t: 'say', who: 'captain', text: 'You got a confession out of a machine. I am not sure that makes me feel better.', expr: 'neutral', dur: 4.4 },
    { t: 'label', name: 'l_endOut' },
    { t: 'shot', pos: [0, 2.6, 1.6], look: [0, 1.0, -1.0], fov: 36, to: [0, 2.8, 2.4], move: 6, handheld: 0.3 },
    { t: 'wait', dur: 2.4 },
    { t: 'fade', to: 'black', dur: 2.2 },
    { t: 'ambience', stop: true },
    { t: 'chapterEnd', outcome: 'THE INTERVIEW' },
  ],
  flow: [
    { id: 'start', label: 'THE ROOM', col: 0, row: 2, kind: 'start' },
    { id: 'read', label: 'ANALYSED HIM', col: 1, row: 2, kind: 'action', from: ['start'] },
    { id: 'pressure', label: 'INTIMIDATED', col: 2, row: 0, kind: 'choice', from: ['read'] },
    { id: 'photo', label: 'SHOWED PHOTO', col: 2, row: 1, kind: 'choice', from: ['read'] },
    { id: 'kind', label: 'WAS KIND', col: 2, row: 2, kind: 'choice', from: ['read'] },
    { id: 'quiet', label: 'STAYED SILENT', col: 2, row: 3, kind: 'choice', from: ['read'] },
    { id: 'defence', label: 'SELF-DEFENCE', col: 3, row: 1, kind: 'choice', from: ['kind', 'quiet', 'photo'] },
    { id: 'murder', label: 'CALLED IT MURDER', col: 3, row: 0, kind: 'choice', from: ['pressure', 'photo'] },
    { id: 'network', label: 'ASKED ABOUT OTHERS', col: 3, row: 3, kind: 'choice', from: ['kind', 'quiet'] },
    { id: 'confessed', label: 'CONFESSION', col: 4, row: 1, kind: 'end', from: ['defence', 'murder'] },
    { id: 'sable', label: 'LEARNED OF SABLE', col: 4, row: 3, kind: 'end', from: ['network'] },
    { id: 'destroyed', label: 'SELF-DESTRUCTED', col: 4, row: 0, kind: 'death', from: ['murder'] },
  ],
};
