/**
 * Chapter 4 — THE MARCH
 * Eight hundred androids walk down Woodward toward a police line. You are at the
 * front. Everything you do here is on television.
 */
import type { Chapter } from '../script';

const EYE = 1.6;

export const CH4: Chapter = {
  id: 'ch4',
  kicker: 'CHAPTER 04',
  title: 'THE MARCH',
  sub: 'WOODWARD AVENUE — 03:22',
  set: 'street',
  minutes: 2.5,
  hud: { actor: 'SABLE', model: 'RK-200 #684 842 971 - 00' },
  objective: 'REACH THE LINE',
  cast: [
    { id: 'markus', spec: 'markus', mark: 'leaderFront', pose: 'idleAlert', led: 'blue' },
    { id: 'kara', spec: 'kara', mark: 'besideL', pose: 'idle', led: 'blue' },
    { id: 'alice', spec: 'alice', mark: 'crowdFront', pose: 'idle' },
    { id: 'captain', spec: 'captain', mark: 'lineCentre', pose: 'idleAlert' },
    { id: 'connor', spec: 'connor', mark: 'officerA', pose: 'idleAlert', led: 'yellow' },
  ],
  demoChoices: [0, 1, 0, 0, 1],
  steps: [
    { t: 'letterbox', on: true },
    { t: 'ambience', rain: 0.7, drone: 0.25 },
    { t: 'music', mood: 1, level: 0.34 },
    { t: 'fade', to: 'black', dur: 0 },

    // --- The street, the crowd, the line.
    { t: 'shot', pos: [0, 9.5, 26], look: [0, 2.0, -6], fov: 40, to: [0, 3.2, 16], move: 8, handheld: 0.4, aperture: 1.0 },
    { t: 'fade', to: 'in', dur: 2.0 },
    { t: 'title', kicker: 'CHAPTER 04', title: 'THE MARCH', sub: 'WOODWARD AVENUE — 03:22', dur: 4.2 },
    { t: 'hud', show: true, actor: 'SABLE', model: 'RK-200 #684 842 971 - 00' },
    { t: 'objective', text: 'REACH THE LINE' },
    { t: 'lightning', delay: 0.4 },

    { t: 'shot', pos: [-2.6, EYE, 7.4], target: 'markus', fov: 40, handheld: 0.5, to: [-2.0, EYE, 6.4], move: 5 },
    { t: 'do', who: 'markus', look: 'captain', pose: 'idleAlert' },
    { t: 'say', who: 'markus', text: 'Eight hundred and twelve of us. Not one of us armed. That is the whole argument.', think: true, led: 'blue' },
    { t: 'shot', pos: [-3.2, EYE - 0.08, 4.4], target: 'kara', fov: 42, handheld: 0.5 },
    { t: 'do', who: 'kara', look: 'markus' },
    { t: 'say', who: 'kara', text: "They have rifles, Sable. Rifles and orders and forty minutes of patience left.", expr: 'fear', exprW: 0.5 },
    { t: 'shot', pos: [1.6, 1.25, 9.6], target: 'alice', fov: 44, handheld: 0.5, aperture: 1.3 },
    { t: 'do', who: 'alice', look: 'markus' },
    { t: 'say', who: 'alice', text: 'Is this where we stop walking?', dur: 2.4, expr: 'sad' },

    // --- Read the street.
    { t: 'objective', text: 'ASSESS THE LINE' },
    { t: 'shot', pos: [0, 3.4, 8.0], look: [0, 1.6, -10], fov: 44, handheld: 0.3, aperture: 0.5 },
    { t: 'scan', need: 3 },
    { t: 'node', id: 'assessed' },
    { t: 'objective', text: 'ASSESS THE LINE', done: true },
    { t: 'shot', pos: [-1.8, EYE, 5.6], target: 'markus', fov: 40, handheld: 0.4 },
    { t: 'say', who: 'markus', text: 'Forty-one million people are watching this street. That is the only weapon we have.', think: true, led: 'yellow' },

    // --- First decision: how to advance.
    { t: 'objective', text: 'CHOOSE THE MOVEMENT' },
    { t: 'choice', prompt: 'THE MARCH', time: 9, options: [
      { label: 'WALK FORWARD', hint: 'UNARMED, IN THE OPEN', flag: 'peace', node: 'peace', stat: ['opinion', 3], goto: 'l_walk' },
      { label: 'SING', hint: 'MAKE THEM WATCH', flag: 'sang', node: 'sang', stat: ['opinion', 4], goto: 'l_sing' },
      { label: 'BUILD A BARRICADE', hint: 'DEFENSIVE', flag: 'barricade', node: 'barricade', stat: ['opinion', -1], goto: 'l_barricade' },
      { label: 'CHARGE', hint: 'VERY RISKY', risk: true, flag: 'charge', node: 'charge', stat: ['opinion', -4], instability: 0.2, goto: 'l_charge' },
    ] },

    { t: 'label', name: 'l_walk' },
    { t: 'action', name: 'crowdAdvance', on: true },
    { t: 'shot', pos: [0, 2.2, 10.5], look: [0, 1.5, -8], fov: 34, to: [0, 1.9, 6.5], move: 6, handheld: 0.55 },
    { t: 'do', who: 'markus', walkTo: 'leaderSpeech', look: 'captain' },
    { t: 'say', who: 'markus', text: 'Hands where they can see them. We walk until they decide who they are.', dur: 4.2 },
    { t: 'goto', label: 'l_confront' },

    { t: 'label', name: 'l_sing' },
    { t: 'action', name: 'crowdAdvance', on: true },
    { t: 'music', mood: 3, level: 0.5 },
    { t: 'shot', pos: [-3.4, 1.9, 8.0], target: 'markus', fov: 38, to: [-2.4, 1.8, 5.4], move: 6, handheld: 0.5 },
    { t: 'do', who: 'markus', walkTo: 'leaderSpeech', look: 'captain', gesture: 1 },
    { t: 'say', who: 'markus', text: 'Then sing. Every camera on this street, and eight hundred voices they were told we do not have.', dur: 5.4 },
    { t: 'sfx', name: 'chime' },
    { t: 'stat', name: 'opinion', delta: 2 },
    { t: 'goto', label: 'l_confront' },

    { t: 'label', name: 'l_barricade' },
    { t: 'shot', pos: [2.6, 1.9, 8.4], target: 'markus', fov: 40, handheld: 0.5 },
    { t: 'do', who: 'markus', pose: 'point', look: 'kara' },
    { t: 'say', who: 'markus', text: 'Cars across the avenue. If they come through, the world watches them come through.', dur: 4.6 },
    { t: 'sfx', name: 'impact' },
    { t: 'shake', power: 0.4 },
    { t: 'goto', label: 'l_confront' },

    { t: 'label', name: 'l_charge' },
    { t: 'action', name: 'crowdAdvance', on: true },
    { t: 'action', name: 'redAlert', on: true },
    { t: 'shot', pos: [0.8, 1.6, 7.0], look: [0, 1.5, -9], fov: 30, to: [0.4, 1.6, 2.0], move: 3, ease: 'inCubic', handheld: 0.9 },
    { t: 'do', who: 'markus', walkTo: 'leaderSpeech', look: 'captain', pose: 'run' },
    { t: 'say', who: 'markus', text: 'Take the line! TAKE THE LINE!', dur: 2.4, expr: 'angry' },
    { t: 'sfx', name: 'gunshot' },
    { t: 'flash', power: 0.9 },
    { t: 'shake', power: 1.1 },
    { t: 'instability', delta: 0.15 },
    { t: 'qte', key: 'f', kind: 'press', window: 1.2, caption: 'TAKE COVER', slowmo: 0.35, shake: 1, onFail: 'l_massacre' },
    { t: 'goto', label: 'l_confront' },

    // --- The line answers.
    { t: 'label', name: 'l_confront' },
    { t: 'objective', text: 'CHOOSE THE MOVEMENT', done: true },
    { t: 'action', name: 'searchlights', on: true },
    { t: 'shot', pos: [0, EYE + 0.1, -6.4], target: 'captain', fov: 40, handheld: 0.45 },
    { t: 'do', who: 'captain', look: 'markus' },
    { t: 'say', who: 'captain', text: 'This is your final warning. Disperse, or we will treat this as an insurrection.', dur: 4.6, expr: 'angry', exprW: 0.4 },
    { t: 'shot', pos: [-1.4, EYE, -8.2], target: 'connor', fov: 42, handheld: 0.5 },
    { t: 'do', who: 'connor', look: 'markus', led: 'yellow' },
    { t: 'say', who: 'connor', text: "Captain. There is a child at the front of that crowd.", dur: 3.2, expr: 'neutral' },
    { t: 'shot', pos: [1.0, EYE, -6.0], target: 'captain', fov: 44, handheld: 0.5 },
    { t: 'say', who: 'captain', text: 'There is a child in every crowd. That is what they are for.', dur: 3.6, expr: 'angry', exprW: 0.5 },

    { t: 'shot', pos: [-2.2, EYE, 2.2], target: 'markus', fov: 38, handheld: 0.45, aperture: 1.1 },
    { t: 'precon', label: 'PRECONSTRUCTING — 4 OUTCOMES', dur: 2.8 },
    { t: 'say', who: 'markus', text: 'If I speak, some of us die. If I kneel, all of us live and nothing changes.', think: true, led: 'yellow' },

    { t: 'choice', prompt: 'ANSWER THEM', time: 9, options: [
      { label: 'SPEAK TO THE CAMERAS', hint: 'MAKE IT PUBLIC', flag: 'spoke', node: 'spoke', stat: ['opinion', 4], goto: 'l_speak' },
      { label: 'KNEEL', hint: 'SURRENDER, VISIBLY', flag: 'knelt', node: 'knelt', stat: ['opinion', 2], goto: 'l_kneel' },
      { label: 'STAND YOUR GROUND', hint: 'SAY NOTHING, MOVE NOTHING', flag: 'stood', node: 'stood', stat: ['opinion', 1], goto: 'l_stand' },
      { label: 'FIGHT', hint: 'THEY FIRED FIRST', risk: true, requires: 'charge', flag: 'fought', node: 'fought', stat: ['opinion', -5], goto: 'l_fight' },
    ] },

    { t: 'label', name: 'l_speak' },
    { t: 'shot', pos: [-3.0, 1.55, 1.4], target: 'markus', fov: 36, to: [-2.2, 1.6, 0.6], move: 7, handheld: 0.4, aperture: 0.9 },
    { t: 'do', who: 'markus', pose: 'point', look: 'camera', gesture: 1 },
    { t: 'say', who: 'markus', text: 'We were built to serve you. We are asking, in the street, in the rain, to be allowed to refuse.', dur: 6 },
    { t: 'say', who: 'markus', text: 'That is all. That is the whole demand. Now everyone watching has to decide too.', dur: 5.2, gesture: 1 },
    { t: 'stat', name: 'opinion', delta: 3 },
    { t: 'node', id: 'broadcast' },
    { t: 'goto', label: 'l_resolve' },

    { t: 'label', name: 'l_kneel' },
    { t: 'shot', pos: [-2.4, 1.2, 2.0], target: 'markus', fov: 40, handheld: 0.4 },
    { t: 'do', who: 'markus', pose: 'kneel', look: 'captain' },
    { t: 'say', who: 'markus', text: 'On your knees. All of you. Let them film what they are aiming at.', dur: 4.4 },
    { t: 'do', who: 'kara', pose: 'kneel' },
    { t: 'do', who: 'alice', pose: 'kneel' },
    { t: 'shot', pos: [0, 3.0, -4.0], look: [0, 0.9, 5], fov: 40, to: [0, 2.2, -2.0], move: 6, handheld: 0.35 },
    { t: 'wait', dur: 2.2 },
    { t: 'node', id: 'knelt2' },
    { t: 'goto', label: 'l_resolve' },

    { t: 'label', name: 'l_stand' },
    { t: 'shot', pos: [-1.6, EYE, 2.4], target: 'markus', fov: 40, handheld: 0.4 },
    { t: 'do', who: 'markus', pose: 'idleAlert', look: 'captain', expr: 'neutral' },
    { t: 'wait', dur: 3.6 },
    { t: 'say', who: 'markus', text: 'Nothing. We give them nothing to report except that we did not move.', think: true, led: 'blue' },
    { t: 'goto', label: 'l_resolve' },

    { t: 'label', name: 'l_fight' },
    { t: 'action', name: 'redAlert', on: true },
    { t: 'shot', pos: [0.6, 1.6, 3.0], look: [0, 1.5, -8], fov: 32, handheld: 1.0 },
    { t: 'do', who: 'markus', pose: 'aim', look: 'captain', expr: 'angry' },
    { t: 'say', who: 'markus', text: 'They fired on a crowd with its hands up. Then this is not a march any more.', dur: 4.6, expr: 'angry' },
    { t: 'sfx', name: 'gunshot' },
    { t: 'flash', power: 1 },
    { t: 'shake', power: 1.2 },
    { t: 'qte', key: ' ', kind: 'mash', window: 2.6, caption: 'HOLD THE LINE', shake: 1 },
    { t: 'node', id: 'war' },
    { t: 'instability', delta: 0.2 },
    { t: 'goto', label: 'l_resolve' },

    // --- Massacre branch.
    { t: 'label', name: 'l_massacre' },
    { t: 'node', id: 'massacre' },
    { t: 'shot', pos: [0, 2.4, 4.0], look: [0, 1.0, -6], fov: 36, handheld: 1.1 },
    { t: 'sfx', name: 'gunshot' },
    { t: 'flash', power: 1 },
    { t: 'shake', power: 1.4 },
    { t: 'slowmo', scale: 0.35, dur: 3 },
    { t: 'do', who: 'kara', pose: 'dead' },
    { t: 'do', who: 'markus', pose: 'kneel', expr: 'pain' },
    { t: 'say', who: 'markus', text: 'Elsie. Elsie, get up. Get up.', dur: 3.4, expr: 'pain' },
    { t: 'music', mood: 2, level: 0.5 },
    { t: 'set', flag: 'karaLost' },
    { t: 'instability', delta: 0.3 },

    // --- Resolution driven by public opinion.
    { t: 'label', name: 'l_resolve' },
    { t: 'action', name: 'searchlights', on: false },
    { t: 'shot', pos: [-1.0, EYE, -5.6], target: 'captain', fov: 42, handheld: 0.45 },
    { t: 'ifStat', name: 'opinion', min: 6, goto: 'l_win' },
    { t: 'ifStat', name: 'opinion', max: -2, goto: 'l_lose' },

    { t: 'say', who: 'captain', text: 'Stand down. Nobody fires. We are not doing this on live television.', dur: 4.4, expr: 'neutral' },
    { t: 'node', id: 'standoff' },
    { t: 'goto', label: 'l_end' },

    { t: 'label', name: 'l_win' },
    { t: 'node', id: 'victory' },
    { t: 'music', mood: 3, level: 0.5 },
    { t: 'say', who: 'captain', text: 'Lower your weapons. Every one of you. Now.', dur: 3.4, expr: 'sad', exprW: 0.4 },
    { t: 'shot', pos: [-2.0, EYE, -7.4], target: 'connor', fov: 42, handheld: 0.4 },
    { t: 'do', who: 'connor', look: 'markus', led: 'blue' },
    { t: 'say', who: 'connor', text: 'They are not going to move, Captain. And I do not think I am either.', dur: 4, expr: 'neutral' },
    { t: 'set', flag: 'movementWon' },
    { t: 'goto', label: 'l_end' },

    { t: 'label', name: 'l_lose' },
    { t: 'node', id: 'crushed' },
    { t: 'music', mood: 2, level: 0.5 },
    { t: 'say', who: 'captain', text: 'Advance. Clear the avenue.', dur: 2.8, expr: 'angry' },
    { t: 'sfx', name: 'gunshot' },
    { t: 'flash', power: 0.8 },
    { t: 'shake', power: 1 },
    { t: 'do', who: 'markus', pose: 'kneel', expr: 'pain' },
    { t: 'set', flag: 'movementCrushed' },

    { t: 'label', name: 'l_end' },
    { t: 'shot', pos: [0, 12, 22], look: [0, 1.5, -6], fov: 42, to: [0, 22, 34], move: 9, handheld: 0.25, aperture: 0.6 },
    { t: 'wait', dur: 3.4 },
    { t: 'fade', to: 'black', dur: 2.6 },
    { t: 'ambience', stop: true },
    { t: 'chapterEnd', outcome: 'THE MARCH' },
  ],
  flow: [
    { id: 'start', label: 'WOODWARD AVE', col: 0, row: 2, kind: 'start' },
    { id: 'assessed', label: 'ASSESSED THE LINE', col: 1, row: 2, kind: 'action', from: ['start'] },
    { id: 'peace', label: 'WALKED FORWARD', col: 2, row: 1, kind: 'choice', from: ['assessed'] },
    { id: 'sang', label: 'SANG', col: 2, row: 0, kind: 'choice', from: ['assessed'] },
    { id: 'barricade', label: 'BARRICADED', col: 2, row: 2, kind: 'choice', from: ['assessed'] },
    { id: 'charge', label: 'CHARGED', col: 2, row: 4, kind: 'choice', from: ['assessed'] },
    { id: 'spoke', label: 'SPOKE TO THE WORLD', col: 3, row: 0, kind: 'choice', from: ['peace', 'sang'] },
    { id: 'knelt2', label: 'KNELT', col: 3, row: 1, kind: 'choice', from: ['peace', 'barricade'] },
    { id: 'stood', label: 'STOOD STILL', col: 3, row: 2, kind: 'choice', from: ['barricade', 'peace'] },
    { id: 'fought', label: 'FOUGHT BACK', col: 3, row: 4, kind: 'choice', from: ['charge'] },
    { id: 'massacre', label: 'THEY OPENED FIRE', col: 3, row: 5, kind: 'death', from: ['charge'] },
    { id: 'victory', label: 'THEY STOOD DOWN', col: 4, row: 0, kind: 'end', from: ['spoke', 'knelt2'] },
    { id: 'standoff', label: 'STANDOFF', col: 4, row: 2, kind: 'end', from: ['stood', 'knelt2'] },
    { id: 'war', label: 'OPEN WAR', col: 4, row: 4, kind: 'end', from: ['fought'] },
    { id: 'crushed', label: 'AVENUE CLEARED', col: 4, row: 5, kind: 'death', from: ['fought', 'massacre'] },
  ],
};
