#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Compiles the Rust noise kernel to wasm and inlines it into a JS module.
//
//   node native/build.mjs
//
// Inlined as base64 rather than shipped as a .wasm asset because the whole
// showcase has to keep building into one self-contained index.html with nothing
// to fetch at runtime. Four kilobytes of base64 is a cheap price for that.
//
// The generated file is committed, so a checkout without a Rust toolchain still
// builds and still gets the accelerator.
// ---------------------------------------------------------------------------

const here = path.dirname(fileURLToPath(import.meta.url));
const crate = path.join(here, 'noise');
const out = path.join(here, '..', 'src', 'lib', 'noise-wasm.js');

execFileSync('cargo', ['build', '--target', 'wasm32-unknown-unknown', '--release'], {
  cwd: crate,
  stdio: 'inherit',
});

const wasm = await readFile(path.join(crate, 'target', 'wasm32-unknown-unknown', 'release', 'ridgeline_noise.wasm'));
const b64 = wasm.toString('base64');

await writeFile(
  out,
  `// Generated by native/build.mjs — do not edit.
//
// The Rust source is native/noise/src/lib.rs. It is inlined as base64 so the
// single-file build stays self-contained; see native/build.mjs.
//
// ${wasm.length} bytes of wasm.
export const NOISE_WASM_B64 =
  '${b64}';
`,
);

console.log(`[native] ${wasm.length} bytes of wasm -> ${path.relative(process.cwd(), out)}`);
