#!/usr/bin/env python3
"""Fail-closed cumulative exceptional first-crossing theorem through terminal alpha6."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
OLD=ROOT/"rank8_exceptional_first_crossing_alpha1_5_cumulative_exact_20260820.json";OLD_AUDIT=ROOT/"rank8_exceptional_first_crossing_alpha1_5_cumulative_audit_exact_20260820.json";S8=ROOT/"rank8_exceptional_first_crossing_alpha6_s8_types73_247_exact_20260820.json";S8_AUDIT=ROOT/"rank8_exceptional_first_crossing_alpha6_s8_types73_247_audit_exact_20260820.json";OUTPUT=ROOT/"rank8_exceptional_first_crossing_alpha1_6_cumulative_exact_20260820.json"
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest().upper()
def source_paths(source):return ROOT/f"rank8_exceptional_first_crossing_alpha6_s{source}_complete_exact_20260820.json",ROOT/f"rank8_exceptional_first_crossing_alpha6_s{source}_complete_audit_exact_20260820.json"
def main():
 old=json.loads(OLD.read_text(encoding="utf-8"));old_audit=json.loads(OLD_AUDIT.read_text(encoding="utf-8"));assert old["status"]=="PASS_FAIL_CLOSED_EXACT_RANK8_EXCEPTIONAL_FIRST_CROSSING_ALPHA1_5" and old_audit["status"]=="PASS_INDEPENDENT_FAIL_CLOSED_RANK8_EXCEPTIONAL_FIRST_CROSSING_ALPHA1_5_AUDIT";assert old_audit["hashes"][OLD.name]==digest(OLD);assert old["aggregate"]==old_audit["aggregate"]
 hashes={OLD.name:digest(OLD),OLD_AUDIT.name:digest(OLD_AUDIT)};s8=json.loads(S8.read_text(encoding="utf-8"));s8a=json.loads(S8_AUDIT.read_text(encoding="utf-8"));assert s8["status"]=="PASS_EXACT_RESOURCE_GATED_RANK8_ALPHA6_S8_TYPES73_247" and s8a["status"]=="PASS_INDEPENDENT_BIDIRECTIONAL_RANK8_ALPHA6_S8_TYPES73_247_AUDIT";assert s8a["hashes"][S8.name]==digest(S8);hashes[S8.name]=digest(S8);hashes[S8_AUDIT.name]=digest(S8_AUDIT)
 assert s8["scope"]["certified_shard"]=={"source":8,"terminal":6,"total":14,"terminal_type_index_start":73,"terminal_type_index_stop":247};assert [row["terminal_type_index"] for row in s8["per_terminal_type"]]==list(range(73,248));assert s8["aggregate"]["ordered_covering_checks"]==s8a["shard"]["canonical_check_keys"] and s8["aggregate"]["distinct_crossing_jets"]==s8a["shard"]["distinct_crossing_jets"]
 alpha6_sources={"8":{"raw":s8a["shard"]["independently_enumerated_multisets"],"checks":s8["aggregate"]["ordered_covering_checks"],"products":s8["aggregate"]["distinct_crossing_jets"],"multiset_key":s8a["shard"]["multiset_to_canonical_key_collisions"],"key_product":s8["aggregate"]["canonical_key_to_product_collisions"],"minimum":s8["aggregate"]["minimum_Q8"],"maximum":s8["aggregate"]["maximum_Q8"],"type_range":[73,247]}}
 for source in range(9,14):
  report_path,audit_path=source_paths(source);report=json.loads(report_path.read_text(encoding="utf-8"));audit=json.loads(audit_path.read_text(encoding="utf-8"));assert report["status"]==f"PASS_EXACT_NO_GAP_RANK8_ALPHA6_SOURCE{source}_COMPLETE" and audit["status"]==f"PASS_INDEPENDENT_NO_GAP_RANK8_ALPHA6_SOURCE{source}_ASSEMBLY_AUDIT";assert audit["hashes"][report_path.name]==digest(report_path);assert report["coverage"]["exact_union"]==[73,247] and report["coverage"]["gaps"]==report["coverage"]["overlaps"]==0;assert report["aggregate"]["source_alpha"]==source and report["aggregate"]["terminal_type_count"]==175
  hashes[report_path.name]=digest(report_path);hashes[audit_path.name]=digest(audit_path);a=report["aggregate"];alpha6_sources[str(source)]={"raw":a["independently_enumerated_multisets"],"checks":a["canonical_checks"],"products":a["distinct_shard_product_jets_sum"],"multiset_key":a["multiset_to_key_collisions"],"key_product":a["key_to_product_collisions_within_shards"],"minimum":a["minimum_Q8"],"maximum":a["maximum_Q8"],"type_range":[73,247]}
 alpha6={"independently_enumerated_multisets":sum(v["raw"] for v in alpha6_sources.values()),"canonical_checks":sum(v["checks"] for v in alpha6_sources.values()),"distinct_shard_product_jets_sum":sum(v["products"] for v in alpha6_sources.values()),"multiset_to_key_collisions":sum(v["multiset_key"] for v in alpha6_sources.values()),"key_to_product_collisions_within_shards":sum(v["key_product"] for v in alpha6_sources.values()),"negative_Q8":0,"zero_Q8":0,"minimum_Q8":min(v["minimum"] for v in alpha6_sources.values()),"maximum_Q8":max(v["maximum"] for v in alpha6_sources.values())}
 assert alpha6=={"independently_enumerated_multisets":39319350,"canonical_checks":28400924,"distinct_shard_product_jets_sum":27605829,"multiset_to_key_collisions":10918426,"key_to_product_collisions_within_shards":795095,"negative_Q8":0,"zero_Q8":0,"minimum_Q8":9399272,"maximum_Q8":282462928635888}
 old_cells=[(row["terminal_alpha"],row["source_alpha"]) for row in old["coverage"]["source_cells"]];new_cells=[(6,s) for s in range(8,14)];actual=old_cells+new_cells;expected=[(terminal,source) for terminal in range(1,7) for source in range(14-terminal,14)];assert actual==expected and len(actual)==len(set(actual))==21
 aggregate={"terminal_bands":6,"source_cells":21,"independently_enumerated_multisets":old["aggregate"]["independently_enumerated_multisets"]+alpha6["independently_enumerated_multisets"],"canonical_check_keys":old["aggregate"]["canonical_check_keys"]+alpha6["canonical_checks"],"distinct_cell_or_shard_crossing_jets_sum":old["aggregate"]["distinct_cell_crossing_jets_sum"]+alpha6["distinct_shard_product_jets_sum"],"multiset_to_canonical_key_collisions":old["aggregate"]["multiset_to_canonical_key_collisions"]+alpha6["multiset_to_key_collisions"],"canonical_key_to_product_collisions":old["aggregate"]["canonical_key_to_product_collisions"]+alpha6["key_to_product_collisions_within_shards"],"negative_Q8":0,"zero_Q8":0,"minimum_Q8":min(old["aggregate"]["minimum_Q8"],alpha6["minimum_Q8"]),"maximum_Q8":max(old["aggregate"]["maximum_Q8"],alpha6["maximum_Q8"])}
 assert aggregate=={"terminal_bands":6,"source_cells":21,"independently_enumerated_multisets":43008068,"canonical_check_keys":31148628,"distinct_cell_or_shard_crossing_jets_sum":29747474,"multiset_to_canonical_key_collisions":11859440,"canonical_key_to_product_collisions":1401154,"negative_Q8":0,"zero_Q8":0,"minimum_Q8":9324000,"maximum_Q8":282462928635888}
 payload={"schema":"rank8-exceptional-first-crossing-alpha1-6-cumulative-v1","status":"PASS_FAIL_CLOSED_EXACT_RANK8_EXCEPTIONAL_FIRST_CROSSING_ALPHA1_6","theorem":"Every exceptional-only threshold-14 first crossing whose unique largest sorted terminal component has alpha at most6 has literal Q8>0.","coverage":{"terminal_alpha_range":[1,6],"terminal_component_type_indices":[1,247],"source_rule":"14-terminal_alpha <= source_alpha <= 13","source_cells":[{"terminal_alpha":t,"source_alpha":s} for t,s in actual],"missing_cells":[],"duplicate_cells":[],"terminal_type_ranges":{"1":[1,2],"2":[3,4],"3":[5,9],"4":[10,24],"5":[25,72],"6":[73,247]}},"alpha6":{"sources":alpha6_sources,"aggregate":alpha6},"aggregate":aggregate,"remaining_terminal_bands":[7,8,9],"scope_warning":"Cumulative exceptional-only first crossing through terminal alpha6; does not certify terminal alpha7..9 or full forest lift.","hashes":{**hashes,Path(__file__).name:digest(Path(__file__))}}
 OUTPUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(payload["status"]);print(f"cells={len(actual)} raw={aggregate['independently_enumerated_multisets']} checks={aggregate['canonical_check_keys']} negative=0 zero=0");print(f"assembly_sha256={digest(OUTPUT)}");return 0
if __name__=="__main__":raise SystemExit(main())
