#!/usr/bin/env python3
"""Assemble 32 new source-alpha13 shards plus unchanged sealed type247 pilot."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
LABELS=("types73_83","types84_93","types94_102","types103_110","types111_118","types119_125","types126_132","types133_139","types140_145","types146_151","types152_157","types158_163","types164_168","types169_173","types174_178","types179_183","types184_188","types189_193","types194_197","types198_201","types202_205","types206_209","types210_213","types214_217","types218_221","types222_225","types226_229","types230_233","types234_237","types238_240","types241_243","types244_246")
EXPECTED_RANGES=[[73,83],[84,93],[94,102],[103,110],[111,118],[119,125],[126,132],[133,139],[140,145],[146,151],[152,157],[158,163],[164,168],[169,173],[174,178],[179,183],[184,188],[189,193],[194,197],[198,201],[202,205],[206,209],[210,213],[214,217],[218,221],[222,225],[226,229],[230,233],[234,237],[238,240],[241,243],[244,246],[247,247]]
PROBE=ROOT/"probe_rank8_exceptional_first_crossing_alpha6_s13_shard_exact.py";AUDITOR=ROOT/"audit_rank8_exceptional_first_crossing_alpha6_s13_shard.py";PILOT_PROBE=ROOT/"probe_rank8_exceptional_first_crossing_alpha6_s13_type247_exact.py";PILOT_AUDITOR=ROOT/"audit_rank8_exceptional_first_crossing_alpha6_s13_type247.py";PILOT_REPORT=ROOT/"rank8_exceptional_first_crossing_alpha6_s13_type247_pilot_exact_20260820.json";PILOT_DB=ROOT/"rank8_exceptional_first_crossing_alpha6_s13_type247_pilot_keys_exact_20260820.sqlite3";PILOT_AUDIT=ROOT/"rank8_exceptional_first_crossing_alpha6_s13_type247_pilot_audit_exact_20260820.json";OUTPUT=ROOT/"rank8_exceptional_first_crossing_alpha6_s13_complete_exact_20260820.json"
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest().upper()
def artifacts(label):
 stem=f"rank8_exceptional_first_crossing_alpha6_s13_{label}";return {"report":ROOT/f"{stem}_exact_20260820.json","database":ROOT/f"{stem}_keys_exact_20260820.sqlite3","audit":ROOT/f"{stem}_audit_exact_20260820.json"}
def main():
 reports=[];audits=[];hashes={PROBE.name:digest(PROBE),AUDITOR.name:digest(AUDITOR),PILOT_PROBE.name:digest(PILOT_PROBE),PILOT_AUDITOR.name:digest(PILOT_AUDITOR)}
 for label in LABELS:
  files=artifacts(label);report=json.loads(files["report"].read_text(encoding="utf-8"));audit=json.loads(files["audit"].read_text(encoding="utf-8"));assert report["status"]==f"PASS_EXACT_RESOURCE_GATED_RANK8_ALPHA6_S13_{label.upper()}" and audit["status"]==f"PASS_INDEPENDENT_BIDIRECTIONAL_RANK8_ALPHA6_S13_{label.upper()}_AUDIT";assert report["hashes"][files["database"].name]==digest(files["database"]);assert audit["hashes"][files["report"].name]==digest(files["report"]);assert audit["hashes"][files["database"].name]==digest(files["database"]);assert report["hashes"][PROBE.name]==digest(PROBE) and audit["hashes"][AUDITOR.name]==digest(AUDITOR)
  r,a=report["aggregate"],audit["shard"];assert (r["ordered_covering_checks"],r["distinct_crossing_jets"],r["canonical_key_to_product_collisions"],r["minimum_Q8"],r["maximum_Q8"])==(a["canonical_check_keys"],a["distinct_crossing_jets"],a["canonical_key_to_product_collisions"],a["minimum_Q8"],a["maximum_Q8"]);assert r["negative_Q8"]==a["negative_Q8"]==r["zero_Q8"]==a["zero_Q8"]==0
  for path in files.values():hashes[path.name]=digest(path)
  reports.append(report);audits.append(audit)
 pilot=json.loads(PILOT_REPORT.read_text(encoding="utf-8"));pilot_audit=json.loads(PILOT_AUDIT.read_text(encoding="utf-8"));assert pilot["status"]=="PASS_EXACT_RESOURCE_GATED_RANK8_ALPHA6_S13_TYPE247_PILOT" and pilot_audit["status"]=="PASS_INDEPENDENT_BIDIRECTIONAL_RANK8_ALPHA6_S13_TYPE247_PILOT_AUDIT";assert pilot["hashes"][PILOT_DB.name]==digest(PILOT_DB);assert pilot_audit["hashes"][PILOT_REPORT.name]==digest(PILOT_REPORT) and pilot_audit["hashes"][PILOT_DB.name]==digest(PILOT_DB);assert pilot["hashes"][PILOT_PROBE.name]==digest(PILOT_PROBE) and pilot_audit["hashes"][PILOT_AUDITOR.name]==digest(PILOT_AUDITOR)
 pc,pa=pilot["cell"],pilot_audit["cell"];assert (pc["ordered_covering_checks"],pc["distinct_crossing_jets"],pc["minimum_Q8"],pc["maximum_Q8"])==(pa["canonical_check_keys"],pa["distinct_crossing_jets"],pa["minimum_Q8"],pa["maximum_Q8"]);assert pc["negative_Q8"]==pa["negative_Q8"]==pc["zero_Q8"]==pa["zero_Q8"]==0
 for path in (PILOT_REPORT,PILOT_DB,PILOT_AUDIT):hashes[path.name]=digest(path)
 ranges=[[r["aggregate"]["terminal_type_index_start"],r["aggregate"]["terminal_type_index_stop"]] for r in reports]+[[247,247]];assert ranges==EXPECTED_RANGES;new_types=[row["terminal_type_index"] for r in reports for row in r["per_terminal_type"]];assert new_types==list(range(73,247));all_types=new_types+[247];assert all_types==list(range(73,248)) and len(set(all_types))==175
 for audit in audits:
  for row in audit["shard"]["per_terminal_type"]:
   L=row["terminal_relative_alpha6_type"];assert row["independently_enumerated_multisets"]==63606+575*L+L*(L+1)
 assert pa["independently_enumerated_multisets"]==63606+575*175+175*176==195031
 aggregate={"source_alpha":13,"terminal_alpha":6,"total_alpha":19,"terminal_type_index_start":73,"terminal_type_index_stop":247,"terminal_type_count":175,"independently_enumerated_multisets":sum(a["shard"]["independently_enumerated_multisets"] for a in audits)+pa["independently_enumerated_multisets"],"canonical_checks":sum(r["aggregate"]["ordered_covering_checks"] for r in reports)+pc["ordered_covering_checks"],"distinct_shard_product_jets_sum":sum(r["aggregate"]["distinct_crossing_jets"] for r in reports)+pc["distinct_crossing_jets"],"multiset_to_key_collisions":sum(a["shard"]["multiset_to_canonical_key_collisions"] for a in audits)+pa["multiset_to_canonical_key_collisions"],"key_to_product_collisions_within_shards":sum(r["aggregate"]["canonical_key_to_product_collisions"] for r in reports)+pc["canonical_key_to_product_collisions"],"negative_Q8":0,"zero_Q8":0,"minimum_Q8":min([r["aggregate"]["minimum_Q8"] for r in reports]+[pc["minimum_Q8"]]),"maximum_Q8":max([r["aggregate"]["maximum_Q8"] for r in reports]+[pc["maximum_Q8"]])}
 assert aggregate=={"source_alpha":13,"terminal_alpha":6,"total_alpha":19,"terminal_type_index_start":73,"terminal_type_index_stop":247,"terminal_type_count":175,"independently_enumerated_multisets":21803250,"canonical_checks":15156851,"distinct_shard_product_jets_sum":14940421,"multiset_to_key_collisions":6646399,"key_to_product_collisions_within_shards":216430,"negative_Q8":0,"zero_Q8":0,"minimum_Q8":3524647923,"maximum_Q8":282462928635888}
 payload={"schema":"rank8-exceptional-first-crossing-alpha6-s13-complete-v1","status":"PASS_EXACT_NO_GAP_RANK8_ALPHA6_SOURCE13_COMPLETE","theorem":"For every terminal exceptional alpha6 type73..247 and every source-alpha13 exceptional multiset using types at most the terminal type, the total-alpha19 product has Q8>0.","coverage":{"shard_ranges":ranges,"exact_union":[73,247],"overlaps":0,"gaps":0,"type247_reused_without_rerun":True},"aggregate":aggregate,"scope_warning":"Completes source alpha13 for terminal alpha6; stops before terminal alpha7.","hashes":{**hashes,Path(__file__).name:digest(Path(__file__))}}
 OUTPUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(payload["status"]);print(f"ranges={len(ranges)} raw={aggregate['independently_enumerated_multisets']} checks={aggregate['canonical_checks']} negative=0 zero=0 reused_type247=true");print(f"assembly_sha256={digest(OUTPUT)}");return 0
if __name__=="__main__":raise SystemExit(main())
