#!/usr/bin/env python3
"""Fail-closed assembly of terminal-alpha7 sources7..13."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
DESIGN=ROOT/"rank8_exceptional_first_crossing_alpha7_streaming_design_exact_20260820.json"
DESIGN_AUDIT=ROOT/"rank8_exceptional_first_crossing_alpha7_streaming_design_audit_exact_20260820.json"
OUTPUT=ROOT/"rank8_exceptional_first_crossing_alpha7_sources7_13_complete_exact_20260820.json"
SOURCES=range(7,14)
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest().upper()
def files(s):return ROOT/f"rank8_exceptional_first_crossing_alpha7_s{s}_complete_exact_20260820.json",ROOT/f"rank8_exceptional_first_crossing_alpha7_s{s}_complete_audit_exact_20260820.json"
def main()->int:
 design=json.loads(DESIGN.read_text(encoding="utf-8"));da=json.loads(DESIGN_AUDIT.read_text(encoding="utf-8"));assert design["status"]=="PASS_EXACT_NO_GAP_RESOURCE_DESIGN_RANK8_EXCEPTIONAL_FIRST_CROSSING_ALPHA7_NO_SIGN_RUN"and da["status"]=="PASS_INDEPENDENT_EXACT_NO_GAP_RESOURCE_DESIGN_AUDIT_RANK8_ALPHA7"
 hashes={Path(__file__).name:digest(Path(__file__)),DESIGN.name:digest(DESIGN),DESIGN_AUDIT.name:digest(DESIGN_AUDIT)};raw=checks=products=rk=kp=0;mn=mx=None;ps=ats=0.;pp=ap=0;shards=0;source_records=[]
 for s in SOURCES:
  cp,aup=files(s);c=json.loads(cp.read_text(encoding="utf-8"));a=json.loads(aup.read_text(encoding="utf-8"));assert c["status"]==f"PASS_EXACT_NO_GAP_RANK8_ALPHA7_SOURCE{s}_COMPLETE"and a["status"]==f"PASS_INDEPENDENT_NO_GAP_RANK8_ALPHA7_SOURCE{s}_ASSEMBLY_AUDIT"and a["hashes"][cp.name]==digest(cp)and c["coverage"]["source_alpha"]==s and c["coverage"]["terminal_alpha"]==7 and c["coverage"]["terminal_type_indices"]==[248,947]and c["coverage"]["terminal_type_count"]==700 and c["coverage"]["gaps"]==c["coverage"]["overlaps"]==0 and a["coverage"]["gaps"]==a["coverage"]["overlaps"]==0 and a["aggregate"]==c["aggregate"]
  x=c["aggregate"];assert x["negative_Q8"]==x["zero_Q8"]==0 and x["minimum_Q8"]>0;raw+=x["independently_enumerated_multisets"];checks+=x["canonical_check_keys"];products+=x["distinct_shard_product_jets_sum"];rk+=x["multiset_to_canonical_key_compression"];kp+=x["canonical_key_to_product_compression_within_shards"];mn=x["minimum_Q8"]if mn is None else min(mn,x["minimum_Q8"]);mx=x["maximum_Q8"]if mx is None else max(mx,x["maximum_Q8"]);ps+=c["resources"]["producer_elapsed_seconds_sum"];ats+=c["resources"]["audit_elapsed_seconds_sum"];pp=max(pp,c["resources"]["maximum_producer_peak_private_bytes"]);ap=max(ap,c["resources"]["maximum_audit_peak_private_bytes"]);n=len(c["coverage"]["shard_ranges"]);shards+=n;hashes[cp.name]=digest(cp);hashes[aup.name]=digest(aup);source_records.append({"source_alpha":s,"total_alpha":s+7,"terminal_type_indices":[248,947],"terminal_type_count":700,"shards":n,"raw_multisets":x["independently_enumerated_multisets"],"canonical_checks":x["canonical_check_keys"],"products":x["distinct_shard_product_jets_sum"],"minimum_Q8":x["minimum_Q8"],"maximum_Q8":x["maximum_Q8"],"complete_sha256":hashes[cp.name],"audit_sha256":hashes[aup.name]})
 assert raw==design["exact_counts"]["raw_crossings_total"]==391576500 and shards==design["exact_counts"]["audit_shards_total"]==909 and checks+rk==raw and products+kp==checks
 aggregate={"independently_enumerated_multisets":raw,"canonical_check_keys":checks,"distinct_source_shard_product_jets_sum":products,"multiset_to_canonical_key_compression":rk,"canonical_key_to_product_compression_within_shards":kp,"negative_Q8":0,"zero_Q8":0,"minimum_Q8":mn,"maximum_Q8":mx}
 payload={"schema":"rank8-exceptional-first-crossing-alpha7-sources7-13-complete-v1","status":"PASS_EXACT_NO_GAP_RANK8_ALPHA7_SOURCES7_13_COMPLETE","theorem":"Every exceptional-only first crossing with terminal alpha7 and total alpha14..20 has literal Q8>0.","coverage":{"source_alpha_indices":[7,13],"source_alpha_count":7,"terminal_alpha":7,"terminal_type_indices":[248,947],"terminal_type_count_per_source":700,"source_terminal_cells":4900,"shards":shards,"gaps":0,"overlaps":0},"aggregate":aggregate,"resources":{"workers":1,"fresh_process_per_shard_and_audit":True,"producer_elapsed_seconds_sum":ps,"audit_elapsed_seconds_sum":ats,"maximum_producer_peak_private_bytes":pp,"maximum_producer_peak_private_MiB":pp/1024**2,"maximum_audit_peak_private_bytes":ap,"maximum_audit_peak_private_MiB":ap/1024**2,"abort_limit_private_bytes":448*1024**2,"hard_limit_private_bytes":512*1024**2},"sources":source_records,"scope_warning":"Completes terminal alpha7 only; terminal alpha8 and alpha9 remain in the exceptional first-crossing lane.","hashes":hashes}
 OUTPUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(payload["status"]);print(f"sources=7 terminal_cells=4900 shards={shards} raw={raw} checks={checks} products={products} neg=0 zero=0 min_Q8={mn} max_Q8={mx}");print(f"assembly_sha256={digest(OUTPUT)}");return 0
if __name__=="__main__":raise SystemExit(main())
