// Independent checked-i256 literal audit for quartic_endpoint_cubic_path:quartic_leaf.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc;use std::thread;
const QLA_THREADS:usize=6;const QLA_BENCH_RAYS:usize=1_024;
#[derive(Clone,Copy)]struct QLAState{size:i32,long:bool}#[derive(Clone,Copy)]struct QLAMessage{parent_absent:V,parent_present:V}
#[derive(Clone,Copy)]struct QLAEndpoint{stem:QLAState,b0:QLAState,b1:QLAState,message:QLAMessage}#[derive(Clone,Copy)]struct QLARoot{root_arm:QLAState,sibling0:QLAState,sibling1:QLAState,to_center:QLAState,center_arm:QLAState}
fn qla_incident(x:i32)->QLAState{QLAState{size:x,long:x==8}}fn qla_spine(x:i32)->QLAState{QLAState{size:x,long:x==8}}fn qla_pendant(x:i32)->QLAState{QLAState{size:x,long:x==7}}
fn qla_propagate(absent:V,present:V,d:i32)->QLAMessage{QLAMessage{parent_absent:add(&mul(&path(d-1),&absent),&mul(&path(d-2),&present)),parent_present:add(&mul(&path(d-2),&absent),&mul(&path(d-3),&present))}}
fn qla_endpoint_message(stem:i32,b0:i32,b1:i32)->QLAMessage{let absent=product(&[path(b0),path(b1)]);let present=shifted(&product(&[path(b0-1),path(b1-1)]),1);qla_propagate(absent,present,stem)}
fn qla_endpoints()->Vec<QLAEndpoint>{let mut out=Vec::with_capacity(224);for b0 in 1..=7_i32{for b1 in b0..=7_i32{for stem in 1..=8_i32{out.push(QLAEndpoint{stem:qla_spine(stem),b0:qla_pendant(b0),b1:qla_pendant(b1),message:qla_endpoint_message(stem,b0,b1)});}}}assert_eq!(out.len(),224);out}
fn qla_roots()->Vec<QLARoot>{let mut out=Vec::with_capacity(12_544);for root_arm in 1..=8_i32{for sibling0 in 1..=7_i32{for sibling1 in sibling0..=7_i32{for to_center in 1..=8_i32{for center_arm in 1..=7_i32{out.push(QLARoot{root_arm:qla_incident(root_arm),sibling0:qla_pendant(sibling0),sibling1:qla_pendant(sibling1),to_center:qla_spine(to_center),center_arm:qla_pendant(center_arm)});}}}}}assert_eq!(out.len(),12_544);out}
fn qla_states(e:QLAEndpoint,r:QLARoot)->[QLAState;8]{[r.root_arm,r.sibling0,r.sibling1,r.to_center,r.center_arm,e.stem,e.b0,e.b1]}fn qla_lengths(s:&[QLAState;8])->[i32;8]{std::array::from_fn(|i|s[i].size)}
fn qla_center(l:&[i32;8],endpoint:QLAMessage)->QLAMessage{let absent=product(&[path(l[4]),endpoint.parent_absent]);let present=shifted(&product(&[path(l[4]-1),endpoint.parent_present]),1);qla_propagate(absent,present,l[3])}
fn qla_root_polynomials(l:&[i32;8],center:QLAMessage)->(V,V){let absent=product(&[path(l[1]),path(l[2]),center.parent_absent]);let present=shifted(&product(&[path(l[1]-1),path(l[2]-1),center.parent_present]),1);let at_root=qla_propagate(absent,present,l[0]);let deleted=at_root.parent_absent;let selected=shifted(&at_root.parent_present,1);(add(&deleted,&selected),deleted)}
fn qla_direct_polynomials(l:&[i32;8])->(V,V){qla_root_polynomials(l,qla_center(l,qla_endpoint_message(l[5],l[6],l[7])))}
fn qla_values(l:&[i32;8],e:QLAEndpoint,varying:Option<usize>)->[Z;4]{let message=if varying.is_some_and(|i|i>=5){qla_endpoint_message(l[5],l[6],l[7])}else{e.message};let(c,d)=qla_root_polynomials(l,qla_center(l,message));deltas03(&c,&d)}
fn qla_extend(a:&mut Vec<Vec<usize>>,start:usize,d:i32)->usize{let mut x=start;for _ in 0..d{let y=a.len();a.push(Vec::new());a[x].push(y);a[y].push(x);x=y;}x}
fn qla_tree(l:&[i32;8])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let q=qla_extend(&mut a,root,l[0]);qla_extend(&mut a,q,l[1]);qla_extend(&mut a,q,l[2]);let center=qla_extend(&mut a,q,l[3]);qla_extend(&mut a,center,l[4]);let endpoint=qla_extend(&mut a,center,l[5]);qla_extend(&mut a,endpoint,l[6]);qla_extend(&mut a,endpoint,l[7]);assert_eq!(a.len(),1+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),1);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}
fn qla_literal_values(l:&[i32;8])->[Z;4]{let(a,r)=qla_tree(l);audit_deltas(&a,r).0}
fn qla_independent_smoke(){let mut random=0x739D12EAC6B8405F_u64;for sample in 0..512{let mut l=[0;8];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}let(c,d)=qla_direct_polynomials(&l);assert_eq!(deltas03(&c,&d),qla_literal_values(&l),"independent endpoint leaf mismatch {}",sample);}let qs=qla_endpoints();let roots=qla_roots();for sample in 0..512{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let q=qs[random as usize%qs.len()];random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let root=roots[random as usize%roots.len()];let mut l=qla_lengths(&qla_states(q,root));let varying=random as usize%8;l[varying]+=(random%19)as i32;assert_eq!(qla_values(&l,q,Some(varying)),qla_literal_values(&l),"cached endpoint leaf mismatch {}",sample);}println!("PASS_E5_QUARTIC_LEAF_INDEPENDENT_1024_LITERAL_SMOKE");}
fn qla_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qla_hash_state(h:&mut AuditSha256,s:QLAState){h.update(&[s.long as u8]);h.update(&s.size.to_le_bytes());}fn qla_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qla_coefficient_leaf(s:&[QLAState;8],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-leaf-coefficient-v1\0");for &x in s{qla_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qla_hash_z(&mut h,z);}}qla_sha_bytes(h)}
fn qla_finite_leaf(s:&[QLAState;8],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-leaf-finite-v1\0");for &x in s{qla_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qla_hash_z(&mut h,z);}qla_sha_bytes(h)}fn qla_order27_leaf(l:&[i32;8],v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-leaf-order27-v1\0");for &x in l{h.update(&x.to_le_bytes());}for &z in v{qla_hash_z(&mut h,z);}qla_sha_bytes(h)}
fn qla_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{for p in(AUDIT_DEGREES[rank]+1)..AUDIT_SAMPLES{if !rows[rank][p].is_zero(){return false;}}}true}fn qla_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{if !rows[rank][0].is_positive()||!rows[rank][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[rank]{if rows[rank][p].is_negative(){return false;}}}qla_degree_ok(rows)}
fn qla_formula_coefficients(s:&[QLAState;8],q:QLAEndpoint,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qla_lengths(s);let baseline=1+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qla_values(&l,q,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qla_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qla_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qla_values(&l,q,Some(varying));if literal{assert_eq!(unseen,qla_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qla_literal_coefficients(s:&[QLAState;8])->(i32,i32,[[Z;AUDIT_SAMPLES];4]){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qla_lengths(s);let baseline=1+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qla_literal_values(&l);for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qla_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qla_literal_values(&l);for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows)}
fn qla_smoke_stream(){let qs=qla_endpoints();let roots=qla_roots();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let root=roots[(sample*17+23)%roots.len()];let s=qla_states(q,root);if !s.iter().any(|x|x.long){let l=qla_lengths(&s);let order=1+l.iter().sum::<i32>();if order>=28{let v=qla_literal_values(&l);fh.update(&qla_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows)=qla_literal_coefficients(&s);if !qla_gate_ok(&rows){gf+=1;}ch.update(&qla_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
fn qla_bench(){let qs=qla_endpoints();let roots=qla_roots();let mut h=AuditSha256::new();let(mut rays,mut c)=(0,0);while rays<QLA_BENCH_RAYS{let q=qs[(c*104_729+5)%qs.len()];let root=roots[(c*17+31)%roots.len()];c+=1;let s=qla_states(q,root);if !s.iter().any(|x|x.long){continue;}let(b,sh,rows,checks)=qla_formula_coefficients(&s,q,true);assert_eq!(checks,3);h.update(&qla_coefficient_leaf(&s,b,sh,&rows));rays+=1;}println!("BENCH_RAYS {}",rays);println!("BENCH_STREAM {}",h.hex());println!("RESOURCE_TABLE_BYTES {} {}",qs.len()*std::mem::size_of::<QLAEndpoint>(),roots.len()*std::mem::size_of::<QLARoot>());println!("RESOURCE_FULL_LEAF_BYTES {}",2_547_030_usize*32);}
fn qla_cuts<F:FnMut(&[i32;8])>(next:i32,depth:usize,cuts:&mut[i32;7],f:&mut F){if depth==7{let mut row=[0;8];let mut prev=0;for i in 0..7{row[i]=cuts[i]-prev;prev=cuts[i];}row[7]=26-prev;f(&row);return;}let max=19+depth as i32;for v in next..=max{cuts[depth]=v;qla_cuts(v+1,depth+1,cuts,f);}}
fn qla_order27(){let(mut raw_count,mut count)=(0_u64,0_u64);let mut non=[0_u64;4];let mut h=AuditSha256::new();let mut cuts=[0;7];qla_cuts(1,0,&mut cuts,&mut|l|{raw_count+=1;if !(l[1]<=l[2]&&l[6]<=l[7]){return;}let v=qla_literal_values(l);for r in 0..4{if !v[r].is_positive(){non[r]+=1;}}h.update(&qla_order27_leaf(l,&v));count+=1;});assert_eq!(raw_count,480_700);assert_eq!(count,161_161);assert_eq!(non,[0;4]);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_QUARTIC_LEAF_ORDER27\nRAW_COMPOSITIONS {}\nORDER27_COUNT {}\nNONPOSITIVE {} {} {} {}\nLITERAL_TREES {}\nVALUE_STREAM {}\n",raw_count,count,non[0],non[1],non[2],non[3],count,h.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_quartic_leaf_order27_literal_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
struct QLAResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qla_worker(worker:usize,qs:Arc<Vec<QLAEndpoint>>,roots:Arc<Vec<QLARoot>>)->QLAResult{let start=qs.len()*worker/QLA_THREADS;let end=qs.len()*(worker+1)/QLA_THREADS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();for qi in start..end{let q=qs[qi];for &root in roots.iter(){let s=qla_states(q,root);let lc=s.iter().filter(|x|x.long).count();if lc==0{counts[0]+=1;let l=qla_lengths(&s);let order=1+l.iter().sum::<i32>();if order<28{continue;}let v=qla_values(&l,q,None);assert_eq!(v,qla_literal_values(&l));assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qla_finite_leaf(&s,order,&v));counts[1]+=1;literal+=1;continue;}if lc==8{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,checks)=qla_formula_coefficients(&s,q,true);audit_assert_gate(&rows);coeff.extend_from_slice(&qla_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;literal+=checks;}}QLAResult{worker,counts,unseen,literal,coeff,finite}}
fn qla_full(){let qs=Arc::new(qla_endpoints());let roots=Arc::new(qla_roots());let mut handles=Vec::new();for w in 0..QLA_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&roots);handles.push(thread::spawn(move||qla_worker(w,a,b)));}let mut results:Vec<_>=handles.into_iter().map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[907_578,644_752,1_902_277,1,1_902_278]);assert_eq!(unseen,7_609_112);assert_eq!(literal,6_351_586);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_QUARTIC_LEAF\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_TREES {}\nLITERAL_RAY_POINTS 0 13 29\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_quartic_leaf_literal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qla_independent_smoke();qla_smoke_stream();},Some("bench")=>qla_bench(),Some("order27")=>qla_order27(),Some(x)=>panic!("unknown mode {}",x),None=>qla_full()}}


