// Independent checked-i256 literal audit for quartic_center_two_cubic:cubic_leaf.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc;use std::thread;
const CLA_THREADS:usize=6;const CLA_BENCH_RAYS:usize=1_024;
#[derive(Clone,Copy)]struct CLAState{size:i32,long:bool}#[derive(Clone,Copy)]struct CLAMessage{parent_absent:V,parent_present:V}
#[derive(Clone,Copy)]struct CLAFar{stem:CLAState,b0:CLAState,b1:CLAState,message:CLAMessage}#[derive(Clone,Copy)]struct CLAPrefix{q0:CLAState,q1:CLAState,far:CLAFar,quartic_absent:V,quartic_present:V}#[derive(Clone,Copy)]struct CLARoot{root_arm:CLAState,sibling:CLAState,to_quartic:CLAState}
fn cla_incident(x:i32)->CLAState{CLAState{size:x,long:x==8}}fn cla_spine(x:i32)->CLAState{CLAState{size:x,long:x==8}}fn cla_pendant(x:i32)->CLAState{CLAState{size:x,long:x==7}}
fn cla_propagate(absent:V,present:V,d:i32)->CLAMessage{CLAMessage{parent_absent:add(&mul(&path(d-1),&absent),&mul(&path(d-2),&present)),parent_present:add(&mul(&path(d-2),&absent),&mul(&path(d-3),&present))}}
fn cla_far_message(stem:i32,b0:i32,b1:i32)->CLAMessage{let absent=product(&[path(b0),path(b1)]);let present=shifted(&product(&[path(b0-1),path(b1-1)]),1);cla_propagate(absent,present,stem)}
fn cla_quartic_parts(l:&[i32;8],far:CLAMessage)->(V,V){(product(&[path(l[3]),path(l[4]),far.parent_absent]),shifted(&product(&[path(l[3]-1),path(l[4]-1),far.parent_present]),1))}
fn cla_prefixes()->Vec<CLAPrefix>{let mut out=Vec::with_capacity(6_272);for q0 in 1..=7_i32{for q1 in q0..=7_i32{for b0 in 1..=7_i32{for b1 in b0..=7_i32{for stem in 1..=8_i32{let message=cla_far_message(stem,b0,b1);out.push(CLAPrefix{q0:cla_pendant(q0),q1:cla_pendant(q1),far:CLAFar{stem:cla_spine(stem),b0:cla_pendant(b0),b1:cla_pendant(b1),message},quartic_absent:product(&[path(q0),path(q1),message.parent_absent]),quartic_present:shifted(&product(&[path(q0-1),path(q1-1),message.parent_present]),1)});}}}}}assert_eq!(out.len(),6_272);out}
fn cla_roots()->Vec<CLARoot>{let mut out=Vec::with_capacity(448);for root_arm in 1..=8_i32{for sibling in 1..=7_i32{for to_quartic in 1..=8_i32{out.push(CLARoot{root_arm:cla_incident(root_arm),sibling:cla_pendant(sibling),to_quartic:cla_spine(to_quartic)});}}}assert_eq!(out.len(),448);out}
fn cla_states(p:CLAPrefix,r:CLARoot)->[CLAState;8]{[r.root_arm,r.sibling,r.to_quartic,p.q0,p.q1,p.far.stem,p.far.b0,p.far.b1]}fn cla_lengths(s:&[CLAState;8])->[i32;8]{std::array::from_fn(|i|s[i].size)}
fn cla_root_polynomials(l:&[i32;8],qa:V,qp:V)->(V,V){let toward_cubic=cla_propagate(qa,qp,l[2]);let cubic_absent=product(&[path(l[1]),toward_cubic.parent_absent]);let cubic_present=shifted(&product(&[path(l[1]-1),toward_cubic.parent_present]),1);let toward_root=cla_propagate(cubic_absent,cubic_present,l[0]);let deleted=toward_root.parent_absent;let selected=shifted(&toward_root.parent_present,1);(add(&deleted,&selected),deleted)}
fn cla_direct_polynomials(l:&[i32;8])->(V,V){let far=cla_far_message(l[5],l[6],l[7]);let(qa,qp)=cla_quartic_parts(l,far);cla_root_polynomials(l,qa,qp)}
fn cla_values(l:&[i32;8],p:CLAPrefix,varying:Option<usize>)->[Z;4]{let far=if varying.is_some_and(|i|i>=5){cla_far_message(l[5],l[6],l[7])}else{p.far.message};let(qa,qp)=if varying.is_some_and(|i|i>=3){cla_quartic_parts(l,far)}else{(p.quartic_absent,p.quartic_present)};let(c,d)=cla_root_polynomials(l,qa,qp);deltas03(&c,&d)}
fn cla_extend(a:&mut Vec<Vec<usize>>,start:usize,d:i32)->usize{let mut x=start;for _ in 0..d{let y=a.len();a.push(Vec::new());a[x].push(y);a[y].push(x);x=y;}x}
fn cla_tree(l:&[i32;8])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let c0=cla_extend(&mut a,root,l[0]);cla_extend(&mut a,c0,l[1]);let q=cla_extend(&mut a,c0,l[2]);cla_extend(&mut a,q,l[3]);cla_extend(&mut a,q,l[4]);let c1=cla_extend(&mut a,q,l[5]);cla_extend(&mut a,c1,l[6]);cla_extend(&mut a,c1,l[7]);assert_eq!(a.len(),1+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),1);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}fn cla_literal_values(l:&[i32;8])->[Z;4]{let(a,r)=cla_tree(l);audit_deltas(&a,r).0}
fn cla_independent_smoke(){let mut x=0x48ECA9127B5D630F_u64;for sample in 0..512{let mut l=[0;8];for z in &mut l{x^=x>>12;x^=x<<25;x^=x>>27;x=x.wrapping_mul(0x2545F4914F6CDD1D);*z=1+(x%23)as i32;}let(c,d)=cla_direct_polynomials(&l);assert_eq!(deltas03(&c,&d),cla_literal_values(&l),"independent cubic leaf mismatch {}",sample);}let ps=cla_prefixes();let roots=cla_roots();for sample in 0..512{x^=x>>12;x^=x<<25;x^=x>>27;x=x.wrapping_mul(0x2545F4914F6CDD1D);let p=ps[x as usize%ps.len()];x^=x>>12;x^=x<<25;x^=x>>27;x=x.wrapping_mul(0x2545F4914F6CDD1D);let root=roots[x as usize%roots.len()];let mut l=cla_lengths(&cla_states(p,root));let varying=x as usize%8;l[varying]+=(x%19)as i32;assert_eq!(cla_values(&l,p,Some(varying)),cla_literal_values(&l),"cached cubic leaf mismatch {}",sample);}println!("PASS_E5_CUBIC_LEAF_INDEPENDENT_1024_LITERAL_SMOKE");}
fn cla_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn cla_hash_state(h:&mut AuditSha256,s:CLAState){h.update(&[s.long as u8]);h.update(&s.size.to_le_bytes());}fn cla_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn cla_coeff_leaf(s:&[CLAState;8],b:i32,sh:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-leaf-coefficient-v1\0");for &x in s{cla_hash_state(&mut h,x);}h.update(&b.to_le_bytes());h.update(&sh.to_le_bytes());for row in rows{for &z in row{cla_hash_z(&mut h,z);}}cla_sha_bytes(h)}fn cla_finite_leaf(s:&[CLAState;8],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-leaf-finite-v1\0");for &x in s{cla_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{cla_hash_z(&mut h,z);}cla_sha_bytes(h)}
fn cla_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for k in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][k].is_zero(){return false;}}}true}fn cla_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for k in 2..=AUDIT_DEGREES[r]{if rows[r][k].is_negative(){return false;}}}cla_degree_ok(rows)}
fn cla_formula_coefficients(s:&[CLAState;8],p:CLAPrefix,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.long).unwrap();let mut l=cla_lengths(s);let b=1+l.iter().sum::<i32>();let sh=(28-b).max(0);let init=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for k in 0..AUDIT_SAMPLES{l[varying]=init+sh+k as i32;let v=cla_values(&l,p,Some(varying));if literal&&(k==0||k==13){assert_eq!(v,cla_literal_values(&l));checks+=1;}for r in 0..4{samples[r][k]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(cla_degree_ok(&rows));l[varying]=init+sh+AUDIT_SAMPLES as i32;let unseen=cla_values(&l,p,Some(varying));if literal{assert_eq!(unseen,cla_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(b,sh,rows,checks)}
fn cla_literal_coefficients(s:&[CLAState;8])->(i32,i32,[[Z;AUDIT_SAMPLES];4]){let varying=s.iter().position(|x|x.long).unwrap();let mut l=cla_lengths(s);let b=1+l.iter().sum::<i32>();let sh=(28-b).max(0);let init=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for k in 0..AUDIT_SAMPLES{l[varying]=init+sh+k as i32;let v=cla_literal_values(&l);for r in 0..4{samples[r][k]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(cla_degree_ok(&rows));l[varying]=init+sh+AUDIT_SAMPLES as i32;let unseen=cla_literal_values(&l);for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(b,sh,rows)}
fn cla_smoke_stream(){let ps=cla_prefixes();let roots=cla_roots();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let p=ps[(sample*104_729+3)%ps.len()];let root=roots[(sample*17+23)%roots.len()];let s=cla_states(p,root);if !s.iter().any(|x|x.long){let l=cla_lengths(&s);let order=1+l.iter().sum::<i32>();if order>=28{let v=cla_literal_values(&l);fh.update(&cla_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows)=cla_literal_coefficients(&s);if !cla_gate_ok(&rows){gf+=1;}ch.update(&cla_coeff_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
fn cla_bench(){let ps=cla_prefixes();let roots=cla_roots();let mut h=AuditSha256::new();let(mut rays,mut c)=(0,0);while rays<CLA_BENCH_RAYS{let p=ps[(c*104_729+5)%ps.len()];let root=roots[(c*17+31)%roots.len()];c+=1;let s=cla_states(p,root);if !s.iter().any(|x|x.long){continue;}let(b,sh,rows,checks)=cla_formula_coefficients(&s,p,true);assert_eq!(checks,3);h.update(&cla_coeff_leaf(&s,b,sh,&rows));rays+=1;}println!("BENCH_RAYS {}",rays);println!("BENCH_STREAM {}",h.hex());println!("RESOURCE_TABLE_BYTES {} {}",ps.len()*std::mem::size_of::<CLAPrefix>(),roots.len()*std::mem::size_of::<CLARoot>());println!("RESOURCE_FULL_LEAF_BYTES {}",2_547_030_usize*32);}
struct CLAResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn cla_worker(w:usize,ps:Arc<Vec<CLAPrefix>>,roots:Arc<Vec<CLARoot>>)->CLAResult{let start=ps.len()*w/CLA_THREADS;let end=ps.len()*(w+1)/CLA_THREADS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();for pi in start..end{let p=ps[pi];for &root in roots.iter(){let s=cla_states(p,root);let lc=s.iter().filter(|x|x.long).count();if lc==0{counts[0]+=1;let l=cla_lengths(&s);let order=1+l.iter().sum::<i32>();if order<28{continue;}let v=cla_values(&l,p,None);assert_eq!(v,cla_literal_values(&l));assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&cla_finite_leaf(&s,order,&v));counts[1]+=1;literal+=1;continue;}if lc==8{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,checks)=cla_formula_coefficients(&s,p,true);audit_assert_gate(&rows);coeff.extend_from_slice(&cla_coeff_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;literal+=checks;}}CLAResult{worker:w,counts,unseen,literal,coeff,finite}}
fn cla_full(){let ps=Arc::new(cla_prefixes());let roots=Arc::new(cla_roots());let mut hs=Vec::new();for w in 0..CLA_THREADS{let a=Arc::clone(&ps);let b=Arc::clone(&roots);hs.push(thread::spawn(move||cla_worker(w,a,b)));}let mut rs:Vec<_>=hs.into_iter().map(|h|h.join().unwrap()).collect();rs.sort_by_key(|x|x.worker);let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in rs{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[907_578,644_752,1_902_277,1,1_902_278]);assert_eq!(unseen,7_609_112);assert_eq!(literal,6_351_586);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_CENTER_TWO_CUBIC_CUBIC_LEAF\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_TREES {}\nLITERAL_RAY_POINTS 0 13 29\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_center_two_cubic_cubic_leaf_literal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{cla_independent_smoke();cla_smoke_stream();},Some("bench")=>cla_bench(),Some(x)=>panic!("unknown mode {}",x),None=>cla_full()}}
