#!/usr/bin/env python3
"""Independent fail-closed audit of cumulative exceptional theorem through alpha6."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent;ASSEMBLER=ROOT/"assemble_rank8_exceptional_first_crossing_alpha1_6.py";ASSEMBLY=ROOT/"rank8_exceptional_first_crossing_alpha1_6_cumulative_exact_20260820.json";OLD=ROOT/"rank8_exceptional_first_crossing_alpha1_5_cumulative_exact_20260820.json";OLD_AUDIT=ROOT/"rank8_exceptional_first_crossing_alpha1_5_cumulative_audit_exact_20260820.json";S8=ROOT/"rank8_exceptional_first_crossing_alpha6_s8_types73_247_exact_20260820.json";S8_AUDIT=ROOT/"rank8_exceptional_first_crossing_alpha6_s8_types73_247_audit_exact_20260820.json";OUTPUT=ROOT/"rank8_exceptional_first_crossing_alpha1_6_cumulative_audit_exact_20260820.json"
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest().upper()
def source_paths(source):return ROOT/f"rank8_exceptional_first_crossing_alpha6_s{source}_complete_exact_20260820.json",ROOT/f"rank8_exceptional_first_crossing_alpha6_s{source}_complete_audit_exact_20260820.json"
def main():
 assembly=json.loads(ASSEMBLY.read_text(encoding="utf-8"));assert assembly["status"]=="PASS_FAIL_CLOSED_EXACT_RANK8_EXCEPTIONAL_FIRST_CROSSING_ALPHA1_6" and assembly["hashes"][ASSEMBLER.name]==digest(ASSEMBLER);hashes={ASSEMBLY.name:digest(ASSEMBLY),ASSEMBLER.name:digest(ASSEMBLER)}
 for path in (OLD,OLD_AUDIT,S8,S8_AUDIT):assert assembly["hashes"][path.name]==digest(path);hashes[path.name]=digest(path)
 old=json.loads(OLD.read_text(encoding="utf-8"));old_audit=json.loads(OLD_AUDIT.read_text(encoding="utf-8"));assert old["aggregate"]==old_audit["aggregate"] and old["coverage"]["missing_cells"]==old["coverage"]["duplicate_cells"]==[]
 sources=[];s8=json.loads(S8.read_text(encoding="utf-8"));s8a=json.loads(S8_AUDIT.read_text(encoding="utf-8"));assert [row["terminal_type_index"] for row in s8["per_terminal_type"]]==list(range(73,248));assert s8["aggregate"]["ordered_covering_checks"]==s8a["shard"]["canonical_check_keys"] and s8["aggregate"]["distinct_crossing_jets"]==s8a["shard"]["distinct_crossing_jets"]
 sources.append({"source":8,"raw":s8a["shard"]["independently_enumerated_multisets"],"checks":s8["aggregate"]["ordered_covering_checks"],"products":s8["aggregate"]["distinct_crossing_jets"],"mk":s8a["shard"]["multiset_to_canonical_key_collisions"],"kp":s8["aggregate"]["canonical_key_to_product_collisions"],"min":s8["aggregate"]["minimum_Q8"],"max":s8["aggregate"]["maximum_Q8"]})
 for source in range(9,14):
  report_path,audit_path=source_paths(source)
  for path in (report_path,audit_path):assert assembly["hashes"][path.name]==digest(path);hashes[path.name]=digest(path)
  report=json.loads(report_path.read_text(encoding="utf-8"));audit=json.loads(audit_path.read_text(encoding="utf-8"));assert report["coverage"]["exact_union"]==[73,247] and report["coverage"]["gaps"]==report["coverage"]["overlaps"]==0;assert audit["coverage"]["exact_union"]==[73,247] and audit["coverage"]["gaps"]==audit["coverage"]["overlaps"]==0
  ra,aa=report["aggregate"],audit["aggregate"]
  for key in ("independently_enumerated_multisets","canonical_checks","distinct_shard_product_jets_sum","multiset_to_key_collisions","key_to_product_collisions_within_shards","negative_Q8","zero_Q8","minimum_Q8","maximum_Q8"):assert ra[key]==aa[key]
  sources.append({"source":source,"raw":ra["independently_enumerated_multisets"],"checks":ra["canonical_checks"],"products":ra["distinct_shard_product_jets_sum"],"mk":ra["multiset_to_key_collisions"],"kp":ra["key_to_product_collisions_within_shards"],"min":ra["minimum_Q8"],"max":ra["maximum_Q8"]})
 assert [row["source"] for row in sources]==list(range(8,14));alpha6={"independently_enumerated_multisets":sum(r["raw"] for r in sources),"canonical_checks":sum(r["checks"] for r in sources),"distinct_shard_product_jets_sum":sum(r["products"] for r in sources),"multiset_to_key_collisions":sum(r["mk"] for r in sources),"key_to_product_collisions_within_shards":sum(r["kp"] for r in sources),"negative_Q8":0,"zero_Q8":0,"minimum_Q8":min(r["min"] for r in sources),"maximum_Q8":max(r["max"] for r in sources)};assert alpha6==assembly["alpha6"]["aggregate"]
 actual=[(row["terminal_alpha"],row["source_alpha"]) for row in assembly["coverage"]["source_cells"]];expected=[(t,s) for t in range(1,7) for s in range(14-t,14)];assert actual==expected and len(actual)==len(set(actual))==21;assert assembly["coverage"]["terminal_type_ranges"]=={"1":[1,2],"2":[3,4],"3":[5,9],"4":[10,24],"5":[25,72],"6":[73,247]}
 aggregate={"terminal_bands":6,"source_cells":21,"independently_enumerated_multisets":old["aggregate"]["independently_enumerated_multisets"]+alpha6["independently_enumerated_multisets"],"canonical_check_keys":old["aggregate"]["canonical_check_keys"]+alpha6["canonical_checks"],"distinct_cell_or_shard_crossing_jets_sum":old["aggregate"]["distinct_cell_crossing_jets_sum"]+alpha6["distinct_shard_product_jets_sum"],"multiset_to_canonical_key_collisions":old["aggregate"]["multiset_to_canonical_key_collisions"]+alpha6["multiset_to_key_collisions"],"canonical_key_to_product_collisions":old["aggregate"]["canonical_key_to_product_collisions"]+alpha6["key_to_product_collisions_within_shards"],"negative_Q8":0,"zero_Q8":0,"minimum_Q8":min(old["aggregate"]["minimum_Q8"],alpha6["minimum_Q8"]),"maximum_Q8":max(old["aggregate"]["maximum_Q8"],alpha6["maximum_Q8"])};assert aggregate==assembly["aggregate"]
 payload={"schema":"rank8-exceptional-first-crossing-alpha1-6-cumulative-audit-v1","status":"PASS_INDEPENDENT_FAIL_CLOSED_RANK8_EXCEPTIONAL_FIRST_CROSSING_ALPHA1_6_AUDIT","coverage":{"terminal_alphas":[1,2,3,4,5,6],"terminal_type_indices":[1,247],"source_cells":21,"missing_cells":[],"duplicate_cells":[]},"alpha6_aggregate":alpha6,"aggregate":aggregate,"scope_warning":"Ends at terminal alpha6; terminal alpha7..9 and full forest lift remain.","hashes":{**hashes,Path(__file__).name:digest(Path(__file__))}}
 OUTPUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(payload["status"]);print(f"cells=21 raw={aggregate['independently_enumerated_multisets']} checks={aggregate['canonical_check_keys']} negative=0 zero=0");print(f"audit_sha256={digest(OUTPUT)}");return 0
if __name__=="__main__":raise SystemExit(main())
