// Independent checked-i256 literal audit for quartic_endpoint_cubic_path:quartic_pendant_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::{Arc,atomic::{AtomicUsize,Ordering}};use std::thread;
const QEA_THREADS:usize=6;const QEA_TASKS:usize=56;
#[derive(Clone,Copy)]struct QEAState{size:i32,long:bool}
#[derive(Clone,Copy)]struct QEAMessage{parent_absent:V,parent_present:V}
#[derive(Clone,Copy)]struct QEAFarSide{qc0:QEAState,c0p:QEAState,c0c1:QEAState,e0:QEAState,e1:QEAState,message:QEAMessage}
#[derive(Clone,Copy)]struct QEAPrefix{gap:QEAState,tail:QEAState,q0:QEAState,q1:QEAState,tail_message:QEAMessage}
fn qea_gap(x:i32)->QEAState{QEAState{size:x,long:x==7}}fn qea_pendant(x:i32)->QEAState{QEAState{size:x,long:x==7}}fn qea_spine(x:i32)->QEAState{QEAState{size:x,long:x==8}}
fn qea_propagate(absent:V,present:V,d:i32)->QEAMessage{QEAMessage{parent_absent:add(&mul(&path(d-1),&absent),&mul(&path(d-2),&present)),parent_present:add(&mul(&path(d-2),&absent),&mul(&path(d-3),&present))}}
fn qea_endpoint(spine:i32,a0:i32,a1:i32)->QEAMessage{qea_propagate(mul(&path(a0),&path(a1)),shifted(&mul(&path(a0-1),&path(a1-1)),1),spine)}
fn qea_far_message(qc0:i32,c0p:i32,c0c1:i32,e0:i32,e1:i32)->QEAMessage{let endpoint=qea_endpoint(c0c1,e0,e1);qea_propagate(mul(&path(c0p),&endpoint.parent_absent),shifted(&mul(&path(c0p-1),&endpoint.parent_present),1),qc0)}
fn qea_root_message(gap:i32,q0:i32,q1:i32,far:QEAMessage)->QEAMessage{qea_propagate(product(&[path(q0),path(q1),far.parent_absent]),shifted(&product(&[path(q0-1),path(q1-1),far.parent_present]),1),gap+1)}
fn qea_tail(tail:i32)->QEAMessage{QEAMessage{parent_absent:path(tail),parent_present:path(tail-1)}}
fn qea_far_sides()->Vec<QEAFarSide>{let mut out=Vec::with_capacity(12_544);for qc0 in 1..=8{for c0p in 1..=7{for c0c1 in 1..=8{for e0 in 1..=7{for e1 in e0..=7{out.push(QEAFarSide{qc0:qea_spine(qc0),c0p:qea_pendant(c0p),c0c1:qea_spine(c0c1),e0:qea_pendant(e0),e1:qea_pendant(e1),message:qea_far_message(qc0,c0p,c0c1,e0,e1)});}}}}}assert_eq!(out.len(),12_544);out}
fn qea_prefixes()->Vec<QEAPrefix>{let mut out=Vec::with_capacity(1_568);for gap in 0..=7{for tail in 1..=7{for q0 in 1..=7{for q1 in q0..=7{out.push(QEAPrefix{gap:qea_gap(gap),tail:qea_pendant(tail),q0:qea_pendant(q0),q1:qea_pendant(q1),tail_message:qea_tail(tail)});}}}}assert_eq!(out.len(),1_568);out}
fn qea_states(q:QEAFarSide,c:QEAPrefix)->[QEAState;9]{[c.gap,c.tail,c.q0,c.q1,q.qc0,q.c0p,q.c0c1,q.e0,q.e1]}fn qea_lengths(s:&[QEAState;9])->[i32;9]{std::array::from_fn(|i|s[i].size)}
fn qea_direct_polynomials(l:&[i32;9])->(V,V){let far=qea_far_message(l[4],l[5],l[6],l[7],l[8]);let core=qea_root_message(l[0],l[2],l[3],far);let tail=qea_tail(l[1]);let d=mul(&core.parent_absent,&tail.parent_absent);let p=shifted(&mul(&core.parent_present,&tail.parent_present),1);(add(&d,&p),d)}
fn qea_values(l:&[i32;9],q:QEAFarSide,c:QEAPrefix,varying:Option<usize>)->[Z;4]{let far=if varying.is_some_and(|i|i>=4){qea_far_message(l[4],l[5],l[6],l[7],l[8])}else{q.message};let core=qea_root_message(l[0],l[2],l[3],far);let tail=if varying==Some(1){qea_tail(l[1])}else{c.tail_message};let d=mul(&core.parent_absent,&tail.parent_absent);let p=shifted(&mul(&core.parent_present,&tail.parent_present),1);deltas03(&add(&d,&p),&d)}
fn qea_extend(a:&mut Vec<Vec<usize>>,start:usize,d:i32)->usize{let mut x=start;for _ in 0..d{let y=a.len();a.push(Vec::new());a[x].push(y);a[y].push(x);x=y;}x}
fn qea_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let q=qea_extend(&mut a,root,l[0]+1);qea_extend(&mut a,root,l[1]);qea_extend(&mut a,q,l[2]);qea_extend(&mut a,q,l[3]);let c0=qea_extend(&mut a,q,l[4]);qea_extend(&mut a,c0,l[5]);let c1=qea_extend(&mut a,c0,l[6]);qea_extend(&mut a,c1,l[7]);qea_extend(&mut a,c1,l[8]);assert_eq!(a.len(),2+l.iter().sum::<i32>()as usize);assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|x|x.len()==4).count(),1);assert_eq!(a.iter().filter(|x|x.len()==3).count(),2);(a,root)}
fn qea_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qea_tree(l);audit_deltas(&a,r).0}
fn qea_independent_smoke(){let mut random=0x4D92AF61C837B50E_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}l[0]-=1;let(c,d)=qea_direct_polynomials(&l);assert_eq!(deltas03(&c,&d),qea_literal_values(&l),"independent quartic pendant mismatch {}",sample);}let qs=qea_far_sides();let cs=qea_prefixes();for sample in 0..512{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let q=qs[random as usize%qs.len()];random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let c=cs[random as usize%cs.len()];let mut l=qea_lengths(&qea_states(q,c));let v=random as usize%9;l[v]+=(random%19)as i32;assert_eq!(qea_values(&l,q,c,Some(v)),qea_literal_values(&l),"cached audit mismatch {}",sample);}println!("PASS_E5_QUARTIC_ENDPOINT_QUARTIC_PENDANT_INTERNAL_INDEPENDENT_1024_LITERAL_SMOKE");}
fn qea_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qea_hash_state(h:&mut AuditSha256,s:QEAState){h.update(&[s.long as u8]);h.update(&s.size.to_le_bytes());}fn qea_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qea_coefficient_leaf(s:&[QEAState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-pendant-internal-coefficient-v1\0");for &x in s{qea_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qea_hash_z(&mut h,z);}}qea_sha_bytes(h)}
fn qea_finite_leaf(s:&[QEAState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-pendant-internal-finite-v1\0");for &x in s{qea_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qea_hash_z(&mut h,z);}qea_sha_bytes(h)}
fn qea_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for p in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][p].is_zero(){return false;}}}true}fn qea_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[r]{if rows[r][p].is_negative(){return false;}}}qea_degree_ok(rows)}
fn qea_formula_coefficients(s:&[QEAState;9],q:QEAFarSide,c:QEAPrefix,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qea_lengths(s);let baseline=2+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qea_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qea_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qea_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qea_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qea_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qea_literal_coefficients(s:&[QEAState;9])->(i32,i32,[[Z;AUDIT_SAMPLES];4]){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qea_lengths(s);let baseline=2+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qea_literal_values(&l);for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qea_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qea_literal_values(&l);for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows)}
fn qea_smoke_stream(){let qs=qea_far_sides();let cs=qea_prefixes();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let c=cs[(sample*17+23)%cs.len()];let s=qea_states(q,c);if !s.iter().any(|x|x.long){let l=qea_lengths(&s);let order=2+l.iter().sum::<i32>();if order>=28{let v=qea_literal_values(&l);fh.update(&qea_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows)=qea_literal_coefficients(&s);if !qea_gate_ok(&rows){gf+=1;}ch.update(&qea_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
struct QEAResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qea_worker(task:usize,qs:Arc<Vec<QEAFarSide>>,cs:Arc<Vec<QEAPrefix>>)->QEAResult{let start=qs.len()*task/QEA_TASKS;let end=qs.len()*(task+1)/QEA_TASKS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();for qi in start..end{let q=qs[qi];for &c in cs.iter(){let s=qea_states(q,c);let lc=s.iter().filter(|x|x.long).count();if lc==0{counts[0]+=1;let l=qea_lengths(&s);let order=2+l.iter().sum::<i32>();if order<28{continue;}let v=qea_values(&l,q,c,None);assert_eq!(v,qea_literal_values(&l));assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qea_finite_leaf(&s,order,&v));counts[1]+=1;literal+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,n)=qea_formula_coefficients(&s,q,c,true);audit_assert_gate(&rows);coeff.extend_from_slice(&qea_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;literal+=n;}}QEAResult{worker:task,counts,unseen,literal,coeff,finite}}
fn qea_full(){let qs=Arc::new(qea_far_sides());let cs=Arc::new(qea_prefixes());let next=Arc::new(AtomicUsize::new(0));let mut handles=Vec::new();for _ in 0..QEA_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&cs);let n=Arc::clone(&next);handles.push(thread::spawn(move||{let mut out=Vec::new();loop{let task=n.fetch_add(1,Ordering::SeqCst);if task>=QEA_TASKS{break;}out.push(qea_worker(task,Arc::clone(&a),Arc::clone(&b)));}out}));}let mut results:Vec<_>=handles.into_iter().flat_map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);assert_eq!(results.len(),QEA_TASKS);for(i,r)in results.iter().enumerate(){assert_eq!(r.worker,i);}let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[5_445_468,4_768_380,14_223_523,1,14_223_524]);assert_eq!(unseen,56_894_096);assert_eq!(literal,47_438_952);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_QUARTIC_PENDANT_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_TREES {}\nLITERAL_RAY_POINTS 0 13 29\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_quartic_pendant_internal_literal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qea_independent_smoke();qea_smoke_stream();},Some(x)=>panic!("unknown mode {}",x),None=>qea_full()}}
