// Independent checked-i256 literal audit for quartic_center_two_cubic:center_cubic_spine_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::{Arc,atomic::{AtomicUsize,Ordering}};use std::thread;
const QCA_THREADS:usize=6;const QCA_TASKS:usize=56;
#[derive(Clone,Copy)]struct QCAState{size:i32,long:bool}
#[derive(Clone,Copy)]struct QCAMessage{parent_absent:V,parent_present:V}
#[derive(Clone,Copy)]struct QCAQSide{gap:QCAState,q0:QCAState,q1:QCAState,spine:QCAState,e0:QCAState,e1:QCAState,message:QCAMessage}
#[derive(Clone,Copy)]struct QCACSide{gap:QCAState,c0:QCAState,c1:QCAState,message:QCAMessage}
fn qca_gap(x:i32)->QCAState{QCAState{size:x,long:x==7}}fn qca_pendant(x:i32)->QCAState{QCAState{size:x,long:x==7}}fn qca_spine(x:i32)->QCAState{QCAState{size:x,long:x==8}}
fn qca_propagate(absent:V,present:V,d:i32)->QCAMessage{QCAMessage{parent_absent:add(&mul(&path(d-1),&absent),&mul(&path(d-2),&present)),parent_present:add(&mul(&path(d-2),&absent),&mul(&path(d-3),&present))}}
fn qca_child(spine:i32,a0:i32,a1:i32)->QCAMessage{qca_propagate(mul(&path(a0),&path(a1)),shifted(&mul(&path(a0-1),&path(a1-1)),1),spine)}
fn qca_qmessage(gap:i32,q0:i32,q1:i32,spine:i32,e0:i32,e1:i32)->QCAMessage{let e=qca_child(spine,e0,e1);qca_propagate(product(&[path(q0),path(q1),e.parent_absent]),shifted(&product(&[path(q0-1),path(q1-1),e.parent_present]),1),gap+1)}
fn qca_cmessage(gap:i32,c0:i32,c1:i32)->QCAMessage{qca_propagate(mul(&path(c0),&path(c1)),shifted(&mul(&path(c0-1),&path(c1-1)),1),gap+1)}
fn qca_qsides()->Vec<QCAQSide>{let mut out=Vec::with_capacity(50_176);for gap in 0..=7{for q0 in 1..=7{for q1 in q0..=7{for spine in 1..=8{for e0 in 1..=7{for e1 in e0..=7{out.push(QCAQSide{gap:qca_gap(gap),q0:qca_pendant(q0),q1:qca_pendant(q1),spine:qca_spine(spine),e0:qca_pendant(e0),e1:qca_pendant(e1),message:qca_qmessage(gap,q0,q1,spine,e0,e1)});}}}}}}assert_eq!(out.len(),50_176);out}
fn qca_csides()->Vec<QCACSide>{let mut out=Vec::with_capacity(224);for gap in 0..=7{for c0 in 1..=7{for c1 in c0..=7{out.push(QCACSide{gap:qca_gap(gap),c0:qca_pendant(c0),c1:qca_pendant(c1),message:qca_cmessage(gap,c0,c1)});}}}assert_eq!(out.len(),224);out}
fn qca_states(q:QCAQSide,c:QCACSide)->[QCAState;9]{[q.gap,c.gap,q.q0,q.q1,q.spine,q.e0,q.e1,c.c0,c.c1]}fn qca_lengths(s:&[QCAState;9])->[i32;9]{std::array::from_fn(|i|s[i].size)}
fn qca_direct_polynomials(l:&[i32;9])->(V,V){let q=qca_qmessage(l[0],l[2],l[3],l[4],l[5],l[6]);let c=qca_cmessage(l[1],l[7],l[8]);let d=mul(&q.parent_absent,&c.parent_absent);let p=shifted(&mul(&q.parent_present,&c.parent_present),1);(add(&d,&p),d)}
fn qca_values(l:&[i32;9],q:QCAQSide,c:QCACSide,varying:Option<usize>)->[Z;4]{let a=if varying.is_some_and(|i|i==0||(2..=6).contains(&i)){qca_qmessage(l[0],l[2],l[3],l[4],l[5],l[6])}else{q.message};let b=if varying.is_some_and(|i|i==1||i>=7){qca_cmessage(l[1],l[7],l[8])}else{c.message};let d=mul(&a.parent_absent,&b.parent_absent);let p=shifted(&mul(&a.parent_present,&b.parent_present),1);deltas03(&add(&d,&p),&d)}
fn qca_extend(a:&mut Vec<Vec<usize>>,start:usize,d:i32)->usize{let mut x=start;for _ in 0..d{let y=a.len();a.push(Vec::new());a[x].push(y);a[y].push(x);x=y;}x}
fn qca_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let q=qca_extend(&mut a,root,l[0]+1);let c=qca_extend(&mut a,root,l[1]+1);qca_extend(&mut a,q,l[2]);qca_extend(&mut a,q,l[3]);let e=qca_extend(&mut a,q,l[4]);qca_extend(&mut a,e,l[5]);qca_extend(&mut a,e,l[6]);qca_extend(&mut a,c,l[7]);qca_extend(&mut a,c,l[8]);assert_eq!(a.len(),3+l.iter().sum::<i32>()as usize);assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|x|x.len()==4).count(),1);assert_eq!(a.iter().filter(|x|x.len()==3).count(),2);(a,root)}
fn qca_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qca_tree(l);audit_deltas(&a,r).0}
fn qca_independent_smoke(){let mut random=0x6E19C2A83D507BF4_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}let(c,d)=qca_direct_polynomials(&l);assert_eq!(deltas03(&c,&d),qca_literal_values(&l),"independent center-cubic spine mismatch {}",sample);}let qs=qca_qsides();let cs=qca_csides();for sample in 0..512{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let q=qs[random as usize%qs.len()];random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let c=cs[random as usize%cs.len()];let mut l=qca_lengths(&qca_states(q,c));let v=random as usize%9;l[v]+=(random%19)as i32;assert_eq!(qca_values(&l,q,c,Some(v)),qca_literal_values(&l),"cached audit mismatch {}",sample);}println!("PASS_E5_CENTER_CUBIC_SPINE_INTERNAL_INDEPENDENT_1024_LITERAL_SMOKE");}
fn qca_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qca_hash_state(h:&mut AuditSha256,s:QCAState){h.update(&[s.long as u8]);h.update(&s.size.to_le_bytes());}fn qca_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qca_coefficient_leaf(s:&[QCAState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-center-cubic-spine-internal-coefficient-v1\0");for &x in s{qca_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qca_hash_z(&mut h,z);}}qca_sha_bytes(h)}
fn qca_finite_leaf(s:&[QCAState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-center-cubic-spine-internal-finite-v1\0");for &x in s{qca_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qca_hash_z(&mut h,z);}qca_sha_bytes(h)}
fn qca_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for p in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][p].is_zero(){return false;}}}true}fn qca_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[r]{if rows[r][p].is_negative(){return false;}}}qca_degree_ok(rows)}
fn qca_formula_coefficients(s:&[QCAState;9],q:QCAQSide,c:QCACSide,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qca_lengths(s);let baseline=3+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qca_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qca_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qca_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qca_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qca_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qca_literal_coefficients(s:&[QCAState;9])->(i32,i32,[[Z;AUDIT_SAMPLES];4]){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qca_lengths(s);let baseline=3+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qca_literal_values(&l);for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qca_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qca_literal_values(&l);for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows)}
fn qca_smoke_stream(){let qs=qca_qsides();let cs=qca_csides();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let c=cs[(sample*17+23)%cs.len()];let s=qca_states(q,c);if !s.iter().any(|x|x.long){let l=qca_lengths(&s);let order=3+l.iter().sum::<i32>();if order>=28{let v=qca_literal_values(&l);fh.update(&qca_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows)=qca_literal_coefficients(&s);if !qca_gate_ok(&rows){gf+=1;}ch.update(&qca_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
struct QCAResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qca_worker(task:usize,qs:Arc<Vec<QCAQSide>>,cs:Arc<Vec<QCACSide>>)->QCAResult{let start=qs.len()*task/QCA_TASKS;let end=qs.len()*(task+1)/QCA_TASKS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();for qi in start..end{let q=qs[qi];for &c in cs.iter(){let s=qca_states(q,c);let lc=s.iter().filter(|x|x.long).count();if lc==0{counts[0]+=1;let l=qca_lengths(&s);let order=3+l.iter().sum::<i32>();if order<28{continue;}let v=qca_values(&l,q,c,None);assert_eq!(v,qca_literal_values(&l));assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qca_finite_leaf(&s,order,&v));counts[1]+=1;literal+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,n)=qca_formula_coefficients(&s,q,c,true);audit_assert_gate(&rows);coeff.extend_from_slice(&qca_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;literal+=n;}}QCAResult{worker:task,counts,unseen,literal,coeff,finite}}
fn qca_full(){let qs=Arc::new(qca_qsides());let cs=Arc::new(qca_csides());let next=Arc::new(AtomicUsize::new(0));let mut handles=Vec::new();for _ in 0..QCA_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&cs);let n=Arc::clone(&next);handles.push(thread::spawn(move||{let mut out=Vec::new();loop{let task=n.fetch_add(1,Ordering::SeqCst);if task>=QCA_TASKS{break;}out.push(qca_worker(task,Arc::clone(&a),Arc::clone(&b)));}out}));}let mut results:Vec<_>=handles.into_iter().flat_map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);assert_eq!(results.len(),QCA_TASKS);for(i,r)in results.iter().enumerate(){assert_eq!(r.worker,i);}let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[3_176_523,2_771_357,8_062_900,1,8_062_901]);assert_eq!(unseen,32_251_604);assert_eq!(literal,26_960_060);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_CENTER_TWO_CUBIC_CENTER_CUBIC_SPINE_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_TREES {}\nLITERAL_RAY_POINTS 0 13 29\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_center_two_cubic_center_cubic_spine_internal_literal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qca_independent_smoke();qca_smoke_stream();},Some(x)=>panic!("unknown mode {}",x),None=>qca_full()}}
