// Independent checked-i256 literal audit for quartic_center_two_cubic:cubic_pendant_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::{Arc,atomic::{AtomicUsize,Ordering}};use std::thread;
const QPA_THREADS:usize=6;const QPA_TASKS:usize=56;
#[derive(Clone,Copy)]struct QPAState{size:i32,long:bool}
#[derive(Clone,Copy)]struct QPAMessage{parent_absent:V,parent_present:V}
#[derive(Clone,Copy)]struct QPAFarSide{c0q:QPAState,q0:QPAState,q1:QPAState,qc1:QPAState,e0:QPAState,e1:QPAState,message:QPAMessage}
#[derive(Clone,Copy)]struct QPAPrefix{gap:QPAState,tail:QPAState,sibling:QPAState,tail_message:QPAMessage}
fn qpa_gap(x:i32)->QPAState{QPAState{size:x,long:x==7}}fn qpa_pendant(x:i32)->QPAState{QPAState{size:x,long:x==7}}fn qpa_spine(x:i32)->QPAState{QPAState{size:x,long:x==8}}
fn qpa_propagate(absent:V,present:V,d:i32)->QPAMessage{QPAMessage{parent_absent:add(&mul(&path(d-1),&absent),&mul(&path(d-2),&present)),parent_present:add(&mul(&path(d-2),&absent),&mul(&path(d-3),&present))}}
fn qpa_module(spine:i32,a0:i32,a1:i32)->QPAMessage{qpa_propagate(mul(&path(a0),&path(a1)),shifted(&mul(&path(a0-1),&path(a1-1)),1),spine)}
fn qpa_far_message(c0q:i32,q0:i32,q1:i32,qc1:i32,e0:i32,e1:i32)->QPAMessage{let other=qpa_module(qc1,e0,e1);qpa_propagate(product(&[path(q0),path(q1),other.parent_absent]),shifted(&product(&[path(q0-1),path(q1-1),other.parent_present]),1),c0q)}
fn qpa_root_message(gap:i32,sibling:i32,far:QPAMessage)->QPAMessage{qpa_propagate(mul(&path(sibling),&far.parent_absent),shifted(&mul(&path(sibling-1),&far.parent_present),1),gap+1)}
fn qpa_tail(tail:i32)->QPAMessage{QPAMessage{parent_absent:path(tail),parent_present:path(tail-1)}}
fn qpa_far_sides()->Vec<QPAFarSide>{let mut out=Vec::with_capacity(50_176);for c0q in 1..=8{for q0 in 1..=7{for q1 in q0..=7{for qc1 in 1..=8{for e0 in 1..=7{for e1 in e0..=7{out.push(QPAFarSide{c0q:qpa_spine(c0q),q0:qpa_pendant(q0),q1:qpa_pendant(q1),qc1:qpa_spine(qc1),e0:qpa_pendant(e0),e1:qpa_pendant(e1),message:qpa_far_message(c0q,q0,q1,qc1,e0,e1)});}}}}}}assert_eq!(out.len(),50_176);out}
fn qpa_prefixes()->Vec<QPAPrefix>{let mut out=Vec::with_capacity(392);for gap in 0..=7{for tail in 1..=7{for sibling in 1..=7{out.push(QPAPrefix{gap:qpa_gap(gap),tail:qpa_pendant(tail),sibling:qpa_pendant(sibling),tail_message:qpa_tail(tail)});}}}assert_eq!(out.len(),392);out}
fn qpa_states(q:QPAFarSide,c:QPAPrefix)->[QPAState;9]{[c.gap,c.tail,c.sibling,q.c0q,q.q0,q.q1,q.qc1,q.e0,q.e1]}fn qpa_lengths(s:&[QPAState;9])->[i32;9]{std::array::from_fn(|i|s[i].size)}
fn qpa_direct_polynomials(l:&[i32;9])->(V,V){let far=qpa_far_message(l[3],l[4],l[5],l[6],l[7],l[8]);let core=qpa_root_message(l[0],l[2],far);let tail=qpa_tail(l[1]);let d=mul(&core.parent_absent,&tail.parent_absent);let p=shifted(&mul(&core.parent_present,&tail.parent_present),1);(add(&d,&p),d)}
fn qpa_values(l:&[i32;9],q:QPAFarSide,c:QPAPrefix,varying:Option<usize>)->[Z;4]{let far=if varying.is_some_and(|i|i>=3){qpa_far_message(l[3],l[4],l[5],l[6],l[7],l[8])}else{q.message};let core=qpa_root_message(l[0],l[2],far);let tail=if varying==Some(1){qpa_tail(l[1])}else{c.tail_message};let d=mul(&core.parent_absent,&tail.parent_absent);let p=shifted(&mul(&core.parent_present,&tail.parent_present),1);deltas03(&add(&d,&p),&d)}
fn qpa_extend(a:&mut Vec<Vec<usize>>,start:usize,d:i32)->usize{let mut x=start;for _ in 0..d{let y=a.len();a.push(Vec::new());a[x].push(y);a[y].push(x);x=y;}x}
fn qpa_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let c0=qpa_extend(&mut a,root,l[0]+1);qpa_extend(&mut a,root,l[1]);qpa_extend(&mut a,c0,l[2]);let q=qpa_extend(&mut a,c0,l[3]);qpa_extend(&mut a,q,l[4]);qpa_extend(&mut a,q,l[5]);let c1=qpa_extend(&mut a,q,l[6]);qpa_extend(&mut a,c1,l[7]);qpa_extend(&mut a,c1,l[8]);assert_eq!(a.len(),2+l.iter().sum::<i32>()as usize);assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|x|x.len()==4).count(),1);assert_eq!(a.iter().filter(|x|x.len()==3).count(),2);(a,root)}
fn qpa_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qpa_tree(l);audit_deltas(&a,r).0}
fn qpa_independent_smoke(){let mut random=0x6E19C2A83D507BF4_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}l[0]-=1;let(c,d)=qpa_direct_polynomials(&l);assert_eq!(deltas03(&c,&d),qpa_literal_values(&l),"independent cubic pendant mismatch {}",sample);}let qs=qpa_far_sides();let cs=qpa_prefixes();for sample in 0..512{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let q=qs[random as usize%qs.len()];random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let c=cs[random as usize%cs.len()];let mut l=qpa_lengths(&qpa_states(q,c));let v=random as usize%9;l[v]+=(random%19)as i32;assert_eq!(qpa_values(&l,q,c,Some(v)),qpa_literal_values(&l),"cached audit mismatch {}",sample);}println!("PASS_E5_CUBIC_PENDANT_INTERNAL_INDEPENDENT_1024_LITERAL_SMOKE");}
fn qpa_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qpa_hash_state(h:&mut AuditSha256,s:QPAState){h.update(&[s.long as u8]);h.update(&s.size.to_le_bytes());}fn qpa_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qpa_coefficient_leaf(s:&[QPAState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-pendant-internal-coefficient-v1\0");for &x in s{qpa_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qpa_hash_z(&mut h,z);}}qpa_sha_bytes(h)}
fn qpa_finite_leaf(s:&[QPAState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-pendant-internal-finite-v1\0");for &x in s{qpa_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qpa_hash_z(&mut h,z);}qpa_sha_bytes(h)}
fn qpa_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for p in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][p].is_zero(){return false;}}}true}fn qpa_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[r]{if rows[r][p].is_negative(){return false;}}}qpa_degree_ok(rows)}
fn qpa_formula_coefficients(s:&[QPAState;9],q:QPAFarSide,c:QPAPrefix,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qpa_lengths(s);let baseline=2+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qpa_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qpa_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qpa_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qpa_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qpa_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qpa_literal_coefficients(s:&[QPAState;9])->(i32,i32,[[Z;AUDIT_SAMPLES];4]){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qpa_lengths(s);let baseline=2+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qpa_literal_values(&l);for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qpa_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qpa_literal_values(&l);for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows)}
fn qpa_smoke_stream(){let qs=qpa_far_sides();let cs=qpa_prefixes();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let c=cs[(sample*17+23)%cs.len()];let s=qpa_states(q,c);if !s.iter().any(|x|x.long){let l=qpa_lengths(&s);let order=2+l.iter().sum::<i32>();if order>=28{let v=qpa_literal_values(&l);fh.update(&qpa_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows)=qpa_literal_coefficients(&s);if !qpa_gate_ok(&rows){gf+=1;}ch.update(&qpa_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
struct QPAResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qpa_worker(task:usize,qs:Arc<Vec<QPAFarSide>>,cs:Arc<Vec<QPAPrefix>>)->QPAResult{let start=qs.len()*task/QPA_TASKS;let end=qs.len()*(task+1)/QPA_TASKS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();for qi in start..end{let q=qs[qi];for &c in cs.iter(){let s=qpa_states(q,c);let lc=s.iter().filter(|x|x.long).count();if lc==0{counts[0]+=1;let l=qpa_lengths(&s);let order=2+l.iter().sum::<i32>();if order<28{continue;}let v=qpa_values(&l,q,c,None);assert_eq!(v,qpa_literal_values(&l));assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qpa_finite_leaf(&s,order,&v));counts[1]+=1;literal+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,n)=qpa_formula_coefficients(&s,q,c,true);audit_assert_gate(&rows);coeff.extend_from_slice(&qpa_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;literal+=n;}}QPAResult{worker:task,counts,unseen,literal,coeff,finite}}
fn qpa_full(){let qs=Arc::new(qpa_far_sides());let cs=Arc::new(qpa_prefixes());let next=Arc::new(AtomicUsize::new(0));let mut handles=Vec::new();for _ in 0..QPA_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&cs);let n=Arc::clone(&next);handles.push(thread::spawn(move||{let mut out=Vec::new();loop{let task=n.fetch_add(1,Ordering::SeqCst);if task>=QPA_TASKS{break;}out.push(qpa_worker(task,Arc::clone(&a),Arc::clone(&b)));}out}));}let mut results:Vec<_>=handles.into_iter().flat_map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);assert_eq!(results.len(),QPA_TASKS);for(i,r)in results.iter().enumerate(){assert_eq!(r.worker,i);}let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[5_445_468,4_768_380,14_223_523,1,14_223_524]);assert_eq!(unseen,56_894_096);assert_eq!(literal,47_438_952);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_CENTER_TWO_CUBIC_CUBIC_PENDANT_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_TREES {}\nLITERAL_RAY_POINTS 0 13 29\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_center_two_cubic_cubic_pendant_internal_literal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qpa_independent_smoke();qpa_smoke_stream();},Some(x)=>panic!("unknown mode {}",x),None=>qpa_full()}}
