#!/usr/bin/env python3
"""Independent rehash/SQLite/no-gap audit of complete alpha7/source9."""
from __future__ import annotations
import csv,hashlib,json,sqlite3
from pathlib import Path
ROOT=Path(__file__).resolve().parent;ASSEMBLER=ROOT/"assemble_rank8_exceptional_first_crossing_alpha7_s9.py";ASSEMBLY=ROOT/"rank8_exceptional_first_crossing_alpha7_s9_complete_exact_20260820.json";JETS=ROOT/"rank8_exceptional_tree_jets_exact_20260820.tsv";RANGES=[(248,343),(344,432),(433,515),(516,593),(594,667),(668,738),(739,806),(807,871),(872,934),(935,947)];OUTPUT=ROOT/"rank8_exceptional_first_crossing_alpha7_s9_complete_audit_exact_20260820.json"
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest().upper()
def paths(start,stop):
 stem=f"rank8_exceptional_first_crossing_alpha7_s9_types{start}_{stop}";return ROOT/f"{stem}_exact_20260820.json",ROOT/f"{stem}_keys_exact_20260820.sqlite3",ROOT/f"{stem}_audit_exact_20260820.json"
def main()->int:
 assembly=json.loads(ASSEMBLY.read_text(encoding="utf-8"));assert assembly["status"]=="PASS_EXACT_NO_GAP_RANK8_ALPHA7_SOURCE9_COMPLETE" and assembly["hashes"][ASSEMBLER.name]==digest(ASSEMBLER)
 with JETS.open(newline="",encoding="utf-8")as handle:rows=list(csv.DictReader(handle,delimiter="\t"))
 coefficients=[0]*10;coefficients[0]=1
 for row in rows[:247]:
  weight=int(row["alpha"])
  for alpha in range(weight,10):coefficients[alpha]+=coefficients[alpha-weight]
 assert coefficients[9]==5437 and coefficients[2]==5
 expected=248;raw=checks=products=raw_key=key_product=0;minimum=maximum=None;hashes={ASSEMBLER.name:digest(ASSEMBLER),ASSEMBLY.name:digest(ASSEMBLY),JETS.name:digest(JETS),Path(__file__).name:digest(Path(__file__))}
 for start,stop in RANGES:
  assert start==expected;expected=stop+1;report_path,database,audit_path=paths(start,stop)
  for path in(report_path,database,audit_path):assert assembly["hashes"][path.name]==digest(path);hashes[path.name]=digest(path)
  connection=sqlite3.connect(database);database_checks=connection.execute("SELECT COUNT(*) FROM keys").fetchone()[0];database_products=connection.execute("SELECT COUNT(*) FROM products").fetchone()[0];assert connection.execute("SELECT MIN(largest_type),MAX(largest_type),COUNT(DISTINCT largest_type) FROM keys").fetchone()==(start,stop,stop-start+1);database_negative=connection.execute("SELECT COUNT(*) FROM keys WHERE CAST(q8 AS INTEGER)<0").fetchone()[0];database_zero=connection.execute("SELECT COUNT(*) FROM keys WHERE CAST(q8 AS INTEGER)=0").fetchone()[0];database_min=connection.execute("SELECT MIN(CAST(q8 AS INTEGER)) FROM keys").fetchone()[0];database_max=connection.execute("SELECT MAX(CAST(q8 AS INTEGER)) FROM keys").fetchone()[0];connection.close();report=json.loads(report_path.read_text(encoding="utf-8"));audit=json.loads(audit_path.read_text(encoding="utf-8"));row=report["aggregate"];assert database_checks==row["canonical_check_keys"]==audit["shard"]["canonical_check_keys"] and database_products==row["distinct_crossing_jets"]==audit["shard"]["distinct_crossing_jets"] and database_negative==database_zero==row["negative_Q8"]==row["zero_Q8"]==0 and database_min==row["minimum_Q8"]==audit["shard"]["minimum_Q8"] and database_max==row["maximum_Q8"]==audit["shard"]["maximum_Q8"];shard_raw=sum(5437+5*(i-247)for i in range(start,stop+1));assert shard_raw==row["independently_counted_raw_multisets"]==audit["shard"]["independently_enumerated_multisets"];raw+=shard_raw;checks+=database_checks;products+=database_products;raw_key+=shard_raw-database_checks;key_product+=database_checks-database_products;minimum=database_min if minimum is None else min(minimum,database_min);maximum=database_max if maximum is None else max(maximum,database_max)
 assert expected==948;aggregate=assembly["aggregate"];assert raw==5032650==aggregate["independently_enumerated_multisets"] and checks==aggregate["canonical_check_keys"] and products==aggregate["distinct_shard_product_jets_sum"] and raw_key==aggregate["multiset_to_canonical_key_compression"] and key_product==aggregate["canonical_key_to_product_compression_within_shards"] and aggregate["negative_Q8"]==aggregate["zero_Q8"]==0 and minimum==aggregate["minimum_Q8"]>0 and maximum==aggregate["maximum_Q8"]
 payload={"schema":"rank8-exceptional-first-crossing-alpha7-s9-complete-audit-v1","status":"PASS_INDEPENDENT_NO_GAP_RANK8_ALPHA7_SOURCE9_ASSEMBLY_AUDIT","method":"rehash all ten triples, derive c9=5437 and c2=5 from TSV, reconstruct formula5437+5L and exact union, query every database for key/product/type/sign/extrema equality","coverage":{"source_alpha":9,"terminal_alpha":7,"terminal_type_indices":[248,947],"terminal_type_count":700,"gaps":0,"overlaps":0},"aggregate":aggregate,"scope_warning":"Independent complete audit only for terminal-alpha7/source9; stops before source10.","hashes":hashes};OUTPUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(payload["status"]);print(f"raw={raw} checks={checks} products={products} neg=0 zero=0 min_Q8={minimum} max_Q8={maximum}");print(f"audit_sha256={digest(OUTPUT)}");return 0
if __name__=="__main__":raise SystemExit(main())
