// Independent checked-i256 literal audit for quartic_endpoint_cubic_path:cubic_cubic_spine_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc;use std::thread;
const QSA_THREADS:usize=6;const QSA_TASKS:usize=48;const QSA_BENCH_RAYS:usize=1_024;
#[derive(Clone,Copy)]struct QSAState{size:i32,long:bool}#[derive(Clone,Copy)]struct QSAMessage{parent_absent:V,parent_present:V}
#[derive(Clone,Copy)]struct QSAQuarticSide{gap:QSAState,spine:QSAState,b0:QSAState,b1:QSAState,b2:QSAState,center_arm:QSAState,message:QSAMessage}#[derive(Clone,Copy)]struct QSACenterSide{gap:QSAState,b0:QSAState,b1:QSAState,message:QSAMessage}
fn qsa_gap(x:i32)->QSAState{QSAState{size:x,long:x==7}}fn qsa_spine(x:i32)->QSAState{QSAState{size:x,long:x==8}}fn qsa_pendant(x:i32)->QSAState{QSAState{size:x,long:x==7}}
fn qsa_propagate(absent:V,present:V,d:i32)->QSAMessage{QSAMessage{parent_absent:add(&mul(&path(d-1),&absent),&mul(&path(d-2),&present)),parent_present:add(&mul(&path(d-2),&absent),&mul(&path(d-3),&present))}}
fn qsa_quartic_to_center(spine:i32,b0:i32,b1:i32,b2:i32)->QSAMessage{qsa_propagate(product(&[path(b0),path(b1),path(b2)]),shifted(&product(&[path(b0-1),path(b1-1),path(b2-1)]),1),spine)}
fn qsa_center_message(gap:i32,spine:i32,b0:i32,b1:i32,b2:i32,arm:i32)->QSAMessage{let q=qsa_quartic_to_center(spine,b0,b1,b2);qsa_propagate(product(&[path(arm),q.parent_absent]),shifted(&product(&[path(arm-1),q.parent_present]),1),gap+1)}
fn qsa_endpoint_message(gap:i32,b0:i32,b1:i32)->QSAMessage{qsa_propagate(product(&[path(b0),path(b1)]),shifted(&product(&[path(b0-1),path(b1-1)]),1),gap+1)}
fn qsa_quartic_sides()->Vec<QSAQuarticSide>{let mut out=Vec::with_capacity(37_632);for gap in 0..=7{for spine in 1..=8{for b0 in 1..=7{for b1 in b0..=7{for b2 in b1..=7{for arm in 1..=7{out.push(QSAQuarticSide{gap:qsa_gap(gap),spine:qsa_spine(spine),b0:qsa_pendant(b0),b1:qsa_pendant(b1),b2:qsa_pendant(b2),center_arm:qsa_pendant(arm),message:qsa_center_message(gap,spine,b0,b1,b2,arm)});}}}}}}assert_eq!(out.len(),37_632);out}
fn qsa_center_sides()->Vec<QSACenterSide>{let mut out=Vec::with_capacity(224);for gap in 0..=7{for b0 in 1..=7{for b1 in b0..=7{out.push(QSACenterSide{gap:qsa_gap(gap),b0:qsa_pendant(b0),b1:qsa_pendant(b1),message:qsa_endpoint_message(gap,b0,b1)});}}}assert_eq!(out.len(),224);out}
fn qsa_states(q:QSAQuarticSide,c:QSACenterSide)->[QSAState;9]{[q.gap,c.gap,q.spine,q.b0,q.b1,q.b2,q.center_arm,c.b0,c.b1]}fn qsa_lengths(s:&[QSAState;9])->[i32;9]{std::array::from_fn(|i|s[i].size)}
fn qsa_direct_polynomials(l:&[i32;9])->(V,V){let q=qsa_center_message(l[0],l[2],l[3],l[4],l[5],l[6]);let c=qsa_endpoint_message(l[1],l[7],l[8]);let d=mul(&q.parent_absent,&c.parent_absent);let p=shifted(&mul(&q.parent_present,&c.parent_present),1);(add(&d,&p),d)}
fn qsa_values(l:&[i32;9],q:QSAQuarticSide,c:QSACenterSide,varying:Option<usize>)->[Z;4]{let a=if varying.is_some_and(|i|i==0||(2..=6).contains(&i)){qsa_center_message(l[0],l[2],l[3],l[4],l[5],l[6])}else{q.message};let b=if varying.is_some_and(|i|i==1||i>=7){qsa_endpoint_message(l[1],l[7],l[8])}else{c.message};let d=mul(&a.parent_absent,&b.parent_absent);let p=shifted(&mul(&a.parent_present,&b.parent_present),1);deltas03(&add(&d,&p),&d)}
fn qsa_extend(a:&mut Vec<Vec<usize>>,start:usize,d:i32)->usize{let mut x=start;for _ in 0..d{let y=a.len();a.push(Vec::new());a[x].push(y);a[y].push(x);x=y;}x}
fn qsa_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let center=qsa_extend(&mut a,root,l[0]+1);let q=qsa_extend(&mut a,center,l[2]);qsa_extend(&mut a,q,l[3]);qsa_extend(&mut a,q,l[4]);qsa_extend(&mut a,q,l[5]);qsa_extend(&mut a,center,l[6]);let endpoint=qsa_extend(&mut a,root,l[1]+1);qsa_extend(&mut a,endpoint,l[7]);qsa_extend(&mut a,endpoint,l[8]);assert_eq!(a.len(),3+l.iter().sum::<i32>()as usize);assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|x|x.len()==4).count(),1);assert_eq!(a.iter().filter(|x|x.len()==3).count(),2);(a,root)}
fn qsa_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qsa_tree(l);audit_deltas(&a,r).0}
fn qsa_independent_smoke(){let mut random=0x739D12EAC6B8405F_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}let(c,d)=qsa_direct_polynomials(&l);assert_eq!(deltas03(&c,&d),qsa_literal_values(&l),"independent cubic-cubic spine mismatch {}",sample);}let qs=qsa_quartic_sides();let roots=qsa_center_sides();for sample in 0..512{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let q=qs[random as usize%qs.len()];random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);let root=roots[random as usize%roots.len()];let mut l=qsa_lengths(&qsa_states(q,root));let varying=random as usize%9;l[varying]+=(random%19)as i32;assert_eq!(qsa_values(&l,q,root,Some(varying)),qsa_literal_values(&l),"cached cubic-cubic spine mismatch {}",sample);}println!("PASS_E5_CUBIC_CUBIC_SPINE_INTERNAL_INDEPENDENT_1024_LITERAL_SMOKE");}
fn qsa_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qsa_hash_state(h:&mut AuditSha256,s:QSAState){h.update(&[s.long as u8]);h.update(&s.size.to_le_bytes());}fn qsa_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qsa_coefficient_leaf(s:&[QSAState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-cubic-cubic-spine-internal-coefficient-v1\0");for &x in s{qsa_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qsa_hash_z(&mut h,z);}}qsa_sha_bytes(h)}
fn qsa_finite_leaf(s:&[QSAState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-cubic-cubic-spine-internal-finite-v1\0");for &x in s{qsa_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qsa_hash_z(&mut h,z);}qsa_sha_bytes(h)}fn qsa_order27_leaf(l:&[i32;9],v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-cubic-cubic-spine-internal-order27-v1\0");for &x in l{h.update(&x.to_le_bytes());}for &z in v{qsa_hash_z(&mut h,z);}qsa_sha_bytes(h)}
fn qsa_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{for p in(AUDIT_DEGREES[rank]+1)..AUDIT_SAMPLES{if !rows[rank][p].is_zero(){return false;}}}true}fn qsa_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{if !rows[rank][0].is_positive()||!rows[rank][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[rank]{if rows[rank][p].is_negative(){return false;}}}qsa_degree_ok(rows)}
fn qsa_formula_coefficients(s:&[QSAState;9],q:QSAQuarticSide,c:QSACenterSide,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qsa_lengths(s);let baseline=3+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qsa_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qsa_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qsa_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qsa_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qsa_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qsa_literal_coefficients(s:&[QSAState;9])->(i32,i32,[[Z;AUDIT_SAMPLES];4]){let varying=s.iter().position(|x|x.long).unwrap();let mut l=qsa_lengths(s);let baseline=3+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qsa_literal_values(&l);for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qsa_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qsa_literal_values(&l);for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows)}
fn qsa_smoke_stream(){let qs=qsa_quartic_sides();let roots=qsa_center_sides();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let root=roots[(sample*17+23)%roots.len()];let s=qsa_states(q,root);if !s.iter().any(|x|x.long){let l=qsa_lengths(&s);let order=3+l.iter().sum::<i32>();if order>=28{let v=qsa_literal_values(&l);fh.update(&qsa_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows)=qsa_literal_coefficients(&s);if !qsa_gate_ok(&rows){gf+=1;}ch.update(&qsa_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
fn qsa_bench(){let qs=qsa_quartic_sides();let roots=qsa_center_sides();let mut h=AuditSha256::new();let(mut rays,mut c)=(0,0);while rays<QSA_BENCH_RAYS{let q=qs[(c*104_729+5)%qs.len()];let root=roots[(c*17+31)%roots.len()];c+=1;let s=qsa_states(q,root);if !s.iter().any(|x|x.long){continue;}let(b,sh,rows,checks)=qsa_formula_coefficients(&s,q,root,true);assert_eq!(checks,3);h.update(&qsa_coefficient_leaf(&s,b,sh,&rows));rays+=1;}println!("BENCH_RAYS {}",rays);println!("BENCH_STREAM {}",h.hex());println!("RESOURCE_TABLE_BYTES {} {}",qs.len()*std::mem::size_of::<QSAQuarticSide>(),roots.len()*std::mem::size_of::<QSACenterSide>());println!("RESOURCE_FULL_LEAF_BYTES {}",8_113_086_usize*32);}
fn qsa_cuts<F:FnMut(&[i32;9])>(next:i32,depth:usize,cuts:&mut[i32;8],f:&mut F){if depth==8{let mut row=[0;9];let mut prev=0;for i in 0..8{row[i]=cuts[i]-prev;prev=cuts[i];}row[8]=26-prev;f(&row);return;}let max=18+depth as i32;for v in next..=max{cuts[depth]=v;qsa_cuts(v+1,depth+1,cuts,f);}}
fn qsa_order27(){let(mut raw_count,mut count)=(0_u64,0_u64);let mut non=[0_u64;4];let mut h=AuditSha256::new();let mut cuts=[0;8];qsa_cuts(1,0,&mut cuts,&mut|positive|{raw_count+=1;let mut l=*positive;l[0]-=1;l[1]-=1;if !(l[3]<=l[4]&&l[4]<=l[5]&&l[7]<=l[8]){return;}let v=qsa_literal_values(&l);for r in 0..4{if !v[r].is_positive(){non[r]+=1;}}h.update(&qsa_order27_leaf(&l,&v));count+=1;});assert_eq!(raw_count,1_081_575);assert_eq!(count,174_083);assert_eq!(non,[0;4]);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_CUBIC_CUBIC_SPINE_INTERNAL_ORDER27\nRAW_COMPOSITIONS {}\nORDER27_COUNT {}\nNONPOSITIVE {} {} {} {}\nLITERAL_TREES {}\nVALUE_STREAM {}\n",raw_count,count,non[0],non[1],non[2],non[3],count,h.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_cubic_cubic_spine_internal_order27_literal_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
struct QSAResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qsa_worker(task:usize,qs:Arc<Vec<QSAQuarticSide>>,roots:Arc<Vec<QSACenterSide>>)->QSAResult{let start=qs.len()*task/QSA_TASKS;let end=qs.len()*(task+1)/QSA_TASKS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();for qi in start..end{let q=qs[qi];for &root in roots.iter(){let s=qsa_states(q,root);let lc=s.iter().filter(|x|x.long).count();if lc==0{counts[0]+=1;let l=qsa_lengths(&s);let order=3+l.iter().sum::<i32>();if order<28{continue;}let v=qsa_values(&l,q,root,None);assert_eq!(v,qsa_literal_values(&l));assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qsa_finite_leaf(&s,order,&v));counts[1]+=1;literal+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,checks)=qsa_formula_coefficients(&s,q,root,true);audit_assert_gate(&rows);coeff.extend_from_slice(&qsa_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;literal+=checks;}}QSAResult{worker:task,counts,unseen,literal,coeff,finite}}
fn qsa_full(){let qs=Arc::new(qsa_quartic_sides());let roots=Arc::new(qsa_center_sides());let mut handles=Vec::new();for w in 0..QSA_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&roots);handles.push(thread::spawn(move||{let mut out=Vec::new();for task in(w..QSA_TASKS).step_by(QSA_THREADS){out.push(qsa_worker(task,Arc::clone(&a),Arc::clone(&b)));}out}));}let mut results:Vec<_>=handles.into_iter().flat_map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[2_420_208,2_103_726,6_009_359,1,6_009_360]);assert_eq!(unseen,24_037_440);assert_eq!(literal,20_131_806);let raw=format!("PASS_INDEPENDENT_LITERAL_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_CUBIC_CUBIC_SPINE_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_TREES {}\nLITERAL_RAY_POINTS 0 13 29\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_cubic_cubic_spine_internal_literal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qsa_independent_smoke();qsa_smoke_stream();},Some("bench")=>qsa_bench(),Some("order27")=>qsa_order27(),Some(x)=>panic!("unknown mode {}",x),None=>qsa_full()}}
