#!/usr/bin/env python3
"""Exact arbitrary-attachment loss coordinates for adjacent no-parent G3."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
import sympy as sp
HERE=Path(__file__).resolve().parent;INPUT=HERE/"iso_n7_bundle_g3_adjacent_no_parent_rooted_partition_exact_rank7_g5_finish_20260831.json";INPUT_SHA256="01DA8DA65E252C5BFA46D17021775EE0A168526A6CF164A325D2B84C01005F74";OUTPUT=HERE/"iso_n7_bundle_g3_adjacent_no_parent_general_attachment_losses_exact_rank7_g5_finish_20260831.json";MARKER="DERIVED_EXACT_ISO_N7_BUNDLE_G3_ADJACENT_NO_PARENT_GENERAL_ATTACHMENT_LOSSES_RANK7_G5_FINISH"
def sha256(p):return hashlib.sha256(p.read_bytes()).hexdigest().upper()
def main():
 assert sha256(INPUT)==INPUT_SHA256;up=json.loads(INPUT.read_text());m=sp.Symbol("m",positive=True);a,b=sp.symbols("a b",nonnegative=True,integer=True);W={0:sp.Integer(1),1:m,**{k:sp.Symbol(f"W{k}",nonnegative=True) for k in range(2,9)}};S={k:sp.Symbol(f"S{k}",nonnegative=True) for k in range(1,8)};T={k:sp.Symbol(f"T{k}",nonnegative=True) for k in range(1,8)};P={1:b,**{k:sp.Symbol(f"P{k}",nonnegative=True) for k in range(2,8)}};Q={1:a,**{k:sp.Symbol(f"Q{k}",nonnegative=True) for k in range(2,8)}};loc={"m":m,**{f"W{k}":W[k] for k in range(2,9)},**{f"S{k}":S[k] for k in S},**{f"T{k}":T[k] for k in T}};master=sp.expand(sp.sympify(up["theorem_input_identity"],locals=loc));exact=sp.expand(master.subs({**{S[k]:W[k]-P[k] for k in S},**{T[k]:W[k]-Q[k] for k in T}},simultaneous=True));zero=sp.expand(exact.subs({**{P[k]:0 for k in range(2,8)},**{Q[k]:0 for k in range(2,8)}}));bilinear={f"P{i}_Q{j}":str(sp.factor(sp.diff(exact,P[i],Q[j]))) for i in range(2,8) for j in range(2,8) if sp.diff(exact,P[i],Q[j])!=0};plin={k:sp.factor(sp.diff(exact,P[k]).subs({Q[j]:0 for j in range(2,8)})) for k in range(2,8)};qlin={k:sp.factor(sp.diff(exact,Q[k]).subs({P[j]:0 for j in range(2,8)})) for k in range(2,8)};recon=zero+sum(plin[k]*P[k]+qlin[k]*Q[k] for k in range(2,8))+sum(sp.Integer(v)*P[int(n.split("_")[0][1:])]*Q[int(n.split("_")[1][1:])] for n,v in bilinear.items());assert sp.expand(exact-recon)==0
 report={"marker":MARKER,"status":"exact algebra; no sign theorem asserted","identity":str(exact),"loss_zero_base":str(zero),"P_linear_coefficients":{str(k):str(v) for k,v in plin.items()},"Q_linear_coefficients":{str(k):str(v) for k,v in qlin.items()},"bilinear_coefficients":bilinear,"bilinear_term_count":len(bilinear),"semantics":{"a":"|X|, attachments at u","b":"|Y|, attachments at v","Pj":"W_j-S_j, independent j-sets meeting Y","Qj":"W_j-T_j, independent j-sets meeting X","structural":"X,Y disjoint and each W-component contains at most one vertex of X union Y"},"scope":"Adjacent no-parent G3, arbitrary attachment count; no sign theorem.","input_sha256":INPUT_SHA256,"source_sha256":sha256(Path(__file__))};raw=json.dumps(report,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(raw,encoding="utf-8",newline="\n");print(json.dumps({"marker":MARKER,"terms":len(sp.Poly(exact,*sorted(exact.free_symbols,key=str)).terms()),"bilinear_terms":len(bilinear),"zero_base_degree_ab":sp.Poly(zero,a,b).total_degree()},indent=2));print("SOURCE_SHA256",report["source_sha256"]);print("REPORT_SHA256",hashlib.sha256(raw.encode()).hexdigest().upper());print(MARKER)
if __name__=="__main__":main()
