#!/usr/bin/env python3
"""Derive the source-paired compensation identity for the ordinary FML gap.

The compact A/B display separates a positive-looking N part from a Schur
curvature of R.  That separation fails on the induction-closed collar.  The
identity derived here keeps each R correction paired with the multiplication
by X that creates it:

    G_N(C,H) = L_N(C) + 2 B_N(XC,XH).

This is exact polynomial algebra only; neither summand is asserted positive.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import sympy as sp

from derive_iso_nested_compact_operator_root import add, scale_x, symbols, w, z
from derive_iso_third_leaf_compact_operator_root import defect_form, nested


HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "iso_compact_ordinary_coupled_compensation_symbolic_root_20260829.json"


def tuple_add(left, right):
    return tuple(add(a, b) for a, b in zip(left, right))


def tuple_x(value):
    return tuple(scale_x(row) for row in value)


def polar(form, left, right):
    return sp.expand(
        (form(tuple_add(left, right)) - form(left) - form(right)) / 2
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def main() -> None:
    C = tuple(symbols(f"C{name}") for name in "EUVW")
    H = tuple(symbols(f"H{name}") for name in "EUVW")
    XC, XH = tuple_x(C), tuple_x(H)
    delta = (z - w) ** 2 / 2

    # For A=C+XH and Full=A+XC, this is the exact ordinary-leaf gap.
    deleted = tuple_add(C, XH)
    full = tuple_add(deleted, XC)
    ordinary = sp.expand(nested(full) - nested(deleted) - z * w * nested(C))

    isolate = sp.expand(
        nested(tuple_add(C, XC)) - nested(C) - z * w * nested(C)
    )
    x_cross = sp.expand(2 * polar(nested, XC, XH))
    assert sp.expand(ordinary - isolate - x_cross) == 0

    # Polarizing N(XT)=zw N(T)-delta R(T) gives the paired cross rule.
    x_cross_claimed = sp.expand(
        2 * z * w * polar(nested, C, H)
        - 2 * delta * polar(defect_form, C, H)
    )
    assert sp.expand(x_cross - x_cross_claimed) == 0

    isolate_claimed = sp.expand(
        (z + w) * nested(C) - delta * defect_form(C)
    )
    assert sp.expand(isolate - isolate_claimed) == 0

    # Reassemble the earlier A/B display and check exact equality.
    A = sp.expand(
        (z + w) * nested(C) + 2 * z * w * polar(nested, C, H)
    )
    B = sp.expand(
        -delta * (defect_form(tuple_add(C, H)) - defect_form(H))
    )
    assert sp.expand(ordinary - A - B) == 0
    assert sp.expand(
        B
        + delta * defect_form(C)
        + 2 * delta * polar(defect_form, C, H)
    ) == 0

    report = {
        "marker": "DERIVED_EXACT_ISO_COMPACT_ORDINARY_COUPLED_COMPENSATION",
        "definitions": {
            "delta": "(z-w)^2/2",
            "B_N": "symmetric polarization of N",
            "B_R": "symmetric polarization of R",
            "L_N(C)": "N((1+X)C)-N(C)-zwN(C)",
            "G_N(C,H)": (
                "N(C+XH+XC)-N(C+XH)-zwN(C)"
            ),
        },
        "source_paired_identity": "G_N(C,H)=L_N(C)+2 B_N(XC,XH)",
        "multiplication_pairs": {
            "isolate": "L_N(C)=(z+w)N(C)-delta R(C)",
            "cross": (
                "B_N(XC,XH)=zw B_N(C,H)-delta B_R(C,H)"
            ),
        },
        "equivalent_compact_split": {
            "A": "(z+w)N(C)+2zw B_N(C,H)",
            "B": "-delta[R(C+H)-R(H)]",
            "identity": "G_N=A+B",
        },
        "interpretation": (
            "Every R-curvature term is exactly the correction generated by "
            "multiplication by X. Bounds should be applied to the paired "
            "L_N and B_N(X.,X.) expressions, not to R in isolation."
        ),
        "scope": (
            "Exact symbolic compensation identity only. It proves no "
            "coefficient sign; the two source-paired summands can still "
            "require compensation with one another."
        ),
        "source_sha256": sha256(Path(__file__).resolve()),
    }
    raw = json.dumps(report, indent=2, sort_keys=True) + "\n"
    OUTPUT.write_bytes(raw.encode("utf-8"))
    print(json.dumps(report, indent=2, sort_keys=True))
    print("REPORT_SHA256", hashlib.sha256(raw.encode()).hexdigest().upper())
    print(report["marker"])


if __name__ == "__main__":
    main()
