#!/usr/bin/env python3
"""Search exact frozen-cell representations of the retained-isolate G1 gap.

For an actual marked forest/minor pair (A,B), adding and retaining a common
isolated unmarked vertex gives (IA,IB)=((1+x)A,(1+x)B).  This script asks
whether

    G1_6(IA,IB)-G1_6(A,B)

lies in the scalar linear span of already-frozen rank-six G2,...,G10 cells
on the natural actual-minor pairs generated by A,B,IA,IB.  A span identity is
algebra only; positivity would additionally require nonnegative coefficients.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import sympy as sp

from audit_iso_n6_bundle_g6_g2_transfer_audit import isolate_multiply
from derive_iso_n6_bundle_g1_ordinary_leaf_increment_identity_g1_nonadjacent import substitute
from explore_iso_n6_bundle_g2_marked_cone_g1_bernstein import reconstruct


HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "iso_n6_bundle_g1_retained_isolate_frozen_span_exact_root_20260901.json"
MARKER = "DERIVED_EXACT_ISO_N6_BUNDLE_G1_RETAINED_ISOLATE_FROZEN_SPAN_ROOT"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def rows(prefix: str):
    return tuple(tuple(sp.symbols(f"{prefix}{family}0:8")) for family in "EUVW")


def zero_rows():
    return tuple(tuple(sp.Integer(0) for _ in range(8)) for _ in "EUVW")


def exact_span(target: sp.Expr, candidates: list[tuple[str, sp.Expr]]):
    variables = tuple(sorted(
        target.free_symbols
        | set().union(*(value.free_symbols for _, value in candidates)),
        key=str,
    ))
    target_terms = dict(sp.Poly(target, *variables).terms())
    candidate_terms = [dict(sp.Poly(value, *variables).terms()) for _, value in candidates]
    monomials = sorted(set(target_terms).union(*(set(row) for row in candidate_terms)))
    matrix = sp.MutableSparseMatrix(
        len(monomials), len(candidates),
        {
            (i, j): candidate_terms[j][monomial]
            for i, monomial in enumerate(monomials)
            for j in range(len(candidates))
            if monomial in candidate_terms[j]
        },
    )
    rhs = sp.Matrix([target_terms.get(monomial, 0) for monomial in monomials])
    solution = sp.linsolve((matrix, rhs))
    return solution, matrix.shape, len(monomials)


def main() -> None:
    arows, brows, zeros = rows("A"), rows("B"), zero_rows()
    iarows = isolate_multiply(arows, 1)
    ibrows = isolate_multiply(brows, 1)
    g1 = reconstruct(1)
    target = sp.expand(substitute(g1, iarows, ibrows) - substitute(g1, arows, brows))

    # Every listed pair is a natural actual-minor pair whenever B is induced
    # in A.  Zero denotes the empty D-linear block, which is also an allowed
    # boundary specialization of the frozen cell polynomial.
    pairs = [
        ("A,0", arows, zeros),
        ("A,B", arows, brows),
        ("IA,0", iarows, zeros),
        ("IA,B", iarows, brows),
        ("IA,IB", iarows, ibrows),
        ("B,0", brows, zeros),
        ("IB,0", ibrows, zeros),
        ("IB,B", ibrows, brows),
    ]
    candidates: list[tuple[str, sp.Expr]] = []
    exact_matches = []
    for index in range(2, 11):
        coefficient = reconstruct(index)
        for pair_label, crows, drows in pairs:
            value = sp.expand(substitute(coefficient, crows, drows))
            label = f"G{index}({pair_label})"
            candidates.append((label, value))
            if sp.expand(target - value) == 0:
                exact_matches.append(label)

    solution, shape, monomials = exact_span(target, candidates)
    report = {
        "marker": MARKER,
        "target": "G1_6((1+x)A,(1+x)B)-G1_6(A,B)",
        "candidate_labels": [label for label, _ in candidates],
        "candidate_count": len(candidates),
        "coefficient_matrix_shape": list(shape),
        "monomial_count": monomials,
        "exact_single_cell_matches": exact_matches,
        "linear_solution": str(solution),
        "linear_span_nonempty": solution != sp.EmptySet,
        "scope_guard": (
            "An empty span rules out only constant scalar combinations of the listed frozen "
            "cells. A nonempty span is not a positivity proof unless one verifies a "
            "nonnegative representation using only theorem-valid cells."
        ),
        "dependencies_sha256": {
            "audit_iso_n6_bundle_g6_g2_transfer_audit.py": sha256(
                HERE / "audit_iso_n6_bundle_g6_g2_transfer_audit.py"
            ),
            "derive_iso_n6_bundle_g1_ordinary_leaf_increment_identity_g1_nonadjacent.py": sha256(
                HERE / "derive_iso_n6_bundle_g1_ordinary_leaf_increment_identity_g1_nonadjacent.py"
            ),
            "explore_iso_n6_bundle_g2_marked_cone_g1_bernstein.py": sha256(
                HERE / "explore_iso_n6_bundle_g2_marked_cone_g1_bernstein.py"
            ),
        },
        "source_sha256": sha256(Path(__file__)),
    }
    payload = (json.dumps(report, indent=2, sort_keys=True) + "\n").encode()
    OUTPUT.write_bytes(payload)
    print(json.dumps({
        "marker": MARKER,
        "candidate_count": len(candidates),
        "shape": list(shape),
        "single_matches": exact_matches,
        "linear_solution": str(solution),
    }, indent=2, sort_keys=True))
    print("SOURCE_SHA256", report["source_sha256"])
    print("REPORT_SHA256", hashlib.sha256(payload).hexdigest().upper())
    print(MARKER)


if __name__ == "__main__":
    main()
