#!/usr/bin/env python3
"""Exact 3+0 and 2+1 attachment reductions for adjacent no-parent G3."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
import sympy as sp
HERE=Path(__file__).resolve().parent;INPUT=HERE/"iso_n7_bundle_g3_adjacent_no_parent_general_attachment_losses_exact_rank7_g5_finish_20260831.json";INPUT_SHA256="CB3E129A9F2E6EBF6F5AF6D70B917147121041505A312628A39BB4960C79F699";OUTPUT=HERE/"iso_n7_bundle_g3_adjacent_no_parent_three_attachment_distributions_exact_rank7_g5_finish_20260831.json";MARKER="DERIVED_EXACT_ISO_N7_BUNDLE_G3_ADJACENT_NO_PARENT_THREE_ATTACHMENT_DISTRIBUTIONS_RANK7_G5_FINISH"
def sha256(p):return hashlib.sha256(p.read_bytes()).hexdigest().upper()
def main():
 assert sha256(INPUT)==INPUT_SHA256;up=json.loads(INPUT.read_text());m=sp.Symbol("m",positive=True);a,b=sp.symbols("a b",nonnegative=True,integer=True);W={k:sp.Symbol(f"W{k}",nonnegative=True) for k in range(2,9)};P={k:sp.Symbol(f"P{k}",nonnegative=True) for k in range(2,8)};Q={k:sp.Symbol(f"Q{k}",nonnegative=True) for k in range(2,8)};loc={"m":m,"a":a,"b":b,**{f"W{k}":W[k] for k in W},**{f"P{k}":P[k] for k in P},**{f"Q{k}":Q[k] for k in Q}};exact=sp.expand(sp.sympify(up["identity"],locals=loc))
 same=sp.expand(exact.subs({a:3,b:0,**{P[k]:0 for k in P}},simultaneous=True));samebase=sp.expand(same.subs({Q[k]:0 for k in Q}));samecoef={k:sp.factor(sp.diff(same,Q[k])) for k in Q};assert sp.expand(same-samebase-sum(samecoef[k]*Q[k] for k in Q))==0
 split=sp.expand(exact.subs({a:2,b:1}));zero=sp.expand(split.subs({**{P[k]:0 for k in P},**{Q[k]:0 for k in Q}}));pl={k:sp.factor(sp.diff(split,P[k]).subs({Q[j]:0 for j in Q})) for k in P};ql={k:sp.factor(sp.diff(split,Q[k]).subs({P[j]:0 for j in P})) for k in Q};bi={f"P{i}_Q{j}":str(sp.factor(sp.diff(split,P[i],Q[j]))) for i in P for j in Q if sp.diff(split,P[i],Q[j])!=0};recon=zero+sum(pl[k]*P[k]+ql[k]*Q[k] for k in P)+sum(sp.Integer(v)*P[int(n.split("_")[0][1:])]*Q[int(n.split("_")[1][1:])] for n,v in bi.items());assert sp.expand(split-recon)==0
 report={"marker":MARKER,"status":"exact algebra; no sign theorem asserted","same_mark_3plus0":{"identity":str(same),"loss_zero_base":str(samebase),"Q_coefficients":{str(k):str(v) for k,v in samecoef.items()},"linear_in_union_loss":True},"split_mark_2plus1":{"identity":str(split),"loss_zero_base":str(zero),"P_coefficients":{str(k):str(v) for k,v in pl.items()},"Q_coefficients":{str(k):str(v) for k,v in ql.items()},"bilinear_coefficients":bi,"bilinear_term_count":len(bi)},"semantics":"For 2+1, Q meets the two X-roots and P meets the single Y-root; all three roots lie in distinct W-components.","scope":"Adjacent no-parent G3 with exactly three attachments only.","input_sha256":INPUT_SHA256,"source_sha256":sha256(Path(__file__))};raw=json.dumps(report,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(raw,encoding="utf-8",newline="\n");print(json.dumps({"marker":MARKER,"same_terms":len(sp.Poly(same,*sorted(same.free_symbols,key=str)).terms()),"split_terms":len(sp.Poly(split,*sorted(split.free_symbols,key=str)).terms()),"split_bilinear_terms":len(bi)},indent=2));print("SOURCE_SHA256",report["source_sha256"]);print("REPORT_SHA256",hashlib.sha256(raw.encode()).hexdigest().upper());print(MARKER)
if __name__=="__main__":main()
