#!/usr/bin/env python3
"""Search for a proved-gadget cone representation of rank-five bundle g2.

This is a discovery script, not a certificate.  It asks whether the raw g2
form lies in the nonnegative cone generated by the already proved all-forest
N4 form and the proved rank-five cross-orientation C5 form on small leaf-star
gadgets built over the same support cell.
"""

from __future__ import annotations

import itertools

import numpy as np
import sympy as sp
from scipy.optimize import linprog

import derive_iso_n5_bundle_g12_canonical_configuration_g1_bernstein as canonical


def at(row, rank):
    return row[rank] if 0 <= rank < len(row) else sp.Integer(0)


def add_isolates(row, number, maximum=6):
    return tuple(
        sp.expand(sum(sp.binomial(number, j) * at(row, rank - j) for j in range(rank + 1)))
        for rank in range(maximum + 1)
    )


def add_xd(crow, drow):
    return tuple(sp.expand(at(crow, rank) + at(drow, rank - 1)) for rank in range(7))


def q(row, rank):
    return (
        rank * at(row, rank) ** 2
        + at(row, rank - 1) ** 2
        - (rank + 1) * at(row, rank - 1) * at(row, rank + 1)
    )


def leaf_d(left, right, rank):
    return (
        at(right, rank - 1) ** 2
        + 2 * rank * at(left, rank) * at(right, rank - 1)
        + 2 * at(left, rank - 1) * at(right, rank - 2)
        - (rank + 1) * at(left, rank - 1) * at(right, rank)
        - (rank + 1) * at(right, rank - 2) * at(left, rank + 1)
        - at(right, rank - 2) * at(right, rank)
    )


def cross(rows, rank):
    _e, u, v, w = rows
    p = tuple(at(u, rank) + at(w, rank - 1) for rank in range(7))
    return sp.expand(q(p, rank) + leaf_d(v, w, rank))


def main():
    crows, drows, _g1, target = canonical.raw_coefficients()

    def graph_row(number, deleted):
        index = int("u" in deleted) + 2 * int("v" in deleted)
        remaining = number - sum(name.startswith("a") for name in deleted)
        cpart = add_isolates(crows[index], remaining)
        if "s" in deleted:
            return cpart
        return add_xd(cpart, drows[index])

    def four_rows(number, first, second):
        return tuple(
            graph_row(number, deleted)
            for deleted in (set(), {first}, {second}, {first, second})
        )

    candidates = []
    for number in range(5):
        vertices = ["u", "v", "s", *(f"a{j}" for j in range(number))]
        seen = set()
        for first, second in itertools.combinations(vertices, 2):
            rows = four_rows(number, first, second)
            for kind, expression in (
                ("C4", cross(rows, 4)),
                ("C5", cross(rows, 5)),
                ("Q4", q(rows[0], 4)),
                ("Q5", q(rows[0], 5)),
                ("N3", sp.expand(canonical.nested(rows, 3))),
                ("N4", sp.expand(canonical.nested(rows, 4))),
            ):
                key = sp.srepr(expression)
                if key in seen:
                    continue
                seen.add(key)
                candidates.append((f"{kind}:B{number}:{first},{second}", expression))

    variables = tuple(symbol for row in crows + drows for symbol in row)
    polynomials = [sp.Poly(target, *variables)] + [
        sp.Poly(expression, *variables) for _name, expression in candidates
    ]
    dictionaries = [dict(polynomial.terms()) for polynomial in polynomials]
    monomials = sorted(set().union(*(dictionary for dictionary in dictionaries)))
    matrix = np.zeros((len(monomials), len(candidates)))
    rhs = np.zeros(len(monomials))
    for row_index, monomial in enumerate(monomials):
        rhs[row_index] = float(dictionaries[0].get(monomial, 0))
        for column_index, dictionary in enumerate(dictionaries[1:]):
            matrix[row_index, column_index] = float(dictionary.get(monomial, 0))

    result = linprog(
        np.ones(len(candidates)),
        A_eq=matrix,
        b_eq=rhs,
        bounds=(0, None),
        method="highs",
    )
    print("CANDIDATES", len(candidates))
    print("MONOMIALS", len(monomials))
    print("FEASIBLE", result.success)
    print("MESSAGE", result.message)
    if result.success:
        for value, (name, _expression) in zip(result.x, candidates):
            if value > 1e-8:
                print(name, value)


if __name__ == "__main__":
    main()
