#!/usr/bin/env python3
"""Test low-degree membership of L in the module generated by Q and derivatives."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import sympy as sp

from analyze_path_isolate_p4_bottom_pair_affine_two_kernel import T, V, m, q, w, x, z
from analyze_path_isolate_p4_group_affine_grouped_tail_symbolic import c
from probe_path_isolate_p4_affine_parameter_monotonicity_reaggregated_v import (
    bottom_increment,
    group_increment,
    quotient,
)
from probe_path_isolate_p4_group_affine_j_ratio_rational import PRIMES, rank_modulo


def sparse_zw(expression: sp.Expr) -> dict[tuple[int, int], int]:
    return {
        tuple(map(int, monomial)): int(coefficient)
        for monomial, coefficient in sp.Poly(sp.expand(expression), z, w).terms()
    }


def shifted(source: dict[tuple[int, int], int], dz: int, dw: int):
    return {(pz + dz, pw + dw): value for (pz, pw), value in source.items()}


def membership(target, generators, maximum_degree: int) -> dict:
    columns = []
    labels = []
    for generator_index, generator in enumerate(generators):
        for total in range(maximum_degree + 1):
            for dz in range(total + 1):
                dw = total - dz
                columns.append(shifted(generator, dz, dw))
                labels.append([generator_index, dz, dw])
    rows = sorted(set(target).union(*(set(column) for column in columns)))
    matrix = [
        [column.get(row, 0) for column in columns]
        for row in rows
    ]
    augmented = [
        row_values + [target.get(row, 0)]
        for row, row_values in zip(rows, matrix)
    ]
    ranks = []
    for prime in PRIMES:
        base_rank = rank_modulo(matrix, prime)
        augmented_rank = rank_modulo(augmented, prime)
        ranks.append({
            "prime": prime,
            "base_rank": base_rank,
            "augmented_rank": augmented_rank,
            "member": base_rank == augmented_rank,
        })
    return {
        "maximum_multiplier_total_degree": maximum_degree,
        "row_count": len(rows),
        "column_count": len(columns),
        "membership_by_prime": ranks,
        "candidate_member": all(item["member"] for item in ranks),
    }


def audit_family(
    family: str, parity: int, coordinate: str, derivative_order: int
) -> dict:
    d_expression, reserve_expression = (
        group_increment(parity, coordinate)
        if family == "group" else bottom_increment(parity, coordinate)
    )
    common = T**3 if family == "group" else q**2 * T**3
    d_reduced = quotient(d_expression, common)
    reserve_reduced = quotient(reserve_expression, common)
    L = quotient(d_reduced - reserve_reduced, V)
    Q = quotient(reserve_reduced, T**2)
    generators = []
    generator_labels = []
    for total in range(derivative_order + 1):
        for z_order in range(total + 1):
            w_order = total - z_order
            expression = (
                z**z_order * w**w_order
                * sp.diff(Q, z, z_order, w, w_order)
            )
            generators.append(sparse_zw(expression))
            generator_labels.append([z_order, w_order])
    parameter_poly = sp.Poly(sp.expand(L), c, m, x)
    slices = []
    for parameter_monomial, coefficient in parameter_poly.terms():
        target = sparse_zw(coefficient)
        maximum_audit = membership(target, generators, 6)
        audits = [maximum_audit]
        minimum_degree = None
        if maximum_audit["candidate_member"]:
            for degree in range(6):
                result = membership(target, generators, degree)
                audits.append(result)
                if result["candidate_member"]:
                    minimum_degree = degree
                    break
            if minimum_degree is None:
                minimum_degree = 6
        slices.append({
            "parameter_monomial_c_m_x": list(map(int, parameter_monomial)),
            "target_term_count": len(target),
            "candidate_minimum_degree": minimum_degree,
            "audits": audits,
        })
        print(family, parameter_monomial, minimum_degree, flush=True)
    return {
        "family": family,
        "parity": parity,
        "coordinate": coordinate,
        "maximum_derivative_order": derivative_order,
        "generator_derivative_orders": generator_labels,
        "generator_term_counts": [len(item) for item in generators],
        "slice_count": len(slices),
        "candidate_slice_count": sum(
            item["candidate_minimum_degree"] is not None for item in slices
        ),
        "slices": slices,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--derivative-order", type=int, choices=(1, 2, 3), default=1)
    args = parser.parse_args()
    records = [
        audit_family("group", 0, "m", args.derivative_order),
    ]
    report = {
        "status": (
            "ALL_SLICES_CANDIDATE" if all(
                record["candidate_slice_count"] == record["slice_count"]
                for record in records
            ) else "MODULE_REFUTED_IN_TESTED_DEGREES"
        ),
        "records": records,
        "scope": (
            "The hard group family alone suffices to refute this proposed "
            "uniform module certificate."
        ),
        "warning": "Modular membership candidates would require exact reconstruction.",
    }
    Path(
        "path_isolate_p4_affine_parameter_monotonicity_"
        f"L_Q_derivative_module_order{args.derivative_order}_probe_20260802.json"
    ).write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "status": report["status"],
        "family_counts": [
            [record["candidate_slice_count"], record["slice_count"]]
            for record in records
        ],
    }, indent=2))


if __name__ == "__main__":
    main()
