#!/usr/bin/env python3
"""Exact finite probe for token-sliding ratio monotonicity on trees.

For a tree T, let i_r count independent r-sets and let s_r be the number
of edges of the token-sliding graph on independent r-sets.  The candidate

    s_(r+1) / ((r+1)i_(r+1)) <= s_r / (r i_r),  r>=2,

would reduce the uniform component-surplus inequality to its elementary
rank-two case.  This program exhausts unlabelled trees generated by nauty
geng and checks every available rank in exact integer arithmetic.  A PASS
is finite evidence only; a failure is an independently replayable graph6
counterexample to this candidate, not automatically to Erdos Problem 993.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import subprocess

import networkx as nx


ROOT = Path(__file__).resolve().parent


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def add(left: list[int], right: list[int], cap: int) -> list[int]:
    out = [0] * min(cap + 1, max(len(left), len(right)))
    for index in range(len(out)):
        out[index] = (left[index] if index < len(left) else 0) + (
            right[index] if index < len(right) else 0
        )
    return out


def multiply(left: list[int], right: list[int], cap: int) -> list[int]:
    out = [0] * min(cap + 1, len(left) + len(right) - 1)
    for i, a in enumerate(left):
        for j, b in enumerate(right[: cap + 1 - i]):
            if i + j < len(out):
                out[i + j] += a * b
    return out


def forest_polynomial(
    adjacency: list[list[int]], active: list[bool], cap: int
) -> list[int]:
    seen = [False] * len(adjacency)

    def visit(vertex: int, parent: int) -> tuple[list[int], list[int]]:
        seen[vertex] = True
        excluded = [1]
        included = [0, 1]
        for child in adjacency[vertex]:
            if child == parent or not active[child] or seen[child]:
                continue
            child_excluded, child_included = visit(child, vertex)
            excluded = multiply(
                excluded, add(child_excluded, child_included, cap), cap
            )
            included = multiply(included, child_excluded, cap)
        return excluded, included

    total = [1]
    for vertex in range(len(adjacency)):
        if active[vertex] and not seen[vertex]:
            excluded, included = visit(vertex, -1)
            total = multiply(total, add(excluded, included, cap), cap)
    return total


def evaluate(graph: nx.Graph, rank_cap: int) -> tuple[list[int], list[int]]:
    n = graph.number_of_nodes()
    adjacency = [sorted(graph.neighbors(vertex)) for vertex in range(n)]
    full = forest_polynomial(adjacency, [True] * n, rank_cap)
    slides = [0] * (rank_cap + 1)
    for left, right in graph.edges():
        deleted = {left, right, *adjacency[left], *adjacency[right]}
        active = [vertex not in deleted for vertex in range(n)]
        residual = forest_polynomial(adjacency, active, rank_cap - 1)
        for rank in range(1, rank_cap + 1):
            if rank - 1 < len(residual):
                slides[rank] += residual[rank - 1]
    return full, slides


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--minimum-order", type=int, default=4)
    parser.add_argument("--maximum-order", type=int, default=16)
    parser.add_argument("--rank-cap", type=int, default=32)
    parser.add_argument(
        "--geng",
        type=Path,
        default=ROOT / "nauty2_8_9" / "geng.exe",
    )
    args = parser.parse_args()

    failures: list[dict] = []
    averaged_failures: list[dict] = []
    orders: list[dict] = []
    tree_count = 0
    ratio_checks = 0
    averaged_checks = 0
    smallest_positive_cross = None
    smallest_positive_row = None

    for n in range(max(4, args.minimum_order), args.maximum_order + 1):
        order_count = 0
        process = subprocess.Popen(
            [
                str(args.geng),
                "-cq",
                str(n),
                f"{n - 1}:{n - 1}",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        assert process.stdout is not None
        for raw in process.stdout:
            graph6 = raw.strip()
            if not graph6:
                continue
            graph = nx.from_graph6_bytes(graph6)
            cap = min(args.rank_cap, n)
            full, slides = evaluate(graph, cap)
            order_count += 1
            tree_count += 1

            w = math.comb(n - 2, 2)
            surplus = sum(
                math.comb(graph.degree(vertex) - 1, 2)
                for vertex in graph.nodes()
            )
            m2 = w - surplus
            previous = None
            for rank in range(2, min(cap, len(full) - 1) + 1):
                if not full[rank]:
                    continue
                current = (slides[rank], rank * full[rank])
                averaged_margin = (
                    rank * m2 * full[rank] - w * slides[rank]
                )
                averaged_checks += 1
                if averaged_margin < 0 and len(averaged_failures) < 25:
                    averaged_failures.append(
                        {
                            "order": n,
                            "rank": rank,
                            "margin": averaged_margin,
                            "graph6": graph6.decode("ascii"),
                        }
                    )
                if previous is not None:
                    # previous ratio >= current ratio iff this cross product >=0.
                    cross = previous[0] * current[1] - current[0] * previous[1]
                    ratio_checks += 1
                    row = {
                        "order": n,
                        "upper_rank": rank,
                        "lower_slides": previous[0],
                        "lower_denominator": previous[1],
                        "upper_slides": current[0],
                        "upper_denominator": current[1],
                        "cross_margin": cross,
                        "graph6": graph6.decode("ascii"),
                    }
                    if cross < 0 and len(failures) < 25:
                        failures.append(row)
                    if cross > 0 and (
                        smallest_positive_cross is None
                        or cross < smallest_positive_cross
                    ):
                        smallest_positive_cross = cross
                        smallest_positive_row = row
                previous = current

            if failures or averaged_failures:
                process.kill()
                break
        _, stderr = process.communicate()
        if process.returncode not in (0, -9, 1) and not failures:
            raise RuntimeError(
                f"geng failed at order {n}: {stderr.decode(errors='replace')}"
            )
        orders.append({"order": n, "trees": order_count})
        print(
            f"ORDER {n} TREES {order_count} RATIO_CHECKS {ratio_checks} "
            f"AVERAGED_CHECKS {averaged_checks}",
            flush=True,
        )
        if failures or averaged_failures:
            break

    report = {
        "schema": "token-sliding-ratio-monotonicity-geng-probe-root-v1",
        "status": (
            "COUNTEREXAMPLE_EXACT_TOKEN_SLIDING_RATIO_MONOTONICITY"
            if failures
            else (
                "COUNTEREXAMPLE_EXACT_UNIFORM_TOKEN_SLIDING_SURPLUS"
                if averaged_failures
                else "PASS_EXACT_FINITE_TOKEN_SLIDING_RATIO_MONOTONICITY"
            )
        ),
        "candidate": (
            "s_(r+1)/((r+1)i_(r+1)) <= s_r/(r i_r) for every tree and r>=2"
        ),
        "orders": orders,
        "tree_count": tree_count,
        "ratio_checks": ratio_checks,
        "averaged_checks": averaged_checks,
        "failures": failures,
        "averaged_candidate_failures": averaged_failures,
        "smallest_positive_cross_margin": smallest_positive_row,
        "geng_sha256": sha256(args.geng),
        "source_sha256": sha256(Path(__file__)),
        "scope_warning": (
            "A finite PASS is diagnostic only and does not prove the all-order ratio theorem."
        ),
    }
    output = ROOT / "token_sliding_ratio_monotonicity_geng_probe_root_20260828.json"
    output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(report["status"])
    print("tree_count", tree_count, "ratio_checks", ratio_checks)
    print("failures", len(failures), "averaged_failures", len(averaged_failures))
    print("source_sha256", report["source_sha256"])
    print("report_sha256", sha256(output))


if __name__ == "__main__":
    main()
