#!/usr/bin/env python3
"""Exact wedge/simplex Bernstein probe for adjacent rank-six g2.

The ambient forest row A uses its exact edge/wedge coefficient

    a2=C(N,2)-e,
    a3=C(N,3)-e(N-2)+Omega,

with the valid continuous relaxation e=r*z and 0<=Omega<=e^2/2.  The remaining
factorial ratios are generated by the four mandatory unit drops, with their
residual budget distributed on a five-part simplex.  Each induced row B,C is
fixed at one path/edgeless box corner; all 32^2 corners are separate shards.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
import hashlib
import json
import math
from pathlib import Path

from flint import fmpq, fmpq_mpoly_ctx

from balanced_flint_mpoly_sum_root import balanced_batched_sum
from tensor_bernstein_flint_matrix_root import tensor_bernstein_from_flint_matrix
from probe_iso_n6_bundle_g2_adjacent_q3_endpoints_flint_root import (
    choose,
    compactify,
    path_floor,
    sha256,
)


HERE = Path(__file__).resolve().parent
OCCUPATION = HERE / "iso_n6_bundle_g2_no_parent_occupation_exact_root_20260831.json"
OCCUPATION_SHA256 = "106BD6048269E1CFE1F51A0DA162312786E28EB8E8707BF57CBBE8E7BA9D0F83"
MARKER = "PROBE_EXACT_ISO_N6_BUNDLE_G2_ADJACENT_WEDGE_SIMPLEX_FLINT_ROOT"
MAX_N_DEN = 4
MAX_A2_DEN = 4


A2_TERMS = (
    (4, 1, 4), (-3, 1, 5), (-17, 1, 6), (-7, 1, 7),
    (12, 2, 3), (8, 2, 4), (-21, 2, 5), (-16, 2, 6),
    (11, 3, 3), (22, 3, 4), (-1, 3, 5), (8, 4, 4),
)
L2_TERMS = (
    (4, 1, 3), (-1, 1, 4), (-16, 1, 5), (-7, 1, 6),
    (8, 2, 2), (9, 2, 3), (-4, 2, 4), (-9, 2, 5),
    (4, 3, 1), (9, 3, 2), (24, 3, 3), (8, 3, 4),
    (-1, 4, 1), (-4, 4, 2), (8, 4, 3),
    (-16, 5, 1), (-9, 5, 2), (-7, 6, 1),
)
K2_TERMS = (
    (4, 1, 2), (1, 1, 3), (-15, 1, 4), (-7, 1, 5),
    (4, 2, 1), (6, 2, 2), (11, 2, 3), (-2, 2, 4),
    (1, 3, 1), (11, 3, 2), (10, 3, 3),
    (-15, 4, 1), (-2, 4, 2), (-7, 5, 1),
)


def weak_compositions(total: int, parts: int, prefix=()):
    if parts == 1:
        yield (*prefix, total)
        return
    for value in range(total + 1):
        yield from weak_compositions(total - value, parts - 1, (*prefix, value))


def multinomial(exponents) -> int:
    out = math.factorial(sum(exponents))
    for exponent in exponents:
        out //= math.factorial(exponent)
    return out


def row_corner(order, mask: int, one, reduced: bool = False):
    row = [(one, 0, 0), (order, 0, 0)]
    for rank in range(2, 7):
        if reduced:
            # Exact derivative reduction: rank 2 is the sole free endpoint;
            # ranks 3,4 minimize at PATH and ranks 5,6 at EDGELESS.
            upper = (rank == 2 and bool(mask & 1)) or rank in (5, 6)
        else:
            upper = bool(mask & (1 << (rank - 2)))
        value = choose(order, rank, one) if upper else path_floor(order, rank, one)
        row.append((value, 0, 0))
    return tuple(row)


def scaled_bilinear(left, right, terms, n, a2):
    pieces = []
    for coefficient, i, j in terms:
        lnum, lnd, lad = left[i]
        rnum, rnd, rad = right[j]
        n_power = MAX_N_DEN - lnd - rnd
        a2_power = MAX_A2_DEN - lad - rad
        assert n_power >= 0 and a2_power >= 0
        pieces.append(coefficient * lnum * rnum * n**n_power * a2**a2_power)
    return balanced_batched_sum(pieces, batch_size=64)


def scaled_source(n, mb, mc, overlap, z, w, simplex, bmask, cmask, one,
                  reduced=False):
    u0, u1, u2, u3, u4 = simplex
    edges = overlap * z
    omega = edges**2 * w * fmpq(1, 2)
    a2 = choose(n, 2, one) - edges
    a3 = choose(n, 3, one) - edges*(n-2) + omega
    budget_num = 6*n*a3 - 4*n*a2
    r3_num = 3*n*a2 + budget_num*(u0+u1+u2+u3)
    r4_num = 2*n*a2 + budget_num*(u0+u1+u2)
    r5_num = n*a2 + budget_num*(u0+u1)
    r6_num = budget_num*u0
    a = (
        (one, 0, 0),
        (n, 0, 0),
        (a2, 0, 0),
        (a3, 0, 0),
        (a3*r3_num*fmpq(1, 8), 1, 1),
        (a3*r3_num*r4_num*fmpq(1, 80), 2, 2),
        (a3*r3_num*r4_num*r5_num*fmpq(1, 960), 3, 3),
        (a3*r3_num*r4_num*r5_num*r6_num*fmpq(1, 13440), 4, 4),
    )
    b = row_corner(mb, bmask, one, reduced)
    c = row_corner(mc, cmask, one, reduced)
    source = balanced_batched_sum((
        scaled_bilinear(a, a, A2_TERMS, n, a2),
        scaled_bilinear(a, b, L2_TERMS, n, a2),
        scaled_bilinear(a, c, L2_TERMS, n, a2),
        scaled_bilinear(b, c, K2_TERMS, n, a2),
    ), batch_size=4)
    return source


def source_polynomial(context, bmask: int, cmask: int, reduced: bool = False):
    s, z, w, u0, u1, u2, u3, u4, p, q = context.gens()
    one = context.constant(1)
    mb = 7 + p
    mc = 7 + p + q
    overlap = mb * s
    n = mb + mc - overlap
    source = scaled_source(
        n, mb, mc, overlap, z, w, (u0, u1, u2, u3, u4),
        bmask, cmask, one, reduced
    )
    metadata = {
        "B_mask": bmask,
        "C_mask": cmask,
        "positive_multiplier": "N^4*a2^4",
        "geometry": "mB=7+p, mC=7+p+q, r=mB*s, e=r*z, Omega=e^2*w/2",
        "simplex": "u0+u1+u2+u3+u4=1",
        "reduced_four_corner_mode": reduced,
    }
    return source, metadata


def source_polynomial_chart(context, chart: str, bmask: int, cmask: int,
                            reduced: bool = False):
    x, y, z, w, u0, u1, u2, u3, u4, h = context.gens()
    one = context.constant(1)
    n = 14 + h
    if chart == "low":
        # 7<=mB<=N/2 and N-mB<=mC<=N.
        mb = 7 + h*x*fmpq(1, 2)
        mc = n-mb + mb*y
        overlap = mb*y
        geometry = "N=14+h; mB=7+h*x/2; mC=N-mB+mB*y"
    else:
        assert chart == "high"
        # N/2<=mB<=N and mB<=mC<=N.
        mb = n*(one+x)*fmpq(1, 2)
        mc = mb + (n-mb)*y
        overlap = mb+mc-n
        geometry = "N=14+h; mB=N*(1+x)/2; mC=mB+(N-mB)*y"
    source = scaled_source(
        n, mb, mc, overlap, z, w, (u0, u1, u2, u3, u4),
        bmask, cmask, one, reduced
    )
    return source, {
        "B_mask": bmask,
        "C_mask": cmask,
        "positive_multiplier": "N^4*a2^4",
        "geometry": geometry + "; e=overlap*z; Omega=e^2*w/2",
        "order_chart": chart,
        "simplex": "u0+u1+u2+u3+u4=1",
        "reduced_four_corner_mode": reduced,
    }


def split_simplex(source, coefficient_context, prefix_count=3, tail_count=2):
    grouped_terms = defaultdict(list)
    for monomial, coefficient in source.terms():
        alpha = tuple(map(int, monomial[prefix_count:prefix_count+5]))
        remaining = (*monomial[0:prefix_count], *monomial[-tail_count:])
        term = coefficient_context.constant(coefficient)
        for variable, exponent in zip(coefficient_context.gens(), remaining):
            term *= variable**int(exponent)
        grouped_terms[alpha].append(term)
    grouped = {alpha: balanced_batched_sum(terms, batch_size=128)
               for alpha, terms in grouped_terms.items()}
    degree = max(map(sum, grouped))
    betas = list(weak_compositions(degree, 5))
    coefficients = []
    for beta in betas:
        terms = []
        for alpha, polynomial in grouped.items():
            if any(alpha[index] > beta[index] for index in range(5)):
                continue
            gaps = tuple(beta[index]-alpha[index] for index in range(5))
            if sum(gaps) != degree-sum(alpha):
                continue
            terms.append(polynomial*multinomial(gaps))
        coefficients.append(balanced_batched_sum(terms, batch_size=128))
    return degree, betas, coefficients, len(grouped)


def compactify_one(source, target_context, bounded_count=4):
    """Map the final unbounded h axis to H=h/(1+h)."""
    terms = list(source.terms())
    degree_h = int(max(monomial[-1] for monomial, _ in terms))
    target_gens = target_context.gens()
    one = target_context.constant(1)
    H = target_gens[-1]
    degrees = [int(max(monomial[axis] for monomial, _ in terms))
               for axis in range(bounded_count)]
    powers = [[target_gens[axis]**exponent for exponent in range(degree+1)]
              for axis, degree in enumerate(degrees)]
    h_powers = [H**exponent for exponent in range(degree_h+1)]
    complements = [(one-H)**exponent for exponent in range(degree_h+1)]

    def mapped_terms():
        for monomial, coefficient in terms:
            term = target_context.constant(coefficient)
            for axis in range(bounded_count):
                term *= powers[axis][monomial[axis]]
            eh = monomial[-1]
            term *= h_powers[eh]*complements[degree_h-eh]
            yield term

    mapped = balanced_batched_sum(mapped_terms(), batch_size=128)
    return mapped, degree_h, len(terms)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--b-mask", type=int, choices=range(32), default=0)
    parser.add_argument("--c-mask", type=int, choices=range(32), default=0)
    parser.add_argument("--reduced-four-corner", action="store_true")
    parser.add_argument("--order-chart", choices=("original", "low", "high"),
                        default="original")
    parser.add_argument("--inspect-only", action="store_true")
    parser.add_argument("--start-beta", type=int, default=0)
    parser.add_argument("--max-betas", type=int, default=1_000_000)
    parser.add_argument("--chunk-columns", type=int, default=4096)
    args = parser.parse_args()
    assert sha256(OCCUPATION) == OCCUPATION_SHA256

    if args.order_chart == "original":
        names = ("s", "z", "w", "u0", "u1", "u2", "u3", "u4", "p", "q")
        coefficient_names = ("s", "z", "w", "p", "q")
        prefix_count, tail_count = 3, 2
    else:
        names = ("x", "y", "z", "w", "u0", "u1", "u2", "u3", "u4", "h")
        coefficient_names = ("x", "y", "z", "w", "h")
        prefix_count, tail_count = 4, 1
    source_context = fmpq_mpoly_ctx.get(names, "degrevlex")
    if args.reduced_four_corner:
        assert args.b_mask in (0, 1) and args.c_mask in (0, 1)
    if args.order_chart == "original":
        source, metadata = source_polynomial(
            source_context, args.b_mask, args.c_mask, args.reduced_four_corner
        )
    else:
        source, metadata = source_polynomial_chart(
            source_context, args.order_chart, args.b_mask, args.c_mask,
            args.reduced_four_corner
        )
    source_terms = list(source.terms())
    source_degrees = [int(max(monomial[axis] for monomial, _ in source_terms))
                      for axis in range(len(names))]
    coefficient_context = fmpq_mpoly_ctx.get(coefficient_names, "degrevlex")
    simplex_degree, betas, coefficients, grouped = split_simplex(
        source, coefficient_context, prefix_count, tail_count
    )
    summary = {
        **metadata,
        "source_terms": len(source_terms),
        "source_degrees": dict(zip(names, source_degrees)),
        "simplex_degree": simplex_degree,
        "raw_simplex_monomials": grouped,
        "homogeneous_simplex_coefficients": len(betas),
    }
    print(json.dumps(summary, indent=2, sort_keys=True), flush=True)
    if args.inspect_only:
        print(MARKER + "_INSPECT_ONLY")
        return

    stop = min(len(betas), args.start_beta + args.max_betas)
    target_names = (("s", "z", "w", "P", "Q")
                    if args.order_chart == "original"
                    else ("x", "y", "z", "w", "H"))
    target_context = fmpq_mpoly_ctx.get(target_names, "degrevlex")
    records = []
    digest = hashlib.sha256()
    for beta_index in range(args.start_beta, stop):
        coefficient = coefficients[beta_index]
        if args.order_chart == "original":
            mapped, degree_p, degree_q, coefficient_terms = compactify(
                coefficient, target_context, 3
            )
            tail_degrees = [degree_p, degree_q]
        else:
            mapped, degree_h, coefficient_terms = compactify_one(
                coefficient, target_context, 4
            )
            tail_degrees = [degree_h]
        mapped_terms = list(mapped.terms())
        degrees, values, replay_terms = tensor_bernstein_from_flint_matrix(
            mapped, 5, chunk_columns=args.chunk_columns
        )
        assert replay_terms == len(mapped_terms)
        minimum = min(values.flat)
        minimum_flat_index = min(range(values.size), key=lambda index: values.flat[index])
        minimum_multiindex = list(map(int, __import__("numpy").unravel_index(
            minimum_flat_index, values.shape
        )))
        negative = sum(1 for value in values.flat if value < 0)
        zero = sum(1 for value in values.flat if value == 0)
        stream = hashlib.sha256()
        for value in values.flat:
            stream.update(f"{value};".encode())
        record = {
            "beta_index": beta_index,
            "beta": betas[beta_index],
            "coefficient_terms": coefficient_terms,
            "compactification_degrees_tail": tail_degrees,
            "mapped_terms": len(mapped_terms),
            "bernstein_degrees": list(map(int, degrees)),
            "bernstein_coefficients": int(values.size),
            "negative": negative,
            "zero": zero,
            "minimum": str(minimum),
            "minimum_multiindex": minimum_multiindex,
            "coefficient_stream_sha256": stream.hexdigest().upper(),
        }
        records.append(record)
        digest.update(json.dumps(record, separators=(",", ":"), sort_keys=True).encode())
        print(json.dumps(record, sort_keys=True), flush=True)

    report = {
        "marker": MARKER,
        **summary,
        "start_beta": args.start_beta,
        "stop_beta": stop,
        "processed_betas": len(records),
        "negative_betas": sum(row["negative"] > 0 for row in records),
        "ordered_record_sha256": digest.hexdigest().upper(),
        "records": records,
        "scope": "large ordered adjacent no-parent rank-six g2 wedge/simplex corner probe only",
        "occupation_report_sha256": OCCUPATION_SHA256,
        "source_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest().upper(),
    }
    reduced_tag = "reduced4_" if args.reduced_four_corner else ""
    chart_tag = "" if args.order_chart == "original" else f"{args.order_chart}_"
    output = HERE / (
        f"iso_n6_bundle_g2_adjacent_wedge_simplex_{chart_tag}{reduced_tag}B{args.b_mask:02d}_C{args.c_mask:02d}_"
        f"beta{args.start_beta}_{stop}_flint_probe_root_20260831.json"
    )
    raw = json.dumps(report, indent=2, sort_keys=True) + "\n"
    output.write_text(raw, encoding="utf-8", newline="\n")
    print(json.dumps({key: report[key] for key in (
        "marker", "B_mask", "C_mask", "processed_betas", "negative_betas"
    )}, indent=2, sort_keys=True))
    print("REPORT_SHA256", hashlib.sha256(raw.encode()).hexdigest().upper())
    print(MARKER)


if __name__ == "__main__":
    main()
