#!/usr/bin/env python3
"""Test marked N_4 on arbitrary simplicial complexes.

All complexes on up to five labelled vertices are generated by the exact
restriction/link recursion.  A deterministic random-facet stress then probes
larger complexes.  This tests whether the promising N_4 base may be a
downset/shadow theorem rather than a forest-specific theorem.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import random
from pathlib import Path


def all_complexes(max_vertices: int) -> list[list[frozenset[int]]]:
    levels: list[list[frozenset[int]]] = [[frozenset({0})]]
    for vertex in range(max_vertices):
        previous = levels[-1]
        current: list[frozenset[int]] = []
        bit = 1 << vertex
        for restriction in previous:
            for link in previous:
                if link <= restriction:
                    current.append(
                        frozenset(set(restriction) | {face | bit for face in link})
                    )
        levels.append(current)
    return levels


def rows(faces: frozenset[int], n: int, forbidden: int = 0) -> tuple[int, ...]:
    out = [0] * (n + 1)
    for face in faces:
        if face & forbidden == 0:
            out[face.bit_count()] += 1
    return tuple(out)


def n4(e: tuple[int, ...], a: tuple[int, ...], b: tuple[int, ...], c: tuple[int, ...]) -> int:
    def at(row: tuple[int, ...], k: int) -> int:
        return row[k] if 0 <= k < len(row) else 0

    r = 4
    return (
        2 * r * at(e, r) * at(c, r - 2)
        - (r + 1) * at(e, r + 1) * at(c, r - 3)
        + at(e, r - 1) * (2 * at(c, r - 3) - (r + 1) * at(c, r - 1))
        + at(a, r) * (-(r + 1) * at(b, r - 2) - at(c, r - 3))
        + at(a, r - 1) * (2 * r * at(b, r - 1) + 2 * at(c, r - 2))
        + at(a, r - 2) * (-(r + 1) * at(b, r) + 2 * at(b, r - 2) - at(c, r - 1))
        - at(b, r) * at(c, r - 3)
        + 2 * at(b, r - 1) * at(c, r - 2)
        - at(b, r - 2) * at(c, r - 1)
    )


def random_complex(rng: random.Random, n: int) -> frozenset[int]:
    facet_count = rng.randint(1, 4 * n)
    facets = []
    for _ in range(facet_count):
        probability = rng.uniform(0.05, 0.95)
        facet = sum((1 << vertex) for vertex in range(n) if rng.random() < probability)
        facets.append(facet)
    # Require every declared vertex to occur, matching graph independence complexes.
    for vertex in range(n):
        facets.append(1 << vertex)
    faces = {0}
    for facet in facets:
        subface = facet
        while True:
            faces.add(subface)
            if subface == 0:
                break
            subface = (subface - 1) & facet
    return frozenset(faces)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--random", type=int, default=20000)
    parser.add_argument("--random-n", type=int, default=14)
    args = parser.parse_args()
    levels = all_complexes(5)
    checks = 0
    minimum: dict | None = None
    first_negatives: list[dict] = []

    def audit(faces: frozenset[int], n: int, source: str) -> None:
        nonlocal checks, minimum
        e = rows(faces, n)
        for u, v in itertools.combinations(range(n), 2):
            a = rows(faces, n, 1 << u)
            b = rows(faces, n, 1 << v)
            c = rows(faces, n, (1 << u) | (1 << v))
            value = n4(e, a, b, c)
            checks += 1
            witness = {
                "N4": value,
                "n": n,
                "marks": [u, v],
                "source": source,
                "f_vector": list(e),
                "facets": sorted(
                    face for face in faces
                    if not any(face != other and face & ~other == 0 for other in faces)
                ),
            }
            if minimum is None or value < minimum["N4"]:
                minimum = witness
            if value < 0 and len(first_negatives) < 20:
                first_negatives.append(witness)

    exact_complexes = 0
    for n, level in enumerate(levels):
        if n < 2:
            continue
        for faces in level:
            # Exclude ghost vertices so all marks are genuine vertices.
            if all((1 << vertex) in faces for vertex in range(n)):
                exact_complexes += 1
                audit(faces, n, "exact")

    rng = random.Random(993_082_902)
    for _ in range(args.random):
        n = rng.randint(6, args.random_n)
        audit(random_complex(rng, n), n, "random")

    report = {
        "marker": (
            "PASS_EXACT_FINITE_NO_N4_NEGATIVE_FOR_SIMPLICIAL_COMPLEXES"
            if not first_negatives
            else "FOUND_EXACT_N4_NEGATIVE_SIMPLICIAL_COMPLEX"
        ),
        "exact_level_counts_including_ghosts": [len(level) for level in levels],
        "exact_complexes_without_ghosts": exact_complexes,
        "random_complexes": args.random,
        "checks": checks,
        "minimum": minimum,
        "first_negatives": first_negatives,
        "scope": "Finite downset evidence only; no universal theorem is asserted.",
        "source_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest().upper(),
    }
    raw = json.dumps(report, indent=2, sort_keys=True) + "\n"
    Path("iso_n4_simplicial_complex_probe_root_20260829.json").write_text(raw, encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    print("REPORT_SHA256", hashlib.sha256(raw.encode()).hexdigest().upper())
    print(report["marker"])


if __name__ == "__main__":
    main()
