// Six-thread checked-i256 producer for quartic_center_two_cubic:center_cubic_spine_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::{Arc,atomic::{AtomicUsize,Ordering}};use std::thread;
const QCS_THREADS:usize=6;const QCS_TASKS:usize=56;
#[derive(Clone,Copy)]struct QCSState{length:i32,is_long:bool}
#[derive(Clone,Copy)]struct QCSMessage{free:V,blocked:V}
#[derive(Clone,Copy)]struct QCSQSide{gap:QCSState,q0:QCSState,q1:QCSState,spine:QCSState,e0:QCSState,e1:QCSState,at_root:QCSMessage}
#[derive(Clone,Copy)]struct QCSCSide{gap:QCSState,c0:QCSState,c1:QCSState,at_root:QCSMessage}
fn qcs_gap(x:i32)->QCSState{QCSState{length:x,is_long:x==7}}fn qcs_pendant(x:i32)->QCSState{QCSState{length:x,is_long:x==7}}fn qcs_spine(x:i32)->QCSState{QCSState{length:x,is_long:x==8}}
fn qcs_cross(absent:V,present:V,length:i32)->QCSMessage{QCSMessage{free:add(&mul(&path(length-1),&absent),&mul(&path(length-2),&present)),blocked:add(&mul(&path(length-2),&absent),&mul(&path(length-3),&present))}}
fn qcs_module(spine:i32,a0:i32,a1:i32)->QCSMessage{qcs_cross(mul(&path(a0),&path(a1)),shifted(&mul(&path(a0-1),&path(a1-1)),1),spine)}
fn qcs_qcore(gap:i32,q0:i32,q1:i32,spine:i32,e0:i32,e1:i32)->QCSMessage{let e=qcs_module(spine,e0,e1);let absent=product(&[path(q0),path(q1),e.free]);let present=shifted(&product(&[path(q0-1),path(q1-1),e.blocked]),1);qcs_cross(absent,present,gap+1)}
fn qcs_ccore(gap:i32,c0:i32,c1:i32)->QCSMessage{qcs_cross(mul(&path(c0),&path(c1)),shifted(&mul(&path(c0-1),&path(c1-1)),1),gap+1)}
fn qcs_qsides()->Vec<QCSQSide>{let mut out=Vec::with_capacity(50_176);for gap in 0..=7{for q0 in 1..=7{for q1 in q0..=7{for spine in 1..=8{for e0 in 1..=7{for e1 in e0..=7{out.push(QCSQSide{gap:qcs_gap(gap),q0:qcs_pendant(q0),q1:qcs_pendant(q1),spine:qcs_spine(spine),e0:qcs_pendant(e0),e1:qcs_pendant(e1),at_root:qcs_qcore(gap,q0,q1,spine,e0,e1)});}}}}}}assert_eq!(out.len(),50_176);out}
fn qcs_csides()->Vec<QCSCSide>{let mut out=Vec::with_capacity(224);for gap in 0..=7{for c0 in 1..=7{for c1 in c0..=7{out.push(QCSCSide{gap:qcs_gap(gap),c0:qcs_pendant(c0),c1:qcs_pendant(c1),at_root:qcs_ccore(gap,c0,c1)});}}}assert_eq!(out.len(),224);out}
fn qcs_states(q:QCSQSide,c:QCSCSide)->[QCSState;9]{[q.gap,c.gap,q.q0,q.q1,q.spine,q.e0,q.e1,c.c0,c.c1]}fn qcs_lengths(s:&[QCSState;9])->[i32;9]{std::array::from_fn(|i|s[i].length)}
fn qcs_formula_polynomials(l:&[i32;9])->(V,V){let q=qcs_qcore(l[0],l[2],l[3],l[4],l[5],l[6]);let c=qcs_ccore(l[1],l[7],l[8]);let deleted=mul(&q.free,&c.free);let selected=shifted(&mul(&q.blocked,&c.blocked),1);(add(&deleted,&selected),deleted)}
fn qcs_values(l:&[i32;9],q:QCSQSide,c:QCSCSide,varying:Option<usize>)->[Z;4]{let a=if varying.is_some_and(|i|i==0||(2..=6).contains(&i)){qcs_qcore(l[0],l[2],l[3],l[4],l[5],l[6])}else{q.at_root};let b=if varying.is_some_and(|i|i==1||i>=7){qcs_ccore(l[1],l[7],l[8])}else{c.at_root};let deleted=mul(&a.free,&b.free);let selected=shifted(&mul(&a.blocked,&b.blocked),1);deltas03(&add(&deleted,&selected),&deleted)}
fn qcs_literal_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let q=audit_attach(&mut a,root,l[0]+1);let c=audit_attach(&mut a,root,l[1]+1);audit_attach(&mut a,q,l[2]);audit_attach(&mut a,q,l[3]);let e=audit_attach(&mut a,q,l[4]);audit_attach(&mut a,e,l[5]);audit_attach(&mut a,e,l[6]);audit_attach(&mut a,c,l[7]);audit_attach(&mut a,c,l[8]);assert_eq!(a.len(),3+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}
fn qcs_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qcs_literal_tree(l);audit_deltas(&a,r).0}
fn qcs_formula_smoke(){let mut random=0xAD29B17C4E63085F_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}let(c,d)=qcs_formula_polynomials(&l);assert_eq!(deltas03(&c,&d),qcs_literal_values(&l),"center-cubic spine internal primary mismatch {}",sample);}println!("PASS_E5_CENTER_CUBIC_SPINE_INTERNAL_PRIMARY_512_LITERAL_FORMULA_SMOKE");}
fn qcs_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qcs_hash_state(h:&mut AuditSha256,s:QCSState){h.update(&[s.is_long as u8]);h.update(&s.length.to_le_bytes());}fn qcs_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qcs_coefficient_leaf(s:&[QCSState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-center-cubic-spine-internal-coefficient-v1\0");for &x in s{qcs_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qcs_hash_z(&mut h,z);}}qcs_sha_bytes(h)}
fn qcs_finite_leaf(s:&[QCSState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-center-cubic-spine-internal-finite-v1\0");for &x in s{qcs_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qcs_hash_z(&mut h,z);}qcs_sha_bytes(h)}
fn qcs_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for p in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][p].is_zero(){return false;}}}true}fn qcs_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[r]{if rows[r][p].is_negative(){return false;}}}qcs_degree_ok(rows)}
fn qcs_coefficients(s:&[QCSState;9],q:QCSQSide,c:QCSCSide,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.is_long).unwrap();let mut l=qcs_lengths(s);let baseline=3+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qcs_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qcs_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qcs_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qcs_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qcs_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qcs_smoke_stream(){let qs=qcs_qsides();let cs=qcs_csides();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let c=cs[(sample*17+23)%cs.len()];let s=qcs_states(q,c);if !s.iter().any(|x|x.is_long){let l=qcs_lengths(&s);let order=3+l.iter().sum::<i32>();if order>=28{let v=qcs_values(&l,q,c,None);fh.update(&qcs_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows,_)=qcs_coefficients(&s,q,c,false);if !qcs_gate_ok(&rows){gf+=1;}ch.update(&qcs_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
struct QCSResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qcs_worker(task:usize,qs:Arc<Vec<QCSQSide>>,cs:Arc<Vec<QCSCSide>>)->QCSResult{let start=qs.len()*task/QCS_TASKS;let end=qs.len()*(task+1)/QCS_TASKS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();let(mut checked_finite,mut checked_ray)=(false,false);for qi in start..end{let q=qs[qi];for &c in cs.iter(){let s=qcs_states(q,c);let lc=s.iter().filter(|x|x.is_long).count();if lc==0{counts[0]+=1;let l=qcs_lengths(&s);let order=3+l.iter().sum::<i32>();if order<28{continue;}let v=qcs_values(&l,q,c,None);assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qcs_finite_leaf(&s,order,&v));if !checked_finite{assert_eq!(v,qcs_literal_values(&l));checked_finite=true;literal+=1;}counts[1]+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,n)=qcs_coefficients(&s,q,c,!checked_ray);audit_assert_gate(&rows);if !checked_ray{checked_ray=true;literal+=n;}coeff.extend_from_slice(&qcs_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;}}QCSResult{worker:task,counts,unseen,literal,coeff,finite}}
fn qcs_full(){let qs=Arc::new(qcs_qsides());let cs=Arc::new(qcs_csides());let next=Arc::new(AtomicUsize::new(0));let mut handles=Vec::new();for _ in 0..QCS_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&cs);let n=Arc::clone(&next);handles.push(thread::spawn(move||{let mut out=Vec::new();loop{let task=n.fetch_add(1,Ordering::SeqCst);if task>=QCS_TASKS{break;}out.push(qcs_worker(task,Arc::clone(&a),Arc::clone(&b)));}out}));}let mut results:Vec<_>=handles.into_iter().flat_map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);assert_eq!(results.len(),QCS_TASKS);for(i,r)in results.iter().enumerate(){assert_eq!(r.worker,i);}let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[3_176_523,2_771_357,8_062_900,1,8_062_901]);assert_eq!(unseen,32_251_604);let raw=format!("PASS_I256_E5_QUARTIC_CENTER_TWO_CUBIC_CENTER_CUBIC_SPINE_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_center_two_cubic_center_cubic_spine_internal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qcs_formula_smoke();qcs_smoke_stream();},Some(x)=>panic!("unknown mode {}",x),None=>qcs_full()}}
