// Six-thread checked-i256 producer for quartic_center_two_cubic:cubic_pendant_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::{Arc,atomic::{AtomicUsize,Ordering}};use std::thread;
const QCP_THREADS:usize=6;const QCP_TASKS:usize=56;
#[derive(Clone,Copy)]struct QCPState{length:i32,is_long:bool}
#[derive(Clone,Copy)]struct QCPMessage{free:V,blocked:V}
#[derive(Clone,Copy)]struct QCPFarSide{c0q:QCPState,q0:QCPState,q1:QCPState,qc1:QCPState,e0:QCPState,e1:QCPState,at_c0:QCPMessage}
#[derive(Clone,Copy)]struct QCPPrefix{gap:QCPState,tail:QCPState,sibling:QCPState,tail_message:QCPMessage}
fn qcp_gap(x:i32)->QCPState{QCPState{length:x,is_long:x==7}}fn qcp_pendant(x:i32)->QCPState{QCPState{length:x,is_long:x==7}}fn qcp_spine(x:i32)->QCPState{QCPState{length:x,is_long:x==8}}
fn qcp_cross(absent:V,present:V,length:i32)->QCPMessage{QCPMessage{free:add(&mul(&path(length-1),&absent),&mul(&path(length-2),&present)),blocked:add(&mul(&path(length-2),&absent),&mul(&path(length-3),&present))}}
fn qcp_module(spine:i32,a0:i32,a1:i32)->QCPMessage{qcp_cross(mul(&path(a0),&path(a1)),shifted(&mul(&path(a0-1),&path(a1-1)),1),spine)}
fn qcp_far_at_c0(c0q:i32,q0:i32,q1:i32,qc1:i32,e0:i32,e1:i32)->QCPMessage{let other=qcp_module(qc1,e0,e1);let absent=product(&[path(q0),path(q1),other.free]);let present=shifted(&product(&[path(q0-1),path(q1-1),other.blocked]),1);qcp_cross(absent,present,c0q)}
fn qcp_root_side(gap:i32,sibling:i32,far:QCPMessage)->QCPMessage{let absent=mul(&path(sibling),&far.free);let present=shifted(&mul(&path(sibling-1),&far.blocked),1);qcp_cross(absent,present,gap+1)}
fn qcp_tail(tail:i32)->QCPMessage{QCPMessage{free:path(tail),blocked:path(tail-1)}}
fn qcp_far_sides()->Vec<QCPFarSide>{let mut out=Vec::with_capacity(50_176);for c0q in 1..=8{for q0 in 1..=7{for q1 in q0..=7{for qc1 in 1..=8{for e0 in 1..=7{for e1 in e0..=7{out.push(QCPFarSide{c0q:qcp_spine(c0q),q0:qcp_pendant(q0),q1:qcp_pendant(q1),qc1:qcp_spine(qc1),e0:qcp_pendant(e0),e1:qcp_pendant(e1),at_c0:qcp_far_at_c0(c0q,q0,q1,qc1,e0,e1)});}}}}}}assert_eq!(out.len(),50_176);out}
fn qcp_prefixes()->Vec<QCPPrefix>{let mut out=Vec::with_capacity(392);for gap in 0..=7{for tail in 1..=7{for sibling in 1..=7{out.push(QCPPrefix{gap:qcp_gap(gap),tail:qcp_pendant(tail),sibling:qcp_pendant(sibling),tail_message:qcp_tail(tail)});}}}assert_eq!(out.len(),392);out}
fn qcp_states(q:QCPFarSide,c:QCPPrefix)->[QCPState;9]{[c.gap,c.tail,c.sibling,q.c0q,q.q0,q.q1,q.qc1,q.e0,q.e1]}fn qcp_lengths(s:&[QCPState;9])->[i32;9]{std::array::from_fn(|i|s[i].length)}
fn qcp_formula_polynomials(l:&[i32;9])->(V,V){let far=qcp_far_at_c0(l[3],l[4],l[5],l[6],l[7],l[8]);let core=qcp_root_side(l[0],l[2],far);let tail=qcp_tail(l[1]);let deleted=mul(&core.free,&tail.free);let selected=shifted(&mul(&core.blocked,&tail.blocked),1);(add(&deleted,&selected),deleted)}
fn qcp_values(l:&[i32;9],q:QCPFarSide,c:QCPPrefix,varying:Option<usize>)->[Z;4]{let far=if varying.is_some_and(|i|i>=3){qcp_far_at_c0(l[3],l[4],l[5],l[6],l[7],l[8])}else{q.at_c0};let core=qcp_root_side(l[0],l[2],far);let tail=if varying==Some(1){qcp_tail(l[1])}else{c.tail_message};let deleted=mul(&core.free,&tail.free);let selected=shifted(&mul(&core.blocked,&tail.blocked),1);deltas03(&add(&deleted,&selected),&deleted)}
fn qcp_literal_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let c0=audit_attach(&mut a,root,l[0]+1);audit_attach(&mut a,root,l[1]);audit_attach(&mut a,c0,l[2]);let q=audit_attach(&mut a,c0,l[3]);audit_attach(&mut a,q,l[4]);audit_attach(&mut a,q,l[5]);let c1=audit_attach(&mut a,q,l[6]);audit_attach(&mut a,c1,l[7]);audit_attach(&mut a,c1,l[8]);assert_eq!(a.len(),2+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}
fn qcp_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qcp_literal_tree(l);audit_deltas(&a,r).0}
fn qcp_formula_smoke(){let mut random=0xAD29B17C4E63085F_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}l[0]-=1;let(c,d)=qcp_formula_polynomials(&l);assert_eq!(deltas03(&c,&d),qcp_literal_values(&l),"cubic pendant internal primary mismatch {}",sample);}println!("PASS_E5_CUBIC_PENDANT_INTERNAL_PRIMARY_512_LITERAL_FORMULA_SMOKE");}
fn qcp_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qcp_hash_state(h:&mut AuditSha256,s:QCPState){h.update(&[s.is_long as u8]);h.update(&s.length.to_le_bytes());}fn qcp_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qcp_coefficient_leaf(s:&[QCPState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-pendant-internal-coefficient-v1\0");for &x in s{qcp_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qcp_hash_z(&mut h,z);}}qcp_sha_bytes(h)}
fn qcp_finite_leaf(s:&[QCPState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-pendant-internal-finite-v1\0");for &x in s{qcp_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qcp_hash_z(&mut h,z);}qcp_sha_bytes(h)}
fn qcp_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for p in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][p].is_zero(){return false;}}}true}fn qcp_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[r]{if rows[r][p].is_negative(){return false;}}}qcp_degree_ok(rows)}
fn qcp_coefficients(s:&[QCPState;9],q:QCPFarSide,c:QCPPrefix,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.is_long).unwrap();let mut l=qcp_lengths(s);let baseline=2+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qcp_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qcp_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qcp_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qcp_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qcp_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qcp_smoke_stream(){let qs=qcp_far_sides();let cs=qcp_prefixes();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let c=cs[(sample*17+23)%cs.len()];let s=qcp_states(q,c);if !s.iter().any(|x|x.is_long){let l=qcp_lengths(&s);let order=2+l.iter().sum::<i32>();if order>=28{let v=qcp_values(&l,q,c,None);fh.update(&qcp_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows,_)=qcp_coefficients(&s,q,c,false);if !qcp_gate_ok(&rows){gf+=1;}ch.update(&qcp_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
struct QCPResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qcp_worker(task:usize,qs:Arc<Vec<QCPFarSide>>,cs:Arc<Vec<QCPPrefix>>)->QCPResult{let start=qs.len()*task/QCP_TASKS;let end=qs.len()*(task+1)/QCP_TASKS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();let(mut checked_finite,mut checked_ray)=(false,false);for qi in start..end{let q=qs[qi];for &c in cs.iter(){let s=qcp_states(q,c);let lc=s.iter().filter(|x|x.is_long).count();if lc==0{counts[0]+=1;let l=qcp_lengths(&s);let order=2+l.iter().sum::<i32>();if order<28{continue;}let v=qcp_values(&l,q,c,None);assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qcp_finite_leaf(&s,order,&v));if !checked_finite{assert_eq!(v,qcp_literal_values(&l));checked_finite=true;literal+=1;}counts[1]+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,n)=qcp_coefficients(&s,q,c,!checked_ray);audit_assert_gate(&rows);if !checked_ray{checked_ray=true;literal+=n;}coeff.extend_from_slice(&qcp_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;}}QCPResult{worker:task,counts,unseen,literal,coeff,finite}}
fn qcp_full(){let qs=Arc::new(qcp_far_sides());let cs=Arc::new(qcp_prefixes());let next=Arc::new(AtomicUsize::new(0));let mut handles=Vec::new();for _ in 0..QCP_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&cs);let n=Arc::clone(&next);handles.push(thread::spawn(move||{let mut out=Vec::new();loop{let task=n.fetch_add(1,Ordering::SeqCst);if task>=QCP_TASKS{break;}out.push(qcp_worker(task,Arc::clone(&a),Arc::clone(&b)));}out}));}let mut results:Vec<_>=handles.into_iter().flat_map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);assert_eq!(results.len(),QCP_TASKS);for(i,r)in results.iter().enumerate(){assert_eq!(r.worker,i);}let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[5_445_468,4_768_380,14_223_523,1,14_223_524]);assert_eq!(unseen,56_894_096);assert_eq!(literal,217);let raw=format!("PASS_I256_E5_QUARTIC_CENTER_TWO_CUBIC_CUBIC_PENDANT_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_center_two_cubic_cubic_pendant_internal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qcp_formula_smoke();qcp_smoke_stream();},Some(x)=>panic!("unknown mode {}",x),None=>qcp_full()}}
