// Memory-bounded checked-i256 producer for four_cubic_path:outer_spine_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc; use std::thread;
const OSI_THREADS: usize = 6; const OSI_BATCH_PREFIXES: usize = 12;

#[derive(Clone, Copy)] struct OSIState { value: i32, long: bool }
#[derive(Clone, Copy)] struct OSIPair { first: OSIState, second: OSIState }
#[derive(Clone, Copy)] struct OSIMessage { free: V, blocked: V }
#[derive(Clone, Copy)] struct OSIPrefix { left_gap: OSIState, left_pair: OSIPair, right_gap: OSIState, left_message: OSIMessage }
#[derive(Clone, Copy)] struct OSIRight { left_inner: OSIState, middle: OSIState, right_inner: OSIState, final_spine: OSIState, far_pair: OSIPair, b1_absent: V, b1_present: V }

fn osi_gap(value:i32)->OSIState{OSIState{value,long:value==7}}
fn osi_pendant(value:i32)->OSIState{OSIState{value,long:value==7}}
fn osi_spine(value:i32)->OSIState{OSIState{value,long:value==8}}
fn osi_pairs()->Vec<OSIPair>{let mut out=Vec::with_capacity(28);for a in 1..=7_i32{for b in a..=7_i32{out.push(OSIPair{first:osi_pendant(a),second:osi_pendant(b)});}}assert_eq!(out.len(),28);out}
fn osi_edge(absent:&V,present:&V,length:i32)->OSIMessage{OSIMessage{free:add(&mul(&path(length-1),absent),&mul(&path(length-2),present)),blocked:add(&mul(&path(length-2),absent),&mul(&path(length-3),present))}}
fn osi_pair_parts(a:i32,b:i32)->(V,V){(mul(&path(a),&path(b)),shifted(&mul(&path(a-1),&path(b-1)),1))}
fn osi_left_message(gap:i32,a:i32,b:i32)->OSIMessage{let(absent,present)=osi_pair_parts(a,b);osi_edge(&absent,&present,gap+1)}
fn osi_b1_parts(p1:i32,middle:i32,p2:i32,final_spine:i32,a:i32,b:i32)->(V,V){
    let(fa,fp)=osi_pair_parts(a,b);let far=osi_edge(&fa,&fp,final_spine);
    let b2a=mul(&path(p2),&far.free);let b2p=shifted(&mul(&path(p2-1),&far.blocked),1);
    let to_b1=osi_edge(&b2a,&b2p,middle);
    (mul(&path(p1),&to_b1.free),shifted(&mul(&path(p1-1),&to_b1.blocked),1))
}
fn osi_prefixes()->Vec<OSIPrefix>{let pairs=osi_pairs();let mut out=Vec::with_capacity(1792);for lg in 0..=7_i32{for &pair in &pairs{for rg in 0..=7_i32{out.push(OSIPrefix{left_gap:osi_gap(lg),left_pair:pair,right_gap:osi_gap(rg),left_message:osi_left_message(lg,pair.first.value,pair.second.value)});}}}assert_eq!(out.len(),1792);out}
fn osi_rights()->Vec<OSIRight>{let pairs=osi_pairs();let mut out=Vec::with_capacity(87_808);for p1 in 1..=7_i32{for middle in 1..=8_i32{for p2 in 1..=7_i32{for final_spine in 1..=8_i32{for &pair in &pairs{let(a,b)=osi_b1_parts(p1,middle,p2,final_spine,pair.first.value,pair.second.value);out.push(OSIRight{left_inner:osi_pendant(p1),middle:osi_spine(middle),right_inner:osi_pendant(p2),final_spine:osi_spine(final_spine),far_pair:pair,b1_absent:a,b1_present:b});}}}}}assert_eq!(out.len(),87_808);out}
fn osi_states(p:OSIPrefix,r:OSIRight)->[OSIState;10]{[p.left_gap,p.left_pair.first,p.left_pair.second,p.right_gap,r.left_inner,r.middle,r.right_inner,r.final_spine,r.far_pair.first,r.far_pair.second]}
fn osi_lengths(s:&[OSIState;10])->[i32;10]{std::array::from_fn(|i|s[i].value)}
fn osi_values_messages(left:OSIMessage,right:OSIMessage)->[Z;4]{let deleted=mul(&left.free,&right.free);let selected=shifted(&mul(&left.blocked,&right.blocked),1);deltas03(&add(&deleted,&selected),&deleted)}
fn osi_values_fixed(p:OSIPrefix,r:OSIRight)->[Z;4]{osi_values_messages(p.left_message,osi_edge(&r.b1_absent,&r.b1_present,p.right_gap.value+1))}
fn osi_values_variable(lengths:&[i32;10],varying:usize,p:OSIPrefix,r:OSIRight)->[Z;4]{
    let left=if varying<=2{osi_left_message(lengths[0],lengths[1],lengths[2])}else{p.left_message};
    let(a,b)=if varying>=4{osi_b1_parts(lengths[4],lengths[5],lengths[6],lengths[7],lengths[8],lengths[9])}else{(r.b1_absent,r.b1_present)};
    osi_values_messages(left,osi_edge(&a,&b,lengths[3]+1))
}
fn osi_formula(lengths:&[i32;10])->(V,V){let left=osi_left_message(lengths[0],lengths[1],lengths[2]);let(a,b)=osi_b1_parts(lengths[4],lengths[5],lengths[6],lengths[7],lengths[8],lengths[9]);let right=osi_edge(&a,&b,lengths[3]+1);let deleted=mul(&left.free,&right.free);let selected=shifted(&mul(&left.blocked,&right.blocked),1);(add(&deleted,&selected),deleted)}
fn osi_build_literal(lengths:&[i32;10])->(Vec<Vec<usize>>,usize){let mut a=vec![Vec::new()];let root=0;let b0=audit_attach(&mut a,root,lengths[0]+1);audit_attach(&mut a,b0,lengths[1]);audit_attach(&mut a,b0,lengths[2]);let b1=audit_attach(&mut a,root,lengths[3]+1);audit_attach(&mut a,b1,lengths[4]);let b2=audit_attach(&mut a,b1,lengths[5]);audit_attach(&mut a,b2,lengths[6]);let b3=audit_attach(&mut a,b2,lengths[7]);audit_attach(&mut a,b3,lengths[8]);audit_attach(&mut a,b3,lengths[9]);assert_eq!(a.len(),3+lengths.iter().sum::<i32>()as usize);assert_eq!(a.iter().filter(|r|r.len()==3).count(),4);assert_eq!(a[root].len(),2);(a,root)}
fn osi_smoke(){let mut state=0x13198A2E03707344_u64;for sample in 0..512{let mut l=[0_i32;10];for(i,v)in l.iter_mut().enumerate(){state^=state>>12;state^=state<<25;state^=state>>27;state=state.wrapping_mul(0x2545F4914F6CDD1D);*v=if i==0||i==3{(state%17)as i32}else{1+(state%17)as i32};}let(adj,root)=osi_build_literal(&l);let(vals,lc,ld)=audit_deltas(&adj,root);let(c,d)=osi_formula(&l);assert_eq!(lc,c,"core {}",sample);assert_eq!(ld,d,"deleted {}",sample);assert_eq!(vals,deltas03(&c,&d),"delta {}",sample);}println!("PASS_FOUR_CUBIC_PATH_OUTER_SPINE_INTERNAL_512_LITERAL_FORMULA_SMOKE");}

fn osi_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0_u8;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn osi_hash_state(h:&mut AuditSha256,s:OSIState){h.update(&[s.long as u8]);h.update(&s.value.to_le_bytes());}
fn osi_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn osi_coeff_leaf(s:&[OSIState;10],base:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"four-cubic-path-outer-spine-internal-coefficient-v1\0");for &x in s{osi_hash_state(&mut h,x);}h.update(&base.to_le_bytes());h.update(&shift.to_le_bytes());for r in rows{for &z in r{osi_hash_z(&mut h,z);}}osi_sha_bytes(h)}
fn osi_finite_leaf(s:&[OSIState;10],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"four-cubic-path-outer-spine-internal-finite-v1\0");for &x in s{osi_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{osi_hash_z(&mut h,z);}osi_sha_bytes(h)}
fn osi_smoke_stream(){let ps=osi_prefixes();let rs=osi_rights();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc)=(0_u64,0_u64);for sample in 0..512_usize{let p=ps[(sample*7919+17)%ps.len()];let r=rs[(sample*104729+23)%rs.len()];let s=osi_states(p,r);let f:[bool;10]=std::array::from_fn(|i|s[i].long);let mut l=osi_lengths(&s);if !f.iter().any(|&x|x){let order=3+l.iter().sum::<i32>();if order>=27{let v=osi_values_fixed(p,r);fh.update(&osi_finite_leaf(&s,order,&v));fc+=1;}continue;}let base=3+l.iter().sum::<i32>();let shift=(27-base).max(0);let var=f.iter().position(|&x|x).unwrap();let initial=l[var];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for point in 0..AUDIT_SAMPLES{l[var]=initial+shift+point as i32;let v=osi_values_variable(&l,var,p,r);for rank in 0..4{samples[rank][point]=v[rank];}}let coeff:[[Z;AUDIT_SAMPLES];4]=std::array::from_fn(|rank|audit_differences(&samples[rank]));audit_assert_gate(&coeff);ch.update(&osi_coeff_leaf(&s,base,shift,&coeff));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}

struct OSIResult{prefix_index:usize,counts:[u64;5],unseen:u64,coefficient_leaves:Vec<u8>,finite_leaves:Vec<u8>,literal_checks:u64}
fn osi_worker(prefix_index:usize,ps:Arc<Vec<OSIPrefix>>,rs:Arc<Vec<OSIRight>>)->OSIResult{let p=ps[prefix_index];let mut counts=[0_u64;5];let mut unseen=0;let mut cl=Vec::new();let mut fl=Vec::new();let mut checks=0;let(mut checked_finite,mut checked_ray)=(false,false);for &r in rs.iter(){let s=osi_states(p,r);let f:[bool;10]=std::array::from_fn(|i|s[i].long);let lc=f.iter().filter(|&&x|x).count();let mut l=osi_lengths(&s);if lc==0{counts[0]+=1;let order=3+l.iter().sum::<i32>();if order<27{continue;}let v=osi_values_fixed(p,r);assert!(v.iter().all(|z|z.is_positive()));fl.extend_from_slice(&osi_finite_leaf(&s,order,&v));if !checked_finite{let(a,root)=osi_build_literal(&l);assert_eq!(audit_deltas(&a,root).0,v);checked_finite=true;checks+=1;}counts[1]+=1;continue;}if lc==10{counts[3]+=1}else{counts[2]+=1}let base=3+l.iter().sum::<i32>();let shift=(27-base).max(0);let var=f.iter().position(|&x|x).unwrap();let initial=l[var];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];for point in 0..AUDIT_SAMPLES{l[var]=initial+shift+point as i32;let v=osi_values_variable(&l,var,p,r);for rank in 0..4{samples[rank][point]=v[rank];}}let coeff:[[Z;AUDIT_SAMPLES];4]=std::array::from_fn(|rank|audit_differences(&samples[rank]));audit_assert_gate(&coeff);cl.extend_from_slice(&osi_coeff_leaf(&s,base,shift,&coeff));l[var]=initial+shift+AUDIT_SAMPLES as i32;let next=osi_values_variable(&l,var,p,r);for rank in 0..4{assert_eq!(next[rank],audit_newton_at_29(&coeff[rank]));unseen+=1;}if !checked_ray{let(a,root)=osi_build_literal(&l);assert_eq!(audit_deltas(&a,root).0,next);checked_ray=true;checks+=1;}counts[4]+=1;}assert_eq!(cl.len(),counts[4]as usize*32);assert_eq!(fl.len(),counts[1]as usize*32);OSIResult{prefix_index,counts,unseen,coefficient_leaves:cl,finite_leaves:fl,literal_checks:checks}}
fn main(){audit_sha_self_test();if std::env::args().nth(1).as_deref()==Some("smoke"){osi_smoke();osi_smoke_stream();return;}let ps=Arc::new(osi_prefixes());let rs=Arc::new(osi_rights());let mut counts=[0_u64;5];let(mut unseen,mut checks)=(0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for start in(0..ps.len()).step_by(OSI_BATCH_PREFIXES){let end=(start+OSI_BATCH_PREFIXES).min(ps.len());let mut handles=Vec::new();for worker in 0..OSI_THREADS{let pc=Arc::clone(&ps);let rc=Arc::clone(&rs);handles.push(thread::spawn(move||{let mut out=Vec::new();let mut i=start+worker;while i<end{out.push(osi_worker(i,Arc::clone(&pc),Arc::clone(&rc)));i+=OSI_THREADS;}out}));}let mut results:Vec<OSIResult>=handles.into_iter().map(|h|h.join().expect("producer panic")).flatten().collect();results.sort_by_key(|r|r.prefix_index);for r in results{for i in 0..5{counts[i]+=r.counts[i];}unseen+=r.unseen;checks+=r.literal_checks;ch.update(&r.coefficient_leaves);fh.update(&r.finite_leaves);}eprintln!("PRODUCER PREFIXES {}/{}",end,ps.len());}assert_eq!(counts,[38_118_276,37_143_771,119_233_659,1,119_233_660]);assert_eq!(unseen,476_934_640);assert_eq!(checks,2_821);let raw=format!(concat!("PASS_I256_FOUR_CUBIC_PATH_OUTER_SPINE_INTERNAL_PRODUCER\n","COUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_SPOT_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n"),counts[0],counts[1],counts[2],counts[3],counts[4],unseen,checks,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e4_four_cubic_path_outer_spine_internal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
