// Six-thread checked-i256 producer for quartic_endpoint_cubic_path:cubic_cubic_spine_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc; use std::thread;
const QSP_THREADS: usize = 6; const QSP_BENCH_RAYS: usize = 1_024;
#[derive(Clone, Copy)] struct QSPState { length: i32, is_long: bool }
#[derive(Clone, Copy)] struct QSPMessage { free: V, blocked: V }
#[derive(Clone, Copy)] struct QSPQuarticSide { gap: QSPState, spine: QSPState, arm0: QSPState, arm1: QSPState, arm2: QSPState, center_arm: QSPState, at_root: QSPMessage }
#[derive(Clone, Copy)] struct QSPCenterSide { gap: QSPState, arm0: QSPState, arm1: QSPState, at_root: QSPMessage }
fn qsp_gap(length:i32)->QSPState{QSPState{length,is_long:length==7}} fn qsp_spine(length:i32)->QSPState{QSPState{length,is_long:length==8}} fn qsp_pendant(length:i32)->QSPState{QSPState{length,is_long:length==7}}
fn qsp_cross(absent:V,present:V,length:i32)->QSPMessage{QSPMessage{free:add(&mul(&path(length-1),&absent),&mul(&path(length-2),&present)),blocked:add(&mul(&path(length-2),&absent),&mul(&path(length-3),&present))}}
fn qsp_quartic_at_center(spine:i32,a0:i32,a1:i32,a2:i32)->QSPMessage{let absent=product(&[path(a0),path(a1),path(a2)]);let present=shifted(&product(&[path(a0-1),path(a1-1),path(a2-1)]),1);qsp_cross(absent,present,spine)}
fn qsp_center_parts(gap:i32,spine:i32,a0:i32,a1:i32,a2:i32,center_arm:i32)->QSPMessage{let quartic=qsp_quartic_at_center(spine,a0,a1,a2);let absent=mul(&path(center_arm),&quartic.free);let present=shifted(&mul(&path(center_arm-1),&quartic.blocked),1);qsp_cross(absent,present,gap+1)}
fn qsp_endpoint_parts(gap:i32,a0:i32,a1:i32)->QSPMessage{let absent=product(&[path(a0),path(a1)]);let present=shifted(&product(&[path(a0-1),path(a1-1)]),1);qsp_cross(absent,present,gap+1)}
fn qsp_quartic_sides()->Vec<QSPQuarticSide>{let mut out=Vec::with_capacity(37_632);for gap in 0..=7_i32{for spine in 1..=8_i32{for a0 in 1..=7_i32{for a1 in a0..=7_i32{for a2 in a1..=7_i32{for center_arm in 1..=7_i32{out.push(QSPQuarticSide{gap:qsp_gap(gap),spine:qsp_spine(spine),arm0:qsp_pendant(a0),arm1:qsp_pendant(a1),arm2:qsp_pendant(a2),center_arm:qsp_pendant(center_arm),at_root:qsp_center_parts(gap,spine,a0,a1,a2,center_arm)});}}}}}}assert_eq!(out.len(),37_632);out}
fn qsp_center_sides()->Vec<QSPCenterSide>{let mut out=Vec::with_capacity(224);for gap in 0..=7_i32{for a0 in 1..=7_i32{for a1 in a0..=7_i32{out.push(QSPCenterSide{gap:qsp_gap(gap),arm0:qsp_pendant(a0),arm1:qsp_pendant(a1),at_root:qsp_endpoint_parts(gap,a0,a1)});}}}assert_eq!(out.len(),224);out}
fn qsp_states(q:QSPQuarticSide,c:QSPCenterSide)->[QSPState;9]{[q.gap,c.gap,q.spine,q.arm0,q.arm1,q.arm2,q.center_arm,c.arm0,c.arm1]} fn qsp_lengths(s:&[QSPState;9])->[i32;9]{std::array::from_fn(|i|s[i].length)}
fn qsp_formula_polynomials(l:&[i32;9])->(V,V){let q=qsp_center_parts(l[0],l[2],l[3],l[4],l[5],l[6]);let c=qsp_endpoint_parts(l[1],l[7],l[8]);let deleted=mul(&q.free,&c.free);let selected=shifted(&mul(&q.blocked,&c.blocked),1);(add(&deleted,&selected),deleted)}
fn qsp_values(l:&[i32;9],q:QSPQuarticSide,c:QSPCenterSide,varying:Option<usize>)->[Z;4]{let left=if varying.is_some_and(|i|i==0||(2..=6).contains(&i)){qsp_center_parts(l[0],l[2],l[3],l[4],l[5],l[6])}else{q.at_root};let right=if varying.is_some_and(|i|i==1||i>=7){qsp_endpoint_parts(l[1],l[7],l[8])}else{c.at_root};let deleted=mul(&left.free,&right.free);let selected=shifted(&mul(&left.blocked,&right.blocked),1);deltas03(&add(&deleted,&selected),&deleted)}
fn qsp_literal_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let center=audit_attach(&mut a,root,l[0]+1);let q=audit_attach(&mut a,center,l[2]);audit_attach(&mut a,q,l[3]);audit_attach(&mut a,q,l[4]);audit_attach(&mut a,q,l[5]);audit_attach(&mut a,center,l[6]);let endpoint=audit_attach(&mut a,root,l[1]+1);audit_attach(&mut a,endpoint,l[7]);audit_attach(&mut a,endpoint,l[8]);assert_eq!(a.len(),3+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}
fn qsp_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qsp_literal_tree(l);audit_deltas(&a,r).0}
fn qsp_formula_smoke(){let mut random=0xA917C63E520DB84F_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}let(c,d)=qsp_formula_polynomials(&l);assert_eq!(deltas03(&c,&d),qsp_literal_values(&l),"cubic-cubic spine primary mismatch {}",sample);}println!("PASS_E5_CUBIC_CUBIC_SPINE_INTERNAL_PRIMARY_512_LITERAL_FORMULA_SMOKE");}
fn qsp_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qsp_hash_state(h:&mut AuditSha256,s:QSPState){h.update(&[s.is_long as u8]);h.update(&s.length.to_le_bytes());}fn qsp_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qsp_coefficient_leaf(s:&[QSPState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-cubic-cubic-spine-internal-coefficient-v1\0");for &x in s{qsp_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qsp_hash_z(&mut h,z);}}qsp_sha_bytes(h)}
fn qsp_finite_leaf(s:&[QSPState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-cubic-cubic-spine-internal-finite-v1\0");for &x in s{qsp_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qsp_hash_z(&mut h,z);}qsp_sha_bytes(h)}
fn qsp_order27_leaf(l:&[i32;9],v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-cubic-cubic-spine-internal-order27-v1\0");for &x in l{h.update(&x.to_le_bytes());}for &z in v{qsp_hash_z(&mut h,z);}qsp_sha_bytes(h)}
fn qsp_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{for p in(AUDIT_DEGREES[rank]+1)..AUDIT_SAMPLES{if !rows[rank][p].is_zero(){return false;}}}true}fn qsp_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{if !rows[rank][0].is_positive()||!rows[rank][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[rank]{if rows[rank][p].is_negative(){return false;}}}qsp_degree_ok(rows)}
fn qsp_coefficients(s:&[QSPState;9],q:QSPQuarticSide,c:QSPCenterSide,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.is_long).unwrap();let mut l=qsp_lengths(s);let baseline=3+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qsp_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qsp_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qsp_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qsp_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qsp_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qsp_smoke_stream(){let qs=qsp_quartic_sides();let roots=qsp_center_sides();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let root=roots[(sample*17+23)%roots.len()];let s=qsp_states(q,root);if !s.iter().any(|x|x.is_long){let l=qsp_lengths(&s);let order=3+l.iter().sum::<i32>();if order>=28{let v=qsp_values(&l,q,root,None);fh.update(&qsp_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows,_)=qsp_coefficients(&s,q,root,false);if !qsp_gate_ok(&rows){gf+=1;}ch.update(&qsp_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
fn qsp_bench(){let qs=qsp_quartic_sides();let roots=qsp_center_sides();let mut h=AuditSha256::new();let(mut rays,mut c)=(0,0);while rays<QSP_BENCH_RAYS{let q=qs[(c*104_729+5)%qs.len()];let root=roots[(c*17+31)%roots.len()];c+=1;let s=qsp_states(q,root);if !s.iter().any(|x|x.is_long){continue;}let(b,sh,rows,_)=qsp_coefficients(&s,q,root,false);h.update(&qsp_coefficient_leaf(&s,b,sh,&rows));rays+=1;}println!("BENCH_RAYS {}",rays);println!("BENCH_STREAM {}",h.hex());println!("RESOURCE_TABLE_BYTES {} {}",qs.len()*std::mem::size_of::<QSPQuarticSide>(),roots.len()*std::mem::size_of::<QSPCenterSide>());println!("RESOURCE_FULL_LEAF_BYTES {}",8_113_086_usize*32);}
fn qsp_compositions<F:FnMut(&[i32;9])>(rem:i32,slot:usize,row:&mut[i32;9],f:&mut F){if slot==8{if rem>=1{row[slot]=rem;f(row);}return;}let left=9-slot;for v in 1..=(rem-left as i32+1){row[slot]=v;qsp_compositions(rem-v,slot+1,row,f);}}
fn qsp_order27(){let(mut count,mut spots)=(0_u64,0_u64);let mut non=[0_u64;4];let mut h=AuditSha256::new();let mut row=[0;9];qsp_compositions(26,0,&mut row,&mut|positive|{let mut l=*positive;l[0]-=1;l[1]-=1;if !(l[3]<=l[4]&&l[4]<=l[5]&&l[7]<=l[8]){return;}let(c,d)=qsp_formula_polynomials(&l);let v=deltas03(&c,&d);for r in 0..4{if !v[r].is_positive(){non[r]+=1;}}if count%4096==0{assert_eq!(v,qsp_literal_values(&l));spots+=1;}h.update(&qsp_order27_leaf(&l,&v));count+=1;});assert_eq!(count,174_083);assert_eq!(non,[0;4]);assert_eq!(spots,43);let raw=format!("PASS_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_CUBIC_CUBIC_SPINE_INTERNAL_ORDER27\nORDER27_COUNT {}\nNONPOSITIVE {} {} {} {}\nLITERAL_SPOTS {}\nVALUE_STREAM {}\n",count,non[0],non[1],non[2],non[3],spots,h.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_cubic_cubic_spine_internal_order27_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
struct QSPResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qsp_worker(worker:usize,qs:Arc<Vec<QSPQuarticSide>>,roots:Arc<Vec<QSPCenterSide>>)->QSPResult{let start=qs.len()*worker/QSP_THREADS;let end=qs.len()*(worker+1)/QSP_THREADS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();let(mut checked_finite,mut checked_ray)=(false,false);for qi in start..end{let q=qs[qi];for &root in roots.iter(){let s=qsp_states(q,root);let lc=s.iter().filter(|x|x.is_long).count();if lc==0{counts[0]+=1;let l=qsp_lengths(&s);let order=3+l.iter().sum::<i32>();if order<28{continue;}let v=qsp_values(&l,q,root,None);assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qsp_finite_leaf(&s,order,&v));if !checked_finite{assert_eq!(v,qsp_literal_values(&l));checked_finite=true;literal+=1;}counts[1]+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,c)=qsp_coefficients(&s,q,root,!checked_ray);audit_assert_gate(&rows);if !checked_ray{checked_ray=true;literal+=c;}coeff.extend_from_slice(&qsp_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;}}QSPResult{worker,counts,unseen,literal,coeff,finite}}
fn qsp_full(){let qs=Arc::new(qsp_quartic_sides());let roots=Arc::new(qsp_center_sides());let mut handles=Vec::new();for w in 0..QSP_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&roots);handles.push(thread::spawn(move||qsp_worker(w,a,b)));}let mut results:Vec<_>=handles.into_iter().map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[2_420_208,2_103_726,6_009_359,1,6_009_360]);assert_eq!(unseen,24_037_440);let raw=format!("PASS_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_CUBIC_CUBIC_SPINE_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_cubic_cubic_spine_internal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qsp_formula_smoke();qsp_smoke_stream();},Some("bench")=>qsp_bench(),Some("order27")=>qsp_order27(),Some(x)=>panic!("unknown mode {}",x),None=>qsp_full()}}
