// Six-thread checked-i256 producer for quartic_endpoint_cubic_path:quartic_leaf.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc; use std::thread;
const QLP_THREADS: usize = 6; const QLP_BENCH_RAYS: usize = 1_024;
#[derive(Clone, Copy)] struct QLPState { length: i32, is_long: bool }
#[derive(Clone, Copy)] struct QLPMessage { free: V, blocked: V }
#[derive(Clone, Copy)] struct QLPEndpoint { spine: QLPState, arm0: QLPState, arm1: QLPState, at_center: QLPMessage }
#[derive(Clone, Copy)] struct QLPRoot { incident: QLPState, sibling0: QLPState, sibling1: QLPState, to_center: QLPState, center_arm: QLPState }
fn qlp_incident(length:i32)->QLPState{QLPState{length,is_long:length==8}} fn qlp_spine(length:i32)->QLPState{QLPState{length,is_long:length==8}} fn qlp_pendant(length:i32)->QLPState{QLPState{length,is_long:length==7}}
fn qlp_cross(absent:V,present:V,length:i32)->QLPMessage{QLPMessage{free:add(&mul(&path(length-1),&absent),&mul(&path(length-2),&present)),blocked:add(&mul(&path(length-2),&absent),&mul(&path(length-3),&present))}}
fn qlp_endpoint_parts(spine:i32,a0:i32,a1:i32)->QLPMessage{let absent=product(&[path(a0),path(a1)]);let present=shifted(&product(&[path(a0-1),path(a1-1)]),1);qlp_cross(absent,present,spine)}
fn qlp_endpoints()->Vec<QLPEndpoint>{let mut out=Vec::with_capacity(224);for a0 in 1..=7_i32{for a1 in a0..=7_i32{for spine in 1..=8_i32{out.push(QLPEndpoint{spine:qlp_spine(spine),arm0:qlp_pendant(a0),arm1:qlp_pendant(a1),at_center:qlp_endpoint_parts(spine,a0,a1)});}}}assert_eq!(out.len(),224);out}
fn qlp_roots()->Vec<QLPRoot>{let mut out=Vec::with_capacity(12_544);for incident in 1..=8_i32{for sibling0 in 1..=7_i32{for sibling1 in sibling0..=7_i32{for to_center in 1..=8_i32{for center_arm in 1..=7_i32{out.push(QLPRoot{incident:qlp_incident(incident),sibling0:qlp_pendant(sibling0),sibling1:qlp_pendant(sibling1),to_center:qlp_spine(to_center),center_arm:qlp_pendant(center_arm)});}}}}}assert_eq!(out.len(),12_544);out}
fn qlp_states(e:QLPEndpoint,r:QLPRoot)->[QLPState;8]{[r.incident,r.sibling0,r.sibling1,r.to_center,r.center_arm,e.spine,e.arm0,e.arm1]} fn qlp_lengths(s:&[QLPState;8])->[i32;8]{std::array::from_fn(|i|s[i].length)}
fn qlp_center(lengths:&[i32;8],endpoint:QLPMessage)->QLPMessage{let absent=mul(&path(lengths[4]),&endpoint.free);let present=shifted(&mul(&path(lengths[4]-1),&endpoint.blocked),1);qlp_cross(absent,present,lengths[3])}
fn qlp_finish(lengths:&[i32;8],center:QLPMessage)->(V,V){let absent=product(&[path(lengths[1]),path(lengths[2]),center.free]);let present=shifted(&product(&[path(lengths[1]-1),path(lengths[2]-1),center.blocked]),1);let at_root=qlp_cross(absent,present,lengths[0]);let deleted=at_root.free;let selected=shifted(&at_root.blocked,1);(add(&deleted,&selected),deleted)}
fn qlp_formula_polynomials(l:&[i32;8])->(V,V){qlp_finish(l,qlp_center(l,qlp_endpoint_parts(l[5],l[6],l[7])))}
fn qlp_values(l:&[i32;8],e:QLPEndpoint,varying:Option<usize>)->[Z;4]{let message=if varying.is_some_and(|i|i>=5){qlp_endpoint_parts(l[5],l[6],l[7])}else{e.at_center};let(core,deleted)=qlp_finish(l,qlp_center(l,message));deltas03(&core,&deleted)}
fn qlp_literal_tree(l:&[i32;8])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let q=audit_attach(&mut a,root,l[0]);audit_attach(&mut a,q,l[1]);audit_attach(&mut a,q,l[2]);let center=audit_attach(&mut a,q,l[3]);audit_attach(&mut a,center,l[4]);let endpoint=audit_attach(&mut a,center,l[5]);audit_attach(&mut a,endpoint,l[6]);audit_attach(&mut a,endpoint,l[7]);assert_eq!(a.len(),1+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),1);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}
fn qlp_literal_values(l:&[i32;8])->[Z;4]{let(a,r)=qlp_literal_tree(l);audit_deltas(&a,r).0}
fn qlp_formula_smoke(){let mut random=0xA917C63E520DB84F_u64;for sample in 0..512{let mut l=[0;8];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}let(c,d)=qlp_formula_polynomials(&l);assert_eq!(deltas03(&c,&d),qlp_literal_values(&l),"endpoint leaf primary mismatch {}",sample);}println!("PASS_E5_QUARTIC_LEAF_PRIMARY_512_LITERAL_FORMULA_SMOKE");}
fn qlp_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qlp_hash_state(h:&mut AuditSha256,s:QLPState){h.update(&[s.is_long as u8]);h.update(&s.length.to_le_bytes());}fn qlp_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qlp_coefficient_leaf(s:&[QLPState;8],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-leaf-coefficient-v1\0");for &x in s{qlp_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qlp_hash_z(&mut h,z);}}qlp_sha_bytes(h)}
fn qlp_finite_leaf(s:&[QLPState;8],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-leaf-finite-v1\0");for &x in s{qlp_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qlp_hash_z(&mut h,z);}qlp_sha_bytes(h)}
fn qlp_order27_leaf(l:&[i32;8],v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-leaf-order27-v1\0");for &x in l{h.update(&x.to_le_bytes());}for &z in v{qlp_hash_z(&mut h,z);}qlp_sha_bytes(h)}
fn qlp_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{for p in(AUDIT_DEGREES[rank]+1)..AUDIT_SAMPLES{if !rows[rank][p].is_zero(){return false;}}}true}fn qlp_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{if !rows[rank][0].is_positive()||!rows[rank][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[rank]{if rows[rank][p].is_negative(){return false;}}}qlp_degree_ok(rows)}
fn qlp_coefficients(s:&[QLPState;8],q:QLPEndpoint,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.is_long).unwrap();let mut l=qlp_lengths(s);let baseline=1+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qlp_values(&l,q,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qlp_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qlp_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qlp_values(&l,q,Some(varying));if literal{assert_eq!(unseen,qlp_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qlp_smoke_stream(){let qs=qlp_endpoints();let roots=qlp_roots();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let root=roots[(sample*17+23)%roots.len()];let s=qlp_states(q,root);if !s.iter().any(|x|x.is_long){let l=qlp_lengths(&s);let order=1+l.iter().sum::<i32>();if order>=28{let v=qlp_values(&l,q,None);fh.update(&qlp_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows,_)=qlp_coefficients(&s,q,false);if !qlp_gate_ok(&rows){gf+=1;}ch.update(&qlp_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
fn qlp_bench(){let qs=qlp_endpoints();let roots=qlp_roots();let mut h=AuditSha256::new();let(mut rays,mut c)=(0,0);while rays<QLP_BENCH_RAYS{let q=qs[(c*104_729+5)%qs.len()];let root=roots[(c*17+31)%roots.len()];c+=1;let s=qlp_states(q,root);if !s.iter().any(|x|x.is_long){continue;}let(b,sh,rows,_)=qlp_coefficients(&s,q,false);h.update(&qlp_coefficient_leaf(&s,b,sh,&rows));rays+=1;}println!("BENCH_RAYS {}",rays);println!("BENCH_STREAM {}",h.hex());println!("RESOURCE_TABLE_BYTES {} {}",qs.len()*std::mem::size_of::<QLPEndpoint>(),roots.len()*std::mem::size_of::<QLPRoot>());println!("RESOURCE_FULL_LEAF_BYTES {}",2_547_030_usize*32);}
fn qlp_compositions<F:FnMut(&[i32;8])>(rem:i32,slot:usize,row:&mut[i32;8],f:&mut F){if slot==7{if rem>=1{row[slot]=rem;f(row);}return;}let left=8-slot;for v in 1..=(rem-left as i32+1){row[slot]=v;qlp_compositions(rem-v,slot+1,row,f);}}
fn qlp_order27(){let(mut count,mut spots)=(0_u64,0_u64);let mut non=[0_u64;4];let mut h=AuditSha256::new();let mut row=[0;8];qlp_compositions(26,0,&mut row,&mut|l|{if !(l[1]<=l[2]&&l[6]<=l[7]){return;}let(c,d)=qlp_formula_polynomials(l);let v=deltas03(&c,&d);for r in 0..4{if !v[r].is_positive(){non[r]+=1;}}if count%4096==0{assert_eq!(v,qlp_literal_values(l));spots+=1;}h.update(&qlp_order27_leaf(l,&v));count+=1;});assert_eq!(count,161_161);assert_eq!(non,[0;4]);assert_eq!(spots,40);let raw=format!("PASS_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_QUARTIC_LEAF_ORDER27\nORDER27_COUNT {}\nNONPOSITIVE {} {} {} {}\nLITERAL_SPOTS {}\nVALUE_STREAM {}\n",count,non[0],non[1],non[2],non[3],spots,h.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_quartic_leaf_order27_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
struct QLPResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qlp_worker(worker:usize,qs:Arc<Vec<QLPEndpoint>>,roots:Arc<Vec<QLPRoot>>)->QLPResult{let start=qs.len()*worker/QLP_THREADS;let end=qs.len()*(worker+1)/QLP_THREADS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();let(mut checked_finite,mut checked_ray)=(false,false);for qi in start..end{let q=qs[qi];for &root in roots.iter(){let s=qlp_states(q,root);let lc=s.iter().filter(|x|x.is_long).count();if lc==0{counts[0]+=1;let l=qlp_lengths(&s);let order=1+l.iter().sum::<i32>();if order<28{continue;}let v=qlp_values(&l,q,None);assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qlp_finite_leaf(&s,order,&v));if !checked_finite{assert_eq!(v,qlp_literal_values(&l));checked_finite=true;literal+=1;}counts[1]+=1;continue;}if lc==8{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,c)=qlp_coefficients(&s,q,!checked_ray);audit_assert_gate(&rows);if !checked_ray{checked_ray=true;literal+=c;}coeff.extend_from_slice(&qlp_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;}}QLPResult{worker,counts,unseen,literal,coeff,finite}}
fn qlp_full(){let qs=Arc::new(qlp_endpoints());let roots=Arc::new(qlp_roots());let mut handles=Vec::new();for w in 0..QLP_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&roots);handles.push(thread::spawn(move||qlp_worker(w,a,b)));}let mut results:Vec<_>=handles.into_iter().map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[907_578,644_752,1_902_277,1,1_902_278]);assert_eq!(unseen,7_609_112);let raw=format!("PASS_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_QUARTIC_LEAF\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_quartic_leaf_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qlp_formula_smoke();qlp_smoke_stream();},Some("bench")=>qlp_bench(),Some("order27")=>qlp_order27(),Some(x)=>panic!("unknown mode {}",x),None=>qlp_full()}}


