// Six-thread checked-i256 producer for quartic_endpoint_cubic_path:quartic_pendant_internal.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::{Arc,atomic::{AtomicUsize,Ordering}};use std::thread;
const QEP_THREADS:usize=6;const QEP_TASKS:usize=56;
#[derive(Clone,Copy)]struct QEPState{length:i32,is_long:bool}
#[derive(Clone,Copy)]struct QEPMessage{free:V,blocked:V}
#[derive(Clone,Copy)]struct QEPFarSide{qc0:QEPState,c0p:QEPState,c0c1:QEPState,e0:QEPState,e1:QEPState,at_q:QEPMessage}
#[derive(Clone,Copy)]struct QEPPrefix{gap:QEPState,tail:QEPState,q0:QEPState,q1:QEPState,tail_message:QEPMessage}
fn qep_gap(x:i32)->QEPState{QEPState{length:x,is_long:x==7}}fn qep_pendant(x:i32)->QEPState{QEPState{length:x,is_long:x==7}}fn qep_spine(x:i32)->QEPState{QEPState{length:x,is_long:x==8}}
fn qep_cross(absent:V,present:V,length:i32)->QEPMessage{QEPMessage{free:add(&mul(&path(length-1),&absent),&mul(&path(length-2),&present)),blocked:add(&mul(&path(length-2),&absent),&mul(&path(length-3),&present))}}
fn qep_module(spine:i32,a0:i32,a1:i32)->QEPMessage{qep_cross(mul(&path(a0),&path(a1)),shifted(&mul(&path(a0-1),&path(a1-1)),1),spine)}
fn qep_far_at_q(qc0:i32,c0p:i32,c0c1:i32,e0:i32,e1:i32)->QEPMessage{let endpoint=qep_module(c0c1,e0,e1);let absent=mul(&path(c0p),&endpoint.free);let present=shifted(&mul(&path(c0p-1),&endpoint.blocked),1);qep_cross(absent,present,qc0)}
fn qep_root_side(gap:i32,q0:i32,q1:i32,far:QEPMessage)->QEPMessage{let absent=product(&[path(q0),path(q1),far.free]);let present=shifted(&product(&[path(q0-1),path(q1-1),far.blocked]),1);qep_cross(absent,present,gap+1)}
fn qep_tail(tail:i32)->QEPMessage{QEPMessage{free:path(tail),blocked:path(tail-1)}}
fn qep_far_sides()->Vec<QEPFarSide>{let mut out=Vec::with_capacity(12_544);for qc0 in 1..=8{for c0p in 1..=7{for c0c1 in 1..=8{for e0 in 1..=7{for e1 in e0..=7{out.push(QEPFarSide{qc0:qep_spine(qc0),c0p:qep_pendant(c0p),c0c1:qep_spine(c0c1),e0:qep_pendant(e0),e1:qep_pendant(e1),at_q:qep_far_at_q(qc0,c0p,c0c1,e0,e1)});}}}}}assert_eq!(out.len(),12_544);out}
fn qep_prefixes()->Vec<QEPPrefix>{let mut out=Vec::with_capacity(1_568);for gap in 0..=7{for tail in 1..=7{for q0 in 1..=7{for q1 in q0..=7{out.push(QEPPrefix{gap:qep_gap(gap),tail:qep_pendant(tail),q0:qep_pendant(q0),q1:qep_pendant(q1),tail_message:qep_tail(tail)});}}}}assert_eq!(out.len(),1_568);out}
fn qep_states(q:QEPFarSide,c:QEPPrefix)->[QEPState;9]{[c.gap,c.tail,c.q0,c.q1,q.qc0,q.c0p,q.c0c1,q.e0,q.e1]}fn qep_lengths(s:&[QEPState;9])->[i32;9]{std::array::from_fn(|i|s[i].length)}
fn qep_formula_polynomials(l:&[i32;9])->(V,V){let far=qep_far_at_q(l[4],l[5],l[6],l[7],l[8]);let core=qep_root_side(l[0],l[2],l[3],far);let tail=qep_tail(l[1]);let deleted=mul(&core.free,&tail.free);let selected=shifted(&mul(&core.blocked,&tail.blocked),1);(add(&deleted,&selected),deleted)}
fn qep_values(l:&[i32;9],q:QEPFarSide,c:QEPPrefix,varying:Option<usize>)->[Z;4]{let far=if varying.is_some_and(|i|i>=4){qep_far_at_q(l[4],l[5],l[6],l[7],l[8])}else{q.at_q};let core=qep_root_side(l[0],l[2],l[3],far);let tail=if varying==Some(1){qep_tail(l[1])}else{c.tail_message};let deleted=mul(&core.free,&tail.free);let selected=shifted(&mul(&core.blocked,&tail.blocked),1);deltas03(&add(&deleted,&selected),&deleted)}
fn qep_literal_tree(l:&[i32;9])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let q=audit_attach(&mut a,root,l[0]+1);audit_attach(&mut a,root,l[1]);audit_attach(&mut a,q,l[2]);audit_attach(&mut a,q,l[3]);let c0=audit_attach(&mut a,q,l[4]);audit_attach(&mut a,c0,l[5]);let c1=audit_attach(&mut a,c0,l[6]);audit_attach(&mut a,c1,l[7]);audit_attach(&mut a,c1,l[8]);assert_eq!(a.len(),2+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),2);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}
fn qep_literal_values(l:&[i32;9])->[Z;4]{let(a,r)=qep_literal_tree(l);audit_deltas(&a,r).0}
fn qep_formula_smoke(){let mut random=0xB7310C9EA2546D8F_u64;for sample in 0..512{let mut l=[0;9];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}l[0]-=1;let(c,d)=qep_formula_polynomials(&l);assert_eq!(deltas03(&c,&d),qep_literal_values(&l),"quartic pendant internal primary mismatch {}",sample);}println!("PASS_E5_QUARTIC_ENDPOINT_QUARTIC_PENDANT_INTERNAL_PRIMARY_512_LITERAL_FORMULA_SMOKE");}
fn qep_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn qep_hash_state(h:&mut AuditSha256,s:QEPState){h.update(&[s.is_long as u8]);h.update(&s.length.to_le_bytes());}fn qep_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn qep_coefficient_leaf(s:&[QEPState;9],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-pendant-internal-coefficient-v1\0");for &x in s{qep_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{qep_hash_z(&mut h,z);}}qep_sha_bytes(h)}
fn qep_finite_leaf(s:&[QEPState;9],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-quartic-pendant-internal-finite-v1\0");for &x in s{qep_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{qep_hash_z(&mut h,z);}qep_sha_bytes(h)}
fn qep_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for p in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][p].is_zero(){return false;}}}true}fn qep_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[r]{if rows[r][p].is_negative(){return false;}}}qep_degree_ok(rows)}
fn qep_coefficients(s:&[QEPState;9],q:QEPFarSide,c:QEPPrefix,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.is_long).unwrap();let mut l=qep_lengths(s);let baseline=2+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=qep_values(&l,q,c,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,qep_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(qep_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=qep_values(&l,q,c,Some(varying));if literal{assert_eq!(unseen,qep_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn qep_smoke_stream(){let qs=qep_far_sides();let cs=qep_prefixes();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let c=cs[(sample*17+23)%cs.len()];let s=qep_states(q,c);if !s.iter().any(|x|x.is_long){let l=qep_lengths(&s);let order=2+l.iter().sum::<i32>();if order>=28{let v=qep_values(&l,q,c,None);fh.update(&qep_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows,_)=qep_coefficients(&s,q,c,false);if !qep_gate_ok(&rows){gf+=1;}ch.update(&qep_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
struct QEPResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn qep_worker(task:usize,qs:Arc<Vec<QEPFarSide>>,cs:Arc<Vec<QEPPrefix>>)->QEPResult{let start=qs.len()*task/QEP_TASKS;let end=qs.len()*(task+1)/QEP_TASKS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();let(mut checked_finite,mut checked_ray)=(false,false);for qi in start..end{let q=qs[qi];for &c in cs.iter(){let s=qep_states(q,c);let lc=s.iter().filter(|x|x.is_long).count();if lc==0{counts[0]+=1;let l=qep_lengths(&s);let order=2+l.iter().sum::<i32>();if order<28{continue;}let v=qep_values(&l,q,c,None);assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&qep_finite_leaf(&s,order,&v));if !checked_finite{assert_eq!(v,qep_literal_values(&l));checked_finite=true;literal+=1;}counts[1]+=1;continue;}if lc==9{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,n)=qep_coefficients(&s,q,c,!checked_ray);audit_assert_gate(&rows);if !checked_ray{checked_ray=true;literal+=n;}coeff.extend_from_slice(&qep_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;}}QEPResult{worker:task,counts,unseen,literal,coeff,finite}}
fn qep_full(){let qs=Arc::new(qep_far_sides());let cs=Arc::new(qep_prefixes());let next=Arc::new(AtomicUsize::new(0));let mut handles=Vec::new();for _ in 0..QEP_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&cs);let n=Arc::clone(&next);handles.push(thread::spawn(move||{let mut out=Vec::new();loop{let task=n.fetch_add(1,Ordering::SeqCst);if task>=QEP_TASKS{break;}out.push(qep_worker(task,Arc::clone(&a),Arc::clone(&b)));}out}));}let mut results:Vec<_>=handles.into_iter().flat_map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);assert_eq!(results.len(),QEP_TASKS);for(i,r)in results.iter().enumerate(){assert_eq!(r.worker,i);}let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[5_445_468,4_768_380,14_223_523,1,14_223_524]);assert_eq!(unseen,56_894_096);assert!(literal>=QEP_TASKS as u64*3&&literal<=QEP_TASKS as u64*4);let raw=format!("PASS_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_QUARTIC_PENDANT_INTERNAL\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_quartic_pendant_internal_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{qep_formula_smoke();qep_smoke_stream();},Some(x)=>panic!("unknown mode {}",x),None=>qep_full()}}
