// Six-thread checked-i256 producer for quartic_center_two_cubic:cubic_leaf.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc;use std::thread;
const CLP_THREADS:usize=6;const CLP_BENCH_RAYS:usize=1_024;
#[derive(Clone,Copy)]struct CLPState{length:i32,is_long:bool}#[derive(Clone,Copy)]struct CLPMessage{free:V,blocked:V}
#[derive(Clone,Copy)]struct CLPFar{spine:CLPState,arm0:CLPState,arm1:CLPState,at_quartic:CLPMessage}
#[derive(Clone,Copy)]struct CLPPrefix{qarm0:CLPState,qarm1:CLPState,far:CLPFar,q_absent:V,q_present:V}
#[derive(Clone,Copy)]struct CLPRoot{incident:CLPState,sibling:CLPState,spine:CLPState}
fn clp_incident(x:i32)->CLPState{CLPState{length:x,is_long:x==8}}fn clp_spine(x:i32)->CLPState{CLPState{length:x,is_long:x==8}}fn clp_pendant(x:i32)->CLPState{CLPState{length:x,is_long:x==7}}
fn clp_cross(absent:V,present:V,d:i32)->CLPMessage{CLPMessage{free:add(&mul(&path(d-1),&absent),&mul(&path(d-2),&present)),blocked:add(&mul(&path(d-2),&absent),&mul(&path(d-3),&present))}}
fn clp_far_parts(spine:i32,a0:i32,a1:i32)->CLPMessage{let absent=mul(&path(a0),&path(a1));let present=shifted(&mul(&path(a0-1),&path(a1-1)),1);clp_cross(absent,present,spine)}
fn clp_q_parts(l:&[i32;8],far:CLPMessage)->(V,V){(product(&[path(l[3]),path(l[4]),far.free]),shifted(&product(&[path(l[3]-1),path(l[4]-1),far.blocked]),1))}
fn clp_prefixes()->Vec<CLPPrefix>{let mut out=Vec::with_capacity(6_272);for q0 in 1..=7_i32{for q1 in q0..=7_i32{for a0 in 1..=7_i32{for a1 in a0..=7_i32{for spine in 1..=8_i32{let msg=clp_far_parts(spine,a0,a1);out.push(CLPPrefix{qarm0:clp_pendant(q0),qarm1:clp_pendant(q1),far:CLPFar{spine:clp_spine(spine),arm0:clp_pendant(a0),arm1:clp_pendant(a1),at_quartic:msg},q_absent:product(&[path(q0),path(q1),msg.free]),q_present:shifted(&product(&[path(q0-1),path(q1-1),msg.blocked]),1)});}}}}}assert_eq!(out.len(),6_272);out}
fn clp_roots()->Vec<CLPRoot>{let mut out=Vec::with_capacity(448);for incident in 1..=8_i32{for sibling in 1..=7_i32{for spine in 1..=8_i32{out.push(CLPRoot{incident:clp_incident(incident),sibling:clp_pendant(sibling),spine:clp_spine(spine)});}}}assert_eq!(out.len(),448);out}
fn clp_states(p:CLPPrefix,r:CLPRoot)->[CLPState;8]{[r.incident,r.sibling,r.spine,p.qarm0,p.qarm1,p.far.spine,p.far.arm0,p.far.arm1]}fn clp_lengths(s:&[CLPState;8])->[i32;8]{std::array::from_fn(|i|s[i].length)}
fn clp_finish(l:&[i32;8],qa:V,qp:V)->(V,V){let at_cubic=clp_cross(qa,qp,l[2]);let absent=mul(&path(l[1]),&at_cubic.free);let present=shifted(&mul(&path(l[1]-1),&at_cubic.blocked),1);let at_root=clp_cross(absent,present,l[0]);let deleted=at_root.free;let selected=shifted(&at_root.blocked,1);(add(&deleted,&selected),deleted)}
fn clp_formula_polynomials(l:&[i32;8])->(V,V){let far=clp_far_parts(l[5],l[6],l[7]);let(qa,qp)=clp_q_parts(l,far);clp_finish(l,qa,qp)}
fn clp_values(l:&[i32;8],p:CLPPrefix,varying:Option<usize>)->[Z;4]{let far=if varying.is_some_and(|i|i>=5){clp_far_parts(l[5],l[6],l[7])}else{p.far.at_quartic};let(qa,qp)=if varying.is_some_and(|i|i>=3){clp_q_parts(l,far)}else{(p.q_absent,p.q_present)};let(c,d)=clp_finish(l,qa,qp);deltas03(&c,&d)}
fn clp_literal_tree(l:&[i32;8])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let c0=audit_attach(&mut a,root,l[0]);audit_attach(&mut a,c0,l[1]);let q=audit_attach(&mut a,c0,l[2]);audit_attach(&mut a,q,l[3]);audit_attach(&mut a,q,l[4]);let c1=audit_attach(&mut a,q,l[5]);audit_attach(&mut a,c1,l[6]);audit_attach(&mut a,c1,l[7]);assert_eq!(a.len(),1+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),1);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}fn clp_literal_values(l:&[i32;8])->[Z;4]{let(a,r)=clp_literal_tree(l);audit_deltas(&a,r).0}
fn clp_formula_smoke(){let mut x=0x92C15F7AB640ED83_u64;for sample in 0..512{let mut l=[0;8];for z in &mut l{x^=x>>12;x^=x<<25;x^=x>>27;x=x.wrapping_mul(0x2545F4914F6CDD1D);*z=1+(x%23)as i32;}let(c,d)=clp_formula_polynomials(&l);assert_eq!(deltas03(&c,&d),clp_literal_values(&l),"cubic leaf primary mismatch {}",sample);}println!("PASS_E5_CUBIC_LEAF_PRIMARY_512_LITERAL_FORMULA_SMOKE");}
fn clp_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn clp_hash_state(h:&mut AuditSha256,s:CLPState){h.update(&[s.is_long as u8]);h.update(&s.length.to_le_bytes());}fn clp_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn clp_coeff_leaf(s:&[CLPState;8],b:i32,sh:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-leaf-coefficient-v1\0");for &x in s{clp_hash_state(&mut h,x);}h.update(&b.to_le_bytes());h.update(&sh.to_le_bytes());for row in rows{for &z in row{clp_hash_z(&mut h,z);}}clp_sha_bytes(h)}fn clp_finite_leaf(s:&[CLPState;8],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-center-cubic-leaf-finite-v1\0");for &x in s{clp_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{clp_hash_z(&mut h,z);}clp_sha_bytes(h)}
fn clp_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{for k in(AUDIT_DEGREES[r]+1)..AUDIT_SAMPLES{if !rows[r][k].is_zero(){return false;}}}true}fn clp_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for r in 0..4{if !rows[r][0].is_positive()||!rows[r][1].is_positive(){return false;}for k in 2..=AUDIT_DEGREES[r]{if rows[r][k].is_negative(){return false;}}}clp_degree_ok(rows)}
fn clp_coefficients(s:&[CLPState;8],p:CLPPrefix,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.is_long).unwrap();let mut l=clp_lengths(s);let b=1+l.iter().sum::<i32>();let sh=(28-b).max(0);let init=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for k in 0..AUDIT_SAMPLES{l[varying]=init+sh+k as i32;let v=clp_values(&l,p,Some(varying));if literal&&(k==0||k==13){assert_eq!(v,clp_literal_values(&l));checks+=1;}for r in 0..4{samples[r][k]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(clp_degree_ok(&rows));l[varying]=init+sh+AUDIT_SAMPLES as i32;let unseen=clp_values(&l,p,Some(varying));if literal{assert_eq!(unseen,clp_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(b,sh,rows,checks)}
fn clp_smoke_stream(){let ps=clp_prefixes();let roots=clp_roots();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let p=ps[(sample*104_729+3)%ps.len()];let root=roots[(sample*17+23)%roots.len()];let s=clp_states(p,root);if !s.iter().any(|x|x.is_long){let l=clp_lengths(&s);let order=1+l.iter().sum::<i32>();if order>=28{let v=clp_values(&l,p,None);fh.update(&clp_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows,_)=clp_coefficients(&s,p,false);if !clp_gate_ok(&rows){gf+=1;}ch.update(&clp_coeff_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
fn clp_bench(){let ps=clp_prefixes();let roots=clp_roots();let mut h=AuditSha256::new();let(mut rays,mut c)=(0,0);while rays<CLP_BENCH_RAYS{let p=ps[(c*104_729+5)%ps.len()];let root=roots[(c*17+31)%roots.len()];c+=1;let s=clp_states(p,root);if !s.iter().any(|x|x.is_long){continue;}let(b,sh,rows,_)=clp_coefficients(&s,p,false);h.update(&clp_coeff_leaf(&s,b,sh,&rows));rays+=1;}println!("BENCH_RAYS {}",rays);println!("BENCH_STREAM {}",h.hex());println!("RESOURCE_TABLE_BYTES {} {}",ps.len()*std::mem::size_of::<CLPPrefix>(),roots.len()*std::mem::size_of::<CLPRoot>());println!("RESOURCE_FULL_LEAF_BYTES {}",2_547_030_usize*32);}
struct CLPResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn clp_worker(w:usize,ps:Arc<Vec<CLPPrefix>>,roots:Arc<Vec<CLPRoot>>)->CLPResult{let start=ps.len()*w/CLP_THREADS;let end=ps.len()*(w+1)/CLP_THREADS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();let(mut cf,mut cr)=(false,false);for pi in start..end{let p=ps[pi];for &root in roots.iter(){let s=clp_states(p,root);let lc=s.iter().filter(|x|x.is_long).count();if lc==0{counts[0]+=1;let l=clp_lengths(&s);let order=1+l.iter().sum::<i32>();if order<28{continue;}let v=clp_values(&l,p,None);assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&clp_finite_leaf(&s,order,&v));if !cf{assert_eq!(v,clp_literal_values(&l));cf=true;literal+=1;}counts[1]+=1;continue;}if lc==8{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,c)=clp_coefficients(&s,p,!cr);audit_assert_gate(&rows);if !cr{cr=true;literal+=c;}coeff.extend_from_slice(&clp_coeff_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;}}CLPResult{worker:w,counts,unseen,literal,coeff,finite}}
fn clp_full(){let ps=Arc::new(clp_prefixes());let roots=Arc::new(clp_roots());let mut hs=Vec::new();for w in 0..CLP_THREADS{let a=Arc::clone(&ps);let b=Arc::clone(&roots);hs.push(thread::spawn(move||clp_worker(w,a,b)));}let mut rs:Vec<_>=hs.into_iter().map(|h|h.join().unwrap()).collect();rs.sort_by_key(|x|x.worker);let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in rs{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[907_578,644_752,1_902_277,1,1_902_278]);assert_eq!(unseen,7_609_112);let raw=format!("PASS_I256_E5_QUARTIC_CENTER_TWO_CUBIC_CUBIC_LEAF\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_center_two_cubic_cubic_leaf_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{clp_formula_smoke();clp_smoke_stream();},Some("bench")=>clp_bench(),Some(x)=>panic!("unknown mode {}",x),None=>clp_full()}}
