// Six-thread checked-i256 producer for quartic_endpoint_cubic_path:endpoint_cubic_leaf.
include!("rank8_delta03_e4_literal_i256_audit_common_agent.rs");
use std::sync::Arc; use std::thread;
const ELP_THREADS: usize = 6; const ELP_BENCH_RAYS: usize = 1_024;
#[derive(Clone, Copy)] struct ELPState { length: i32, is_long: bool }
#[derive(Clone, Copy)] struct ELPMessage { free: V, blocked: V }
#[derive(Clone, Copy)] struct ELPQuartic { spine: ELPState, arm0: ELPState, arm1: ELPState, arm2: ELPState, at_center: ELPMessage }
#[derive(Clone, Copy)] struct ELPRoot { incident: ELPState, sibling: ELPState, center_spine: ELPState, center_arm: ELPState }
fn elp_incident(length:i32)->ELPState{ELPState{length,is_long:length==8}} fn elp_spine(length:i32)->ELPState{ELPState{length,is_long:length==8}} fn elp_pendant(length:i32)->ELPState{ELPState{length,is_long:length==7}}
fn elp_cross(absent:V,present:V,length:i32)->ELPMessage{ELPMessage{free:add(&mul(&path(length-1),&absent),&mul(&path(length-2),&present)),blocked:add(&mul(&path(length-2),&absent),&mul(&path(length-3),&present))}}
fn elp_quartic_parts(spine:i32,a0:i32,a1:i32,a2:i32)->ELPMessage{let absent=product(&[path(a0),path(a1),path(a2)]);let present=shifted(&product(&[path(a0-1),path(a1-1),path(a2-1)]),1);elp_cross(absent,present,spine)}
fn elp_quartics()->Vec<ELPQuartic>{let mut out=Vec::with_capacity(672);for a0 in 1..=7_i32{for a1 in a0..=7_i32{for a2 in a1..=7_i32{for spine in 1..=8_i32{out.push(ELPQuartic{spine:elp_spine(spine),arm0:elp_pendant(a0),arm1:elp_pendant(a1),arm2:elp_pendant(a2),at_center:elp_quartic_parts(spine,a0,a1,a2)});}}}}assert_eq!(out.len(),672);out}
fn elp_roots()->Vec<ELPRoot>{let mut out=Vec::with_capacity(3_136);for incident in 1..=8_i32{for sibling in 1..=7_i32{for center_spine in 1..=8_i32{for center_arm in 1..=7_i32{out.push(ELPRoot{incident:elp_incident(incident),sibling:elp_pendant(sibling),center_spine:elp_spine(center_spine),center_arm:elp_pendant(center_arm)});}}}}assert_eq!(out.len(),3_136);out}
fn elp_states(q:ELPQuartic,r:ELPRoot)->[ELPState;8]{[r.incident,r.sibling,r.center_spine,r.center_arm,q.spine,q.arm0,q.arm1,q.arm2]} fn elp_lengths(s:&[ELPState;8])->[i32;8]{std::array::from_fn(|i|s[i].length)}
fn elp_center(lengths:&[i32;8],q:ELPMessage)->ELPMessage{let absent=mul(&path(lengths[3]),&q.free);let present=shifted(&mul(&path(lengths[3]-1),&q.blocked),1);elp_cross(absent,present,lengths[2])}
fn elp_finish(lengths:&[i32;8],center:ELPMessage)->(V,V){let absent=mul(&path(lengths[1]),&center.free);let present=shifted(&mul(&path(lengths[1]-1),&center.blocked),1);let at_root=elp_cross(absent,present,lengths[0]);let deleted=at_root.free;let selected=shifted(&at_root.blocked,1);(add(&deleted,&selected),deleted)}
fn elp_formula_polynomials(l:&[i32;8])->(V,V){elp_finish(l,elp_center(l,elp_quartic_parts(l[4],l[5],l[6],l[7])))}
fn elp_values(l:&[i32;8],q:ELPQuartic,varying:Option<usize>)->[Z;4]{let message=if varying.is_some_and(|i|i>=4){elp_quartic_parts(l[4],l[5],l[6],l[7])}else{q.at_center};let(core,deleted)=elp_finish(l,elp_center(l,message));deltas03(&core,&deleted)}
fn elp_literal_tree(l:&[i32;8])->(Vec<Vec<usize>>,usize){let root=0;let mut a=vec![Vec::new()];let endpoint=audit_attach(&mut a,root,l[0]);audit_attach(&mut a,endpoint,l[1]);let center=audit_attach(&mut a,endpoint,l[2]);audit_attach(&mut a,center,l[3]);let q=audit_attach(&mut a,center,l[4]);audit_attach(&mut a,q,l[5]);audit_attach(&mut a,q,l[6]);audit_attach(&mut a,q,l[7]);assert_eq!(a.len(),1+l.iter().sum::<i32>()as usize);assert_eq!(a.iter().map(Vec::len).sum::<usize>(),2*(a.len()-1));assert_eq!(a[root].len(),1);assert_eq!(a.iter().filter(|r|r.len()==4).count(),1);assert_eq!(a.iter().filter(|r|r.len()==3).count(),2);(a,root)}
fn elp_literal_values(l:&[i32;8])->[Z;4]{let(a,r)=elp_literal_tree(l);audit_deltas(&a,r).0}
fn elp_formula_smoke(){let mut random=0xA917C63E520DB84F_u64;for sample in 0..512{let mut l=[0;8];for x in &mut l{random^=random>>12;random^=random<<25;random^=random>>27;random=random.wrapping_mul(0x2545F4914F6CDD1D);*x=1+(random%23)as i32;}let(c,d)=elp_formula_polynomials(&l);assert_eq!(deltas03(&c,&d),elp_literal_values(&l),"endpoint leaf primary mismatch {}",sample);}println!("PASS_E5_ENDPOINT_CUBIC_LEAF_PRIMARY_512_LITERAL_FORMULA_SMOKE");}
fn elp_sha_bytes(mut h:AuditSha256)->[u8;32]{let bits=h.bytes.checked_mul(8).unwrap();h.buffer[h.used]=0x80;h.used+=1;if h.used>56{for i in h.used..64{h.buffer[i]=0;}let b=h.buffer;h.block(&b);h.buffer=[0;64];h.used=0;}for i in h.used..56{h.buffer[i]=0;}h.buffer[56..64].copy_from_slice(&bits.to_be_bytes());let b=h.buffer;h.block(&b);let mut out=[0;32];for i in 0..8{out[4*i..4*i+4].copy_from_slice(&h.state[i].to_be_bytes());}out}
fn elp_hash_state(h:&mut AuditSha256,s:ELPState){h.update(&[s.is_long as u8]);h.update(&s.length.to_le_bytes());}fn elp_hash_z(h:&mut AuditSha256,z:Z){h.update(&[z.negative as u8]);for x in z.limbs{h.update(&x.to_le_bytes());}}
fn elp_coefficient_leaf(s:&[ELPState;8],baseline:i32,shift:i32,rows:&[[Z;AUDIT_SAMPLES];4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-endpoint-cubic-leaf-coefficient-v1\0");for &x in s{elp_hash_state(&mut h,x);}h.update(&baseline.to_le_bytes());h.update(&shift.to_le_bytes());for row in rows{for &z in row{elp_hash_z(&mut h,z);}}elp_sha_bytes(h)}
fn elp_finite_leaf(s:&[ELPState;8],order:i32,v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-endpoint-cubic-leaf-finite-v1\0");for &x in s{elp_hash_state(&mut h,x);}h.update(&order.to_le_bytes());for &z in v{elp_hash_z(&mut h,z);}elp_sha_bytes(h)}
fn elp_order27_leaf(l:&[i32;8],v:&[Z;4])->[u8;32]{let mut h=AuditSha256::new();h.update(b"e5-quartic-endpoint-endpoint-cubic-leaf-order27-v1\0");for &x in l{h.update(&x.to_le_bytes());}for &z in v{elp_hash_z(&mut h,z);}elp_sha_bytes(h)}
fn elp_degree_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{for p in(AUDIT_DEGREES[rank]+1)..AUDIT_SAMPLES{if !rows[rank][p].is_zero(){return false;}}}true}fn elp_gate_ok(rows:&[[Z;AUDIT_SAMPLES];4])->bool{for rank in 0..4{if !rows[rank][0].is_positive()||!rows[rank][1].is_positive(){return false;}for p in 2..=AUDIT_DEGREES[rank]{if rows[rank][p].is_negative(){return false;}}}elp_degree_ok(rows)}
fn elp_coefficients(s:&[ELPState;8],q:ELPQuartic,literal:bool)->(i32,i32,[[Z;AUDIT_SAMPLES];4],u64){let varying=s.iter().position(|x|x.is_long).unwrap();let mut l=elp_lengths(s);let baseline=1+l.iter().sum::<i32>();let shift=(28-baseline).max(0);let initial=l[varying];let mut samples=[[Z::zero();AUDIT_SAMPLES];4];let mut checks=0;for p in 0..AUDIT_SAMPLES{l[varying]=initial+shift+p as i32;let v=elp_values(&l,q,Some(varying));if literal&&(p==0||p==13){assert_eq!(v,elp_literal_values(&l));checks+=1;}for r in 0..4{samples[r][p]=v[r];}}let rows=std::array::from_fn(|r|audit_differences(&samples[r]));assert!(elp_degree_ok(&rows));l[varying]=initial+shift+AUDIT_SAMPLES as i32;let unseen=elp_values(&l,q,Some(varying));if literal{assert_eq!(unseen,elp_literal_values(&l));checks+=1;}for r in 0..4{assert_eq!(unseen[r],audit_newton_at_29(&rows[r]));}(baseline,shift,rows,checks)}
fn elp_smoke_stream(){let qs=elp_quartics();let roots=elp_roots();let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();let(mut fc,mut rc,mut gf)=(0_u64,0_u64,0_u64);for sample in 0..512{let q=qs[(sample*104_729+3)%qs.len()];let root=roots[(sample*17+23)%roots.len()];let s=elp_states(q,root);if !s.iter().any(|x|x.is_long){let l=elp_lengths(&s);let order=1+l.iter().sum::<i32>();if order>=28{let v=elp_values(&l,q,None);fh.update(&elp_finite_leaf(&s,order,&v));fc+=1;}continue;}let(b,sh,rows,_)=elp_coefficients(&s,q,false);if !elp_gate_ok(&rows){gf+=1;}ch.update(&elp_coefficient_leaf(&s,b,sh,&rows));rc+=1;}println!("SMOKE_RECORDS {} {}",fc,rc);println!("SMOKE_GATE_FAILURES {}",gf);println!("SMOKE_STREAM {} {}",ch.hex(),fh.hex());}
fn elp_bench(){let qs=elp_quartics();let roots=elp_roots();let mut h=AuditSha256::new();let(mut rays,mut c)=(0,0);while rays<ELP_BENCH_RAYS{let q=qs[(c*104_729+5)%qs.len()];let root=roots[(c*17+31)%roots.len()];c+=1;let s=elp_states(q,root);if !s.iter().any(|x|x.is_long){continue;}let(b,sh,rows,_)=elp_coefficients(&s,q,false);h.update(&elp_coefficient_leaf(&s,b,sh,&rows));rays+=1;}println!("BENCH_RAYS {}",rays);println!("BENCH_STREAM {}",h.hex());println!("RESOURCE_TABLE_BYTES {} {}",qs.len()*std::mem::size_of::<ELPQuartic>(),roots.len()*std::mem::size_of::<ELPRoot>());println!("RESOURCE_FULL_LEAF_BYTES {}",1_905_124_usize*32);}
fn elp_compositions<F:FnMut(&[i32;8])>(rem:i32,slot:usize,row:&mut[i32;8],f:&mut F){if slot==7{if rem>=1{row[slot]=rem;f(row);}return;}let left=8-slot;for v in 1..=(rem-left as i32+1){row[slot]=v;elp_compositions(rem-v,slot+1,row,f);}}
fn elp_order27(){let(mut count,mut spots)=(0_u64,0_u64);let mut non=[0_u64;4];let mut h=AuditSha256::new();let mut row=[0;8];elp_compositions(26,0,&mut row,&mut|l|{if !(l[5]<=l[6]&&l[6]<=l[7]){return;}let(c,d)=elp_formula_polynomials(l);let v=deltas03(&c,&d);for r in 0..4{if !v[r].is_positive(){non[r]+=1;}}if count%4096==0{assert_eq!(v,elp_literal_values(l));spots+=1;}h.update(&elp_order27_leaf(l,&v));count+=1;});assert_eq!(count,123_131);assert_eq!(non,[0;4]);assert_eq!(spots,31);let raw=format!("PASS_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_ENDPOINT_CUBIC_LEAF_ORDER27\nORDER27_COUNT {}\nNONPOSITIVE {} {} {} {}\nLITERAL_SPOTS {}\nVALUE_STREAM {}\n",count,non[0],non[1],non[2],non[3],spots,h.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_endpoint_cubic_leaf_order27_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
struct ELPResult{worker:usize,counts:[u64;5],unseen:u64,literal:u64,coeff:Vec<u8>,finite:Vec<u8>}
fn elp_worker(worker:usize,qs:Arc<Vec<ELPQuartic>>,roots:Arc<Vec<ELPRoot>>)->ELPResult{let start=qs.len()*worker/ELP_THREADS;let end=qs.len()*(worker+1)/ELP_THREADS;let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut coeff=Vec::new();let mut finite=Vec::new();let(mut checked_finite,mut checked_ray)=(false,false);for qi in start..end{let q=qs[qi];for &root in roots.iter(){let s=elp_states(q,root);let lc=s.iter().filter(|x|x.is_long).count();if lc==0{counts[0]+=1;let l=elp_lengths(&s);let order=1+l.iter().sum::<i32>();if order<28{continue;}let v=elp_values(&l,q,None);assert!(v.iter().all(|z|z.is_positive()));finite.extend_from_slice(&elp_finite_leaf(&s,order,&v));if !checked_finite{assert_eq!(v,elp_literal_values(&l));checked_finite=true;literal+=1;}counts[1]+=1;continue;}if lc==8{counts[3]+=1;}else{counts[2]+=1;}let(b,sh,rows,c)=elp_coefficients(&s,q,!checked_ray);audit_assert_gate(&rows);if !checked_ray{checked_ray=true;literal+=c;}coeff.extend_from_slice(&elp_coefficient_leaf(&s,b,sh,&rows));counts[4]+=1;unseen+=4;}}ELPResult{worker,counts,unseen,literal,coeff,finite}}
fn elp_full(){let qs=Arc::new(elp_quartics());let roots=Arc::new(elp_roots());let mut handles=Vec::new();for w in 0..ELP_THREADS{let a=Arc::clone(&qs);let b=Arc::clone(&roots);handles.push(thread::spawn(move||elp_worker(w,a,b)));}let mut results:Vec<_>=handles.into_iter().map(|h|h.join().unwrap()).collect();results.sort_by_key(|r|r.worker);let(mut counts,mut unseen,mut literal)=([0;5],0,0);let mut ch=AuditSha256::new();let mut fh=AuditSha256::new();for x in results{for i in 0..5{counts[i]+=x.counts[i];}unseen+=x.unseen;literal+=x.literal;ch.update(&x.coeff);fh.update(&x.finite);}assert_eq!(counts,[691_488,489_220,1_415_903,1,1_415_904]);assert_eq!(unseen,5_663_616);let raw=format!("PASS_I256_E5_QUARTIC_ENDPOINT_CUBIC_PATH_ENDPOINT_CUBIC_LEAF\nCOUNTS {} {} {} {} {}\nUNSEEN {}\nLITERAL_CHECKS {}\nCOEFFICIENT_MERKLE_STREAM {}\nFINITE_MERKLE_STREAM {}\n",counts[0],counts[1],counts[2],counts[3],counts[4],unseen,literal,ch.hex(),fh.hex());std::fs::write("rank8_delta03_e5_quartic_endpoint_cubic_path_endpoint_cubic_leaf_i256_raw_agent_20260823.txt",raw.as_bytes()).unwrap();print!("{}",raw);}
fn main(){audit_sha_self_test();match std::env::args().nth(1).as_deref(){Some("smoke")=>{elp_formula_smoke();elp_smoke_stream();},Some("bench")=>elp_bench(),Some("order27")=>elp_order27(),Some(x)=>panic!("unknown mode {}",x),None=>elp_full()}}
