#!/usr/bin/env python3
"""Exact all-rank certificate for the minimal low/high strong boundary.

For rank k and m >= 0 consider the two ratio rows

    L = (k+1, k-1, k-2, ..., 1, 0),
    R = (m+k+1, m+k-1, m+k-2, ..., m+1, m).

Let a and b be the coefficient rows generated by these ratios, c their
binomial convolution, and v the convolution after deleting a_0,a_1,a_2.
With

    M(c) = c_k^2-c_(k-1)c_(k+1)-c_(k-1)c_k

and B(c,v) the polarized derivative of M, this proves exactly that

    (k-2) M(c) + B(c,v) > 0

for every real m >= 0 and every integer k >= 8.  The proof is symbolic for
all k >= 10 and uses direct positive-coefficient expansions for k=8,9.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
from pathlib import Path

import sympy as sp


HERE = Path(__file__).resolve().parent
OUTPUT = (
    HERE
    / "uniform_low_high_minimal_zero_slack_boundary_theorem_exact_root_20260826.json"
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def coefficients_from_ratios(ratios: list[sp.Expr]) -> list[sp.Expr]:
    result = [sp.Integer(1)]
    for ratio in ratios:
        result.append(sp.expand(result[-1] * ratio))
    return result


def convolution_at(left, right, rank: int) -> sp.Expr:
    return sp.expand(sum(
        math.comb(rank, index) * left[index] * right[rank - index]
        for index in range(rank + 1)
    ))


def direct_boundary(rank: int, m: sp.Symbol) -> sp.Expr:
    left_ratios = [
        sp.Integer(rank + 1), sp.Integer(rank - 1),
        *[sp.Integer(rank - index) for index in range(2, rank + 1)],
    ]
    right_ratios = [
        m + rank + 1, m + rank - 1,
        *[m + rank - index for index in range(2, rank + 1)],
    ]
    left = coefficients_from_ratios(left_ratios)
    right = coefficients_from_ratios(right_ratios)
    tail = [sp.Integer(0), sp.Integer(0), sp.Integer(0), *left[3:]]
    c = {
        value: convolution_at(left, right, value)
        for value in (rank - 1, rank, rank + 1)
    }
    v = {
        value: convolution_at(tail, right, value)
        for value in (rank - 1, rank, rank + 1)
    }
    margin = c[rank] ** 2 - c[rank - 1] * c[rank + 1] - c[rank - 1] * c[rank]
    derivative = (
        2 * c[rank] * v[rank]
        - c[rank - 1] * v[rank + 1]
        - v[rank - 1] * c[rank + 1]
        - c[rank - 1] * v[rank]
        - v[rank - 1] * c[rank]
    )
    return sp.expand((rank - 2) * margin + derivative)


def positive_coefficients(poly: sp.Expr, variable: sp.Symbol) -> list[int]:
    coefficients = [int(value) for value in sp.Poly(poly, variable).all_coeffs()]
    assert coefficients and min(coefficients) > 0
    return coefficients


def nonnegative_shift(poly: sp.Expr, variable: sp.Symbol, shift: int) -> list[int]:
    t = sp.Symbol("t", nonnegative=True)
    coefficients = [
        int(value)
        for value in sp.Poly(sp.expand(poly.subs(variable, t + shift)), t).all_coeffs()
    ]
    assert coefficients and min(coefficients) > 0
    return coefficients


def main() -> int:
    k, m, t = sp.symbols("k m t", real=True)
    A, B, D = sp.symbols("A B D", real=True)
    n = k + m

    # The exponential generating functions are
    #   ((k+1)(1+z)^k-1)/k and ((n+1)(1+z)^n-1)/n.
    # Hence the three convolution coefficients can be written using only
    # A=f(m+k), B=f(m), D=f(0), f(x)=prod_{j=2}^k(x+j).
    c_km1 = ((k + 1) * (n + 1) * A - (k + 1) * D - (n + 1) * B) / (k * n)
    c_k = (
        (k + 1) * (n + 1) ** 2 * A
        - (k + 1) * D
        - (n + 1) * (m + 1) * B
    ) / (k * n)
    c_kp1 = (
        (k + 1) * (n + 1) * n * (n + 1) * A
        - (n + 1) * m * (m + 1) * B
    ) / (k * n)

    # The deleted head u=c-v is the convolution with a_0,a_1,a_2 only.
    b_km3 = (n + 1) * B / (n * (m + 2) * (m + 3))
    b_km2 = (n + 1) * B / (n * (m + 2))
    b_km1 = (n + 1) * B / n
    b_k = (n + 1) * (m + 1) * B / n
    b_kp1 = (n + 1) * m * (m + 1) * B / n
    choose_km1_2 = (k - 1) * (k - 2) / 2
    choose_k_2 = k * (k - 1) / 2
    choose_kp1_2 = k * (k + 1) / 2
    u_km1 = (
        b_km1
        + (k - 1) * (k + 1) * b_km2
        + choose_km1_2 * (k ** 2 - 1) * b_km3
    )
    u_k = (
        b_k
        + k * (k + 1) * b_km1
        + choose_k_2 * (k ** 2 - 1) * b_km2
    )
    u_kp1 = (
        b_kp1
        + (k + 1) ** 2 * b_k
        + choose_kp1_2 * (k ** 2 - 1) * b_km1
    )

    margin = c_k ** 2 - c_km1 * c_kp1 - c_km1 * c_k
    head_polarization = (
        2 * c_k * u_k
        - c_km1 * u_kp1
        - u_km1 * c_kp1
        - c_km1 * u_k
        - u_km1 * c_k
    )
    # Since B(c,c)=2M(c), (k-2)M(c)+B(c,c-u)=kM(c)-B(c,u).
    strong = k * margin - head_polarization

    P = (
        k ** 5 - 6 * k ** 4 - 2 * k ** 3 * m + 5 * k ** 3
        + 4 * k ** 2 * m + 10 * k ** 2 + 2 * k * m ** 2
        + 12 * k * m + 6 * k - 4 * m - 4
    )
    CAD = 2 * (k + 1) ** 2 * n ** 2 * (m + 2) * (m + 3) * (n + 1)
    CAB = (k - 1) * (k + 1) * (n + 1) ** 2 * P
    Q = (
        k ** 4 * m ** 2 + 4 * k ** 4 * m + 4 * k ** 4
        + k ** 3 * m ** 2 + 6 * k ** 3 * m + 6 * k ** 3
        + 2 * k ** 2 * m ** 3 + 9 * k ** 2 * m ** 2
        + 10 * k ** 2 * m + 4 * k ** 2 + 4 * k * m ** 3
        + 21 * k * m ** 2 + 28 * k * m + 6 * k
        + 4 * m ** 4 + 22 * m ** 3 + 36 * m ** 2 + 20 * m + 4
    )
    CDB = (k + 1) * (n + 1) * Q
    CBB = 2 * (k + 1) * (n + 1) ** 3 * (2 * k ** 2 + k * m - k + 2)
    numerator = A * D * CAD + A * B * CAB - D * B * CDB - B ** 2 * CBB
    denominator = 2 * k * n ** 2 * (m + 2) * (m + 3)
    assert sp.factor(sp.together(strong - numerator / denominator)) == 0

    # CAB-CBB is positive for k>=8: the remaining quadratic W has positive
    # leading coefficient and a strictly negative discriminant.
    W = sp.factor((CAB - CBB) / (k * (k + 1) * (n + 1) ** 2))
    W_expected = (
        k ** 5 - 7 * k ** 4 - 2 * k ** 3 * m + 11 * k ** 3
        + 6 * k ** 2 * m + k ** 2 + 2 * k * m ** 2
        + 2 * k * m - 6 * k - 4 * m ** 2 - 16 * m - 12
    )
    assert sp.expand(W - W_expected) == 0
    W_discriminant_core = (
        k ** 6 - 12 * k ** 5 + 43 * k ** 4 - 64 * k ** 3
        + 31 * k ** 2 + 16 * k - 16
    )
    assert sp.expand(sp.discriminant(W, m) + 4 * W_discriminant_core) == 0
    W_core_shift = nonnegative_shift(W_discriminant_core, k, 8)
    assert sp.LC(sp.Poly(W, m)) == 2 * k - 4

    # f(m+k)-f(m) has nonnegative coefficients.  Its constant and linear
    # coefficients are at least D*k^3 and D*k^2 for k>=10, using
    # Catalan_k-1>=k^3 and Catalan_k>=4k^2 together with the elementary
    # harmonic lower bound sum_{j=k+2}^{2k} 1/j >= (k-1)/(2k).
    assert math.comb(20, 10) // 11 - 1 >= 10 ** 3
    assert math.comb(20, 10) // 11 >= 4 * 10 ** 2
    # The induction multipliers used in the written certificate are positive
    # throughout k>=10, as witnessed coefficientwise after k=t+10.
    catalan_induction_shifts = {
        "cubic_bound": nonnegative_shift(
            2 * k ** 3 - 3 * k ** 2 - 3 * k + 1, k, 10
        ),
        "quadratic_bound": nonnegative_shift(
            2 * k ** 2 - 2 * k - 1, k, 10
        ),
        "harmonic_remainder": nonnegative_shift(
            k ** 2 - 3 * k + 1, k, 10
        ),
    }

    Wlower = sp.expand((k ** 3 + k ** 2 * m) * CAB - CDB)
    w = [sp.expand(sp.Poly(Wlower, m).coeff_monomial(m ** degree)) for degree in range(6)]
    expected_w = [
        (k + 1) ** 3 * (
            k ** 9 - 7 * k ** 8 + 11 * k ** 7 + 5 * k ** 6
            - 4 * k ** 5 - 10 * k ** 4 - 2 * k ** 2 - 2 * k - 4
        ),
        (k + 1) ** 2 * (
            3 * k ** 9 - 22 * k ** 8 + 30 * k ** 7 + 40 * k ** 6
            - 15 * k ** 5 - 50 * k ** 4 - 4 * k ** 3
            - 8 * k ** 2 - 30 * k - 24
        ),
        (k + 1) * (
            3 * k ** 9 - 25 * k ** 8 + 31 * k ** 7 + 85 * k ** 6
            - 15 * k ** 5 - 90 * k ** 4 - 24 * k ** 3
            - 28 * k ** 2 - 85 * k - 56
        ),
        (k + 1) * (
            k ** 8 - 13 * k ** 7 + 31 * k ** 6 + 43 * k ** 5
            - 43 * k ** 4 - 35 * k ** 3 - 3 * k ** 2 - 47 * k - 58
        ),
        -2 * (k + 1) * (
            k ** 6 - 6 * k ** 5 - 3 * k ** 4 + 10 * k ** 3
            - k ** 2 + 4 * k + 13
        ),
        2 * (k + 1) ** 2 * (k ** 3 - 2 * k ** 2 + 2 * k - 2),
    ]
    assert all(sp.expand(left - right) == 0 for left, right in zip(w, expected_w))
    shifted_positive_w = {
        str(index): nonnegative_shift(w[index], k, 10)
        for index in (0, 1, 2, 3, 5)
    }

    discriminant_reserve = sp.factor(4 * w[3] * w[5] - w[4] ** 2)
    R = (
        k ** 12 - 16 * k ** 11 + 58 * k ** 10 - 32 * k ** 9
        - 63 * k ** 8 + 108 * k ** 7 - 144 * k ** 6
        - 60 * k ** 5 + 147 * k ** 4 + 4 * k ** 3
        + 22 * k ** 2 + 84 * k + 63
    )
    assert discriminant_reserve == 4 * (k + 1) ** 2 * R
    R_shift_12 = nonnegative_shift(R, k, 12)

    # k=10,11 are the only cases not covered by the quadratic discriminant.
    # Wlower is nevertheless increasing: the following two exact projective
    # substitutions cover [0,L] and [L,infinity), with positive coefficients.
    finite_derivative_certificates = {}
    for rank, split in ((10, 34), (11, 47)):
        specialized = sp.Poly(Wlower.subs(k, rank), m)
        assert specialized.eval(0) > 0
        derivative = sp.diff(specialized.as_expr(), m)
        content, primitive = sp.Poly(derivative, m).primitive()
        assert content > 0
        primitive_expression = primitive.as_expr()
        low = sp.cancel(
            (1 + t) ** 4
            * primitive_expression.subs(m, sp.Integer(split) * t / (1 + t))
        )
        high = sp.expand(primitive_expression.subs(m, sp.Integer(split) + t))
        low_coefficients = positive_coefficients(low, t)
        high_coefficients = positive_coefficients(high, t)
        finite_derivative_certificates[str(rank)] = {
            "split": split,
            "derivative_positive_content": int(content),
            "low_projective_coefficients_descending": low_coefficients,
            "high_shift_coefficients_descending": high_coefficients,
            "Wlower_at_zero": int(specialized.eval(0)),
        }

    direct_rows = []
    for rank in (8, 9):
        direct = direct_boundary(rank, m)
        divisor = (rank - 2) * (rank + 1) * (m + rank + 1)
        quotient = sp.cancel(direct / divisor)
        assert sp.denom(quotient) == 1
        coefficients = positive_coefficients(quotient, m)
        direct_rows.append({
            "rank": rank,
            "factor": f"{(rank - 2) * (rank + 1)}*(m+{rank + 1})",
            "quotient_degree": int(sp.degree(quotient, m)),
            "quotient_coefficients_descending": coefficients,
            "minimum_quotient_coefficient": min(coefficients),
        })

    payload = {
        "schema": "uniform-low-high-minimal-zero-slack-boundary-theorem-exact-root-v1",
        "status": "PASS_EXACT_ALL_RANK_MINIMAL_ZERO_SLACK_STRONG_BOUNDARY",
        "theorem": {
            "rank_range": "every integer k >= 8",
            "parameter_range": "every real m >= 0",
            "left_ratios": "(k+1,k-1,k-2,...,1,0)",
            "right_ratios": "(m+k+1,m+k-1,m+k-2,...,m+1,m)",
            "claim": "(k-2)M(c)+B(c,v)>0",
        },
        "symbolic_rational_identity": {
            "verified": True,
            "denominator": "2*k*(k+m)^2*(m+2)*(m+3)",
            "numerator_terms": ["A*D*CAD", "A*B*CAB", "-D*B*CDB", "-B^2*CBB"],
        },
        "sign_certificate": {
            "CAB_minus_CBB_quadratic_discriminant_core_shift8_coefficients_descending": W_core_shift,
            "catalan_induction_shift_coefficients_descending": catalan_induction_shifts,
            "Wlower_positive_coefficient_shifts_at_k10": shifted_positive_w,
            "tail_discriminant_core_shift12_coefficients_descending": R_shift_12,
            "finite_k10_k11_derivative_certificates": finite_derivative_certificates,
            "direct_k8_k9": direct_rows,
        },
        "scope": (
            "This is a rigorous all-rank theorem for the minimal zero-slack "
            "one-parameter boundary slice of the abstract low/high strong "
            "auxiliary. It is not by itself a proof of Erdos Problem 993."
        ),
        "source_sha256": sha256(Path(__file__)),
    }
    temporary = OUTPUT.with_suffix(OUTPUT.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, OUTPUT)
    print(payload["status"], flush=True)
    print("REPORT", sha256(OUTPUT), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
