#!/usr/bin/env python3
"""One exact |F|=m shard for the Delta2 new-leaf literal root tail.

The component-to-root partitions are generated by a canonical block-state DP,
avoiding Bell-number materialization while preserving every deletion-jet and
partition quotient exactly.  Run separately for m=11,...,15.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
from pathlib import Path

import networkx as nx
import sympy as sp

import analyze_rank8_delta03_arbitrary_leaf_extension_q_corner_agent as corner
import analyze_rank8_delta03_arbitrary_leaf_extension_symbolic_agent as leaf
import prove_rank8_delta0_new_leaf_mask3_small_m_2495_literal_attachment_agent as literal
import prove_rank8_delta2_new_leaf_m0_6_literal_empty_root_tail_agent as low
import prove_rank8_forest16_f5_f6_ratio_agent as forest


HERE = Path(__file__).resolve().parent
EXPECTED = {
    "prove_rank8_delta2_new_leaf_m0_6_literal_empty_root_tail_agent.py": "6B533FFBCF504FFB3CAB5BF1B08FF6BB1BC70B8AB773DF3C4C0A4751C14BC2E1",
    "analyze_rank8_delta03_arbitrary_leaf_extension_q_corner_agent.py": "D3A17F85CC3E31A229BED7E16201FCDA031E8C9D63ED5568AF0F90D0A66DBBBB",
    "prove_rank8_delta0_new_leaf_mask3_small_m_2495_literal_attachment_agent.py": "23ABB3E543DD19CE9B0E4963675A89099F4A111692049FCC3D971B1BA54EC7CB",
    "prove_rank8_forest16_f5_f6_ratio_agent.py": "D2D9E23E930904B3C55EF5BB2B75D5CBB5D389A39B0A0F1AE7CA1B3A61BFDB21",
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def build_records(max_order: int):
    records = {}
    counts = [0]
    peak = forest.gate()
    for order in range(1, max_order + 1):
        trees = [nx.empty_graph(1)] if order == 1 else list(nx.nonisomorphic_trees(order))
        counts.append(len(trees))
        records[order] = tuple(
            literal.TreeRecord(order, index, forest.tree_jet(tree), literal.deletion_jet_set(tree))
            for index, tree in enumerate(trees)
        )
        peak = max(peak, forest.gate())
    assert counts == literal.EXPECTED_TREE_COUNTS[: max_order + 1]
    return records, peak


def canonical_blocks(blocks):
    return tuple(sorted(blocks))


def quotient_states_dp(components):
    """All (nonempty-root count, D-core jet) quotients by unlabeled-block DP."""
    states = {()}
    peak_states = 1
    transitions = 0
    for component in components:
        next_states = set()
        for blocks in states:
            distinct_blocks = tuple(dict.fromkeys(blocks))
            for deletion in component.deletion_jets:
                next_states.add(canonical_blocks(blocks + ((component.jet, deletion),)))
                transitions += 1
                for block in distinct_blocks:
                    index = blocks.index(block)
                    merged = (
                        forest.multiply(block[0], component.jet),
                        forest.multiply(block[1], deletion),
                    )
                    updated = blocks[:index] + (merged,) + blocks[index + 1 :]
                    next_states.add(canonical_blocks(updated))
                    transitions += 1
        states = next_states
        peak_states = max(peak_states, len(states))
        forest.gate()
    quotients = set()
    for blocks in states:
        product = (1, 0, 0, 0, 0, 0, 0)
        for excluded, deleted in blocks:
            product = forest.multiply(product, literal.add(excluded, literal.shift(deleted)))
        quotients.add((len(blocks), product))
    return quotients, peak_states, transitions


def validate_block_dp(records):
    forests = quotients = 0
    for total in range(0, 7):
        component_range = (0,) if total == 0 else range(1, total + 1)
        for component_count in component_range:
            for components in literal.forest_types(records, total, component_count):
                expected = set(literal.nonempty_root_quotients(components))
                observed, _, _ = quotient_states_dp(components)
                assert observed == expected
                forests += 1
                quotients += len(observed)
    assert (forests, quotients) == (43, 205)
    return {"forest_types": forests, "quotient_cases": quotients}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--m", type=int, choices=range(11, 16), required=True)
    args = parser.parse_args()
    m = args.m
    output = HERE / f"rank8_delta2_new_leaf_m{m}_literal_empty_root_tail_exact_agent_20260823.json"
    hashes = {name: sha256(HERE / name) for name in EXPECTED}
    assert hashes == EXPECTED

    base, metadata = corner.new_leaf_corner(2, 3)
    assert metadata["endpoint_mask"] == 3
    generators = (leaf.d[3], leaf.d[4], leaf.d[5], leaf.d[6], leaf.f[3], leaf.f[4], leaf.f[5], leaf.f[6])
    polynomial = sp.Poly(base, *generators)
    terms = polynomial.terms()
    serial = json.dumps(
        {
            "generators": [str(value) for value in generators],
            "terms": [[list(monomial), str(coefficient)] for monomial, coefficient in terms],
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode()
    assert hashlib.sha256(serial).hexdigest().upper() == "C61B3F468548F9400E60C1604F05FAD1A2448B76A47C33A4BD140DFE12754FAE"
    degree = max(
        3 * monomial[0] + 4 * monomial[1] + 5 * monomial[2] + 6 * monomial[3]
        for monomial, _ in terms
    )
    assert degree == 52

    records, peak = build_records(m)
    dp_self_test = validate_block_dp(records)
    totals = {
        "forest_types": 0,
        "quotient_cases": 0,
        "negative_values_at_minimum_order": 0,
        "negative_forward_differences": 0,
        "canonical_block_states_peak": 0,
        "block_dp_transitions": 0,
    }
    component_rows = []
    fingerprint = {"xor": 0, "sum": 0, "sum_squares": 0}
    first_obstruction = None
    complete = True
    for component_count in range(1, m + 1):
        row = {
            "components": component_count,
            "forest_types": 0,
            "quotient_cases": 0,
            "negative_values_at_minimum_order": 0,
            "negative_forward_differences": 0,
            "canonical_block_states_peak": 0,
            "block_dp_transitions": 0,
            "minimum_value": None,
            "minimum_forward_difference": None,
        }
        for components in literal.forest_types(records, m, component_count):
            row["forest_types"] += 1
            totals["forest_types"] += 1
            fjet = literal.product_jets(record.jet for record in components)
            quotients, state_peak, transitions = quotient_states_dp(components)
            row["canonical_block_states_peak"] = max(row["canonical_block_states_peak"], state_peak)
            totals["canonical_block_states_peak"] = max(totals["canonical_block_states_peak"], state_peak)
            row["block_dp_transitions"] += transitions
            totals["block_dp_transitions"] += transitions
            for nonempty_roots, nonempty_jet in sorted(quotients):
                minimum_total_roots = max(26 - m, nonempty_roots)
                minimum_empty = minimum_total_roots - nonempty_roots
                values = [
                    low.evaluate_terms(terms, low.empty_extension(nonempty_jet, minimum_empty + t), fjet)
                    for t in range(degree + 1)
                ]
                differences = low.forward_differences(values)
                negative_value = values[0] < 0
                negative_differences = sum(value < 0 for value in differences)
                row["quotient_cases"] += 1
                totals["quotient_cases"] += 1
                row["negative_values_at_minimum_order"] += int(negative_value)
                totals["negative_values_at_minimum_order"] += int(negative_value)
                row["negative_forward_differences"] += negative_differences
                totals["negative_forward_differences"] += negative_differences
                row["minimum_value"] = values[0] if row["minimum_value"] is None else min(row["minimum_value"], values[0])
                local_min = min(differences)
                row["minimum_forward_difference"] = local_min if row["minimum_forward_difference"] is None else min(row["minimum_forward_difference"], local_min)
                low.update_fingerprint(
                    fingerprint,
                    [
                        m,
                        component_count,
                        list(fjet),
                        nonempty_roots,
                        list(nonempty_jet),
                        minimum_total_roots,
                        minimum_empty,
                        str(values[0]),
                        [str(value) for value in differences],
                    ],
                )
                if negative_value or negative_differences:
                    first_obstruction = {
                        "m": m,
                        "component_count": component_count,
                        "component_tree_order_and_networkx_index": [
                            [record.order, record.index] for record in components
                        ],
                        "fjet": list(fjet),
                        "nonempty_roots": nonempty_roots,
                        "nonempty_jet": list(nonempty_jet),
                        "minimum_total_roots": minimum_total_roots,
                        "minimum_empty_roots": minimum_empty,
                        "minimum_value": str(values[0]),
                        "negative_difference_ranks": [
                            rank for rank, value in enumerate(differences) if value < 0
                        ],
                    }
                    complete = False
                    break
            if not complete:
                break
            peak = max(peak, forest.gate())
        component_rows.append(row)
        print(
            "M", m,
            "C", component_count,
            "FORESTS", row["forest_types"],
            "QUOTIENTS", row["quotient_cases"],
            "STATE_PEAK", row["canonical_block_states_peak"],
            "NEG", row["negative_values_at_minimum_order"], row["negative_forward_differences"],
            flush=True,
        )
        gc.collect()
        peak = max(peak, forest.gate())
        if not complete:
            break

    status = (
        f"PASS_EXACT_DELTA2_NEW_LEAF_M{m}_LITERAL_EMPTY_ROOT_ALL_ORDER_TAIL"
        if complete
        else f"OPEN_EXACT_M{m}_LITERAL_TAIL_FIRST_OBSTRUCTION_NO_COUNTEREXAMPLE_CLAIM"
    )
    payload = {
        "schema": "rank8-delta2-new-leaf-m11-15-literal-tail-shard-v1",
        "status": status,
        "scope": f"Delta2 new-leaf Q7(C)-upper/Q6(D)-upper endpoint corner, source n>=27, |F|={m}",
        "structural_exhaustion": "Canonical unlabeled block-state DP enumerates every forest F, deletion jet, and component-to-nonempty-root partition without materializing all set partitions. Remaining roots are isolated in D.",
        "tail_certificate": "For each literal quotient, exact forward differences from its first allowed source order expand the entire remaining empty-root tail in binomial(t,k).",
        "minimum_root_rule": "For c nonempty roots use r_min=max(26-m,c), so n=m+r+1>=27 and every partition is included at its first realizable order.",
        "degree_in_empty_roots": degree,
        "canonical_block_dp_self_test_m0_6": dp_self_test,
        "coverage_complete": complete,
        "component_rows": component_rows,
        "counts": totals,
        "first_obstruction": first_obstruction,
        "canonical_quotient_fingerprint_mod_2_256": {
            key: f"{value:064X}" for key, value in fingerprint.items()
        },
        "resources": {"abort_private_bytes": forest.ABORT_BYTES},
        "input_sha256": hashes,
        "proof_boundary": f"A PASS closes only this endpoint corner for |F|={m}. The full Delta2 new-leaf gate and every broader theorem remain open. A forward-difference obstruction alone is not a graph counterexample.",
    }
    output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(status)
    print("FORESTS", totals["forest_types"], "QUOTIENTS", totals["quotient_cases"])
    print("NEG_VALUES", totals["negative_values_at_minimum_order"], "NEG_DIFFS", totals["negative_forward_differences"])
    print("PEAK_MIB", round(peak / 1024**2, 2))
    print("SOURCE", sha256(Path(__file__)))
    print("REPORT", sha256(output))


if __name__ == "__main__":
    main()
