// Exact finite certificate for rank-7 terminal-broom residuals on rooted
// free-tree cores. Free trees use the WROM generator; all arithmetic is i128.

#[derive(Clone, Copy)]
struct State { excluded: [i128; 9], included: [i128; 9] }
fn one()->[i128;9]{let mut a=[0;9];a[0]=1;a}
fn x()->[i128;9]{let mut a=[0;9];a[1]=1;a}
fn add(a:[i128;9],b:[i128;9])->[i128;9]{let mut z=[0;9];for j in 0..9{z[j]=a[j]+b[j]}z}
fn mul(a:[i128;9],b:[i128;9])->[i128;9]{let mut z=[0;9];for i in 0..9{for j in 0..(9-i){z[i+j]+=a[i]*b[j]}}z}
fn split_tree(layout:&[usize])->(Vec<usize>,Vec<usize>){let mut seen=false;let mut split=layout.len();for(i,l)in layout.iter().enumerate(){if *l==1{if seen{split=i;break}seen=true}}let left=layout[1..split].iter().map(|l|l-1).collect();let mut rest=vec![0];rest.extend_from_slice(&layout[split..]);(left,rest)}
fn next_rooted(pre:&[usize], specified:Option<usize>)->Option<Vec<usize>>{let p=match specified{Some(v)=>v,None=>{let mut v=pre.len()-1;while pre[v]==1{v-=1}v}};if p==0{return None}let mut q=p-1;while pre[q]!=pre[p]-1{q-=1}let mut out=pre.to_vec();for i in p..out.len(){out[i]=out[i-p+q]}Some(out)}
fn next_tree(c:&[usize])->Option<Vec<usize>>{let(left,rest)=split_tree(c);let lh=*left.iter().max().unwrap();let rh=*rest.iter().max().unwrap();let valid=rh>lh||(rh==lh&&(left.len()<rest.len()||(left.len()==rest.len()&&left<=rest)));if valid{return Some(c.to_vec())}let p=left.len();let mut out=next_rooted(c,Some(p))?;if c[p]>2{let(nl,_)=split_tree(&out);let h=*nl.iter().max().unwrap();let len=h+1;let start=out.len()-len;for k in 0..len{out[start+k]=k+1}}Some(out)}
fn adjacency(layout:&[usize])->Vec<Vec<usize>>{let n=layout.len();let mut a:Vec<Vec<usize>>=vec![Vec::new();n];let mut stack:Vec<usize>=Vec::new();for i in 0..n{let level=layout[i];if let Some(&last)=stack.last(){let mut p=last;while layout[p]>=level{stack.pop();p=*stack.last().unwrap()}a[i].push(p);a[p].push(i)}stack.push(i)}a}
fn directed(v:usize,p:usize,a:&[Vec<usize>],memo:&mut[Option<State>])->State{let n=a.len();let key=v*n+p;if let Some(s)=memo[key]{return s}let mut ex=one();let mut inc=x();for &u in &a[v]{if u==p{continue}let s=directed(u,v,a,memo);ex=mul(ex,add(s.excluded,s.included));inc=mul(inc,s.excluded)}let s=State{excluded:ex,included:inc};memo[key]=Some(s);s}
fn root(v:usize,a:&[Vec<usize>],memo:&mut[Option<State>])->State{let mut ex=one();let mut inc=x();for &u in &a[v]{let s=directed(u,v,a,memo);ex=mul(ex,add(s.excluded,s.included));inc=mul(inc,s.excluded)}State{excluded:ex,included:inc}}
fn choose(n:usize,k:usize)->i128{if k>n{return 0}let mut v=1i128;for j in 0..k{v=v*(n-j)as i128/(j+1)as i128}v}
fn smooth(c:[i128;9],r:usize,t:usize)->i128{let mut v=0;for l in 0..=r.min(t){v+=choose(t,l)*c[r-l]}v}
fn residual(c:[i128;9],h:[i128;9],t:usize)->i128{let p6=smooth(c,6,t)+h[5];let p7=smooth(c,7,t)+h[6];let mut p8o=0;for l in 1..=8.min(t){p8o+=choose(t,l)*c[8-l]}7*c[6]*h[5]*(14*p7*p7-p6*p7-16*p6*p8o)-7*h[5]*p6*(14*c[7]*c[7]-c[6]*c[7])-8*c[6]*p6*(12*h[6]*h[6]-h[5]*h[6])}
fn main(){let args:Vec<String>=std::env::args().collect();let max_n:usize=args.get(1).and_then(|s|s.parse().ok()).unwrap_or(18);let expected:[u64;19]=[0,1,1,1,2,3,6,11,23,47,106,235,551,1301,3159,7741,19320,48629,123867];for n in 1..=max_n{let mut layout:Option<Vec<usize>>=if n==1{Some(vec![0])}else{Some((0..=n/2).chain(1..((n+1)/2)).collect())};let mut trees=0u64;let mut roots=0u64;let mut mins=[i128::MAX;14];while let Some(cand)=layout{layout=if n==1{None}else{next_tree(&cand)};let valid=if n==1{cand}else{match layout.clone(){Some(v)=>v,None=>break}};let a=adjacency(&valid);let mut memo=vec![None;n*n];let s=root(0,&a,&mut memo);let core=add(s.excluded,s.included);trees+=1;for v in 0..n{let del=root(v,&a,&mut memo).excluded;if core[6]>0&&del[5]>0{let mut vals:Vec<i128>=(1..=15).map(|t|residual(core,del,t)).collect();mins[0]=mins[0].min(vals[0]);for d in 1..14{vals=vals.windows(2).map(|p|p[1]-p[0]).collect();mins[d]=mins[d].min(vals[0])}}roots+=1}if n>1{layout=next_rooted(&valid,None)}}assert_eq!(trees,expected[n]);assert_eq!(roots,expected[n]*n as u64);let negative:Vec<usize>=mins.iter().enumerate().filter_map(|(j,v)|if *v<0{Some(j)}else{None}).collect();if n>=13{assert!(negative.is_empty())}if n>=7{assert!(mins[1..].iter().all(|v|*v>=0))}println!("core_n={} trees={} roots={} minima={:?} negative={:?}",n,trees,roots,mins,negative)}println!("PASS_EXACT_RANK7_TERMINAL_BROOM_ALL_ROOTED_CORES_THROUGH_N{}",max_n)
}
