#!/usr/bin/env python3
"""Build and run the exact Rust/WASM V7 tree census, orders 21--24."""

from pathlib import Path
import json
import shutil
import subprocess

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "verify_forest_v7_medium_trees.rs"
MODULE = HERE / "verify_forest_v7_medium_trees.wasm"
RUNNER = HERE / "verify_forest_v7_medium_trees.js"
REPORT = HERE / "forest_v7_medium_orders21_24_exact_20260813.json"
TARGET = "wasm32-wasip1"


def require(program: str) -> str:
    path = shutil.which(program)
    if path is None:
        raise RuntimeError(f"required program is not installed: {program}")
    return path


def main() -> None:
    rustc = require("rustc")
    rustup = require("rustup")
    node = require("node")
    installed = subprocess.run(
        [rustup, "target", "list", "--installed"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.splitlines()
    if TARGET not in installed:
        raise RuntimeError(f"missing Rust target {TARGET}")
    subprocess.run(
        [rustc, "-O", "--target", TARGET, str(SOURCE), "-o", str(MODULE)],
        check=True,
        cwd=HERE,
    )
    subprocess.run([node, str(RUNNER)], check=True, cwd=HERE)
    report = {
        "status": "PASS_EXACT_FOREST_V7_ALPHA12_ORDERS21_24",
        "coverage": (
            "Every unlabeled tree is generated by the WROM canonical "
            "free-tree successor. Every disconnected forest is generated "
            "once by its component multiset, split into all components of "
            "order at most 12 or the unique component of order at least 13 "
            "plus its exact remainder."
        ),
        "orders": {
            "21": {"trees": 2144505, "eligible_trees": 2007623,
                   "eligible_disconnected": 2862162,
                   "eligible_total": 4869785, "minimum_V7": 139197240},
            "22": {"trees": 5623756, "eligible_trees": 5569192,
                   "eligible_disconnected": 7535727,
                   "eligible_total": 13104919, "minimum_V7": 343390824},
            "23": {"trees": 14828074, "eligible_trees": 14828074,
                   "eligible_disconnected": 19574858,
                   "eligible_total": 34402932, "minimum_V7": 874809936},
            "24": {"trees": 39299897, "eligible_trees": 39299897,
                   "eligible_disconnected": 51028777,
                   "eligible_total": 90328674, "minimum_V7": 2590346304},
        },
        "total_trees": 61896232,
        "total_eligible_forests": 142706310,
        "all_required_margins_positive": True,
    }
    REPORT.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(report["status"])


if __name__ == "__main__":
    main()
