// Exact finite certificate for rank-6 sibling-isolate payments on
// rooted tree cores of orders 1 through 17.
//
// Free trees are generated by the WROM level-sequence algorithm.
// Independence polynomials at every root are obtained with rerooted
// messages.  All payment and forward-difference arithmetic is i128.

#[derive(Clone, Copy)]
struct State {
    excluded: [i128; 8],
    included: [i128; 8],
}

fn one() -> [i128; 8] {
    let mut out = [0; 8];
    out[0] = 1;
    out
}

fn x() -> [i128; 8] {
    let mut out = [0; 8];
    out[1] = 1;
    out
}

fn add(left: [i128; 8], right: [i128; 8]) -> [i128; 8] {
    let mut out = [0; 8];
    for rank in 0..=7 {
        out[rank] = left[rank] + right[rank];
    }
    out
}

fn multiply(left: [i128; 8], right: [i128; 8]) -> [i128; 8] {
    let mut out = [0; 8];
    for first in 0..=7 {
        for second in 0..=(7 - first) {
            out[first + second] += left[first] * right[second];
        }
    }
    out
}

fn split_tree(layout: &[usize]) -> (Vec<usize>, Vec<usize>) {
    let mut one_found = false;
    let mut split = layout.len();
    for (index, level) in layout.iter().enumerate() {
        if *level == 1 {
            if one_found {
                split = index;
                break;
            }
            one_found = true;
        }
    }
    let left = layout[1..split]
        .iter()
        .map(|level| level - 1)
        .collect();
    let mut rest = vec![0];
    rest.extend_from_slice(&layout[split..]);
    (left, rest)
}

fn next_rooted_tree_clean(
    predecessor: &[usize],
    specified_p: Option<usize>,
) -> Option<Vec<usize>> {
    let p = match specified_p {
        Some(value) => value,
        None => {
            let mut value = predecessor.len() - 1;
            while predecessor[value] == 1 {
                value -= 1;
            }
            value
        }
    };
    if p == 0 {
        return None;
    }
    let mut q = p - 1;
    while predecessor[q] != predecessor[p] - 1 {
        q -= 1;
    }
    let mut result = predecessor.to_vec();
    for index in p..result.len() {
        result[index] = result[index - p + q];
    }
    Some(result)
}

fn next_tree(candidate: &[usize]) -> Option<Vec<usize>> {
    let (left, rest) = split_tree(candidate);
    let left_height = *left.iter().max().unwrap();
    let rest_height = *rest.iter().max().unwrap();
    let mut valid = rest_height >= left_height;
    if valid && rest_height == left_height {
        if left.len() > rest.len() {
            valid = false;
        } else if left.len() == rest.len() && left > rest {
            valid = false;
        }
    }
    if valid {
        return Some(candidate.to_vec());
    }
    let p = left.len();
    let mut new_candidate = next_rooted_tree_clean(candidate, Some(p))?;
    if candidate[p] > 2 {
        let (new_left, _) = split_tree(&new_candidate);
        let new_left_height = *new_left.iter().max().unwrap();
        let suffix_length = new_left_height + 1;
        let start = new_candidate.len() - suffix_length;
        for offset in 0..suffix_length {
            new_candidate[start + offset] = offset + 1;
        }
    }
    Some(new_candidate)
}

fn layout_to_adjacency(layout: &[usize]) -> Vec<Vec<usize>> {
    let order = layout.len();
    let mut adjacency = vec![Vec::new(); order];
    let mut stack: Vec<usize> = Vec::new();
    for index in 0..order {
        let level = layout[index];
        if let Some(&last) = stack.last() {
            let mut parent = last;
            while layout[parent] >= level {
                stack.pop();
                parent = *stack.last().unwrap();
            }
            adjacency[index].push(parent);
            adjacency[parent].push(index);
        }
        stack.push(index);
    }
    adjacency
}

fn directed_state(
    vertex: usize,
    parent: usize,
    adjacency: &[Vec<usize>],
    memo: &mut [Option<State>],
) -> State {
    let order = adjacency.len();
    let key = vertex * order + parent;
    if let Some(value) = memo[key] {
        return value;
    }
    let mut excluded = one();
    let mut included = x();
    for &neighbor in &adjacency[vertex] {
        if neighbor == parent {
            continue;
        }
        let child = directed_state(neighbor, vertex, adjacency, memo);
        excluded = multiply(
            excluded,
            add(child.excluded, child.included),
        );
        included = multiply(included, child.excluded);
    }
    let value = State { excluded, included };
    memo[key] = Some(value);
    value
}

fn root_state(
    root: usize,
    adjacency: &[Vec<usize>],
    memo: &mut [Option<State>],
) -> State {
    let mut excluded = one();
    let mut included = x();
    for &neighbor in &adjacency[root] {
        let child = directed_state(neighbor, root, adjacency, memo);
        excluded = multiply(
            excluded,
            add(child.excluded, child.included),
        );
        included = multiply(included, child.excluded);
    }
    State { excluded, included }
}

fn choose(n: usize, k: usize) -> i128 {
    if k > n {
        return 0;
    }
    let mut value = 1i128;
    for j in 0..k {
        value = value * (n - j) as i128 / (j + 1) as i128;
    }
    value
}

fn smoothed(core: [i128; 8], rank: usize, smoothing: usize) -> i128 {
    let mut value = 0;
    for offset in 0..=rank.min(smoothing) {
        value += choose(smoothing, offset) * core[rank - offset];
    }
    value
}

fn payment(a: i128, b: i128, d: i128, e: i128, f: i128) -> i128 {
    let previous = 10 * e * e - d * e - 12 * d * f;
    7 * a * (a + d) * previous
        + a * d * e * (a + d + 2 * e)
        + 2 * a * a * e * e
        - 72 * (b * d - a * e).pow(2)
}

fn payment_values(
    core: [i128; 8],
    deleted: [i128; 8],
) -> [i128; 21] {
    let h = deleted[4];
    let k = deleted[5];
    let mut values = [0i128; 21];
    for smoothing in 0..=20 {
        let d = smoothed(core, 4, smoothing);
        let e = smoothed(core, 5, smoothing);
        let f = smoothed(core, 6, smoothing);
        values[smoothing] = payment(e + h, f + k, d, e, f);
    }
    values
}

fn bundle_residual(
    core: [i128; 8],
    deleted: [i128; 8],
    leaves: usize,
) -> i128 {
    let c5 = core[5];
    let c6 = core[6];
    let h4 = deleted[4];
    let h5 = deleted[5];
    let p5 = smoothed(core, 5, leaves) + h4;
    let p6 = smoothed(core, 6, leaves) + h5;
    let mut p7_without_boundaries = 0i128;
    for offset in 1..=7.min(leaves) {
        p7_without_boundaries +=
            choose(leaves, offset) * core[7 - offset];
    }
    6 * c5 * h4
        * (
            12 * p6 * p6
                - p5 * p6
                - 14 * p5 * p7_without_boundaries
        )
        - 6 * h4 * p5 * (12 * c6 * c6 - c5 * c6)
        - 7 * c5 * p5 * (10 * h5 * h5 - h4 * h5)
}

fn bundle_q6(
    core: [i128; 8],
    deleted: [i128; 8],
    leaves: usize,
) -> i128 {
    let p5 = smoothed(core, 5, leaves) + deleted[4];
    let p6 = smoothed(core, 6, leaves) + deleted[5];
    let p7 = smoothed(core, 7, leaves) + deleted[6];
    12 * p6 * p6 - p5 * p6 - 14 * p5 * p7
}

fn update_minimum(target: &mut Option<i128>, value: i128) {
    if target.is_none() || value < target.unwrap() {
        *target = Some(value);
    }
}

fn verify_order(order: usize, expected_trees: u64) {
    if order == 1 {
        let core = [1, 1, 0, 0, 0, 0, 0, 0];
        audit_root(
            order,
            core,
            [1, 0, 0, 0, 0, 0, 0, 0],
            1,
            1,
        );
        return;
    }

    let mut layout: Option<Vec<usize>> = Some(
        (0..=(order / 2))
            .chain(1..((order + 1) / 2))
            .collect(),
    );
    let mut tree_count = 0u64;
    let mut rooted_count = 0u64;
    let mut minimum_m1 = None;
    let mut minimum_m2 = None;
    let mut minima_at_zero = [None; 19];
    let mut minima_at_one = [None; 19];
    let mut bundle_minima = [None; 12];

    while let Some(candidate) = layout {
        layout = next_tree(&candidate);
        if let Some(valid_layout) = layout.clone() {
            let adjacency = layout_to_adjacency(&valid_layout);
            let mut memo = vec![None; order * order];
            let first = root_state(0, &adjacency, &mut memo);
            let core = add(first.excluded, first.included);
            tree_count += 1;
            for root in 0..order {
                let deleted = root_state(root, &adjacency, &mut memo).excluded;
                let mut values = payment_values(core, deleted).to_vec();
                update_minimum(&mut minimum_m1, values[1]);
                update_minimum(&mut minimum_m2, values[2]);
                for difference in 0..19 {
                    values = values
                        .windows(2)
                        .map(|pair| pair[1] - pair[0])
                        .collect();
                    update_minimum(
                        &mut minima_at_zero[difference],
                        values[0],
                    );
                    update_minimum(
                        &mut minima_at_one[difference],
                        values[1],
                    );
                }
                if core[5] > 0 && deleted[4] > 0 {
                    let mut residuals: Vec<i128> = (1..=13)
                        .map(|leaves| {
                            bundle_residual(core, deleted, leaves)
                        })
                        .collect();
                    update_minimum(&mut bundle_minima[0], residuals[0]);
                    for difference in 1..12 {
                        residuals = residuals
                            .windows(2)
                            .map(|pair| pair[1] - pair[0])
                            .collect();
                        update_minimum(
                            &mut bundle_minima[difference],
                            residuals[0],
                        );
                    }
                }
                rooted_count += 1;
            }
            layout = next_rooted_tree_clean(&valid_layout, None);
        }
    }
    assert_eq!(tree_count, expected_trees);
    assert_eq!(rooted_count, expected_trees * order as u64);
    let negative_zero: Vec<usize> = minima_at_zero
        .iter()
        .enumerate()
        .filter_map(|(j, value)| {
            if value.unwrap() < 0 { Some(j + 1) } else { None }
        })
        .collect();
    let negative_one: Vec<usize> = minima_at_one
        .iter()
        .enumerate()
        .filter_map(|(j, value)| {
            if value.unwrap() < 0 { Some(j + 1) } else { None }
        })
        .collect();
    assert!(
        negative_one.is_empty(),
        "negative shifted Newton coefficient at core order {}",
        order
    );
    if order == 7 {
        assert_eq!(minimum_m1, Some(-288));
        assert!(minimum_m2.unwrap() >= 0);
        assert_eq!(negative_zero, vec![1]);
    } else {
        assert!(minimum_m1.unwrap() >= 0);
        assert!(negative_zero.is_empty());
    }
    if order >= 11 {
        assert!(
            bundle_minima
                .iter()
                .all(|value| value.unwrap() >= 0),
            "negative terminal-bundle Newton coefficient at core order {}",
            order
        );
    }
    println!(
        "core_n={} trees={} rooted={} min_M1={} min_M2={} \
         min_Delta1_M0={} min_Delta1_M1={} neg_at_0={:?} neg_at_1={:?}",
        order,
        tree_count,
        rooted_count,
        minimum_m1.unwrap(),
        minimum_m2.unwrap(),
        minima_at_zero[0].unwrap(),
        minima_at_one[0].unwrap(),
        negative_zero,
        negative_one,
    );
    if bundle_minima[0].is_some() {
        println!(
            "  bundle min_R1={} min_DeltaR1={} negative={:?}",
            bundle_minima[0].unwrap(),
            bundle_minima[1].unwrap(),
            bundle_minima
                .iter()
                .enumerate()
                .filter_map(|(j, value)| {
                    if value.unwrap() < 0 {
                        Some(j)
                    } else {
                        None
                    }
                })
                .collect::<Vec<usize>>(),
        );
    }
}

fn audit_root(
    order: usize,
    core: [i128; 8],
    deleted: [i128; 8],
    trees: u64,
    rooted: u64,
) {
    let mut values = payment_values(core, deleted).to_vec();
    let m1 = values[1];
    let m2 = values[2];
    let mut minima_zero = Vec::new();
    let mut minima_one = Vec::new();
    for _ in 0..19 {
        values = values
            .windows(2)
            .map(|pair| pair[1] - pair[0])
            .collect();
        minima_zero.push(values[0]);
        minima_one.push(values[1]);
    }
    assert!(m1 >= 0);
    assert!(minima_one.iter().all(|value| *value >= 0));
    println!(
        "core_n={} trees={} rooted={} min_M1={} min_M2={} \
         min_Delta1_M0={} min_Delta1_M1={} neg_at_0={:?} neg_at_1={:?}",
        order,
        trees,
        rooted,
        m1,
        m2,
        minima_zero[0],
        minima_one[0],
        Vec::<usize>::new(),
        Vec::<usize>::new(),
    );
}

fn verify_boundary_order_sharded(
    order: usize,
    expected_trees: u64,
    shard: Option<(u64, u64)>,
) {
    let mut layout: Option<Vec<usize>> = Some(
        (0..=(order / 2))
            .chain(1..((order + 1) / 2))
            .collect(),
    );
    let mut tree_count = 0u64;
    let mut generated_count = 0u64;
    let mut rooted_count = 0u64;
    let mut minimum_r1 = None;
    let mut minimum_delta1 = None;

    while let Some(candidate) = layout {
        layout = next_tree(&candidate);
        if let Some(valid_layout) = layout.clone() {
            let tree_index = generated_count;
            generated_count += 1;
            let assigned = shard
                .map(|(index, count)| tree_index % count == index)
                .unwrap_or(true);
            if assigned {
                let adjacency = layout_to_adjacency(&valid_layout);
                let mut memo = vec![None; order * order];
                let first = root_state(0, &adjacency, &mut memo);
                let core = add(first.excluded, first.included);
                tree_count += 1;
                for root in 0..order {
                    let deleted =
                        root_state(root, &adjacency, &mut memo).excluded;
                    let r1 = bundle_residual(core, deleted, 1);
                    let r2 = bundle_residual(core, deleted, 2);
                    update_minimum(&mut minimum_r1, r1);
                    update_minimum(&mut minimum_delta1, r2 - r1);
                    rooted_count += 1;
                }
            }
            layout = next_rooted_tree_clean(&valid_layout, None);
        }
    }
    assert_eq!(generated_count, expected_trees);
    let expected_processed = shard
        .map(|(index, count)| {
            assert!(index < count);
            (expected_trees + count - 1 - index) / count
        })
        .unwrap_or(expected_trees);
    assert_eq!(tree_count, expected_processed);
    assert_eq!(rooted_count, expected_processed * order as u64);
    assert!(minimum_r1.unwrap() >= 0);
    assert!(minimum_delta1.unwrap() >= 0);
    println!(
        "boundary core_n={} trees={} rooted={} min_R1={} \
         min_DeltaR1={} shard={:?}",
        order,
        tree_count,
        rooted_count,
        minimum_r1.unwrap(),
        minimum_delta1.unwrap(),
        shard,
    );
}

fn verify_boundary_order(order: usize, expected_trees: u64) {
    verify_boundary_order_sharded(order, expected_trees, None);
}

fn verify_direct_bundle_order(order: usize, expected_trees: u64) {
    if order == 1 {
        let core = [1, 1, 0, 0, 0, 0, 0, 0];
        let deleted = [1, 0, 0, 0, 0, 0, 0, 0];
        let mut values: Vec<i128> = (1..=15)
            .map(|leaves| bundle_q6(core, deleted, leaves))
            .collect();
        let first_three = [values[0], values[1], values[2]];
        let mut minima_at_one = [0i128; 13];
        let mut minima_at_two = [0i128; 13];
        minima_at_one[0] = values[0];
        minima_at_two[0] = values[1];
        for difference in 1..13 {
            values = values
                .windows(2)
                .map(|pair| pair[1] - pair[0])
                .collect();
            minima_at_one[difference] = values[0];
            minima_at_two[difference] = values[1];
        }
        assert!(minima_at_one.iter().all(|value| *value >= 0));
        assert!(minima_at_two.iter().all(|value| *value >= 0));
        println!(
            "direct core_n=1 trees=1 rooted=1 min_Q1={} min_Q2={} \
             min_Q3={} negative_at_1=[] negative_at_2=[]",
            first_three[0],
            first_three[1],
            first_three[2],
        );
        return;
    }
    let mut layout: Option<Vec<usize>> = Some(
        (0..=(order / 2))
            .chain(1..((order + 1) / 2))
            .collect(),
    );
    let mut tree_count = 0u64;
    let mut rooted_count = 0u64;
    let mut minimum_q = [None; 3];
    let mut minima_at_one = [None; 13];
    let mut minima_at_two = [None; 13];

    while let Some(candidate) = layout {
        layout = next_tree(&candidate);
        if let Some(valid_layout) = layout.clone() {
            let adjacency = layout_to_adjacency(&valid_layout);
            let mut memo = vec![None; order * order];
            let first = root_state(0, &adjacency, &mut memo);
            let core = add(first.excluded, first.included);
            tree_count += 1;
            for root in 0..order {
                let deleted = root_state(root, &adjacency, &mut memo).excluded;
                let mut values: Vec<i128> = (1..=15)
                    .map(|leaves| bundle_q6(core, deleted, leaves))
                    .collect();
                for index in 0..3 {
                    update_minimum(&mut minimum_q[index], values[index]);
                }
                update_minimum(&mut minima_at_one[0], values[0]);
                update_minimum(&mut minima_at_two[0], values[1]);
                for difference in 1..13 {
                    values = values
                        .windows(2)
                        .map(|pair| pair[1] - pair[0])
                        .collect();
                    update_minimum(
                        &mut minima_at_one[difference],
                        values[0],
                    );
                    update_minimum(
                        &mut minima_at_two[difference],
                        values[1],
                    );
                }
                rooted_count += 1;
            }
            layout = next_rooted_tree_clean(&valid_layout, None);
        }
    }
    assert_eq!(tree_count, expected_trees);
    assert_eq!(rooted_count, expected_trees * order as u64);
    let negative_at_one: Vec<usize> = minima_at_one
        .iter()
        .enumerate()
        .filter_map(|(j, value)| {
            if value.unwrap() < 0 { Some(j) } else { None }
        })
        .collect();
    let negative_at_two: Vec<usize> = minima_at_two
        .iter()
        .enumerate()
        .filter_map(|(j, value)| {
            if value.unwrap() < 0 { Some(j) } else { None }
        })
        .collect();
    if order <= 6 || order >= 11 {
        assert!(negative_at_one.is_empty());
    } else if order == 7 {
        assert_eq!(negative_at_one, vec![1]);
        assert_eq!(negative_at_two, vec![0]);
        assert!(minimum_q[2].unwrap() >= 0);
    } else {
        assert!((8..=10).contains(&order));
        assert_eq!(negative_at_one, vec![0]);
        assert!(negative_at_two.is_empty());
    }
    println!(
        "direct core_n={} trees={} rooted={} min_Q1={} min_Q2={} \
         min_Q3={} negative_at_1={:?} negative_at_2={:?}",
        order,
        tree_count,
        rooted_count,
        minimum_q[0].unwrap(),
        minimum_q[1].unwrap(),
        minimum_q[2].unwrap(),
        negative_at_one,
        negative_at_two,
    );
}

fn main() {
    let expected = [
        0, 1, 1, 1, 2, 3, 6, 11, 23, 47, 106, 235, 551, 1301,
        3159, 7741, 19320, 48629, 123867, 317955, 823065, 2144505,
        5623756, 14828074,
    ];
    let arguments: Vec<String> = std::env::args().collect();
    if arguments.get(1).map(String::as_str) == Some("boundary21") {
        for order in 18..=21 {
            verify_boundary_order(order, expected[order]);
        }
        println!(
            "rank-6 terminal-bundle boundary through order 21: CERTIFIED"
        );
        return;
    }
    if arguments.get(1).map(String::as_str) == Some("boundary23") {
        for order in 22..=23 {
            verify_boundary_order(order, expected[order]);
        }
        println!(
            "rank-6 terminal-bundle boundary at orders 22--23: CERTIFIED"
        );
        return;
    }
    if arguments.get(1).map(String::as_str)
        == Some("boundary23shard")
    {
        let shard_index = arguments[2].parse::<u64>().unwrap();
        let shard_count = arguments[3].parse::<u64>().unwrap();
        verify_boundary_order_sharded(
            23,
            expected[23],
            Some((shard_index, shard_count)),
        );
        return;
    }
    if arguments.get(1).map(String::as_str) == Some("direct17") {
        for order in 1..=17 {
            verify_direct_bundle_order(order, expected[order]);
        }
        println!(
            "rank-6 direct terminal bundles through core order 17: \
             CERTIFIED"
        );
        return;
    }
    let maximum_order = arguments
        .get(1)
        .map(|value| value.parse::<usize>().unwrap())
        .unwrap_or(17);
    assert!((1..=23).contains(&maximum_order));
    for order in 1..=maximum_order {
        verify_order(order, expected[order]);
    }
    println!(
        "rank-6 terminal payments through core order {}: CERTIFIED",
        maximum_order
    );
}
