/**
 * Scene running order.
 *
 * Each entry is a module exporting `meta` and `build(ctx)`. Durations come
 * from `public/audio/manifest.json` (generated by tools/tts.mjs) so scenes are
 * always long enough for their narration.
 */
import * as crawl from './00-crawl.js';
import * as chase from './01-chase.js';
import * as boarding from './02-boarding.js';
import * as plans from './03-plans.js';
import * as tatooine from './04-tatooine.js';
import * as deathstar from './05-deathstar.js';
import * as trench from './06-trench.js';
import * as medals from './07-medals.js';

export const modules = [crawl, chase, boarding, plans, tatooine, deathstar, trench, medals];
