"""Isbell's 7-colouring of the plane, verified exactly:  CNP <= 7.

Tile the plane with the Voronoi cells of a triangular lattice of spacing s.  Those cells
are regular hexagons of circumradius r = s/sqrt(3).  Identify the lattice with the
Eisenstein integers Z[w], w = exp(i*pi/3), and colour a cell by the residue of its centre
modulo the ideal generated by pi = 1 + 2w, whose norm is 7.  Two cells share a colour iff
their centres differ by an element of that ideal, and every nonzero element of the ideal
has norm at least 7, so distinct same-coloured centres are at least s*sqrt(7) apart.

Two same-coloured points are then either in one cell, at distance at most the diameter 2r,
or in different cells, at distance at least s*sqrt(7) - 2r = r*(sqrt(21) - 2).  Choosing r
with 2r < 1 < r*(sqrt(21) - 2) makes distance exactly 1 impossible.  Both inequalities are
rational once squared, so no floating point enters the proof.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass
from fractions import Fraction

NUM_COLORS = 7

# w = exp(i*pi/3) satisfies w^2 = w - 1, and 3 is a root of t^2 - t + 1 modulo 7, so
# (a, b) -> a + 3b mod 7 is the quotient map Z[w] -> Z[w]/(1 + 2w) = F_7.
_OMEGA_RESIDUE = 3


def lattice_color(a: int, b: int) -> int:
    """Colour of the cell centred at a*u + b*(u rotated by 60 degrees)."""
    return (a + _OMEGA_RESIDUE * b) % NUM_COLORS


def eisenstein_norm(a: int, b: int) -> int:
    """Squared length of a*u + b*w*u in units of |u|^2."""
    return a * a + a * b + b * b


@dataclass
class UpperBoundCertificate:
    circumradius: Fraction
    diameter_squared: Fraction
    min_same_color_center_norm: int
    separation_ok: bool
    diameter_ok: bool
    colors_used: int

    @property
    def valid(self) -> bool:
        return (
            self.diameter_ok
            and self.separation_ok
            and self.min_same_color_center_norm == NUM_COLORS
            and self.colors_used == NUM_COLORS
        )

    def __str__(self) -> str:
        r = self.circumradius
        return (
            f"Isbell 7-colouring with hexagon circumradius r = {r} ({float(r):.4f})\n"
            f"  cell diameter 2r          = {float(2 * r):.6f}  (< 1 required: "
            f"{'ok' if self.diameter_ok else 'FAIL'})\n"
            f"  min same-colour centre gap= sqrt(7)*sqrt(3)*r = {float(r) * math.sqrt(21):.6f}\n"
            f"  min same-colour point gap = r*(sqrt(21)-2)    = "
            f"{float(r) * (math.sqrt(21) - 2):.6f}  (> 1 required: "
            f"{'ok' if self.separation_ok else 'FAIL'})\n"
            f"  colours used              = {self.colors_used}\n"
            f"  shortest vector of the colour sublattice has norm "
            f"{self.min_same_color_center_norm} (must be 7)"
        )


def verify_upper_bound(circumradius: Fraction = Fraction(9, 20), search: int = 40) -> UpperBoundCertificate:
    """Check every ingredient of the 7-colouring argument with exact rational arithmetic."""
    r = Fraction(circumradius)

    # (i) A cell has diameter 2r, so it contains no unit-distance pair iff 4r^2 < 1.
    diameter_squared = 4 * r * r
    diameter_ok = diameter_squared < 1

    # (ii) Distinct same-coloured cells are >= r*(sqrt(21) - 2) apart; require that to
    #      exceed 1.  Squaring the positive inequality sqrt(21)*r > 1 + 2r keeps it rational.
    separation_ok = 21 * r * r > (1 + 2 * r) ** 2

    # (iii) The colour classes are the cosets of a sublattice whose shortest nonzero vector
    #       has squared length 7 (in units of the lattice spacing).
    min_norm = min(
        eisenstein_norm(a, b)
        for a in range(-search, search + 1)
        for b in range(-search, search + 1)
        if (a, b) != (0, 0) and lattice_color(a, b) == 0
    )

    colors_used = len({lattice_color(a, b) for a in range(-search, search + 1) for b in range(-search, search + 1)})

    return UpperBoundCertificate(r, diameter_squared, min_norm, separation_ok, diameter_ok, colors_used)


# ---------------------------------------------------------------------------------
# The explicit colouring function, plus a randomised cross-check
# ---------------------------------------------------------------------------------


class PlaneColoring:
    """The concrete 7-colouring c: R^2 -> {0..6} described above."""

    def __init__(self, circumradius: float = 0.45) -> None:
        self.r = circumradius
        self.s = circumradius * math.sqrt(3.0)  # centre-to-centre spacing

    def lattice_coords(self, x: float, y: float) -> tuple[int, int]:
        """Nearest lattice point, i.e. which Voronoi hexagon (x, y) falls in."""
        # basis u = (s, 0), v = (s/2, s*sqrt(3)/2); invert to get real-valued (a, b)
        b = y / (self.s * math.sqrt(3.0) / 2.0)
        a = x / self.s - b / 2.0
        best, best_d2 = (0, 0), float("inf")
        ai, bi = math.floor(a), math.floor(b)
        for da in (0, 1):
            for db in (0, 1):
                ca, cb = ai + da, bi + db
                cx, cy = self.center(ca, cb)
                d2 = (x - cx) ** 2 + (y - cy) ** 2
                if d2 < best_d2 - 1e-15:
                    best, best_d2 = (ca, cb), d2
        return best

    def center(self, a: int, b: int) -> tuple[float, float]:
        return (a * self.s + b * self.s / 2.0, b * self.s * math.sqrt(3.0) / 2.0)

    def __call__(self, x: float, y: float) -> int:
        return lattice_color(*self.lattice_coords(x, y))


def stress_test(samples: int = 200_000, circumradius: float = 0.45, seed: int = 20180408) -> tuple[int, int]:
    """Sample unit-distance pairs and count how many receive the same colour (must be 0)."""
    rng = random.Random(seed)
    coloring = PlaneColoring(circumradius)
    clashes = 0
    for _ in range(samples):
        x = rng.uniform(-50.0, 50.0)
        y = rng.uniform(-50.0, 50.0)
        theta = rng.uniform(0.0, 2.0 * math.pi)
        x2, y2 = x + math.cos(theta), y + math.sin(theta)
        if coloring(x, y) == coloring(x2, y2):
            clashes += 1
    return clashes, samples
