import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RGBELoader } from 'three/addons/loaders/RGBELoader.js';
import { clone as skeletonClone } from 'three/addons/utils/SkeletonUtils.js';

/**
 * Asset loading with caching. All Poly Haven assets live under /assets (see public/assets/index.json,
 * generated by tools/fetch-assets.mjs).
 *
 *   const maps = await assets.loadPBR('cobblestone_floor_08', { repeat: [4, 4] });
 *   const mat  = assets.createPBRMaterial('cobblestone_floor_08', { repeat: [4, 4], roughness: 1 });
 *   const hdr  = await assets.loadHDR('kloofendal_48d_partly_cloudy_puresky');
 *   const gltf = await assets.loadModel('street_lamp_01');        // returns cached GLTF
 *   const inst = assets.instantiate('street_lamp_01');            // fresh Object3D clone (skinned-safe)
 */
export class Assets {
  constructor(renderer) {
    this.renderer = renderer;
    this.base = `${import.meta.env.BASE_URL}assets/`; // '/assets/' in dev, './assets/' in the relative-base build
    this.index = null;
    this.textureLoader = new THREE.TextureLoader();
    this.gltfLoader = new GLTFLoader();
    this.hdrLoader = new RGBELoader();
    this._textures = new Map();
    this._pbr = new Map();
    this._models = new Map();
    this._hdrs = new Map();
    this._pending = 0;
    this._done = 0;
    this.onProgress = null;
    this.maxAnisotropy = renderer ? renderer.capabilities.getMaxAnisotropy() : 8;
    this.anisotropy = Math.min(16, this.maxAnisotropy);
  }

  async init() {
    if (this.index) return this.index;
    const res = await fetch(`${this.base}index.json`);
    this.index = await res.json();
    return this.index;
  }

  _track(promise) {
    this._pending++;
    this._report();
    return promise.finally(() => {
      this._done++;
      this._report();
    });
  }

  _report() {
    if (this.onProgress) this.onProgress(this._done, this._pending);
  }

  get progress() {
    return this._pending === 0 ? 1 : this._done / this._pending;
  }

  /** Load a single texture (cached by URL). */
  loadTexture(url, { srgb = false, repeat = null, anisotropy = true, flipY = true } = {}) {
    const key = `${url}|${srgb}|${flipY}`;
    if (this._textures.has(key)) return this._textures.get(key);
    const p = this._track(
      new Promise((resolve, reject) => {
        this.textureLoader.load(
          url,
          (tex) => {
            tex.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
            tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
            tex.flipY = flipY;
            if (anisotropy) tex.anisotropy = this.anisotropy;
            if (repeat) tex.repeat.set(repeat[0], repeat[1]);
            tex.needsUpdate = true;
            resolve(tex);
          },
          undefined,
          (err) => reject(new Error(`texture failed: ${url} (${err?.message || err})`)),
        );
      }),
    );
    this._textures.set(key, p);
    return p;
  }

  /**
   * Load a PBR set from the Poly Haven index. Returns { map, normalMap, aoMap, roughnessMap,
   * metalnessMap, displacementMap } — arm packed maps are shared across ao/rough/metal channels
   * (three.js reads AO from R, roughness from G, metalness from B — matching Poly Haven's ARM layout).
   */
  async loadPBR(id) {
    if (this._pbr.has(id)) return this._pbr.get(id);
    const p = (async () => {
      await this.init();
      const entry = this.index.textures[id];
      if (!entry) throw new Error(`unknown texture set "${id}" (see public/assets/index.json)`);
      const dir = `${this.base}textures/${id}/`;
      const has = (m) => entry.maps.includes(m);
      const [map, normalMap, arm, rough, ao, disp] = await Promise.all([
        has('diff') ? this.loadTexture(`${dir}diff.jpg`, { srgb: true }) : null,
        has('nor_gl') ? this.loadTexture(`${dir}nor_gl.jpg`) : null,
        has('arm') ? this.loadTexture(`${dir}arm.jpg`) : null,
        has('rough') ? this.loadTexture(`${dir}rough.jpg`) : null,
        has('ao') ? this.loadTexture(`${dir}ao.jpg`) : null,
        has('disp') ? this.loadTexture(`${dir}disp.jpg`) : null,
      ]);
      return {
        id,
        map,
        normalMap,
        aoMap: arm || ao,
        roughnessMap: arm || rough,
        metalnessMap: arm,
        displacementMap: disp,
        res: entry.res,
      };
    })();
    this._pbr.set(id, p);
    return p;
  }

  /**
   * Convenience: create a MeshStandardMaterial (or MeshPhysicalMaterial with `physical: true`) from a
   * PBR set. Textures are cloned so per-material repeat/offset does not leak between materials.
   * The material is returned synchronously with maps assigned once loaded (material.userData.ready).
   */
  createPBRMaterial(id, opts = {}) {
    const {
      repeat = [1, 1],
      offset = [0, 0],
      rotation = 0,
      physical = false,
      color = 0xffffff,
      roughness = 1,
      metalness = 0,
      normalScale = 1,
      aoIntensity = 1,
      displacementScale = 0,
      envMapIntensity = 1,
      side = THREE.FrontSide,
      ...rest
    } = opts;
    const Mat = physical ? THREE.MeshPhysicalMaterial : THREE.MeshStandardMaterial;
    const mat = new Mat({ color, roughness, metalness, side, envMapIntensity, ...rest });
    mat.name = id;
    mat.userData.pbrId = id;
    mat.userData.ready = this.loadPBR(id).then((set) => {
      const prep = (tex) => {
        if (!tex) return null;
        const t = tex.clone();
        t.repeat.set(repeat[0], repeat[1]);
        t.offset.set(offset[0], offset[1]);
        t.rotation = rotation;
        t.center.set(0.5, 0.5);
        t.needsUpdate = true;
        return t;
      };
      mat.map = prep(set.map);
      mat.normalMap = prep(set.normalMap);
      mat.normalScale.set(normalScale, normalScale);
      mat.aoMap = prep(set.aoMap);
      mat.aoMapIntensity = aoIntensity;
      mat.roughnessMap = prep(set.roughnessMap);
      // metalnessMap needs metalness=1 to have effect; Poly Haven ARM blue channel is usually 0 for dielectrics.
      if (set.metalnessMap && metalness > 0) mat.metalnessMap = prep(set.metalnessMap);
      if (displacementScale > 0 && set.displacementMap) {
        mat.displacementMap = prep(set.displacementMap);
        mat.displacementScale = displacementScale;
      }
      mat.needsUpdate = true;
      return mat;
    });
    return mat;
  }

  /** Load an equirectangular .hdr (cached). Returns THREE.DataTexture with EquirectangularReflectionMapping. */
  loadHDR(id) {
    if (this._hdrs.has(id)) return this._hdrs.get(id);
    const p = this._track(
      (async () => {
        await this.init();
        const entry = this.index.hdris[id];
        if (!entry) throw new Error(`unknown HDRI "${id}"`);
        const tex = await this.hdrLoader.loadAsync(`${this.base}${entry.file}`);
        tex.mapping = THREE.EquirectangularReflectionMapping;
        return tex;
      })(),
    );
    this._hdrs.set(id, p);
    return p;
  }

  /** Load a glTF by Poly Haven id or by explicit URL (cached). */
  loadModel(idOrUrl) {
    if (this._models.has(idOrUrl)) return this._models.get(idOrUrl);
    const p = this._track(
      (async () => {
        await this.init();
        let url = idOrUrl;
        if (!/[/.]/.test(idOrUrl)) {
          const entry = this.index.models[idOrUrl];
          if (!entry) throw new Error(`unknown model "${idOrUrl}"`);
          url = `${this.base}${entry.file}`;
        } else if (!idOrUrl.startsWith('/') && !idOrUrl.startsWith('http')) {
          url = `${this.base}${idOrUrl}`;
        }
        const gltf = await this.gltfLoader.loadAsync(url);
        gltf.scene.traverse((o) => {
          if (o.isMesh) {
            o.castShadow = true;
            o.receiveShadow = true;
            const mats = Array.isArray(o.material) ? o.material : [o.material];
            for (const m of mats) {
              if (m.map) m.map.anisotropy = this.anisotropy;
              if (m.normalMap) m.normalMap.anisotropy = this.anisotropy;
            }
          }
        });
        return gltf;
      })(),
    );
    this._models.set(idOrUrl, p);
    return p;
  }

  /** Synchronous clone of an already-loaded model scene (use after loadModel resolved). */
  instantiate(idOrUrl, gltf) {
    const source = gltf?.scene;
    if (!source) throw new Error(`instantiate("${idOrUrl}") requires a loaded gltf`);
    return skeletonClone(source);
  }

  /** Loads a model and returns a fresh clone of its scene. */
  async spawnModel(idOrUrl) {
    const gltf = await this.loadModel(idOrUrl);
    return this.instantiate(idOrUrl, gltf);
  }

  /** Create a texture from a canvas (procedural textures). */
  canvasTexture(canvas, { srgb = true, repeat = [1, 1], anisotropy = true } = {}) {
    const tex = new THREE.CanvasTexture(canvas);
    tex.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
    tex.repeat.set(repeat[0], repeat[1]);
    if (anisotropy) tex.anisotropy = this.anisotropy;
    tex.needsUpdate = true;
    return tex;
  }
}
