// The twenty required building programs of docs/overhaul/SPEC.md section 7 (rubric 16 A2, A5). Data only: each
// record names its rooms (kind = a template in rooms/programs.js or the standard library, function = the spec's
// words, core = every host must have it, extended rooms only where the host has >= EXTENDED_MIN_ROOMS planner rooms),
// the public and service circulation, the intended room graph, the material identity (block names, resolved to ids
// by programs/index.js), the player interactions per room (verbs from INTERACTIONS, each backed by blueprint
// evidence), customers, economic inputs/outputs as GOODS keys (goods the economy lacks are in
// docs/overhaul/goods-requests.md, listed here under `wants`) and the story hooks the dossier draws from.
//
// Room placement hints (`where`): ground = the entry floor, low = floors 0-2, upper = above the entry floor, top =
// the highest floor, inner = a room reached through another room (concealed back of house), any.
// `serviceEntry` marks the room that gets the service door when the host's ground floor allows one.
// `accept` is the kind pattern that lets a landmark's own hand-built rooms satisfy the requirement.

export const EXTENDED_MIN_ROOMS = 40;

// Player interactions and the blueprint evidence each needs inside the room: any of `spots` (spot kinds), any of
// `works` (work-record kinds), any of `blocks` (block names), all listed groups must be present.
export const INTERACTIONS = {
  sit: { spots: ['seat'] },
  wait: { spots: ['wait', 'seat'] },
  'read board': { blocks: ['HOLO_SIGN'] },
  'talk to staff': { works: ['*'] },
  buy: { works: ['vendor', 'shopkeeper', 'server', 'bartender', 'cook', 'barista', 'desk', 'broker', 'receptionist', 'tailor', 'stock'] },
  'order food': { works: ['cook', 'server', 'barista'], spots: ['seat'] },
  'order drink': { works: ['bartender'] },
  'book appointment': { works: ['desk', 'receptionist'], blocks: ['HOLO_SIGN'] },
  'file petition': { works: ['desk', 'receptionist'], blocks: ['HOLO_SIGN', 'CONSOLE'] },
  'buy ticket': { works: ['desk', 'conductor', 'receptionist'], blocks: ['HOLO_SIGN', 'CONSOLE'] },
  'check timetable': { blocks: ['HOLO_SIGN'] },
  'use console': { blocks: ['CONSOLE'] },
  'watch performance': { spots: ['seat'], blocks: ['PIANO', 'SMOOTH_STONE', 'HOLO_SIGN'] },
  'listen to the band': { spots: ['seat', 'musician'], blocks: ['PIANO'] },
  'browse stock': { blocks: ['SHELF', 'CRATE', 'BOOKSHELF', 'BARREL', 'CHEST'] },
  'haggle': { works: ['vendor', 'shopkeeper', 'broker', 'tailor'] },
  'pick up unit': { works: ['desk'], blocks: ['IRON_BLOCK'] },
  'watch the work': { works: ['mechanic', 'technician', 'droid tech', 'engineer', 'operator', 'deck officer', 'stock', 'cook', 'musician', 'projectionist', 'quartermaster', 'foreman', 'smith', 'tailor', 'pilot', 'medic', 'nurse', 'archivist', 'warden', 'guard', 'conductor', 'vendor', 'bartender', 'barista', 'instructor', 'master', 'knight', 'padawan', 'worker', 'cleaner', 'porter'] },
  'inspect the craft': { blocks: ['IRON_BARS', 'HULL_PLATE', 'STEEL_GLASS', 'CHROME'] },
  'register for treatment': { works: ['nurse', 'medic', 'desk'], blocks: ['HOLO_SIGN', 'CONSOLE'] },
  'receive treatment': { works: ['medic', 'nurse', 'surgeon', 'surgical droid', 'doctor', 'bacta tech', 'med droid', 'healer'], blocks: ['STEEL_GLASS', 'BED_HEAD', 'WHITE_WOOL'] },
  'rest in a bed': { beds: true },
  'sleep': { beds: true },
  'cook a meal': { blocks: ['FURNACE'] },
  'wash': { blocks: ['TROUGH'] },
  'collect mail': { blocks: ['SHELF', 'CRATE'] },
  'read': { blocks: ['BOOKSHELF'] },
  'play the piano': { blocks: ['PIANO'] },
  'admire the art': { blocks: ['GOLD_BLOCK', 'HOLO_SIGN', 'RED_WOOL', 'CHROME'] },
  'enjoy the view': { spots: ['seat', 'stand', 'wait'] },
  'report a crime': { works: ['guard', 'desk'], blocks: ['HOLO_SIGN', 'CONSOLE'] },
  'read the case board': { blocks: ['HOLO_SIGN'] },
  'inspect evidence': { blocks: ['CHEST', 'IRON_BARS'] },
  'look into the cells': { blocks: ['IRON_BARS'] },
  'read the status board': { blocks: ['HOLO_SIGN', 'GLOW_PANEL_BLUE', 'PANEL_RED'] },
  'follow the walkway': { blocks: ['PANEL_STRIPE', 'DECK_PLATE', 'IRON_BARS'] },
  'sell scrap': { works: ['desk', 'stock'] },
  'weigh a load': { blocks: ['CONSOLE', 'IRON_BLOCK'] },
  'book freight': { works: ['broker', 'desk'], blocks: ['HOLO_SIGN'] },
  'read the notices': { blocks: ['HOLO_SIGN'] },
  'take bread': { blocks: ['HAY_BALE', 'CRATE'] },
  'meditate': { spots: ['seat'], blocks: ['LANTERN', 'WHITE_WOOL'] },
  'tend the garden': { blocks: ['GRASS', 'OAK_LEAVES', 'BIRCH_LEAVES', 'TALL_GRASS', 'FARMLAND', 'WHEAT', 'SPRUCE_LEAVES', 'DANDELION', 'POPPY'] },
  'wait for a cab': { spots: ['wait', 'seat'] },
  'use the lift': { lifts: true },
  'leave by the service door': { serviceDoor: true },
  'check in baggage': { blocks: ['CRATE', 'RAIL'] },
  'pass the scanner': { blocks: ['IRON_BARS', 'GLOW_PANEL_BLUE'] },
  'inspect a shipment': { blocks: ['CRATE', 'BARREL', 'CONSOLE'] },
  'watch the departures': { blocks: ['HOLO_SIGN', 'GLOW_PANEL_BLUE'] },
  'charge a droid': { blocks: ['GLOW_PANEL_BLUE', 'IRON_BLOCK'] },
  'test a droid': { blocks: ['PANEL_RED', 'PANEL_STRIPE'] },
  'change clothes': { blocks: ['IRON_BLOCK', 'OAK_FENCE', 'GLASS', 'TINTED_GLASS', 'CHEST', 'SHELF'] },
  'check out equipment': { works: ['quartermaster', 'stock', 'guard', 'warden'], blocks: ['IRON_BLOCK', 'IRON_BARS', 'CHEST', 'CRATE'] },
  'sort scrap': { works: ['stock', 'mechanic', 'worker'], blocks: ['GRAVEL', 'IRON_BLOCK', 'IRON_BARS', 'CRATE'] },
  'take a private meeting': { spots: ['seat'], blocks: ['TABLE'] },
  'dance': { blocks: ['GLOW_PANEL', 'GLOW_PANEL_BLUE', 'NEON_PINK', 'NEON_GREEN'] },
};

const R = (kind, fn, o = {}) => ({ kind, function: fn, core: o.core !== false, where: o.where || 'any', signature: !!o.signature, service: !!o.service, serviceEntry: !!o.serviceEntry, merge: !!o.merge, accept: o.accept || null, interactions: o.interactions || ['talk to staff'], served: o.served !== false });

export const PROGRAMS = [
  {
    id: 'senate', name: 'Galactic Senate', special: true, ownerTitle: 'Speaker of the Senate',
    hosts: { kinds: [], families: ['senate'] },
    palette: { accent: 'GOLD_BLOCK', seat: 'RED_WOOL', counter: 'SMOOTH_STONE', light: 'GLOW_PANEL', trim: 'GOLD_BLOCK' },
    rooms: [
      R('senate_chamber', 'the rotunda: repeating delegation pods on a curved stepped plan around the podium', { signature: true, accept: /chamber|rotunda|pod/, interactions: ['sit', 'watch performance'] }),
      R('public_approach', 'public approach, plaza and entrance hall', { where: 'ground', accept: /approach|plaza|forecourt|lobby|atrium|entrance|vestibule|hall/, interactions: ['wait'] }),
      R('security_screening', 'security screening between the public approach and the delegation circulation', { where: 'ground', accept: /screening|security|checkpoint|guard/, interactions: ['pass the scanner'] }),
      R('delegation_suite', 'delegation suites: offices and reception for each represented system', { accept: /suite|delegation|office/, interactions: ['book appointment'] }),
      R('committee_room', 'committee and hearing rooms', { accept: /committee|hearing|meeting|conference/, interactions: ['sit'] }),
      R('petition_office', 'the petition office where a citizen files a petition', { accept: /petition/, interactions: ['file petition'] }),
      R('press_gallery', 'press gallery and media rooms', { accept: /press|gallery|media|news/, interactions: ['read board'] }),
      R('senate_records', 'records and archives', { accept: /records|archive/, interactions: ['read'] }),
      R('diplomatic_reception', 'diplomatic reception', { accept: /reception|diplomatic/, interactions: ['sit'] }),
      R('staff_services', 'staff services: canteen, kitchens, refreshers', { core: false, service: true, accept: /staff|canteen|kitchen|restroom|refresher|service|cafeteria/, interactions: ['order food'] }),
      R('maintenance_access', 'maintenance access and plant', { core: false, service: true, accept: /maintenance|utility|plant|mechanical|reactor/, interactions: ['use console'] }),
    ],
    circulation: { public: ['street', 'entry', 'public_approach', 'security_screening', 'press_gallery', 'petition_office', 'senate_chamber'], service: ['service_entry', 'staff_services', 'maintenance_access'], staff: ['security_screening', 'delegation_suite', 'committee_room', 'senate_chamber'] },
    graph: [['public_approach', 'security_screening'], ['security_screening', 'senate_chamber'], ['security_screening', 'delegation_suite'], ['delegation_suite', 'committee_room'], ['public_approach', 'petition_office'], ['public_approach', 'press_gallery'], ['delegation_suite', 'senate_records'], ['public_approach', 'diplomatic_reception'], ['staff_services', 'maintenance_access']],
    customers: 'senators, aides, petitioners, the press, visiting delegations',
    inputs: ['glow_panel', 'holo_sign', 'console'], outputs: [], wants: ['legislation', 'petition_filing'],
    story: { problem: 'a vote on the Military Creation Act is deadlocked and the corridors are full of lobbyists', connection: 'the Chancellery next door' },
  },
  {
    id: 'delegation_office', name: 'Delegation office', ownerTitle: 'Chargé d\'affaires',
    hosts: { kinds: ['embassy', 'ministry'], families: ['chancellery'] },
    palette: { accent: 'BLUE_WOOL', seat: 'BLUE_WOOL', counter: 'SMOOTH_STONE', light: 'GLOW_PANEL', trim: 'GOLD_BLOCK' },
    districtPalette: { financial: { accent: 'WHITE_WOOL', trim: 'CHROME' }, residential: { accent: 'GREEN_WOOL' } },
    rooms: [
      R('delegation_reception', 'reception: a clerk, the appointment board and seats for constituents', { where: 'ground', signature: true, accept: /reception|lobby|antechamber/, interactions: ['book appointment', 'sit', 'read board'] }),
      R('appointments_office', 'staff area handling appointments and correspondence', { where: 'low', accept: /office|secretar|aide/, interactions: ['talk to staff', 'use console'] }),
      R('delegation_meeting_room', 'meeting room for delegations and petitioners', { where: 'low', accept: /meeting|conference|council/, interactions: ['take a private meeting'] }),
      R('research_library', 'research area: records, precedents, holo archives', { core: false, where: 'upper', accept: /library|archive|research|records/, interactions: ['read'] }),
      R('delegation_staff_office', 'staff office with lockers and the caf urn', { core: false, where: 'upper', accept: /office/, interactions: ['talk to staff'] }),
      R('envoy_private_office', 'the envoy\'s private office behind the staff area', { core: false, where: 'upper', accept: /private|chancellor|executive|envoy|ambassador/, interactions: ['take a private meeting', 'admire the art'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'delegation_reception', 'delegation_meeting_room'], staff: ['delegation_reception', 'appointments_office', 'research_library', 'delegation_staff_office', 'envoy_private_office'] },
    graph: [['lobby_atrium', 'delegation_reception'], ['delegation_reception', 'appointments_office'], ['delegation_reception', 'delegation_meeting_room'], ['appointments_office', 'research_library'], ['appointments_office', 'delegation_staff_office'], ['delegation_staff_office', 'envoy_private_office']],
    customers: 'constituents with petitions, visiting delegations, journalists',
    inputs: ['holo_sign', 'console', 'bread'], outputs: [], wants: ['petition_filing', 'visa'],
    story: { problem: 'a trade dispute with a neighbouring system has doubled the queue at reception', connection: 'the Senate rotunda' },
  },
  {
    id: 'jedi_temple', name: 'Jedi Temple precinct', special: true, ownerTitle: 'Master of the Order',
    hosts: { kinds: ['temple_annex'], families: ['temple'] },
    palette: { accent: 'WHITE_WOOL', seat: 'SANDSTONE', counter: 'SANDSTONE', light: 'GLOW_PANEL', trim: 'GOLD_BLOCK' },
    rooms: [
      R('temple_threshold', 'reception threshold where visitors are met', { where: 'ground', accept: /threshold|reception|vestibule|lobby|atrium|great_hall|entrance|gate/, interactions: ['wait', 'admire the art'] }),
      R('training_hall', 'training hall', { signature: true, accept: /training|dojo|sparring|gym/, interactions: ['watch the work', 'sit'] }),
      R('archive_access', 'archive access', { accept: /archive|library|records|holocron/, interactions: ['read'] }),
      R('meditation_space', 'meditation space', { accept: /meditat|contemplat|sanctum/, interactions: ['meditate'] }),
      R('briefing_room', 'briefing room', { accept: /briefing|meeting|council|war_room/, interactions: ['sit', 'read board'] }),
      R('healers_room', 'healer\'s room', { accept: /heal|medic|infirmary|bacta|ward/, interactions: ['receive treatment'] }),
      R('living_quarters', 'living and service quarters', { core: false, service: true, accept: /quarters|dorm|cell|barrack|kitchen|refectory|laundry|store/, interactions: ['sleep'] }),
      R('temple_garden', 'garden', { core: false, accept: /garden|terrace|greenhouse|grove/, interactions: ['tend the garden', 'sit'] }),
      R('hangar_connection', 'hangar connection', { core: false, accept: /hangar|bay|dock|landing|pad/, interactions: ['inspect the craft'] }),
    ],
    circulation: { public: ['street', 'entry', 'temple_threshold', 'meditation_space'], staff: ['temple_threshold', 'training_hall', 'archive_access', 'briefing_room', 'healers_room', 'living_quarters', 'hangar_connection'] },
    graph: [['temple_threshold', 'training_hall'], ['temple_threshold', 'archive_access'], ['temple_threshold', 'meditation_space'], ['training_hall', 'briefing_room'], ['training_hall', 'healers_room'], ['briefing_room', 'hangar_connection'], ['living_quarters', 'temple_garden'], ['meditation_space', 'temple_garden']],
    customers: 'padawans, knights, masters, Senate liaison officers, the injured',
    inputs: ['bread', 'apple', 'bacta_shot', 'bookshelf'], outputs: [], wants: ['holocron', 'kyber_crystal'],
    story: { problem: 'the Order is short of knights and half the briefing rooms are dark', connection: 'the Senate by way of the Chancellor\'s liaison' },
  },
  {
    id: 'passenger_terminal', name: 'Commercial passenger terminal', special: true, ownerTitle: 'Terminal director',
    hosts: { kinds: ['customs'], families: [] },
    palette: { accent: 'BLUE_WOOL', seat: 'STONE_BRICK_SLAB', counter: 'PANEL_BLACK', light: 'GLOW_PANEL', trim: 'CHROME' },
    rooms: [
      R('ticket_counter', 'ticketing: the counter, queue rail and the fares board', { where: 'ground', signature: true, accept: /ticket|check_in|counter/, interactions: ['buy ticket', 'read board'] }),
      R('departure_lounge', 'waiting: the departure lounge under the departures board', { where: 'ground', accept: /lounge|waiting|departure|gate/, interactions: ['wait', 'watch the departures'] }),
      R('baggage_store', 'baggage handling on the belt', { where: 'ground', service: true, accept: /baggage|luggage|cargo|store/, interactions: ['check in baggage'] }),
      R('customs_checkpoint', 'customs and security: the scanner arch and the inspection table', { where: 'ground', accept: /customs|security|checkpoint|screening/, interactions: ['pass the scanner'] }),
      R('information_desk', 'information desk under the city map', { core: false, where: 'ground', accept: /information|desk|help/, interactions: ['talk to staff', 'read board'] }),
      R('terminal_cafe', 'refreshments', { core: false, where: 'low', accept: /cafe|caf|refreshment|restaurant|canteen/, interactions: ['order food', 'sit'] }),
      R('washroom', 'restrooms', { core: false, where: 'low', accept: /restroom|washroom|refresher/, interactions: ['wash'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'ticket_counter', 'customs_checkpoint', 'departure_lounge', 'boarding gate (spaceport)'], service: ['service_entry', 'baggage_store', 'customs_checkpoint'] },
    graph: [['lobby_atrium', 'ticket_counter'], ['lobby_atrium', 'information_desk'], ['ticket_counter', 'customs_checkpoint'], ['customs_checkpoint', 'departure_lounge'], ['ticket_counter', 'baggage_store'], ['baggage_store', 'customs_checkpoint'], ['departure_lounge', 'terminal_cafe'], ['departure_lounge', 'washroom']],
    customers: 'travellers with luggage, traders clearing goods, pilots between runs',
    inputs: ['speeder_ride', 'bread'], outputs: ['speeder_ride'], wants: ['passage_ticket', 'customs_clearance'],
    story: { problem: 'a docking-bay strike has left the departures board full of delays', connection: 'the spaceport landing bays across the gate' },
  },
  {
    id: 'cargo_terminal', name: 'Cargo terminal', ownerTitle: 'Yard master',
    hosts: { kinds: ['depot', 'warehouse'], families: [] },
    palette: { accent: 'PANEL_STRIPE', seat: 'STONE_BRICK_SLAB', counter: 'DURASTEEL', light: 'GLOW_PANEL', trim: 'IRON_BLOCK' },
    rooms: [
      R('manifest_office', 'manifest office: clerks, the traffic board and the filed manifests', { where: 'ground', accept: /manifest|office|clerk/, interactions: ['talk to staff', 'read board'] }),
      R('cargo_inspection', 'inspection bench and scanner', { where: 'ground', accept: /inspection|customs|scan/, interactions: ['inspect a shipment'] }),
      R('bonded_store', 'bonded storage behind the cage', { where: 'low', service: true, accept: /bonded|secure|vault|store/, interactions: ['browse stock'] }),
      R('loading_yard', 'loading yard: the apron line, pallets and the cargo droid', { where: 'ground', signature: true, service: true, serviceEntry: true, accept: /loading|yard|dock|bay/, interactions: ['watch the work'] }),
      R('freight_dispatch', 'dispatch: routes and crews', { where: 'low', accept: /dispatch|control|ops/, interactions: ['read board', 'use console'] }),
      R('bulk_storage', 'bulk storage stacks', { core: false, where: 'upper', service: true, accept: /bulk|storage|warehouse/, interactions: ['browse stock'] }),
      R('sorting_depot', 'sorting floor with colour-coded bins', { core: false, where: 'low', service: true, accept: /sort|depot/, interactions: ['watch the work'] }),
      R('staff_canteen', 'staff facilities', { core: false, where: 'upper', accept: /canteen|mess|staff|break/, interactions: ['order food', 'sit'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'manifest_office', 'freight_dispatch'], service: ['service_entry', 'loading_yard', 'cargo_inspection', 'sorting_depot', 'bonded_store', 'bulk_storage'] },
    graph: [['lobby_atrium', 'manifest_office'], ['manifest_office', 'freight_dispatch'], ['loading_yard', 'cargo_inspection'], ['cargo_inspection', 'sorting_depot'], ['sorting_depot', 'bonded_store'], ['sorting_depot', 'bulk_storage'], ['manifest_office', 'cargo_inspection'], ['freight_dispatch', 'staff_canteen']],
    customers: 'freighter crews, shopkeepers collecting stock, factory buyers',
    inputs: ['iron_block', 'planks', 'chest', 'wheat', 'wool'], outputs: ['iron_block', 'planks', 'chest', 'wheat', 'wool'], wants: ['freight_contract'],
    story: { problem: 'two manifests for the same container and neither crew will leave without it', connection: 'the freight brokerage on the industrial edge' },
  },
  {
    id: 'repair_hangar', name: 'Ship repair hangar', ownerTitle: 'Chief mechanic',
    hosts: { kinds: ['repair_shop', 'hangar'], families: [] },
    palette: { accent: 'PANEL_RED', seat: 'STONE_BRICK_SLAB', counter: 'DURASTEEL_DARK', light: 'GLOW_PANEL', trim: 'CHROME' },
    rooms: [
      R('repair_bay', 'the work bay: a craft on its cradle under the hoist gantry, tool wall and diagnostics console', { where: 'ground', signature: true, merge: true, service: true, serviceEntry: true, accept: /bay|hangar|dock|berth/, interactions: ['inspect the craft', 'watch the work'] }),
      R('parts_store', 'parts storage with labelled bins', { where: 'low', service: true, accept: /parts|store|storage|spares/, interactions: ['browse stock'] }),
      R('tool_workshop', 'tool station: bench, anvil, furnace and the tool rail', { where: 'low', accept: /tool|workshop|machine/, interactions: ['watch the work'] }),
      R('diagnostics_control', 'diagnostics: the scanner console and the hull sample', { where: 'low', accept: /diagnos|control|test/, interactions: ['use console', 'read the status board'] }),
      R('crew_office', 'crew office and the job board', { core: false, where: 'upper', accept: /office/, interactions: ['read board'] }),
      R('crew_break_room', 'crew break room', { core: false, where: 'upper', accept: /break|lounge|canteen|mess/, interactions: ['sit'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'diagnostics_control', 'repair_bay'], service: ['service_entry', 'repair_bay', 'parts_store', 'tool_workshop'] },
    graph: [['lobby_atrium', 'repair_bay'], ['repair_bay', 'tool_workshop'], ['repair_bay', 'parts_store'], ['repair_bay', 'diagnostics_control'], ['diagnostics_control', 'crew_office'], ['crew_office', 'crew_break_room']],
    customers: 'freighter captains, speeder owners, the transit authority\'s fleet',
    inputs: ['iron_block', 'iron_bars', 'glass', 'console'], outputs: ['ship_speeder', 'ship_shuttle'], wants: ['repair_service', 'hyperdrive_part'],
    story: { problem: 'a freighter\'s hyperdrive part is on back order and the owner sleeps in the bay', connection: 'the cargo terminal that ships the parts' },
  },
  {
    id: 'droid_workshop', name: 'Droid workshop', ownerTitle: 'Proprietor',
    hosts: { kinds: ['droid_shop', 'droid_factory'], families: [] },
    palette: { accent: 'GLOW_PANEL_BLUE', seat: 'STONE_BRICK_SLAB', counter: 'PANEL_BLACK', light: 'GLOW_PANEL_BLUE', trim: 'CHROME' },
    rooms: [
      R('droid_intake', 'intake counter with the tagged units waiting in line', { where: 'ground', accept: /intake|reception|counter|front/, interactions: ['talk to staff', 'read board'] }),
      R('droid_diagnostics', 'diagnostics rig', { where: 'low', accept: /diagnos|test|scan/, interactions: ['watch the work', 'use console'] }),
      R('droid_repair_bench', 'repair benches with half-built units, active and idle machines', { where: 'low', signature: true, accept: /repair|bench|assembly|workshop|line/, interactions: ['watch the work'] }),
      R('parts_sorting', 'parts sorting into colour-coded bins', { where: 'low', service: true, accept: /parts|sort|store|storage/, interactions: ['browse stock'] }),
      R('droid_test_range', 'test lane with the target and the safety rail', { core: false, where: 'upper', accept: /test|range/, interactions: ['test a droid'] }),
      R('droid_charging', 'charging bays, some live and some idle', { core: false, where: 'upper', accept: /charg|power/, interactions: ['charge a droid'] }),
      R('pickup_desk', 'pickup desk with finished units waiting for their owners', { core: false, where: 'ground', accept: /pickup|collection|desk/, interactions: ['pick up unit'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'droid_intake', 'pickup_desk'], staff: ['droid_intake', 'droid_diagnostics', 'droid_repair_bench', 'parts_sorting', 'droid_test_range', 'droid_charging', 'pickup_desk'] },
    graph: [['lobby_atrium', 'droid_intake'], ['droid_intake', 'droid_diagnostics'], ['droid_diagnostics', 'droid_repair_bench'], ['droid_repair_bench', 'parts_sorting'], ['droid_repair_bench', 'droid_test_range'], ['droid_test_range', 'droid_charging'], ['droid_charging', 'pickup_desk'], ['lobby_atrium', 'pickup_desk']],
    customers: 'households with a broken kitchen unit, shops with a limping cargo droid, the works\' maintenance chief',
    inputs: ['iron_block', 'console', 'glow_panel_blue', 'iron_bars'], outputs: ['console'], wants: ['droid_part', 'droid_repair'],
    story: { problem: 'a protocol droid\'s memory wipe was refused and its owner is arguing at intake', connection: 'the salvage yard that supplies the parts' },
  },
  {
    id: 'diner', name: 'Diner', ownerTitle: 'Owner-cook',
    hosts: { kinds: ['diner', 'noodle_bar', 'caf'], families: [] },
    palette: { accent: 'RED_WOOL', seat: 'RED_WOOL', counter: 'PANEL_BLACK', light: 'GLOW_PANEL', trim: 'CHROME' },
    districtPalette: { financial: { accent: 'WHITE_WOOL', seat: 'WHITE_WOOL' }, industrial: { accent: 'PANEL_STRIPE', counter: 'DURASTEEL' }, entertainment: { light: 'LANTERN', accent: 'BLUE_WOOL' } },
    rooms: [
      R('diner_counter', 'counter seating with stools, the hot plate and pass, the menu board, booths where the room allows', { where: 'ground', signature: true, accept: /diner|counter|cafe|caf|noodle|restaurant|dining/, interactions: ['order food', 'sit', 'read board'] }),
      R('diner_kitchen', 'kitchen with stoves, prep counter and sink', { where: 'ground', service: true, accept: /kitchen|galley/, interactions: ['cook a meal', 'watch the work'] }),
      R('cold_store', 'cold storage', { where: 'low', service: true, accept: /cold|store|storage|pantry|larder/, interactions: ['browse stock'] }),
      R('kitchen_scullery', 'dish washing', { core: false, where: 'low', service: true, accept: /scullery|wash|dish/, interactions: ['wash'] }),
      R('delivery_store', 'delivery access for the morning produce', { core: false, where: 'ground', service: true, serviceEntry: true, accept: /deliver|receiv|store/, interactions: ['browse stock'] }),
      R('staff_locker', 'staff belongings', { core: false, where: 'upper', service: true, accept: /locker|staff|changing/, interactions: ['change clothes'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'diner_counter'], service: ['service_entry', 'delivery_store', 'cold_store', 'diner_kitchen', 'diner_counter'] },
    graph: [['lobby_atrium', 'diner_counter'], ['diner_counter', 'diner_kitchen'], ['diner_kitchen', 'cold_store'], ['diner_kitchen', 'kitchen_scullery'], ['delivery_store', 'cold_store'], ['diner_kitchen', 'staff_locker']],
    customers: 'shift workers before dawn, transit crews, clerks at noon, the regulars who never order',
    inputs: ['wheat', 'raw_beef', 'raw_chicken', 'raw_porkchop', 'apple'], outputs: ['bread', 'cooked_beef', 'cooked_chicken', 'cooked_porkchop'], wants: ['caf', 'noodles'],
    story: { problem: 'the produce delivery comes late three days out of five and the owner knows exactly why', connection: 'the market arcade\'s produce kiosk' },
  },
  {
    id: 'cantina_club', name: 'Cantina and club', ownerTitle: 'Licensee',
    hosts: { kinds: ['cantina', 'night_club'], families: ['underworld'] },
    palette: { accent: 'NEON_PINK', seat: 'PANEL_BLACK', counter: 'PANEL_BLACK', light: 'LANTERN', trim: 'CHROME' },
    districtPalette: { entertainment: { accent: 'NEON_GREEN' }, residential: { accent: 'RED_WOOL', light: 'GLOW_PANEL' } },
    rooms: [
      R('cantina_bar', 'serving area: the bar and its bottle wall', { where: 'ground', signature: true, accept: /cantina|bar|club|tavern|lounge/, interactions: ['order drink', 'sit'] }),
      R('booth_seating', 'seating with sightline variety: floor tables and raised booths', { where: 'ground', accept: /booth|seating|lounge|floor/, interactions: ['sit'] }),
      R('cantina_stage', 'performance and music source: the band on its stage under the lights', { where: 'ground', accept: /stage|band|music|dance|dj|night_club|club/, interactions: ['listen to the band', 'sit'] }),
      R('stock_room', 'service storage', { where: 'low', service: true, accept: /stock|store|storage|cellar/, interactions: ['browse stock'] }),
      R('private_booth', 'a private conversation area behind its own door', { where: 'any', accept: /private|back_room|booth|den|office/, interactions: ['take a private meeting'] }),
      R('staff_break', 'staff space', { core: false, where: 'upper', service: true, accept: /staff|break|locker|dressing/, interactions: ['sit'] }),
      R('back_office', 'the licensee\'s office: safe and ledgers', { core: false, where: 'upper', accept: /office/, interactions: ['use console'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'cantina_bar', 'booth_seating', 'cantina_stage', 'private_booth'], service: ['service_entry', 'stock_room', 'cantina_bar'] },
    graph: [['lobby_atrium', 'cantina_bar'], ['cantina_bar', 'booth_seating'], ['booth_seating', 'cantina_stage'], ['cantina_bar', 'stock_room'], ['booth_seating', 'private_booth'], ['stock_room', 'staff_break'], ['staff_break', 'back_office']],
    customers: 'off-shift dock crews, musicians between sets, people who need a private table',
    inputs: ['wheat', 'apple', 'lantern'], outputs: [], wants: ['ale', 'juri_juice', 'spice'],
    story: { problem: 'the band\'s Bith horn player has not turned up and the crowd is getting restless', connection: 'the security station two streets over, which knows the private booth well' },
  },
  {
    id: 'opera_house', name: 'Opera house', ownerTitle: 'Artistic director',
    hosts: { kinds: ['holo_theatre'], families: ['opera'] },
    palette: { accent: 'RED_WOOL', seat: 'RED_WOOL', counter: 'PANEL_BLACK', light: 'GLOW_PANEL', trim: 'GOLD_BLOCK' },
    rooms: [
      R('ticket_desk', 'ticketing under tonight\'s bill', { where: 'ground', accept: /ticket|box_office|desk/, interactions: ['buy ticket', 'read board'] }),
      R('auditorium', 'the auditorium: raked seating, centre aisle, stage and holo backdrop', { where: 'low', signature: true, merge: true, accept: /auditorium|hall|stage|theatre|stalls|orchestra/, interactions: ['watch performance', 'sit'] }),
      R('backstage', 'backstage: scenery flats, prop crates and the fly rope', { where: 'low', service: true, accept: /backstage|scenery|wing|fly|prop/, interactions: ['watch the work'] }),
      R('lighting_control', 'technical access: the lighting desk', { where: 'low', service: true, accept: /light|control|technical|projection|booth/, interactions: ['use console'] }),
      R('private_box', 'differentiated public seating: a private box', { core: false, where: 'upper', accept: /box|balcony|tier|circle/, interactions: ['sit'] }),
      R('dressing_room', 'dressing rooms', { core: false, where: 'upper', service: true, accept: /dressing|green_room|wardrobe/, interactions: ['change clothes'] }),
      R('foyer_bar', 'foyer bar for the interval', { core: false, where: 'ground', accept: /foyer|bar|lounge/, interactions: ['order drink', 'sit'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'ticket_desk', 'foyer_bar', 'auditorium', 'private_box'], service: ['service_entry', 'backstage', 'dressing_room', 'lighting_control'] },
    graph: [['lobby_atrium', 'ticket_desk'], ['ticket_desk', 'auditorium'], ['lobby_atrium', 'foyer_bar'], ['auditorium', 'private_box'], ['auditorium', 'backstage'], ['backstage', 'dressing_room'], ['auditorium', 'lighting_control']],
    customers: 'season-ticket holders, first-timers with cheap seats, critics, the Chancellor\'s box',
    inputs: ['glow_panel', 'red_wool', 'lantern'], outputs: [], wants: ['performance_ticket'],
    story: { problem: 'the soprano has lost her voice and the understudy is a Mon Calamari nobody has heard sing', connection: 'the delegation offices whose staff fill the boxes' },
  },
  {
    id: 'market_arcade', name: 'Market arcade', ownerTitle: 'Market warden',
    hosts: { kinds: ['market_stall'], families: ['market'] },
    palette: { accent: 'GREEN_WOOL', seat: 'STONE_BRICK_SLAB', counter: 'OAK_PLANKS', light: 'LANTERN', trim: 'OAK_LOG' },
    rooms: [
      R('produce_kiosk', 'food vendor: produce on display, haggling', { where: 'ground', signature: true, accept: /produce|food|grocer|fruit|bakery/, interactions: ['buy', 'haggle', 'browse stock'] }),
      R('mechanical_kiosk', 'parts vendor: mechanical parts, fixed prices', { where: 'ground', accept: /parts|mechanical|hardware|tool/, interactions: ['buy', 'browse stock'] }),
      R('textile_kiosk', 'textiles vendor: bolts of cloth, haggling', { where: 'ground', accept: /textile|cloth|tailor|fabric/, interactions: ['buy', 'haggle'] }),
      R('appliance_kiosk', 'domestic equipment vendor, fixed prices', { where: 'ground', accept: /appliance|domestic|household|furniture/, interactions: ['buy', 'browse stock'] }),
      R('delivery_store', 'deliveries behind the kiosks', { where: 'ground', service: true, serviceEntry: true, accept: /deliver|store|storage|stock/, interactions: ['browse stock'] }),
      R('navigation_kiosk', 'navigation and data services vendor, fixed prices', { core: false, where: 'low', accept: /nav|data|chart|holo|book/, interactions: ['buy', 'use console'] }),
      R('salvage_kiosk', 'salvage vendor, haggling', { core: false, where: 'low', accept: /salvage|scrap|junk|pawn/, interactions: ['buy', 'haggle'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'produce_kiosk', 'mechanical_kiosk', 'textile_kiosk', 'appliance_kiosk', 'navigation_kiosk', 'salvage_kiosk'], service: ['service_entry', 'delivery_store', 'produce_kiosk'] },
    graph: [['lobby_atrium', 'produce_kiosk'], ['lobby_atrium', 'mechanical_kiosk'], ['lobby_atrium', 'textile_kiosk'], ['lobby_atrium', 'appliance_kiosk'], ['delivery_store', 'produce_kiosk'], ['delivery_store', 'appliance_kiosk'], ['lobby_atrium', 'navigation_kiosk'], ['lobby_atrium', 'salvage_kiosk']],
    customers: 'households, diner cooks buying produce, mechanics hunting a part, navigators buying charts',
    inputs: ['wheat', 'apple', 'wool', 'iron_bars', 'console', 'chest'], outputs: ['apple', 'bread', 'wool', 'red_wool', 'blue_wool', 'iron_bars', 'console', 'table', 'chest'], wants: ['nav_chart', 'scrap'],
    story: { problem: 'the textile vendor accuses the salvage vendor of reselling stolen bolts and the warden has to rule', connection: 'the salvage yard where the bolts came from' },
  },
  {
    id: 'clinic', name: 'Clinic', ownerTitle: 'Chief medical officer',
    hosts: { kinds: ['clinic', 'bacta_ward', 'cybernetics_clinic'], families: ['medcenter'] },
    palette: { accent: 'WHITE_WOOL', seat: 'WHITE_WOOL', counter: 'WHITE_WOOL', light: 'GLOW_PANEL_BLUE', trim: 'CHROME' },
    rooms: [
      R('triage_reception', 'reception and triage: numbered seats under the triage screen', { where: 'ground', accept: /triage|reception|waiting|lobby|admissions/, interactions: ['register for treatment', 'wait'] }),
      R('medical_exam', 'examination room', { where: 'low', accept: /exam|consult|surgery|medbay|medical/, interactions: ['receive treatment'] }),
      R('treatment_room', 'treatment room with the bacta tank', { where: 'low', signature: true, accept: /treatment|bacta|surgery|theatre|cybernetic/, interactions: ['receive treatment'] }),
      R('recovery_ward', 'recovery ward: beds behind privacy panels', { where: 'low', accept: /ward|recovery|beds/, interactions: ['rest in a bed'] }),
      R('supply_store', 'supplies', { where: 'low', service: true, accept: /supply|store|pharmacy|dispensary/, interactions: ['browse stock'] }),
      R('medical_staff_post', 'staff space', { core: false, where: 'upper', service: true, accept: /staff|post|office|lounge/, interactions: ['talk to staff'] }),
      R('washroom', 'patient restrooms', { core: false, where: 'low', accept: /restroom|washroom|refresher/, interactions: ['wash'] }),
      R('emergency_bay', 'emergency access: the gurney bay with its own door', { core: false, where: 'ground', service: true, serviceEntry: true, accept: /emergency|ambulance|trauma/, interactions: ['receive treatment', 'inspect the craft'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'triage_reception', 'medical_exam', 'treatment_room', 'recovery_ward'], service: ['service_entry', 'emergency_bay', 'treatment_room', 'supply_store'] },
    graph: [['lobby_atrium', 'triage_reception'], ['triage_reception', 'medical_exam'], ['medical_exam', 'treatment_room'], ['treatment_room', 'recovery_ward'], ['treatment_room', 'supply_store'], ['emergency_bay', 'treatment_room'], ['recovery_ward', 'washroom'], ['supply_store', 'medical_staff_post']],
    customers: 'dock workers with crushed hands, families, speeder-crash victims from the emergency bay',
    inputs: ['bacta_shot', 'wool', 'glass', 'bed'], outputs: ['bacta_shot'], wants: ['cybernetic_implant', 'medical_supplies'],
    story: { problem: 'the bacta shipment is short again and triage is turning away everything that can wait', connection: 'the works, whose shift injuries fill the ward' },
  },
  {
    id: 'worker_apartments', name: 'Worker apartments', ownerTitle: 'Building superintendent',
    hosts: { kinds: ['apartments'], families: [] },
    palette: { accent: 'GREEN_WOOL', seat: 'STONE_BRICK_SLAB', counter: 'PANEL_BLACK', light: 'GLOW_PANEL', trim: 'DURASTEEL' },
    districtPalette: { financial: { accent: 'BLUE_WOOL' }, market: { accent: 'RED_WOOL' } },
    rooms: [
      R('nightshift_flat', 'a night-shift worker\'s flat: blackout panels over the window wall', { where: 'upper', signature: true, accept: /flat|apartment|studio|home/, interactions: ['sleep'] }),
      R('mechanic_flat', 'a mechanic\'s flat: the half-repaired appliance on the table', { where: 'upper', accept: /flat|apartment|studio|home/, interactions: ['sleep'] }),
      R('musician_flat', 'a musician\'s flat: the practice corner', { where: 'upper', accept: /flat|apartment|studio|home/, interactions: ['sleep', 'play the piano'] }),
      R('parcel_store', 'mail and deliveries: the parcel room', { where: 'ground', service: true, accept: /mail|parcel|post|deliver/, interactions: ['collect mail'] }),
      R('shared_laundry', 'utilities: the shared laundry', { where: 'low', service: true, accept: /laundry|utility/, interactions: ['wash'] }),
      R('utility_room', 'utilities: boilers and ducts', { core: false, where: 'low', service: true, accept: /utility|plant|boiler|service/, interactions: ['use console'] }),
      R('communal_kitchen', 'communal services: the shared kitchen', { core: false, where: 'upper', accept: /kitchen|canteen|communal/, interactions: ['cook a meal'] }),
      R('residents_garden', 'roof or courtyard: the residents\' garden', { core: false, where: 'top', accept: /garden|terrace|roof|courtyard/, interactions: ['tend the garden', 'sit'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'parcel_store', 'lift', 'nightshift_flat', 'mechanic_flat', 'musician_flat', 'residents_garden'], service: ['service_entry', 'utility_room', 'shared_laundry'] },
    graph: [['lobby_atrium', 'parcel_store'], ['lobby_atrium', 'shared_laundry'], ['shared_laundry', 'utility_room'], ['lobby_atrium', 'nightshift_flat'], ['lobby_atrium', 'mechanic_flat'], ['lobby_atrium', 'musician_flat'], ['mechanic_flat', 'communal_kitchen'], ['musician_flat', 'residents_garden']],
    customers: 'the residents: shift workers, a mechanic, a musician, families with children at the school',
    inputs: ['bread', 'apple', 'bed', 'lantern'], outputs: [], wants: ['rent', 'power'],
    story: { problem: 'the lift has been out for a week and the night-shift worker on the top floor has stopped sleeping', connection: 'the community hall two blocks away, whose noticeboard carries the complaint' },
  },
  {
    id: 'affluent_apartments', name: 'Affluent apartments', ownerTitle: 'Residents\' association chair',
    hosts: { kinds: ['luxury_residences'], families: ['republica'] },
    palette: { accent: 'GOLD_BLOCK', seat: 'WHITE_WOOL', counter: 'CHROME', light: 'GLOW_PANEL', trim: 'GOLD_BLOCK' },
    rooms: [
      R('visitor_reception', 'visitor reception: the concierge, marble and art on a pedestal', { where: 'ground', signature: true, accept: /reception|lobby|concierge|atrium|foyer/, interactions: ['talk to staff', 'admire the art', 'sit'] }),
      R('grand_residence', 'a residence built on proportion, privacy, materials and views', { where: 'upper', accept: /residence|penthouse|suite|apartment|flat/, interactions: ['sleep', 'admire the art'] }),
      R('art_salon', 'art: the salon', { where: 'upper', accept: /salon|gallery|art|lounge/, interactions: ['admire the art', 'sit'] }),
      R('domestic_service', 'domestic and service spaces', { where: 'low', service: true, accept: /service|laundry|domestic|staff|kitchen/, interactions: ['watch the work'] }),
      R('private_study', 'a private study', { core: false, where: 'upper', accept: /study|library|office/, interactions: ['read'] }),
      R('view_terrace', 'views: the terrace', { core: false, where: 'top', accept: /terrace|observation|view|garden|roof/, interactions: ['enjoy the view'] }),
      R('service_pantry', 'service pantry behind the residences', { core: false, where: 'upper', service: true, accept: /pantry|service|store|laundry/, interactions: ['browse stock'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'visitor_reception', 'lift', 'art_salon', 'view_terrace'], service: ['service_entry', 'domestic_service', 'service_pantry', 'grand_residence'] },
    graph: [['lobby_atrium', 'visitor_reception'], ['visitor_reception', 'grand_residence'], ['grand_residence', 'art_salon'], ['grand_residence', 'private_study'], ['domestic_service', 'service_pantry'], ['service_pantry', 'grand_residence'], ['art_salon', 'view_terrace']],
    customers: 'residents and their guests, delivery staff at the service door, the residents\' social calendar at the opera',
    inputs: ['gold_block', 'glow_panel', 'bed', 'apple'], outputs: [], wants: ['rent', 'art_piece'],
    story: { problem: 'a resident\'s protocol droid has been let go and the whole floor knows why', connection: 'the opera house whose boxes the residents keep' },
  },
  {
    id: 'transit_interchange', name: 'Transit interchange', ownerTitle: 'Station manager',
    hosts: { kinds: ['transit_station', 'taxi_stand'], families: [] },
    palette: { accent: 'BLUE_WOOL', seat: 'STONE_BRICK_SLAB', counter: 'DURASTEEL', light: 'GLOW_PANEL', trim: 'PANEL_STRIPE' },
    rooms: [
      R('ticket_hall', 'ticket and access mechanisms: machines, the destination board and the barrier gates', { where: 'ground', signature: true, accept: /ticket|hall|concourse|gate|barrier/, interactions: ['buy ticket', 'check timetable'] }),
      R('boarding_platform', 'boarding area: the platform edge under the timetable', { where: 'ground', accept: /platform|boarding|rank|stand/, interactions: ['wait', 'check timetable'] }),
      R('waiting_hall', 'waiting: benches and the vending machine', { where: 'ground', accept: /wait|lounge/, interactions: ['wait', 'sit'] }),
      R('service_control', 'service control: the route map with its disruption lamp', { where: 'low', service: true, accept: /control|dispatch|ops|signal/, interactions: ['read the status board'] }),
      R('maintenance_workshop', 'maintenance', { core: false, where: 'low', service: true, accept: /maintenance|workshop|depot/, interactions: ['watch the work'] }),
      R('speeder_rank', 'the speeder rank', { core: false, where: 'ground', accept: /speeder|rank|taxi|garage/, interactions: ['wait for a cab'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'ticket_hall', 'waiting_hall', 'boarding_platform', 'speeder_rank'], service: ['service_entry', 'service_control', 'maintenance_workshop'] },
    graph: [['lobby_atrium', 'ticket_hall'], ['ticket_hall', 'waiting_hall'], ['ticket_hall', 'boarding_platform'], ['boarding_platform', 'service_control'], ['service_control', 'maintenance_workshop'], ['lobby_atrium', 'speeder_rank']],
    customers: 'commuters, night-shift crews, travellers changing between the tram and a cab',
    inputs: ['speeder_ride', 'glow_panel'], outputs: ['speeder_ride'], wants: ['transit_pass'],
    story: { problem: 'the eastbound route is disrupted and the board sends everyone to the speeder rank', connection: 'the passenger terminal at the end of the line' },
    schedule: { headwayMin: 6, firstService: 5, lastService: 25 },
  },
  {
    id: 'security_station', name: 'Security station', ownerTitle: 'Station commander',
    hosts: { kinds: ['security_station', 'guard_barracks'], families: ['detention'] },
    palette: { accent: 'PANEL_RED', seat: 'STONE_BRICK_SLAB', counter: 'DURASTEEL_DARK', light: 'GLOW_PANEL', trim: 'IRON_BLOCK' },
    rooms: [
      R('public_reporting_post', 'public reporting: the duty counter under the case board', { where: 'ground', signature: true, accept: /reporting|front_desk|duty|post|reception|lobby|checkpoint/, interactions: ['report a crime', 'read the case board'] }),
      R('dispatch_room', 'dispatch: consoles and the sector map', { where: 'low', accept: /dispatch|control|ops|comms/, interactions: ['read the status board'] }),
      R('evidence_records', 'evidence and records behind the cage', { where: 'low', service: true, accept: /evidence|records|archive|property/, interactions: ['inspect evidence'] }),
      R('holding_cells', 'secure holding', { where: 'low', service: true, accept: /cell|holding|detention|brig/, interactions: ['look into the cells'] }),
      R('briefing_room', 'briefing', { core: false, where: 'upper', accept: /briefing|meeting|muster/, interactions: ['sit', 'read board'] }),
      R('rest_bunks', 'rest space', { core: false, where: 'upper', service: true, accept: /bunk|barrack|dorm|rest|quarters/, interactions: ['sleep'] }),
      R('equipment_armory', 'equipment storage', { core: false, where: 'upper', service: true, accept: /armory|armoury|equipment|weapons/, interactions: ['check out equipment', 'browse stock'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'public_reporting_post'], staff: ['public_reporting_post', 'dispatch_room', 'briefing_room', 'evidence_records', 'holding_cells', 'rest_bunks', 'equipment_armory'] },
    graph: [['lobby_atrium', 'public_reporting_post'], ['public_reporting_post', 'dispatch_room'], ['public_reporting_post', 'holding_cells'], ['dispatch_room', 'briefing_room'], ['public_reporting_post', 'evidence_records'], ['briefing_room', 'rest_bunks'], ['rest_bunks', 'equipment_armory']],
    customers: 'citizens reporting a theft, advocates visiting the cells, patrols coming off shift',
    inputs: ['iron_bars', 'console', 'bread'], outputs: [], wants: ['fine', 'bounty'],
    story: { problem: 'a case on the board has been open for a month and the reporting citizen comes in every morning', connection: 'the cantina whose private booth the case is about' },
  },
  {
    id: 'utility_plant', name: 'Utility and reclamation plant', ownerTitle: 'Plant superintendent',
    hosts: { kinds: ['power_plant', 'refinery', 'foundry'], families: ['works'] },
    palette: { accent: 'PANEL_STRIPE', seat: 'STONE_BRICK_SLAB', counter: 'DURASTEEL_DARK', light: 'GLOW_PANEL', trim: 'IRON_BARS' },
    rooms: [
      R('plant_control', 'control: the console wall and the status board', { where: 'low', signature: true, accept: /control|ops|command/, interactions: ['read the status board', 'use console'] }),
      R('feedstock_store', 'intake: feedstock hoppers under the feed pipe', { where: 'ground', service: true, serviceEntry: true, accept: /intake|feed|hopper|store|storage|scrap|ore/, interactions: ['browse stock'] }),
      R('processing_reactor', 'processing: the core in its cage with the safe walkway', { where: 'low', accept: /reactor|process|furnace|smelt|casting|foundry|works|refin/, interactions: ['follow the walkway', 'watch the work'] }),
      R('distribution_relay', 'distribution: switchgear and the customer board', { where: 'low', accept: /distribut|relay|switch|transformer|grid|power|comms|data/, interactions: ['read the status board'] }),
      R('plant_maintenance', 'maintenance', { core: false, where: 'upper', service: true, accept: /maintenance|workshop|machine/, interactions: ['watch the work'] }),
      R('spares_store', 'storage of spares', { core: false, where: 'upper', service: true, accept: /spares|store|storage/, interactions: ['browse stock'] }),
      R('gantry_walkway', 'safe walkways: the railed gantry', { core: false, where: 'upper', accept: /gantry|walkway|catwalk|corridor/, interactions: ['follow the walkway'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'plant_control'], service: ['service_entry', 'feedstock_store', 'processing_reactor', 'distribution_relay', 'plant_maintenance', 'spares_store'] },
    graph: [['lobby_atrium', 'plant_control'], ['feedstock_store', 'processing_reactor'], ['processing_reactor', 'distribution_relay'], ['plant_control', 'processing_reactor'], ['processing_reactor', 'gantry_walkway'], ['gantry_walkway', 'plant_maintenance'], ['plant_maintenance', 'spares_store']],
    customers: 'the named neighbours the distribution board lists: the nearest towers on the grid',
    inputs: ['coal_ore', 'iron_ore', 'gold_ore'], outputs: ['iron_block', 'gold_block', 'glass'], wants: ['power', 'reclaimed_water', 'scrap'],
    story: { problem: 'the core has run at 110% since the works doubled its shifts and the superintendent has stopped answering the board', connection: 'the towers it feeds, named on the distribution board' },
  },
  {
    id: 'salvage_yard', name: 'Salvage yard', ownerTitle: 'Yard owner',
    hosts: { kinds: ['recycling_plant'], families: [] },
    palette: { accent: 'PANEL_STRIPE', seat: 'STONE_BRICK_SLAB', counter: 'DURASTEEL', light: 'GLOW_PANEL', trim: 'IRON_BARS' },
    rooms: [
      R('unloading_yard', 'unloading: the apron, the weigh scale and heaps sorted by material', { where: 'ground', signature: true, service: true, serviceEntry: true, accept: /unload|yard|intake|dock/, interactions: ['weigh a load', 'sell scrap'] }),
      R('assessment_desk', 'assessment: the desk, the scale and the sample bench', { where: 'ground', accept: /assess|desk|office|valuation/, interactions: ['sell scrap', 'talk to staff'] }),
      R('disassembly_workshop', 'disassembly benches', { where: 'low', accept: /disassembl|workshop|strip|bench/, interactions: ['watch the work'] }),
      R('reusable_parts_store', 'reusable parts on labelled shelves', { where: 'low', accept: /reusable|parts|store/, interactions: ['browse stock', 'buy'] }),
      R('scrap_store', 'scrap by type', { where: 'low', service: true, accept: /scrap|metal|storage/, interactions: ['sort scrap', 'browse stock'] }),
      R('dispatch_office', 'outgoing orders', { core: false, where: 'upper', accept: /dispatch|orders|office|control/, interactions: ['read board'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'assessment_desk', 'reusable_parts_store'], service: ['service_entry', 'unloading_yard', 'disassembly_workshop', 'scrap_store', 'dispatch_office'] },
    graph: [['lobby_atrium', 'assessment_desk'], ['unloading_yard', 'assessment_desk'], ['assessment_desk', 'disassembly_workshop'], ['disassembly_workshop', 'reusable_parts_store'], ['disassembly_workshop', 'scrap_store'], ['scrap_store', 'dispatch_office'], ['reusable_parts_store', 'dispatch_office']],
    customers: 'mechanics hunting a part, the droid workshop, the plant buying scrap by the tonne',
    inputs: ['iron_bars', 'iron_block', 'console', 'glass'], outputs: ['iron_bars', 'iron_block', 'stick', 'glass'], wants: ['scrap', 'salvage_permit'],
    story: { problem: 'a hull section came in with a registry number that should not exist', connection: 'the market arcade\'s salvage kiosk, which sells what the yard cannot' },
  },
  {
    id: 'criminal_front', name: 'Freight brokerage (criminal front)', ownerTitle: 'Managing broker',
    hosts: { kinds: [], families: [], assigned: 'criminal_front' },
    palette: { accent: 'BLUE_WOOL', seat: 'STONE_BRICK_SLAB', counter: 'PANEL_BLACK', light: 'GLOW_PANEL', trim: 'CHROME' },
    rooms: [
      R('brokerage_office', 'the real business: brokers\' desks under the rate board, a chair for the client', { where: 'ground', signature: true, accept: /broker|office|trading/, interactions: ['book freight', 'talk to staff'] }),
      R('client_meeting_room', 'client meeting room', { where: 'low', accept: /meeting|client/, interactions: ['take a private meeting'] }),
      R('manifest_records', 'manifest records: the first set of books', { where: 'low', accept: /records|archive|manifest/, interactions: ['read'] }),
      R('bonded_store', 'bonded storage: the legitimate back of house', { where: 'low', service: true, accept: /bonded|store|storage|warehouse/, interactions: ['browse stock'] }),
      R('contraband_store', 'the concealed illicit activity: unmarked crates behind the shelves, reached only through another room, the second set of books', { where: 'inner', accept: /contraband|hidden|concealed|cache|smuggl/, interactions: ['browse stock', 'inspect evidence'] }),
      R('back_office', 'the managing broker\'s back office', { core: false, where: 'upper', accept: /back_office|private|office/, interactions: ['use console'] }),
      R('loading_yard', 'the loading yard the legitimate freight moves through', { core: false, where: 'ground', service: true, serviceEntry: true, accept: /loading|yard|dock/, interactions: ['watch the work'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'brokerage_office', 'client_meeting_room'], service: ['service_entry', 'loading_yard', 'bonded_store', 'contraband_store'] },
    graph: [['lobby_atrium', 'brokerage_office'], ['brokerage_office', 'client_meeting_room'], ['brokerage_office', 'manifest_records'], ['brokerage_office', 'bonded_store'], ['bonded_store', 'contraband_store'], ['loading_yard', 'bonded_store'], ['manifest_records', 'back_office']],
    customers: 'legitimate shippers by day, a Hutt cartel courier by night, a security officer who has not yet noticed',
    inputs: ['chest', 'iron_block', 'planks'], outputs: ['chest', 'iron_block', 'planks'], wants: ['freight_contract', 'spice'],
    story: { problem: 'a junior broker has found the second ledger and has to decide whether to report it or take a cut', connection: 'the security station (report it) or the cantina\'s private booth (take the cut)', resolutions: ['report the ledger at the security station reporting post', 'meet the managing broker in the cantina\'s private booth and take the cut'] },
  },
  {
    id: 'community_hall', name: 'Community hall and rooftop garden', ownerTitle: 'Caretaker',
    hosts: { kinds: ['order_house'], families: [] },
    palette: { accent: 'GREEN_WOOL', seat: 'GREEN_WOOL', counter: 'OAK_PLANKS', light: 'LANTERN', trim: 'OAK_LOG' },
    rooms: [
      R('gathering_lounge', 'gathering space: the circle of seats, the noticeboard and the tea urn', { where: 'ground', signature: true, accept: /gathering|hall|lounge|refectory|assembly|common/, interactions: ['sit', 'read the notices'] }),
      R('neighbours_store', 'mutual-aid storage: bread, blankets and the shared tool chest', { where: 'ground', service: true, accept: /store|storage|pantry|aid/, interactions: ['take bread', 'browse stock'] }),
      R('community_kitchen', 'shared services: the kitchen', { where: 'low', service: true, accept: /kitchen|galley/, interactions: ['cook a meal'] }),
      R('rooftop_garden', 'the rooftop garden', { where: 'top', accept: /garden|terrace|roof|greenhouse/, interactions: ['tend the garden', 'sit'] }),
      R('caretaker_office', 'the caretakers\' office: the key board and the lost-property chest', { core: false, where: 'low', accept: /office|caretaker|warden/, interactions: ['talk to staff'] }),
      R('quiet_meditation', 'a quiet room', { core: false, where: 'upper', accept: /meditat|quiet|chapel|shrine|prayer/, interactions: ['meditate'] }),
    ],
    circulation: { public: ['street', 'entry', 'lobby_atrium', 'gathering_lounge', 'neighbours_store', 'lift', 'rooftop_garden'], service: ['service_entry', 'community_kitchen', 'neighbours_store'] },
    graph: [['lobby_atrium', 'gathering_lounge'], ['gathering_lounge', 'neighbours_store'], ['neighbours_store', 'community_kitchen'], ['gathering_lounge', 'caretaker_office'], ['gathering_lounge', 'rooftop_garden'], ['rooftop_garden', 'quiet_meditation']],
    customers: 'neighbours: the tenants of the worker apartments, pensioners, children after school, anyone who needs bread',
    inputs: ['wheat', 'apple', 'wool'], outputs: ['bread'], wants: ['donation'],
    story: { problem: 'the rooftop garden\'s water allocation was cut and the caretaker is arguing with the plant', connection: 'the worker apartments whose tenants use the hall' },
  },
];

export const PROGRAM_BY_ID = Object.fromEntries(PROGRAMS.map((p) => [p.id, p]));
