#!/usr/bin/env python3
"""Renders every line of the screenplay to an audio file with piper, then gives
each character a different voice treatment with ffmpeg.

    node tools/export-script.mjs
    python3 tools/tts.py --piper /tmp/ttsenv/bin/piper --voices /tmp/voices

Outputs assets/vo/<id>.mp3 and src/data/vo-manifest.js (durations are baked in
so the film timeline can lay shots out around the actual length of each line).

Verify the result with tools/check-audio.py, which transcribes the output and
diffs it against the script.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
OUT = ROOT / "assets" / "vo"

# Per-character post-processing chains. Pitch is applied by resampling and then
# correcting the tempo, which shifts formants too -- exactly what we want for a
# 2.1 metre tall man breathing through a chest plate.
FX = {
    "narrator": "highpass=f=70,equalizer=f=140:t=q:w=1.2:g=2.5,equalizer=f=3200:t=q:w=1.5:g=2,"
                "acompressor=threshold=0.09:ratio=3:attack=12:release=220,aecho=0.85:0.35:22:0.12",
    "dry": "highpass=f=90,acompressor=threshold=0.1:ratio=2.6:attack=10:release=180",
    "room": "highpass=f=80,acompressor=threshold=0.1:ratio=2.6:attack=12:release=200,"
            "aecho=0.8:0.5:60|110:0.22|0.12",
    # Kept lighter than it wants to be: pitched further down and drowned in
    # reverb, the Dark Lord stops being intelligible.
    "vader": "highpass=f=55,lowpass=f=4400,equalizer=f=110:t=q:w=1:g=5,"
             "acompressor=threshold=0.06:ratio=5:attack=6:release=180,"
             "aecho=0.85:0.5:80|150:0.22|0.12,equalizer=f=2600:t=q:w=2:g=-1.5,"
             "equalizer=f=3600:t=q:w=1.6:g=2",
    "comm": "highpass=f=320,lowpass=f=3800,acompressor=threshold=0.08:ratio=4:attack=6:release=110,"
            "equalizer=f=1800:t=q:w=1.4:g=4,equalizer=f=3000:t=q:w=1.6:g=3",
    "droid": "highpass=f=280,lowpass=f=5200,equalizer=f=2400:t=q:w=1.6:g=4,tremolo=f=52:d=0.13,"
             "acompressor=threshold=0.08:ratio=4:attack=6:release=140",
}

LOUDNESS = {
    "narrator": -15.0,
    "dry": -15.5,
    "room": -15.5,
    "vader": -14.5,
    "comm": -15.0,
    "droid": -15.5,
}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kw)


def probe_rate(path: Path) -> int:
    out = run(["ffprobe", "-v", "error", "-select_streams", "a:0",
               "-show_entries", "stream=sample_rate", "-of", "csv=p=0", str(path)]).stdout
    return int(out.strip())


def duration(path: Path) -> float:
    out = run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
               "-of", "csv=p=0", str(path)]).stdout
    return float(out.strip())


def read_manifest(path: Path) -> dict:
    """Parses the VO object out of the generated module (brace-matched, because
    the file also contains helper functions)."""
    if not path.exists():
        return {}
    txt = path.read_text()
    marker = "export const VO = "
    i = txt.find(marker)
    if i < 0:
        return {}
    start = i + len(marker)
    depth = 0
    for j in range(start, len(txt)):
        if txt[j] == "{":
            depth += 1
        elif txt[j] == "}":
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(txt[start:j + 1])
                except json.JSONDecodeError:
                    return {}
    return {}


def write_manifest(path: Path, script: dict, manifest: dict, fmt: str) -> None:
    ordered = {k: manifest[k] for k in script["lines"].keys() if k in manifest}
    body = json.dumps(ordered, indent=2)
    path.write_text(
        "// GENERATED by tools/tts.py -- do not edit by hand.\n"
        "// Duration in seconds of each rendered voice line; the film timeline is\n"
        "// laid out around these numbers so picture and voice never drift.\n"
        f"export const VO = {body};\n\n"
        f"export const VO_FORMAT = '{fmt}';\n\n"
        "export function voDur(id) {\n"
        "  const e = VO[id];\n"
        "  if (!e) { console.warn('missing VO', id); return 2; }\n"
        "  return e.d;\n"
        "}\n"
        "\nexport function voUrl(id) {\n"
        "  return `assets/vo/${id}." + fmt + "`;\n"
        "}\n")
    total = sum(v["d"] for v in ordered.values())
    print(f"\n{len(ordered)} lines, {total:.1f}s of dialogue -> {path.relative_to(ROOT)}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--piper", default=os.environ.get("PIPER", "piper"))
    ap.add_argument("--voices", default=os.environ.get("PIPER_VOICES", "/tmp/voices"))
    ap.add_argument("--only", default=None, help="comma separated line ids")
    ap.add_argument("--format", default="mp3", choices=["mp3", "wav"])
    ap.add_argument("--manifest-only", dest="manifest_only", action="store_true",
                    help="re-measure the audio already on disk and rewrite the manifest")
    args = ap.parse_args()

    script_path = BUILD / "script.json"
    if not script_path.exists():
        print("run `node tools/export-script.mjs` first", file=sys.stderr)
        return 1
    script = json.loads(script_path.read_text())

    manifest_path = ROOT / "src" / "data" / "vo-manifest.js"
    manifest = read_manifest(manifest_path) if (args.only or args.manifest_only) else {}

    if args.manifest_only:
        for line in script["all"]:
            final = OUT / f"{line['id']}.{args.format}"
            if final.exists():
                manifest[line["id"]] = {"d": round(duration(final), 3), "who": line["who"]}
        write_manifest(manifest_path, script, manifest, args.format)
        return 0

    lines = script["all"]
    if args.only:
        wanted = set(args.only.split(","))
        lines = [l for l in lines if l["id"] in wanted]

    OUT.mkdir(parents=True, exist_ok=True)
    tmp = BUILD / "tts_tmp"
    tmp.mkdir(parents=True, exist_ok=True)

    for i, line in enumerate(lines):
        lid = line["id"]
        raw = tmp / f"{lid}.raw.wav"
        final = OUT / f"{lid}.{args.format}"
        text = line["text"]
        length = float(line.get("length", 1.0))
        pitch = float(line.get("pitch", 1.0))
        fx = FX.get(line.get("fx", "dry"), FX["dry"])
        target_lufs = LOUDNESS.get(line.get("fx", "dry"), -15.5)

        # NB: piper treats unrecognised argv as the text to speak, so the
        # argument list here must contain nothing it does not understand.
        p = subprocess.run(
            [args.piper, "-m", line["voice"], "--data-dir", args.voices,
             "--length-scale", str(length), "--noise-scale", "0.55", "--noise-w-scale", "0.6",
             "--sentence-silence", "0.30", "-f", str(raw)],
            input=text + "\n", text=True, capture_output=True)
        if p.returncode != 0:
            print(f"piper failed for {lid}: {p.stderr[-400:]}", file=sys.stderr)
            return 1

        rate = probe_rate(raw)
        chain = []
        if abs(pitch - 1.0) > 0.001:
            chain.append(f"asetrate={int(rate * pitch)}")
            chain.append(f"aresample={rate}")
            tempo = 1.0 / pitch
            while tempo > 2.0:
                chain.append("atempo=2.0")
                tempo /= 2.0
            while tempo < 0.5:
                chain.append("atempo=0.5")
                tempo /= 0.5
            chain.append(f"atempo={tempo:.6f}")
        chain.append(fx)
        chain.append(f"loudnorm=I={target_lufs}:TP=-1.5:LRA=11")
        chain.append("aresample=48000")

        enc = ["-c:a", "libmp3lame", "-b:a", "80k"] if args.format == "mp3" else ["-c:a", "pcm_s16le"]
        run(["ffmpeg", "-y", "-v", "error", "-i", str(raw), "-af", ",".join(chain),
             "-ac", "1", *enc, str(final)])

        dur = duration(final)
        manifest[lid] = {"d": round(dur, 3), "who": line["who"]}
        print(f"[{i + 1:2d}/{len(lines)}] {lid:5s} {line['who']:10s} {dur:5.2f}s  {text[:58]}")

    write_manifest(manifest_path, script, manifest, args.format)
    shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
