// Central tunables. Every number here is a gameplay/visual balance value for a
// fictional entertainment demo; none of it models real hardware performance.

export const WORLD = {
  gravity: 9.81,
  /** Ground level of the operating pad. */
  padY: 0,
  /** Radius of the flat, graded base platform. */
  baseRadius: 190,
  fenceRadius: 205,
  /** Near terrain tile extent (metres) and mountain ring distances. */
  terrainInner: 2600,
  terrainOuter: 46000,
  mountainNear: 9000,
  mountainFar: 30000,
  cameraNear: 0.25,
  cameraFar: 120000,
  /** Sea-level air density and scale height for the simplified drag model. */
  rho0: 1.225,
  scaleHeight: 8500,
  speedOfSound: 340,
};

export const PLAYER = {
  eyeHeight: 1.7,
  crouchHeight: 1.1,
  radius: 0.38,
  walkSpeed: 4.1,
  sprintSpeed: 7.6,
  accel: 42,
  friction: 11,
  airAccel: 6,
  jumpSpeed: 4.6,
  gravity: 21,
  stepHeight: 0.42,
  lookSpeed: 0.0022,
  maxPitch: 1.48,
  bobRate: 8.6,
  bobAmount: 0.036,
  swayAmount: 0.021,
  footstepStride: 2.05,
  spawn: [22, 0, 46],
  spawnYaw: -2.45,
};

/**
 * Fictional interceptor batteries. `windowAlt` is the advertised engagement band
 * used for gameplay cueing only.
 */
export const BATTERIES = [
  {
    id: 'PATRIOT',
    label: 'PAC-STYLE TERMINAL',
    short: 'TERMINAL',
    codeName: 'HAWKEYE 1',
    color: 0x5fd0ff,
    accent: '#5fd0ff',
    ammo: 8,
    salvoSize: 1,
    reloadTime: 6.5,
    prepTime: 1.4,
    launchInterval: 1.1,
    boostThrust: 400,
    boostTime: 3.8,
    sustainThrust: 46,
    sustainTime: 5.0,
    maxSpeed: 1420,
    maxLateralG: 30,
    minElev: 0.44,
    maxElev: 1.36,
    loft: 0.26,
    seekerRange: 14000,
    dragK: 3.0e-5,
    fuzeRadius: 34,
    windowAlt: [200, 11000],
    windowRange: [900, 24000],
    plumeScale: 1.0,
    trailWidth: 2.1,
    warheadYield: 1.0,
    desc: 'Fast reaction, tight terminal basket. Best on low, close threats.',
  },
  {
    id: 'THAAD',
    label: 'HIGH-ALTITUDE AREA',
    short: 'HI-ALT',
    codeName: 'LONGVIEW 2',
    color: 0xffc46b,
    accent: '#ffc46b',
    ammo: 6,
    salvoSize: 1,
    reloadTime: 9.5,
    prepTime: 3.2,
    launchInterval: 1.8,
    boostThrust: 300,
    boostTime: 6.2,
    sustainThrust: 22,
    sustainTime: 9.0,
    maxSpeed: 1820,
    maxLateralG: 22,
    minElev: 0.52,
    maxElev: 1.43,
    loft: 0.30,
    seekerRange: 26000,
    dragK: 2.2e-5,
    fuzeRadius: 46,
    windowAlt: [3000, 26000],
    windowRange: [4000, 36000],
    plumeScale: 1.45,
    trailWidth: 3.2,
    warheadYield: 1.25,
    desc: 'Slower to prepare, very wide basket. Engage early in the descent.',
  },
  {
    id: 'SENTINEL',
    label: 'SENTINEL LONG-RANGE TEST',
    short: 'SENTINEL',
    codeName: 'IRONWOOD 3',
    color: 0xff7de3,
    accent: '#ff7de3',
    ammo: 3,
    salvoSize: 1,
    reloadTime: 16,
    prepTime: 5.0,
    launchInterval: 3.0,
    boostThrust: 410,
    boostTime: 8.0,
    sustainThrust: 30,
    sustainTime: 12.0,
    maxSpeed: 2380,
    maxLateralG: 18,
    minElev: 0.56,
    maxElev: 1.48,
    loft: 0.34,
    seekerRange: 40000,
    dragK: 1.6e-5,
    fuzeRadius: 58,
    windowAlt: [6000, 36000],
    windowRange: [8000, 48000],
    plumeScale: 2.2,
    trailWidth: 4.4,
    warheadYield: 1.6,
    desc: 'Experimental. Three rounds only, longest flight, biggest spectacle.',
  },
];

export const BATTERY_BY_ID = Object.fromEntries(BATTERIES.map((b) => [b.id, b]));

/** Emplacement transforms on the pad (metres, radians). */
export const EMPLACEMENTS = {
  PATRIOT: [
    { pos: [-64, 0, -18], yaw: 0.22 },
    { pos: [-64, 0, 24], yaw: -0.16 },
  ],
  THAAD: [
    { pos: [58, 0, -34], yaw: -0.34 },
    { pos: [72, 0, 12], yaw: -0.12 },
  ],
  SENTINEL: [{ pos: [4, 0, -96], yaw: 0.05 }],
};

export const SCENARIOS = [
  {
    id: 'SINGLE',
    label: 'SINGLE TRACK',
    desc: 'One high-visibility ballistic target. Training profile.',
    tod: 'day',
    waves: [{ at: 2.0, count: 1, decoys: 0 }],
    spread: [-0.30, 0.30],
    baseAlt: [19000, 21500],
    baseRange: [42000, 46000],
    speed: [880, 930],
    searchlights: false,
    targetDuration: [50, 70],
  },
  {
    id: 'SATURATION',
    label: 'SATURATION',
    desc: 'Three to five targets on divergent arcs inside a short window.',
    tod: 'sunset',
    waves: [
      { at: 1.5, count: 2, decoys: 0 },
      { at: 8.0, count: 2, decoys: 0 },
      { at: 15.0, count: 1, decoys: 0 },
    ],
    spread: [-0.95, 0.95],
    baseAlt: [17000, 22000],
    baseRange: [38000, 47000],
    speed: [880, 960],
    searchlights: false,
    targetDuration: [60, 90],
  },
  {
    id: 'NIGHT_RAID',
    label: 'NIGHT RAID',
    desc: 'Multiple targets with harmless decoys under searchlights.',
    tod: 'night',
    waves: [
      { at: 1.5, count: 2, decoys: 1 },
      { at: 8.0, count: 2, decoys: 1 },
      { at: 15.0, count: 1, decoys: 1 },
    ],
    spread: [-1.25, 1.25],
    baseAlt: [17000, 21000],
    baseRange: [38000, 46000],
    speed: [870, 950],
    searchlights: true,
    targetDuration: [65, 90],
  },
];

export const SCENARIO_BY_ID = Object.fromEntries(SCENARIOS.map((s) => [s.id, s]));

export const TOD = {
  day: {
    label: 'DAY',
    sunElev: 0.78,
    sunAzim: 2.15,
    turbidity: 3.1,
    exposure: 0.7,
    skyExposure: 0.3,
    sunColor: 0xfff1d6,
    sunIntensity: 2.7,
    ambient: 0x88a6cc,
    ambientIntensity: 0.24,
    envIntensity: 0.5,
    fogColor: 0x9fb3cb,
    fogDensity: 2.1e-5,
    starIntensity: 0,
    bloom: 0.32,
    bloomThreshold: 0.95,
    hazeStrength: 1.15,
    groundBounce: 0x8a6e50,
  },
  sunset: {
    label: 'SUNSET',
    sunElev: 0.062,
    sunAzim: 2.95,
    turbidity: 5.2,
    exposure: 0.86,
    skyExposure: 0.38,
    sunColor: 0xffa758,
    sunIntensity: 2.1,
    ambient: 0x4e5480,
    ambientIntensity: 0.2,
    envIntensity: 0.46,
    fogColor: 0xb07a56,
    fogDensity: 2.9e-5,
    starIntensity: 0.2,
    bloom: 0.52,
    bloomThreshold: 0.82,
    hazeStrength: 1.45,
    groundBounce: 0x6f4326,
  },
  night: {
    label: 'NIGHT',
    sunElev: -0.3,
    sunAzim: 1.05,
    turbidity: 2.0,
    exposure: 1.15,
    skyExposure: 0.52,
    sunColor: 0x93a9dc,
    sunIntensity: 0.2,
    ambient: 0x16203a,
    ambientIntensity: 0.16,
    envIntensity: 0.2,
    fogColor: 0x0a1018,
    fogDensity: 2.2e-5,
    starIntensity: 1,
    bloom: 0.8,
    bloomThreshold: 0.5,
    hazeStrength: 0.7,
    groundBounce: 0x101319,
  },
};

export const THREAT = {
  /**
   * Effective Cd*A/m for the drag term (units m^2/kg). Chosen so a re-entry body
   * decelerates only mildly while a light decoy visibly falls behind.
   */
  cdA: 4.2e-5,
  decoyCdA: 3.0e-4,
  reentryAlt: 11000,
  terminalAlt: 4600,
  weaveAmplitude: 0.55,
  weaveRate: 0.42,
  impactCrater: 26,
  /** Fictional radar cross sections, arbitrary units. */
  rcs: { RV: 1.0, DECOY: 0.34, DEBRIS: 0.12 },
};

export const RADAR = {
  rpm: 14,
  beamWidth: 0.16,
  range: 52000,
  minAlt: -50,
  /** Seconds of accumulated illumination before a track is firm. */
  acquireTime: 1.15,
  /** A tentative contact is dropped this long after its last illumination. */
  dropTime: 9,
  /** Firm tracks are held by the tracking channel and only drop when stale. */
  firmDropTime: 22,
  jitter: 26,
};

export const QUALITY = {
  ultra: {
    label: 'ULTRA',
    pixelRatio: 1.0,
    shadowMapSize: 4096,
    bloom: true,
    smaa: true,
    particleBudget: 4200,
    trailSegments: 128,
    clouds: 2,
    volumetricLight: true,
    terrainSegments: 220,
    decals: 64,
    anisotropy: 8,
  },
  high: {
    label: 'HIGH',
    pixelRatio: 1.0,
    shadowMapSize: 2048,
    bloom: true,
    smaa: true,
    particleBudget: 2800,
    trailSegments: 96,
    clouds: 2,
    volumetricLight: true,
    terrainSegments: 170,
    decals: 48,
    anisotropy: 4,
  },
  medium: {
    label: 'MEDIUM',
    pixelRatio: 0.86,
    shadowMapSize: 1024,
    bloom: true,
    smaa: false,
    particleBudget: 1700,
    trailSegments: 64,
    clouds: 1,
    volumetricLight: false,
    terrainSegments: 130,
    decals: 32,
    anisotropy: 2,
  },
  low: {
    label: 'LOW',
    pixelRatio: 0.7,
    shadowMapSize: 512,
    bloom: false,
    smaa: false,
    particleBudget: 900,
    trailSegments: 40,
    clouds: 0,
    volumetricLight: false,
    terrainSegments: 96,
    decals: 16,
    anisotropy: 1,
  },
};

export const LAYERS = {
  DEFAULT: 0,
  SKY: 1,
  HOLO: 2,
  BLOOM_ONLY: 3,
};
