// The worlds a ship can travel between (pass 3, "off-world"). One flat voxel world holds every planet: each planet
// is a region of world coordinates far enough from the others that their chunks never meet, and space is a
// separate rendered scene entered by climbing above ORBIT_Y (src/space/*). This registry is the contract between
// the pilot module (src/vehicles/pilot.js), the space scene, worldgen regions and the spaceport boards:
//
//   WORLDS.home    - the planet the game starts on: the frontier continent, the ocean, Coruscant, the Death Star's
//                    patch of sky. Its globe texture is sampled from worldgen around `globe.centre`.
//   WORLDS.desert  - a small desert planet with one town and a spaceport, at x 30000 (generated by the 'desert'
//                    region in worldgen.js; structures under src/structures/desert/).
//
// Coordinates below are world blocks. `arrivals` are the pad centres a descending ship may land on (the piloting
// module snaps to the nearest free one); `orbit` is where a ship appears after a hyperspace jump towards this
// world (world coordinates at ORBIT_Y, above the arrival pads).
export const ORBIT_Y = 240;          // climbing through this altitude leaves the atmosphere (space scene takes over)
export const REENTRY_Y = 200;        // a descending ship re-enters the voxel world here, above its destination pads

export const WORLDS = {
  home: {
    id: 'home', name: 'Frontier / Coruscant', kind: 'temperate',
    globe: { centre: { x: 1500, z: 0 }, radius: 3200, sea: 62, tint: [0.36, 0.55, 0.32], ocean: [0.10, 0.28, 0.55], haze: [0.62, 0.72, 0.88] },
    orbit: { x: 2600, y: ORBIT_Y, z: 0 },
    arrivals: [{ name: 'Westport Spaceport', x: 2296, z: -100 }, { name: 'Frontier station deck', x: 262, z: 8 }],
    description: 'Dustwater and the frontier continent, the Coruscant plateau, Westport.',
  },
  desert: {
    id: 'desert', name: 'Jakku Reach', kind: 'desert',
    globe: { centre: { x: 30000, z: 0 }, radius: 1400, sea: -1, tint: [0.78, 0.62, 0.38], ocean: null, haze: [0.86, 0.74, 0.58] },
    orbit: { x: 30000, y: ORBIT_Y, z: 0 },
    arrivals: [{ name: 'Sandhaven landing field', x: 30000, z: 60 }],
    description: 'A small dry world: one town of domed houses, a cantina, a moisture farm belt and a landing field.',
  },
};

export const WORLD_IDS = Object.keys(WORLDS);
export function worldAt(x, z) {
  let best = null, bd = Infinity;
  for (const w of Object.values(WORLDS)) { const d = Math.hypot(x - w.globe.centre.x, z - w.globe.centre.z); if (d < bd) { bd = d; best = w; } }
  return best;
}
export function otherWorlds(id) { return WORLD_IDS.filter((k) => k !== id).map((k) => WORLDS[k]); }
